### ISSUE TITLE
Add support for the old "merge light groups" feature

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#101]
In LuxBlend it was possible to merge all light groups into one for faster final renders and to decrease RAM usage (at the cost of not having the lightgroup flexibility anymore - it reduces them to a convenience tool for manipulating multiple lights at once).
Essentially it bakes the lightgroup gain, color and temperature settings into the light settings of each light in the group.

Check if it is possible to add support for this feature in BlendLuxCore.
My main concern is that it might not be possible to "bake" the temperature into a color multiplier. We will have to look at the LuxCore lightgroup code to see how that works.

**Comment by Dade916** [comment]
Yes, it is not possible at the moment because there textures are not used in light sources.
However the "temperature" can easily be processed at parsing time and transformed in a normal color gain. So let me know when you need it and will add the support for parsing an additional property.

**Comment by Theverat** [comment]
I don't understand the part about textures?
I thought I can just compute the light source gain as:
`gain = light.gain * (group.gain * group.color * group.temperature)`
The gain can not be textured anyway, so this should work, was my idea.

I don't think there are any changes in LuxCore required to support this feature.
But maybe I misunderstand you?

**Comment by Dade916** [comment]
Temperature would require a BlackBody texture to compute the result: https://github.com/LuxCoreRender/LuxCore/blob/41f45ca0ad7aa2b42a991a751afcfc840a455b4e/src/slg/film/imagepipeline/radiancechannelscale.cpp#L38

However, as we both wrote, it can be done statically without the need of a real texture plugged in the light source gain.

**Comment by Theverat** [comment]
No longer relevant since the lightgroup rework in v2.5.
