### ISSUE TITLE
Smoke Node not available in OpenCL

### ISSUE THREAD

**Issue by batstick** [LuxCoreRender/BlendLuxCore#103]
#### System Information

Windows 10 Pro, Radeon Pro Duo 32GB

#### Software Version

* Blender version: 2.79a
* LuxCore version: 2.0 alpha 7

#### Error message from Blender console

```
RuntimeError: Unknown texture in CompiledScene::CompileTextures(): 15
ERROR: Unknown texture in CompiledScene::CompileTextures(): 15
LuxCoreRenderEngine del
Error: Unknown texture in CompiledScene::CompileTextures(): 15
```

#### Short description of error

Scenes using the smoke node cause the error listed above.

#### Exact steps for others to reproduce the error

Having the smoke data node attached anywhere.

**Comment by Theverat** [comment]
Hm, I can not reproduce it here.
Are you using CPU or OpenCL?
Can you attach a small example scene showing the problem to your report?

While trying to reproduce the problem I found another bug: the smoke domain transformation seems wrong.

**Comment by Dade916** [comment]
I can confirm that OpenCL lacks the support for "density grid" texture. I'm checking if I can add the support without too much problems.

**Comment by Theverat** [comment]
> While trying to reproduce the problem I found another bug: the smoke domain transformation seems wrong.

Fixed this extra bug: the worldscale was not being applied.

**Comment by Dade916** [comment]
I have added the support for density grid texture to OpenCL. I'm also re-working the volume rendering code to have far better results.

**Comment by Theverat** [comment]
Great to hear that!
