### ISSUE TITLE
Syntax error in film.imagepipelines.0.radiancescales.type

### ISSUE THREAD

**Issue by Thuil** [LuxCoreRender/BlendLuxCore#104]
First, check if your problem was already reported:
https://github.com/LuxCoreRender/BlendLuxCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug

#### System Information

Windows 10 Pro
AMD FX-8320
GTX 1050 TI
GTX 780 TI

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0 Alpha 7

#### Error message from Blender console

* On Linux: start Blender from a terminal to see the error messages:
  cd /path/to/blender
  ./blender
* On Windows: open Blender > "Window" menu > "Toggle System Console"

If possible, include a traceback of the error messages.
Paste it into this code block:
[LuxCore][227.171] Configuration:
[LuxCore][227.171]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][227.171]   lightstrategy.type = "LOG_POWER"
[LuxCore][227.171]   path.pathdepth.diffuse = 5
[LuxCore][227.171]   rtpathcpu.zoomphase.weight = 0
[LuxCore][227.171]   path.pathdepth.specular = 6
[LuxCore][227.187]   path.pathdepth.total = 7
[LuxCore][227.187]   film.width = 613
[LuxCore][227.187]   rtpathcpu.zoomphase.size = 4
[LuxCore][227.187]   renderengine.seed = 1
[LuxCore][227.187]   film.height = 754
[LuxCore][227.187]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][227.187]   path.forceblackbackground.enable = 0
[LuxCore][227.187]   film.filter.width = 1.5
[LuxCore][227.187]   renderengine.type = "RTPATHCPU"
[LuxCore][227.187]   path.pathdepth.glossy = 5
[LuxCore][227.187]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][227.203]   film.outputs.0.index = 0
[LuxCore][227.203]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][227.203]   film.imagepipelines.0.1.sensitivity = 100
[LuxCore][227.203]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][227.203]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][227.203]   film.imagepipelines.0.1.fstop = 2.7999999523162842
[LuxCore][227.203]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][227.203]   film.imagepipelines.0.1.exposure = 0.0099999997764825821
[LuxCore][227.203]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][227.203]   film.imagepipelines.0.1.type = "TONEMAP_LUXLINEAR"
Export took 0.1s
[LuxCore][227.218] Film resolution: 613x754
[SDL][227.218] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][227.218] Image pipeline: film.imagepipelines.0
[SDL][227.218] Image pipeline step 0: NOP
[SDL][227.218] Image pipeline step 1: TONEMAP_LUXLINEAR
exporter init
ERROR: Syntax error in film.imagepipelines.0.radiancescales.type
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\viewport.py", line 19, in view_update
    engine.session = engine.exporter.create_session(scene, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\export\__init__.py", line 146, in create_session
    session = pyluxcore.RenderSession(renderconfig)
RuntimeError: Syntax error in film.imagepipelines.0.radiancescales.type
view_update
new session
exporter init
create_session
[SDL][227.218] Camera type: perspective
[SDL][227.218] Camera position: Point[7.48113, -6.50764, 5.34367]
[SDL][227.218] Camera target: Point[6.82957, -5.89347, 4.89839]
[SDL][227.218] Camera clipping plane disabled
WARNING: Object "Plane": No material defined
converting lamp: Lamp
[SDL][227.234] Texture definition: __grid_10cm_1
[SDL][227.234] Texture definition: __grid_10cm_2
[SDL][227.234] Texture definition: __grid_1m
[SDL][227.234] Material definition: __CLAY__
[SDL][227.234] Material definition: 1718246538184
[SDL][227.234] Scene objects count: 2
[SDL][227.234] Light definition: 1718246232920
[SDL][227.234] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][227.281] Configuration:
[LuxCore][227.281]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][227.281]   lightstrategy.type = "LOG_POWER"
[LuxCore][227.281]   path.pathdepth.diffuse = 5
[LuxCore][227.281]   rtpathcpu.zoomphase.weight = 0
[LuxCore][227.281]   path.pathdepth.specular = 6
[LuxCore][227.281]   path.pathdepth.total = 7
[LuxCore][227.281]   film.width = 613
[LuxCore][227.281]   rtpathcpu.zoomphase.size = 4
[LuxCore][227.281]   renderengine.seed = 1
[LuxCore][227.281]   film.height = 754
[LuxCore][227.281]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][227.296]   path.forceblackbackground.enable = 0
[LuxCore][227.296]   film.filter.width = 1.5
[LuxCore][227.296]   renderengine.type = "RTPATHCPU"
[LuxCore][227.296]   path.pathdepth.glossy = 5
[LuxCore][227.296]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][227.296]   film.outputs.0.index = 0
[LuxCore][227.296]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][227.296]   film.imagepipelines.0.1.sensitivity = 100
[LuxCore][227.296]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][227.296]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][227.312]   film.imagepipelines.0.1.fstop = 2.7999999523162842
[LuxCore][227.312]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][227.312]   film.imagepipelines.0.1.exposure = 0.0099999997764825821
[LuxCore][227.312]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][227.312]   film.imagepipelines.0.1.type = "TONEMAP_LUXLINEAR"
Export took 0.1s
[LuxCore][227.312] Film resolution: 613x754
[SDL][227.312] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][227.312] Image pipeline: film.imagepipelines.0
[SDL][227.312] Image pipeline step 0: NOP
[SDL][227.328] Image pipeline step 1: TONEMAP_LUXLINEAR
exporter init
ERROR: Syntax error in film.imagepipelines.0.radiancescales.type
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\viewport.py", line 19, in view_update
    engine.session = engine.exporter.create_session(scene, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\export\__init__.py", line 146, in create_session
    session = pyluxcore.RenderSession(renderconfig)
RuntimeError: Syntax error in film.imagepipelines.0.radiancescales.type
LuxCoreRenderEngine del
init
LuxCoreRenderEngine del
init
view_update
new session
exporter init
create_session
[SDL][238.359] Camera type: perspective
[SDL][238.359] Camera position: Point[7.48113, -6.50764, 5.34367]
[SDL][238.359] Camera target: Point[6.82957, -5.89347, 4.89839]
[SDL][238.375] Camera clipping plane disabled
converting lamp: Lamp
[SDL][238.375] Material definition: 1718246538184
[SDL][238.375] Scene objects count: 2
[SDL][238.375] Light definition: 1718246232920
[SDL][238.375] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][238.406] Configuration:
[LuxCore][238.406]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][238.406]   lightstrategy.type = "LOG_POWER"
[LuxCore][238.406]   path.pathdepth.diffuse = 5
[LuxCore][238.406]   rtpathcpu.zoomphase.weight = 0
[LuxCore][238.406]   path.pathdepth.specular = 6
[LuxCore][238.421]   path.pathdepth.total = 7
[LuxCore][238.421]   film.width = 613
[LuxCore][238.421]   rtpathcpu.zoomphase.size = 4
[LuxCore][238.421]   renderengine.seed = 1
[LuxCore][238.421]   film.height = 754
[LuxCore][238.421]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][238.421]   path.forceblackbackground.enable = 0
[LuxCore][238.421]   film.filter.width = 1.5
[LuxCore][238.421]   renderengine.type = "RTPATHCPU"
[LuxCore][238.421]   path.pathdepth.glossy = 5
[LuxCore][238.421]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][238.421]   film.outputs.0.index = 0
[LuxCore][238.421]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][238.437]   film.imagepipelines.0.1.sensitivity = 100
[LuxCore][238.437]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][238.437]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][238.437]   film.imagepipelines.0.1.fstop = 2.7999999523162842
[LuxCore][238.437]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][238.437]   film.imagepipelines.0.1.exposure = 0.0099999997764825821
[LuxCore][238.437]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][238.437]   film.imagepipelines.0.1.type = "TONEMAP_LUXLINEAR"
Export took 0.1s
[LuxCore][238.453] Film resolution: 613x754
[SDL][238.453] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][238.453] Image pipeline: film.imagepipelines.0
[SDL][238.453] Image pipeline step 0: NOP
[SDL][238.453] Image pipeline step 1: TONEMAP_LUXLINEAR
exporter init
ERROR: Syntax error in film.imagepipelines.0.radiancescales.type
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\viewport.py", line 19, in view_update
    engine.session = engine.exporter.create_session(scene, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\export\__init__.py", line 146, in create_session
    session = pyluxcore.RenderSession(renderconfig)
RuntimeError: Syntax error in film.imagepipelines.0.radiancescales.type
view_update
new session
exporter init
create_session
[SDL][238.453] Camera type: perspective
[SDL][238.453] Camera position: Point[7.48113, -6.50764, 5.34367]
[SDL][238.453] Camera target: Point[6.82957, -5.89347, 4.89839]
[SDL][238.453] Camera clipping plane disabled
converting lamp: Lamp
[SDL][238.468] Material definition: 1718246538184
[SDL][238.468] Scene objects count: 2
[SDL][238.468] Light definition: 1718246232920
[SDL][238.468] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][238.500] Configuration:
[LuxCore][238.500]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][238.500]   lightstrategy.type = "LOG_POWER"
[LuxCore][238.500]   path.pathdepth.diffuse = 5
[LuxCore][238.515]   rtpathcpu.zoomphase.weight = 0
[LuxCore][238.515]   path.pathdepth.specular = 6
[LuxCore][238.515]   path.pathdepth.total = 7
[LuxCore][238.515]   film.width = 613
[LuxCore][238.515]   rtpathcpu.zoomphase.size = 4
[LuxCore][238.515]   renderengine.seed = 1
[LuxCore][238.515]   film.height = 754
[LuxCore][238.515]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][238.515]   path.forceblackbackground.enable = 0
[LuxCore][238.515]   film.filter.width = 1.5
[LuxCore][238.515]   renderengine.type = "RTPATHCPU"
[LuxCore][238.515]   path.pathdepth.glossy = 5
[LuxCore][238.515]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][238.531]   film.outputs.0.index = 0
[LuxCore][238.531]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][238.531]   film.imagepipelines.0.1.sensitivity = 100
[LuxCore][238.531]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][238.531]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][238.531]   film.imagepipelines.0.1.fstop = 2.7999999523162842
[LuxCore][238.531]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][238.531]   film.imagepipelines.0.1.exposure = 0.0099999997764825821
[LuxCore][238.531]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][238.546]   film.imagepipelines.0.1.type = "TONEMAP_LUXLINEAR"
Export took 0.1s
[LuxCore][238.546] Film resolution: 613x754
[SDL][238.546] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][238.546] Image pipeline: film.imagepipelines.0
[SDL][238.546] Image pipeline step 0: NOP
[SDL][238.546] Image pipeline step 1: TONEMAP_LUXLINEAR
exporter init
ERROR: Syntax error in film.imagepipelines.0.radiancescales.type
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\viewport.py", line 19, in view_update
    engine.session = engine.exporter.create_session(scene, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\export\__init__.py", line 146, in create_session
    session = pyluxcore.RenderSession(renderconfig)
RuntimeError: Syntax error in film.imagepipelines.0.radiancescales.type
LuxCoreRenderEngine del
init
Can't tag errorlog for redraw in _RestrictContext
Rendering layer "RenderLayer"
exporter init
create_session
[SDL][242.203] Camera type: perspective
[SDL][242.203] Camera position: Point[7.48113, -6.50764, 5.34367]
[SDL][242.203] Camera target: Point[6.82957, -5.89347, 4.89839]
[SDL][242.203] Camera clipping plane disabled
converting lamp: Lamp
[SDL][242.203] Material definition: Surface_Material_1718246538184
[SDL][242.203] Scene objects count: 2
[SDL][242.203] Light definition: Lamp_Lamp_1718246232920
[SDL][242.218] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][242.250] Configuration:
[LuxCore][242.250]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][242.250]   lightstrategy.type = "LOG_POWER"
[LuxCore][242.250]   path.pathdepth.diffuse = 5
[LuxCore][242.250]   film.filter.width = 1.5
[LuxCore][242.250]   path.pathdepth.specular = 6
[LuxCore][242.250]   path.pathdepth.total = 7
[LuxCore][242.250]   renderengine.type = "PATHCPU"
[LuxCore][242.250]   path.forceblackbackground.enable = 0
[LuxCore][242.250]   film.height = 540
[LuxCore][242.250]   sampler.type = "SOBOL"
[LuxCore][242.265]   film.width = 960
[LuxCore][242.265]   renderengine.seed = 1
[LuxCore][242.265]   batch.haltthreshold.stoprendering.enable = 0
[LuxCore][242.265]   batch.haltthreshold = 0.0001
[LuxCore][242.265]   sampler.sobol.adaptive.strength = 0.69999998807907104
[LuxCore][242.265]   path.pathdepth.glossy = 5
[LuxCore][242.265]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][242.265]   film.outputs.2.index = 1
[LuxCore][242.265]   film.outputs.0.index = 0
[LuxCore][242.265]   film.outputs.2.type = "RGB_IMAGEPIPELINE"
[LuxCore][242.281]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][242.281]   film.outputs.2.filename = "RGB_IMAGEPIPELINE_1.png"
[LuxCore][242.281]   film.outputs.1.filename = "RADIANCE_GROUP.exr"
[LuxCore][242.281]   film.outputs.1.id = 0
[LuxCore][242.281]   film.outputs.1.type = "RADIANCE_GROUP"
[LuxCore][242.281]   film.imagepipelines.1.0.exposure = 0.0099999997764825821
[LuxCore][242.281]   film.imagepipelines.1.radiancescales.0.enabled = 1
[LuxCore][242.281]   film.imagepipelines.1.0.type = "TONEMAP_LUXLINEAR"
[LuxCore][242.281]   film.imagepipelines.1.0.fstop = 2.7999999523162842
[LuxCore][242.296]   film.imagepipelines.1.0.sensitivity = 100
[LuxCore][242.296]   film.imagepipelines.0.1.sensitivity = 100
[LuxCore][242.296]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][242.296]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][242.296]   film.imagepipelines.0.1.fstop = 2.7999999523162842
[LuxCore][242.296]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][242.296]   film.imagepipelines.0.1.exposure = 0.0099999997764825821
[LuxCore][242.296]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][242.296]   film.imagepipelines.0.1.type = "TONEMAP_LUXLINEAR"
Export took 0.1s
[LuxCore][242.312] Film resolution: 960x540
[SDL][242.312] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][242.328] Image pipeline: film.imagepipelines.0
[SDL][242.343] Image pipeline step 0: NOP
[SDL][242.343] Image pipeline step 1: TONEMAP_LUXLINEAR
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\__init__.py", line 38, in render_final
    final.render(self, scene)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\final.py", line 34, in render
    _render_layer(engine, scene)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\final.py", line 46, in _render_layer
    engine.session = engine.exporter.create_session(scene, engine=engine)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\export\__init__.py", line 146, in create_session
    session = pyluxcore.RenderSession(renderconfig)
RuntimeError: Syntax error in film.imagepipelines.0.radiancescales.type
ERROR: Syntax error in film.imagepipelines.0.radiancescales.type
Can't tag errorlog for redraw in _RestrictContext
LuxCoreRenderEngine del
Error: Syntax error in film.imagepipelines.0.radiancescales.type

```
(Example output, please delete)
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/export/light.py", line 123, in convert
    raise NotImplementedError("Area light not implemented yet")
NotImplementedError: Area light not implemented yet
```

#### Exact steps for others to reproduce the error
Based on a (as simple as possible) attached .blend file with minimum amount of steps

[imagepipeline.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1861342/imagepipeline.zip)

**Comment by Theverat** [comment]
I can not reproduce the error here.
My guess is that you are using the latest (un-released) BlendLuxCore from github, but not the latest LuxCore binaries. Is that correct?

**Comment by Theverat** [comment]
You need to compile the latest LuxCore binaries and put them in the bin/ folder.
See the following pages:
* http://wiki.luxcorerender.org/Compiling_LuxCore
* https://github.com/LuxCoreRender/BlendLuxCore/tree/master/bin

We will publish the next release on monday by the way.

**Comment by Theverat** [comment]
Ok I'm closing this issue then.
If you have trouble with compilation, please feel free to open a new issue in the respective repo ([WindowsCompile](https://github.com/LuxCoreRender/WindowsCompile) or [LinuxCompile](https://github.com/LuxCoreRender/LinuxCompile)).
Thanks for testing!
