### ISSUE TITLE
Feature Request: Bidir with GPU support

### ISSUE THREAD

**Issue by batstick** [LuxCoreRender/BlendLuxCore#108]
The bidir path tracer is amazing at solving caustics. The only thing that would make it better would be running it on a graphics card.  I am raising this request as there is no way to leverage GPUs to solve caustics apart from day long brute force rendering. Thank you.

**Comment by Dade916** [comment]
You should make the request in LuxCore repository (I don't think I can move issue across repositories).

Anyway you are asking for the most complex feature I can think to at the moment =)

Porting the current CPU code to OpenCL would require an huge amount of work and, at least, OpenCL v2.x support with fine grained SVM (Shared Virtual Memory) to make the problem a bit manageable. I'm not aware of any vendor supporting fine grained SVM at the moment.

The other option would be to use CUDA but it would require even more work, it would work on NVIDIA GPU only and require a very recent GPU too.

**Comment by batstick** [comment]
Okay. I knew this would be asking a lot but I was hopeful that it wasn't as bad as I thought it would be. It sounds harder than I could have thought. Ill move it to the LuxCore repo. Thank you for the answer!
