### ISSUE TITLE
ImageNode texture still remains in viewport after deleting node.

### ISSUE THREAD

**Issue by valcar3d** [LuxCoreRender/BlendLuxCore#116]
#### System Information

Window 10 x64 GTX 980ti

#### Software Version

* Blender version: 2.79b 64bits
* LuxCore version: 2.0 Beta 2

#### Error message from Blender console+
None

#### Short description of error
After deleting an ImageMap node the material preview in the 3d viewport still remains 

#### Exact steps for others to reproduce the error
Create a simple  scence with a plane and UV map it, create a Matte material and a ImageMap node put any texture on the ImageMap node conect texture to diffuse slot and click show in viewport, now delete the ImageMap node and the texture is still showing in the viewport, but in render is fine it renders without texture but is misleading having a preview texture which is not there anymore.

I'm using the standar presets (as it comes when first installed) of LuxCoreRenderer nothing changed.

**Comment by Theverat** [comment]
Just for categorization: this is about the OpenGL viewport, related to this issue: https://github.com/LuxCoreRender/BlendLuxCore/issues/38

**Comment by Theverat** [comment]
No longer relevant in Blender 2.80.
