### ISSUE TITLE
Cannot save render buffers, check the temp default path

### ISSUE THREAD

**Issue by valcar3d** [LuxCoreRender/BlendLuxCore#118]
#### System Information

Windows 10 x64 GTX 980ti

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0 Beta 2

#### Error message from Blender console

Cannot save render buffers, check the temp default path

#### Short description of error
It happens randomly, when I hit F12 or the render button it says "Cannot save render buffers, check the temp default path"

#### Exact steps for others to reproduce the error
Happens randomnly the thing that I see that could trigger that is to render an image, then change the render engine from path to bidirectional and viceversa do a couple of renders and use light groups tweak a little in the compositor and then all of the sudden It doesn't want to render anymore.

What I've done:
- In the output there is a path pointing to my desktop.
- In the compositor there is the same path to my desktop

I don't think is my "path" maybe  Lux does something? because I can render perfectly fine without changing any paths but then it stops working.

**Comment by Theverat** [comment]
The error message talks about the temp path, not the output or compositor paths.
Currently we use the temp directory Python uses, on Windows this is usually %tmp% - is it on a disk that is full or too small?

Try switching the render engine back to Cycles, go to the performance panel in the render tab and disable "Save Buffers".
The error message comes from Blender, not from the LuxCore addon, and it seems to be related to that setting.

I found this thread related to the issue via google: https://blenderartists.org/forum/showthread.php?119017-No-image-rendered-YES-THERE-WAS!&p=1066961&viewfull=1#post1066961
Are you trying to render a very huge image, or do you have little RAM?

**Comment by valcar3d** [comment]
Hey I've checked all you wrote and no is not that my scene is big (it is only 2 cubes, a plane, suzane and a sphere all lit by 2 spot lights), I have 8GB of RAM but only like 47% is used, and yeah I see this is related to blender but it didn't happened before installing Lux so I thought that would be the cause, but as I can see yeah  most probably is blender. Thanks for the quick response still experimenting with the amazing LuxCoreRender...you can close this if you like.

**Comment by Theverat** [comment]
Did it help to disable "Save Buffers"?

**Comment by valcar3d** [comment]
I didn't unchecked "save buffer" from cycles but I did switch to cycles and back to Lux and everything was working as expected not sure if has something to do with it but it got fixed.

**Comment by DarthMoulByte** [comment]
I've been trying to get information on this topic for several months, blender org does not recognize this as a bug, for me it is, it's bad programming, and there's not even any information about it, until blender guru suffered it when version 2.45 of blender

the temporary routes are fine on my pc, 8 TB of free HDD space, no dedicated GPU, 128 GB RAM, and still telling me that you can not save the buffers, and I just turn it off and restart it and fix it and it works again

**Comment by ilko-k** [comment]
It's a bit old, but sometimes buffers can conflict with already saved buffers. Cleaning the temp Folder solves this issue.
