### ISSUE TITLE
LuxCore not uses Blender custom normals

### ISSUE THREAD

**Issue by starkdd** [LuxCoreRender/BlendLuxCore#120]
#### System Information

Kubuntu Linux 16.04 x64

#### Software Version

* Blender version: 2.79b official
* LuxCore version: 2.0 beta2

#### Error message from Blender console

none

#### Short description of error

LuxCore not uses Blender custom normals, while Viewport, Blender Internal and Cycles are using them. In case of other renders, custom normals are used if present, but not with LuxCore.

#### Exact steps for others to reproduce the error

1. Open custom-normals-test.blend, ensure active scene is "Scene LuxCore".
2. Hit Render (F12) and see LuxCore rendering Icosphere with normals split in the middle.
3. Enable DataTransfer modifier on Icosphere for render and render again - nothing changes. But modifier transfers normals from intact Icosphere and normals should be smooth.
4. Switch to Scene Cycles or Scene Blender Internal and do the same test. See Icosphere smooth when DataTransfer modifier is enabled and split when not.

To custom normals to work Blender requires enabling Auto Smooth. But Auto Smooth option isn't supported by LuxCore according to [https://github.com/LuxCoreRender/BlendLuxCore/issues/39](https://github.com/LuxCoreRender/BlendLuxCore/issues/39) So these could be related issues.

[custom-normals-test.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1886660/custom-normals-test.blend.zip)

**Comment by Theverat** [comment]
Yes, this is a known limitation of LuxCore meshes at the moment (along with other stuff like only one UV map and no autosmooth).

**Comment by Dade916** [comment]
Mmm, what do you (or better Blender) mean exactly with "custom" normals ? LuxCore uses the normals received with the mesh. They can be whatever you want.

Do you want to specify multiple normals for the same vertex (like multiple UVs)  and used in different triangles sharing the same vertex ?

**Comment by Theverat** [comment]
> So it is not only LuxBlend not writing custom normals to the output, but also LuxCore itself not ready to accept them, like not reading normals at all? Computing them on-the-fly for example.

Hm it seems to be a BlendLuxCore only problem.
According to [people on stackoverflow](https://blender.stackexchange.com/questions/28034/blender-2-74-exporting-custom-normals-without-applying-split-normals-modifier/28052) we should be able to get the custom normals with `to_mesh` (which we already use), but it does not seem to work.

**Comment by starkdd** [comment]
> Mmm, what do you (or better Blender) mean exactly with "custom" normals ? LuxCore uses the normals received with the mesh. They can be whatever you want.

You gave me a hope :) If there are arbitrary per vertex normals that LuxCore can use, than the thing I trying to achieve is relatively "cheap" to implement.

> Do you want to specify multiple normals for the same vertex (like multiple UVs) and used in different triangles sharing the same vertex ?

By custom normals **I mean** **per vertex normals** different from normals calculated automatically.
But it is also important what **Blender means** by them. Blender has them since [2.74](https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.74/Modeling). According to [this](https://wiki.blender.org/index.php/User:Mont29/Foundation/Split_Vertex_Normals/Custom_Split_Normals_Manual) feature is also named **custom split normals** in Blender and defined for each face corner, i.e. more than 1 per vertex.

So while my test case requires only per-vertex normals so shouldn't be hard to implement, the whole custom split normals thing is the same as in auto-smooth issue [#39](https://github.com/LuxCoreRender/BlendLuxCore/issues/39) and requires changes in LuxCore, if I got it right.

> Hm it seems to be a BlendLuxCore only problem.
> According to people on stackoverflow we should be able to get the custom normals with to_mesh (which we already use), but it does not seem to work.

Probably custom normals are stored and extracted separately because In Blender's Editmode there are options to see per-vertex, per-polygon and these custom split normals. Now I'm trying to get these custom split normals from Blender via its Python API and have found a lot of different normals: vertex normals, polygon normals, loop normals, tessface normals and tessface split normals to name a few.

**Comment by Theverat** [comment]
In case you want to take a look at our code:
Here we export the mesh in BlendLuxCore: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/blender_object.py#L47
It uses this C++ function in pyluxcore for Blender for fast export:
https://github.com/LuxCoreRender/LuxCore/blob/master/src/luxcore/pyluxcoreforblender.cpp#L454

**Comment by Theverat** [comment]
I have reworked the mesh export a bit in commit a63f6a3cd267a0a9be92fa0fb0bccc930e9c0a5d and I *think* custom normals are somewhat working now (at least the shading changes when I tune values in an Normal Edit modifier).

@starkdd, could you test custom normals, if they are working correctly? You'll have to use the latest BlendLuxCore sources from the repo. If you need help with this, I can explain how to set it up.

**Comment by starkdd** [comment]
Hi @Theverat !

I got luxcore 2.1 beta 2 by updating LuxCore from Blender. Then I downloaded latest BlendLuxCore from GitHub and I think correctly replaced files used by Blender with HitHub version. Commit a63f6a3 is present.

But my test case provided in the first message still not working.

With your hints I experimented with reading custom split normal values in Blender and here what I ended up with:
1. need to check `mesh.use_auto_smooth` to yield correct result. If use_auto_smooth is on then
2. call `mesh.calc_normals_split()` to make custom split normals ready for reading
3. access them with like `for loop in mesh.loops: loop.normal`
4. if use_auto_smooth is off then
5. use vertex normals like `for vertex in mesh.vertices: vertex.normal`
Here my test blend file. It has a mesh and a script and prints normals to console.
[custom-normals-test-print.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2586141/custom-normals-test-print.blend.zip)
Output reacts to enabling/disabling of the Data Transfer modifier and enabling/disabling of the Auto Smooth flag. Mesh has 10 vertices and 6 triangles, so script reports 10 vertex and 18 face corner normals.

I looked at https://github.com/LuxCoreRender/LuxCore/blob/master/src/luxcore/pyluxcoreforblender.cpp and as I see it uses Vertex normals if face is smooth and calculates flat face corner normals if face is flat. So custom split normals accessible through loop normals are still not used by now.

I know issue isn't first on TODO list, feature is used not very much and it looks rather complex to solve so I'm not complaining :) Method `Scene_DefineBlenderMesh` even is not receiving enough information at present, if I get it correctly.

**Comment by Theverat** [comment]
Apparently it's not possible to get a direct pointer to the loop normals:
https://devtalk.blender.org/t/accessing-raw-loop-array/3048
We could use foreach_get, it would be a bit slower but would work (we could only use it when custom normals are present).
If you want to implement this yourself I would be happy to help.

**Comment by starkdd** [comment]
So, as can be concluded from your post, now LuxCore/BlendLuxCore takes pointers on arrays inside Blender mesh object and then uses reinterpret_cast on them to read data. And, as mentioned at the thread https://devtalk.blender.org/t/accessing-raw-loop-array/3048 , this technique not possible for loop normals cause they are not forming one consistent array to work with them that way. And Brecht advises using foreach_get from Blender Python API. And you suggest creating an array and passing its pointer.

> If you want to implement this yourself I would be happy to help.

If no one need this feature except of me and you guys are busy (and sure you are :) ), than it looks reasonable to implement it myself eventually. I have no deep knowledge of LuxCore/BlendLuxCore sources, but at least I can try.

**Comment by starkdd** [comment]
> https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/blender_object.py#L190

Thank you, that should help.

**Comment by Corefrecs** [comment]
Hey, are there any News on this topic? It is the only thing I miss at the moment from LuxCore so it would be nice to have this feature in the near future :)

**Comment by Theverat** [comment]
No news, unfortunately.
With all the [other stuff](https://github.com/LuxCoreRender/BlendLuxCore/projects/3) I have to do, I doubt this will make it into v2.3.

**Comment by WJSabey** [comment]
Until it is implemented, a possible workaround is the EdgeSplit modifier. May not work for all use cases, of course.

**Comment by Corefrecs** [comment]
Thanks for the Info! Yes the EdgeSplit modifier is some kind of a workaround but it doesn't give the same result when using for example CAD-Files with custom split normals. Are there plans for implementing it in the next v2.4 release?

**Comment by Theverat** [comment]
Implemented in v2.4.
