### ISSUE TITLE
Non OpenCl Add-on crash on OS with Open cl

### ISSUE THREAD

**Issue by pafurijaz** [LuxCoreRender/BlendLuxCore#121]
#### System Information

Lubuntu  16.04.03 NVidia GTX 750Ti

#### Software Version

* Blender 2.79 (sub 0), Commit date: 2018-03-22 14:10, Hash f4dc9f9d68b
* BlendLuxCore-v2.0alpha7-linux64. (without OpenCL support)

#### blender.crash.txt

bpy.ops.wm.splash()  # Operator
bpy.ops.screen.userpref_show()  # Operator
bpy.data.window_managers["WinMan"].addon_search = "lux"  # Property

# backtrace
./blender(BLI_system_backtrace+0x20) [0x1a6c700]
./blender() [0x1078395]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7efef31694b0]
/lib64/ld-linux-x86-64.so.2(+0xc311) [0x7efef4e47311]
/lib64/ld-linux-x86-64.so.2(+0x15851) [0x7efef4e50851]
/lib64/ld-linux-x86-64.so.2(+0x10564) [0x7efef4e4b564]
/lib64/ld-linux-x86-64.so.2(+0x14da9) [0x7efef4e4fda9]
/lib/x86_64-linux-gnu/libdl.so.2(+0xf09) [0x7efef34fef09]
/lib64/ld-linux-x86-64.so.2(+0x10564) [0x7efef4e4b564]
/lib/x86_64-linux-gnu/libdl.so.2(+0x1571) [0x7efef34ff571]
/lib/x86_64-linux-gnu/libdl.so.2(dlopen+0x31) [0x7efef34fefa1]
./blender(_PyImport_FindSharedFuncptr+0x17e) [0x2f5fd3e]
./blender(_PyImport_LoadDynamicModuleWithSpec+0x135) [0x2f33ec5]
./blender() [0x2f31395]
./blender(PyCFunction_Call+0xb9) [0x2e9d579]
./blender(PyEval_EvalFrameEx+0x7d09) [0x2f16899]
./blender() [0x2f1869e]
./blender(PyEval_EvalFrameEx+0x6c8a) [0x2f1581a]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender() [0x2f1869e]
./blender(PyEval_EvalCodeEx+0x23) [0x2f18773]
./blender() [0x2e79674]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender(_PyObject_CallMethodIdObjArgs+0x190) [0x2e50140]
./blender(PyImport_ImportModuleLevelObject+0x8ca) [0x2f32b8a]
./blender() [0x2f0b314]
./blender(PyCFunction_Call+0xd9) [0x2e9d599]
./blender(PyEval_EvalFrameEx+0x7d09) [0x2f16899]
./blender() [0x2f1869e]
./blender(PyEval_EvalFrameEx+0x6c8a) [0x2f1581a]
./blender() [0x2f1869e]
./blender(PyEval_EvalCodeEx+0x23) [0x2f18773]
./blender() [0x2e79674]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender(_PyObject_CallMethodIdObjArgs+0x190) [0x2e50140]
./blender(PyImport_ImportModuleLevelObject+0x713) [0x2f329d3]
./blender(PyImport_ImportModuleLevel+0x39) [0x2f32eb9]
./blender() [0x149be8c]
./blender(PyCFunction_Call+0xd9) [0x2e9d599]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender(PyEval_EvalFrameEx+0x3b9e) [0x2f1272e]
./blender() [0x2f1869e]
./blender(PyEval_EvalCode+0x1f) [0x2f1879f]
./blender() [0x2f0c85e]
./blender(PyCFunction_Call+0xb9) [0x2e9d579]
./blender(PyEval_EvalFrameEx+0x7d09) [0x2f16899]
./blender() [0x2f1869e]
./blender(PyEval_EvalFrameEx+0x6c8a) [0x2f1581a]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender() [0x2f1869e]
./blender(PyEval_EvalCodeEx+0x23) [0x2f18773]
./blender() [0x2e79674]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender(_PyObject_CallMethodIdObjArgs+0x190) [0x2e50140]
./blender(PyImport_ImportModuleLevelObject+0x8ca) [0x2f32b8a]
./blender(PyImport_ImportModuleLevel+0x39) [0x2f32eb9]
./blender() [0x149be8c]
./blender(PyCFunction_Call+0xd9) [0x2e9d599]
./blender(PyEval_EvalFrameEx+0x81ec) [0x2f16d7c]
./blender() [0x2f1869e]
./blender(PyEval_EvalFrameEx+0x6c8a) [0x2f1581a]
./blender() [0x2f1869e]
./blender(PyEval_EvalCodeEx+0x23) [0x2f18773]
./blender() [0x2e79674]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender() [0x1472964]
./blender() [0x19f2f46]
./blender() [0x107fbfa]
./blender() [0x107ffe2]
./blender() [0x125cedb]
./blender() [0x126d5a9]
./blender() [0x10814ec]
./blender() [0x1081958]
./blender(wm_event_do_handlers+0x1d4) [0x1081c64]
./blender(WM_main+0x18) [0x1078f78]
./blender(main+0x3f8) [0x1016a38]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7efef3154830]
./blender() [0x10752ee]

#### Exact steps for others to reproduce the error
When I activated  the non open cl add-on of last v2 beta, blender closing instantly  but with open cl version works fine.

**Comment by Dade916** [comment]
Have you tried with beta2 ?

**Comment by pafurijaz** [comment]
Yes, I tried with the last beta v2

**Comment by Theverat** [comment]
Can you try if the problem still happens with the latest stable or alpha release?
https://github.com/LuxCoreRender/BlendLuxCore/releases

**Comment by pafurijaz** [comment]
Now works with the latest Luxcore build, thanks for the attention.. Compliments for the awesome render engine..
