### ISSUE TITLE
Camera view render doesn't fit if sensor fit isn't on auto

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/BlendLuxCore#122]
Open blender and start viewport render in camera view with border rendering and portrait Format (height > width). Change automatic sensor fit to either horizontal or vertical.
automatic fit:
![auto](https://user-images.githubusercontent.com/17701407/38538358-f05dafe0-3c82-11e8-8b18-4c5713e7c5eb.JPG)
horizontal fit:
![horizontal](https://user-images.githubusercontent.com/17701407/38538360-f1a37a60-3c82-11e8-91b7-2de41be6dc0c.JPG)
vertical fit:
![vertical](https://user-images.githubusercontent.com/17701407/38538361-f2f532aa-3c82-11e8-9752-b054b090cbc9.JPG)

**Comment by Theverat** [comment]
It might help to take a look at the Cycles code here: https://github.com/sobotka/blender/blob/master/intern/cycles/blender/blender_camera.cpp#L274

**Comment by Theverat** [comment]
You know what's really weird?
When I change this line: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/utils/__init__.py#L221
to `border_max_x = scene.render.border_max_x * 2` (multiply with 2 at the end), it seems to work almost correctly...
However this also affects the final render filmsize which is then incorrect.
