### ISSUE TITLE
Unicode characters are not supported in material name

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/BlendLuxCore#125]
#### System Information

Windows 7 64 bit, GPU: None

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0 beta 2

#### Error message from Blender console
```
ui_do_but_textedit: utf8 char '╨в'
ui_do_but_textedit: utf8 char '╨╡'
ui_do_but_textedit: utf8 char '╤Б'
ui_do_but_textedit: utf8 char '╤В'
```

#### Short description of error
unicode characters are not supported in material name

#### Exact steps for others to reproduce the error
1. create new material
2. rename material to `Тест` (russian text)
3. open material selecter:
![01](https://user-images.githubusercontent.com/7983249/38611434-4f1d4c48-3d8c-11e8-98f9-e5d27edd65c5.jpg)

**Comment by Dade916** [comment]
The problem may be not only limited to BlendLuxCore but involve LuxCore code to.

**Comment by Theverat** [comment]
This is the material selector: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/operators/material.py#L115
As far as I can see we are only using standard Blender API methods here (EnumProperty to generate the material list, window manager for the search popup).
So it is probably a limitation of the Blender API.

**Comment by Theverat** [comment]
@PavelBlend please open a bug report in the Blender bug tracker.
My guess is that the [WindowManager.invoke_search_popup](https://docs.blender.org/api/current/bpy.types.WindowManager.html?highlight=invoke_search_popup#bpy.types.WindowManager.invoke_search_popup) method invokes an outdated Blender function internally which can't handle unicode.

It is similar to this old bug report: https://developer.blender.org/T35824

**Comment by PavelBlend** [comment]
Created Task:
https://developer.blender.org/T54591

**Comment by brechtvl** [comment]
It may be the bug mentioned in the Python API docs here, that needs to be worked around for now:
https://docs.blender.org/api/current/bpy.props.html?highlight=enumproperty#bpy.props.EnumProperty

**Comment by Theverat** [comment]
Thanks, that was exactly the issue.
The `ui_do_but_textedit` warnings still appear, but they seem to be unrelated to the problem.
The search works now.
