### ISSUE TITLE
Make network rendering available from inside BlendLuxCore

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#128]
See https://forums.luxcorerender.org/viewtopic.php?f=5&t=9&p=2973#p2973
* Maybe as a button (operator)
* We will need to add the pyluxcoretools to the addon packages

**Comment by Theverat** [comment]
Implemented in commits:
aa6d2a4868b54ada6880c8cb00314554046a847f
20d635de33b4df9a94cba566cce1caaa5522f7d9
90f7591a8192fc46ebabffe82c04a195466b3737

**Comment by thhart** [comment]
I can see it is possible to start the network console in Blender when installed correctly. But I can not see the network is really used for "Rendering View" inside of Blender?
Is this still an open issue or am I missing something which might to have setup?

**Comment by Theverat** [comment]
That was not really the goal of this issue (the title is probably not so well chosen).
Currently, you have to use the pyluxcoretools for network rendering - at the end you can import the EXR into Blender for tonemapping/compositing, but there's no live preview in Blender.
