### ISSUE TITLE
Viewport Exposure is not proper

### ISSUE THREAD

**Issue by batstick** [LuxCoreRender/BlendLuxCore#129]
#### System Information

Win 10 Pro, Radeon Pro Duo x2, GTX 980 for Display

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0 Beta 2 (The issue has existed since at least before version 2.0)

#### Short description of error

Adjusting the exposure/gamma in the viewport does not work properly. It seems that the full range of brightness is not being used? I have attached a collage of examples. The top is a final render. Bottom is a viewport of the same scene. Notice how the light bulb itself is so much brighter that the exposure had to be lowered to -8 for it to get dimmer at all. In the viewport everything starts getting uniformly dimmer the moment the exposure is lowered.
![exposure issues tiny](https://user-images.githubusercontent.com/30424137/38779688-bfb69116-4099-11e8-9660-3f5ed44d37cc.png)

#### Exact steps for others to reproduce the error
All you have to do is play with the exposure with a final render and the viewport open at the same time to see the difference. I have attached a sample blend file.
[room01.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1913007/room01.zip)

The issue occurs only on the RT Path CPU + RT Path Path Sampler inside the viewport. All other combinations work properly for the final render.

**Comment by Theverat** [comment]
It is indeed OpenGL which clamps the values into 0..1 range: 
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml

**Comment by Theverat** [comment]
Fixed it, we need to use `internal_format = GL_RGBA32F`

![scrn_2018-04-18_10-48-59](https://user-images.githubusercontent.com/1584761/38921562-5fe5667c-42f6-11e8-80d8-45e2d9e1d1f1.png)
