### ISSUE TITLE
no Rough Glass presets

### ISSUE THREAD

**Issue by cycicyci** [LuxCoreRender/BlendLuxCore#130]
#### System Information

Win 10 x64,  GeForce GT 710

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0 Beta 2

#### Short description of error

There is no Rough Glass presets in the add menu in the node editor , but I suppose it should exist according to https://wiki.luxcorerender.org/LuxCoreRender_Materials.

**Comment by Theverat** [comment]
The rough glass material is no longer a separate node. It was integrated into the glass node.
Add a glass material node and enable the "Rough" checkbox.

**Comment by cycicyci** [comment]
I see, thanks.
