### ISSUE TITLE
Ctrl-Z clears all material nodes in scene

### ISSUE THREAD

**Issue by Jgrover111** [LuxCoreRender/BlendLuxCore#134]
#### System Information

Windows 10 Home (64-bit)
Intel Core i5-6200U

#### Software Version

* Blender version: 2.79a
* LuxCore version: Beta3 (No OpenCL)

#### Short description of error

When I press Ctrl-Z to undo something all of my material nodes get cleared and I have to recreate them all over again, which is really annoying as I seem to press it more often than I notice :?

#### Exact steps for others to reproduce the error

The error is not scene or context specific and nothing specific is needed to reproduce it.
Just create a new scene, create a material out of nodes for the default cube **using the node tree preset buttons**, move the cube and press Ctrl-Z so the cube snaps back to the original position, but the material nodes will disappear

**Comment by Jgrover111** [comment]
Tested in 2.79b and still happens

**Comment by Jgrover111** [comment]
Demonstration in 2.79b: http://www.filedropper.com/2018-04-1808-58-30

**Comment by Theverat** [comment]
You can just attach files here to this issue (might have to zip it).
