### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by retsyo** [LuxCoreRender/BlendLuxCore#138]
maybe my HD4000 prevents BlenderLuxCore from finding Geforce 740M on my win7 64 bits, so
```
Traceback (most recent call last):
 File "E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\modules\addon_utils.py", line 331, in enable
 mod = __import__(module_name)
 File "E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons\BlendLuxCore\__init_ _.py", line 13, in <module>
 from .bin import pyluxcore
 ImportError: DLL load failed: The specified module could not be found.
```

I come to this conclusion because I find that only when I unselect HD4000, LuxMark can render the ball without crash.

I also posted the problem as https://github.com/LuxCoreRender/LuxMark/issues/1

**Comment by Dade916** [comment]
The error with RTPATOCL is an internal error of Intel OpenCL compiler. This can be traced back to the HD4000 problems I was talking about in the LuxMark issue and it is not a surprise.
However, I'm surprised that BlendLuxCore-v2.0beta3-win64.zip (OpenCL-less version) doesn't work and give the same import error. So, I assume the ImportError is a different problem.

Can you post the list of files in "E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons\BlendLuxCore" ? It is where the pyluxcore.pyd should be with few other DLLs.

**Comment by retsyo** [comment]
I just decompress `BlendLuxCore-v2.0beta3-win64.zip` ( the one without opencl) to `E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons`, so everything under `E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons\BlendLuxCore` is from BlendLuxCore-v2.0beta3-win64.zip. You can read it at the ending of this post. The directory `__pycache__`  is here because I try to enable BlendLuxCore in Blender

It is the same if I install the addon by using `install add-on from file` in Blender

there is only on pyluxcore.pyd on my PC as the image says
![clipboard01](https://user-images.githubusercontent.com/7960913/39116270-8b24713a-46d3-11e8-92e0-3f86514c32ef.png)


```batch
E:\GREENSOFT\3D\BLENDER\BLENDER-2.79A-WINDOWS64\2.79\SCRIPTS\ADDONS\BLENDLUXCORE

│  .gitignore
│  .travis.yml
│  LICENSE
│  readme.md
│  __init__.py
│
├─bin
│  │  .gitignore
│  │  embree.dll
│  │  get_binaries.py
│  │  OpenImageIO.dll
│  │  pyluxcore.pyd
│  │  pyluxcoretool.exe
│  │  pyluxcoretools.zip
│  │  readme.md
│  │  tbb.dll
│  │  tbbmalloc.dll
│  │  __init__.py
│  │
│  └─__pycache__
│          __init__.cpython-35.pyc
│
├─draw
│      __init__.py
│
├─engine
│      final.py
│      preview.py
│      viewport.py
│      __init__.py
│
├─export
│      aovs.py
│      blender_object.py
│      caches.py
│      camera.py
│      config.py
│      duplis.py
│      hair.py
│      halt.py
│      image.py
│      imagepipeline.py
│      light.py
│      material.py
│      motion_blur.py
│      smoke.py
│      world.py
│      __init__.py
│
├─handlers
│      __init__.py
│
├─nodes
│  │  output.py
│  │  sockets.py
│  │  __init__.py
│  │
│  ├─materials
│  │      carpaint.py
│  │      cloth.py
│  │      emission.py
│  │      glass.py
│  │      glossy2.py
│  │      glossycoating.py
│  │      glossytranslucent.py
│  │      matte.py
│  │      mattetranslucent.py
│  │      metal.py
│  │      mirror.py
│  │      mix.py
│  │      null.py
│  │      output.py
│  │      velvet.py
│  │      __init__.py
│  │
│  ├─textures
│  │      band.py
│  │      blackbody.py
│  │      blenderblend.py
│  │      blenderclouds.py
│  │      blenderdistortednoise.py
│  │      blendermagic.py
│  │      blendermarble.py
│  │      blendermusgrave.py
│  │      blendernoise.py
│  │      blenderstucci.py
│  │      blendervoronoi.py
│  │      blenderwood.py
│  │      brick.py
│  │      bump.py
│  │      checkerboard2d.py
│  │      checkerboard3d.py
│  │      coloratdepth.py
│  │      colormix.py
│  │      constfloat1.py
│  │      constfloat3.py
│  │      dots.py
│  │      fbm.py
│  │      fresnel.py
│  │      hitpoint.py
│  │      hsv.py
│  │      imagemap.py
│  │      iorpreset.py
│  │      irregulardata.py
│  │      lampspectrum.py
│  │      mapping2d.py
│  │      mapping3d.py
│  │      marble.py
│  │      math.py
│  │      normalmap.py
│  │      output.py
│  │      pointiness.py
│  │      smoke.py
│  │      uv.py
│  │      windy.py
│  │      wrinkled.py
│  │      __init__.py
│  │
│  └─volumes
│          clear.py
│          heterogeneous.py
│          homogeneous.py
│          output.py
│          __init__.py
│
├─operators
│      camera.py
│      camera_response_func.py
│      ior_presets.py
│      lightgroups.py
│      material.py
│      node_tree_presets.py
│      pointer_node.py
│      pyluxcoretools.py
│      texture.py
│      update.py
│      utils.py
│      world.py
│      __init__.py
│
├─properties
│      addon_preferences.py
│      aovs.py
│      blender_object.py
│      camera.py
│      config.py
│      display.py
│      errorlog.py
│      hair.py
│      halt.py
│      ies.py
│      imagepipeline.py
│      light.py
│      lightgroups.py
│      material.py
│      opencl.py
│      render_layer.py
│      scene.py
│      world.py
│      __init__.py
│
├─release
│      package_releases.py
│
├─ui
│      aovs.py
│      blender_object.py
│      camera.py
│      config.py
│      display.py
│      errorlog.py
│      halt.py
│      light.py
│      lightgroups.py
│      material.py
│      mesh.py
│      particle.py
│      postpro.py
│      render.py
│      render_layer.py
│      texture.py
│      units.py
│      world.py
│      __init__.py
│
├─utils
│      compatibility.py
│      node.py
│      render.py
│      ui.py
│      __init__.py
│
└─__pycache__
        __init__.cpython-35.pyc
```

**Comment by retsyo** [comment]
if I copy `e:\greensoft\3d\blender\blender-2.79a-windows64\python35.dll` into `E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons\BlendLuxCore\bin\`, (I know it is not necessary to do the copy), all dll dependency of `pyluxcore.pyd` seems ok. 

but blender still cannot import BlendLuxCore as my first post

![dep](https://user-images.githubusercontent.com/7960913/39116516-3371af38-46d4-11e8-8cd5-120cd285b462.png)

**Comment by Theverat** [comment]
Which locale are you using?

**Comment by retsyo** [comment]
in fact, there is `e:\greensoft\3d\blender\blender-2.79a-windows64\2.79\python\bin\python.exe`
it can `import pyluxcore`
```batch
E:\greensoft\3d\blender\blender-2.79a-windows64\2.79\scripts\addons\BlendLuxCore
\bin>e:\greensoft\3d\blender\blender-2.79a-windows64\2.79\python\bin\python.exe

Python 3.5.3 (default, May 20 2017, 19:10:40) [MSC v.1800 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
(None, None)
>>> locale.getdefaultlocale()
('zh_CN', 'cp936')
>>> import pyluxcore
>>> dir(pyluxcore)
['Camera', 'ConvertFilmChannelOutput_1xFloat_To_1xFloatList', 'ConvertFilmChanne
lOutput_1xFloat_To_4xFloatList', 'ConvertFilmChannelOutput_1xUInt_To_1xFloatList
', 'ConvertFilmChannelOutput_2xFloat_To_3xFloatList', 'ConvertFilmChannelOutput_
3xFloat_To_3xFloatList', 'ConvertFilmChannelOutput_3xFloat_To_4xFloatList', 'Con
vertFilmChannelOutput_4xFloat_To_4xFloatList', 'Film', 'FilmOutputType', 'GetOpe
nCLDeviceDescs', 'GetOpenCLDeviceList', 'GetPlatformDesc', 'Init', 'ParseLXS', '
Properties', 'Property', 'RenderConfig', 'RenderSession', 'RenderState', 'Scene'
, 'SetLogHandler', 'Version', '__doc__', '__file__', '__loader__', '__name__', '
__package__', '__path__', '__spec__']
>>>
```

**Comment by retsyo** [comment]
well, finally I found that when I `set PATH=` then run blender, BlenderLuxCore can be enabled in Blender. So there must be some conflict on my PC. I will try to find and report it here.

Sorry to bother your all.

**Comment by Dade916** [comment]
Try to check if you have anyone of the DLLs in bin directory installed somewhere in PATH directories.  For instance, a different version of Embree DLL  (or python) may have been installed by another application.

**Comment by retsyo** [comment]
the answer: bad environment variables without double quotation marks for directory name with space

there is a segment `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;` in my environment variables PATH (right click `My Computer`, `Properties`, `Advanced system setting`, `environment variables`, `Edit System Variable`, `PATH`) . As we can see, there is space in the directory name, but no double quotation marks are used. So if I change it to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;"C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86";"C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64";`, Blender can enable LuxCoreRender

Please note that I do not add double quotation marks to close `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin`


the problem is solved but there is still some puzzles for me. 
1. if I rename `C:\Program Files (x86)\Intel\OpenCL SDK\2.0` to `C:\Program Files (x86)\Intel\OpenCL SDK\2.0=`, Blender can enable LuxCoreRender. So I think there is no LuxCoreRender's dependencies under `C:\Program Files (x86)\Intel\OpenCL SDK\2.0`
2. but if `C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;` is in PATH, `from .bin import pyluxcore` can't find DLL. I think it searches under `C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86` but for what?

```
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86\
or 
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64\

│  clang_compiler.dll
│  clbltfng9.dll
│  clbltfng9.rtl
│  clbltfnn8.dll
│  clbltfnn8.rtl
│  clbltfnp8.dll
│  clbltfnp8.rtl
│  clbltfnv8.dll
│  clbltfnv8.rtl
│  cpu_device.dll
│  intelocl.dll
│  msvcm90.dll
│  msvcp90.dll
│  msvcr90.dll
│  OclCpuBackEnd.dll
│  task_executor.dll
│  __ocl_svml_g9.dll
│  __ocl_svml_n8.dll
│  __ocl_svml_p8.dll
│  __ocl_svml_v8.dll
│
└─tbb
        tbb.dll
        tbbmalloc.dll
```

**Comment by Dade916** [comment]
It may happen because you have 2 OpenCL drivers installed for your HD4000: one in system directory, installed with the latest HD4000 driver and the other with the Intel OpenCL SDK. The second may be a different version (and/or not work) and it is used only if it is in your PATH.

The other possible source of problem could be a different version of tbb.dll/tbbmalloc.dll used by Intel OpenCL driver and pyluxcore.
