### ISSUE TITLE
Lose materials after adding 2nd instance

### ISSUE THREAD

**Issue by zezic** [LuxCoreRender/BlendLuxCore#149]
#### System Information

Ubuntu 16.04 (64-bit), GeForce GTX 1060

#### Software Version

* Blender version: 2.79b (f4dc9f9d68b)
* LuxCore version: 2.0 rc1

#### Error message from Blender console

* There is no error messages

#### Short description of error

When adding second instance of a group to a scene, instances (and some objects) lose materials if instance was added to other layer than to layer with original group.

#### Exact steps for others to reproduce the error

1. Create a group of an objects with assigned materials
2. **Switch to another layer**
3. Create **two** instances of a previously created group
4. Start render (non-viewport)

I attach demo .blend which contains 3 layers:
* 1st layer with problem described (two instances)
* 2nd layer with no problem (one instance)
* 3rd layer with original group

[instances-lose-mats.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1960315/instances-lose-mats.blend.zip)

Problem occurs when rendering with GPU as well as CPU-only.

#### Some details

* Problem not occurs when adding instances to same layer where group located
* Problem not occurs in viewport (live) rendering mode
* There is short material flicker in live mode (~0.2s, from matte to correct) when switching to layer that contains problematic pair of instances (not a problem, but may be it gives some info)

##### Extra: how it looks

![instances-lose-mats](https://user-images.githubusercontent.com/1945127/39425152-c39a1858-4c82-11e8-8309-6f710dd93ea4.jpg)

**Comment by Theverat** [comment]
Thanks for the very well-written bug report!
This problem is already fixed in the latest master, so the bug will be gone in the next release.
