### ISSUE TITLE
ERROR: clGetPlatformIDs

### ISSUE THREAD

**Issue by Zaldor** [LuxCoreRender/BlendLuxCore#150]
#### System Information

Linux Mint sarah 
Lenovo y50
Geforce GTX860M

#### Software Version

* Blender version: 279b
* LuxCore version: 2.0rc1

#### Error message from Blender console

pyluxcore version: 2.0rc1
Traceback (most recent call last):
  File "/home/zaldor/.config/blender/2.79/scripts/addons/BlendLuxCore/handlers/__init__.py", line 24, in luxcore_load_post
    scene.luxcore.opencl.update_devices_if_necessary()
  File "/home/zaldor/.config/blender/2.79/scripts/addons/BlendLuxCore/properties/opencl.py", line 39, in update_devices_if_necessary
    device_list = self.get_opencl_devices()
  File "/home/zaldor/.config/blender/2.79/scripts/addons/BlendLuxCore/properties/opencl.py", line 74, in get_opencl_devices
    return pyluxcore.GetOpenCLDeviceList()
RuntimeError: clGetPlatformIDs

#### Short description of error
ERROR: clGetPlatformIDs

#### Exact steps for others to reproduce the error
 open

**Comment by Theverat** [comment]
Have you tried the No-OpenCL version?

You might be lacking OpenCL drivers.
Try to update your graphics drivers.
You can also try to run LuxMark and see if that works.

**Comment by Zaldor** [comment]
Blender does recognize the card in preference panel properly and activates
cuda.

Il gio 3 mag 2018, 11:03 Simon Wendsche <notifications@github.com> ha
scritto:

**Comment by Dade916** [comment]
Cuda and OpenCL are different standards. You need a working OpenCL installation. Try to install LuxMark to check if your OpenCL driver works fine.

Do you have an Intel integrated GPU in your laptop too ? They are often the source of a lot of problems with OpenCL because their drivers and hardware is very limited.

**Comment by Zaldor** [comment]
Yes Intel integrated card is there... I'll try luxmark

Il gio 3 mag 2018, 11:45 David Bucciarelli <notifications@github.com> ha
scritto:

**Comment by Dade916** [comment]
It is very likely to be the source of your problem. Try to disable the integrated GPU if you can.

Another handy command is "clinfo": it will list the OpenCL platforms available on your laptop.

**Comment by Zaldor** [comment]
Same error with no open cl version

Il gio 3 mag 2018, 11:57 David Bucciarelli <notifications@github.com> ha
scritto:

**Comment by Dade916** [comment]
It is not possible, there has been a mistake during the installation. For obvious reason, the OpenCL-less version doesn't call clGetPlatformIDs() at all.

**Comment by Zaldor** [comment]
Solved!

**Comment by Dade916** [comment]
Good =)

**Comment by Theverat** [comment]
What was the solution?

**Comment by Zaldor** [comment]
Now I need to make it work with openCL

**Comment by Zaldor** [comment]
Shouldn't I be able to use OpenCL witht the gtx 860M?

**Comment by Dade916** [comment]
Yes, but you have to disable Intel OpenCL and to check your OpenCL NVIDIA installation.

For the first, you could just use a trick: you should have a file in "/etc/OpenCL/vendors" directory named intel64.icd or something similar. Just move the file in a backup directory.

For the second, try to run LuxMark and checks if ot works fine.
