### ISSUE TITLE
Check if we can decrease the RAM usage

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#151]
Compared to Cycles, our RAM usage is extremely high, most noticeable with high-resolution film size.
Find out where we can save RAM.
For example, I think each render pass needs 3 times as much RAM as strictly necessary:
1. the render pass in Blender (unavoidable)
1. a Python array we use for reading the AOV from LuxCore, then convert it to Blender render pass
1. the AOV in LuxCore (unavoidable)

Maybe we can save number 2 by directly converting from LuxCore AOV to Blender pass rect in the pyluxcoreforblender helper functions.

Todos:
* [x] Optimize pyluxcoreforblender conversion functions (see above)
* [x] Only define film outputs for lightgroups that are actually used
* [ ] Find out why the RAM usage is still high

**Comment by Theverat** [comment]
I have removed the need for Python buffers during the restructuring of the pyluxcoreforblender conversion functions.

I will also remove the intermediate float arrays in all functions where we simply `std::copy` the values (writing the data directly to `pass.rect` with `GetOutput`).

**Comment by Theverat** [comment]
luxcoreui needs 2.7 GiB of RAM.
luxcoreconsole needs 2.7 GiB of RAM.
.bcf attached:
[test.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2042829/test.zip)

**Comment by Kompwu** [comment]
@Theverat How's going ?

**Comment by Theverat** [comment]
I'm waiting for Dade to look into this issue.
Unfortunately I have nearly no free time at the moment.

**Comment by Theverat** [comment]
Here is a profiling run done with [massif](http://valgrind.org/docs/manual/ms-manual.html).
I was using the scene that is attached 3 posts up (in test.zip).

* massif.out.1411 is the raw output generated by massif.
* ms_print_1411.txt is the output of `ms_print massif.out.1411` redirected to a file
[massif.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2274451/massif.zip)

**Comment by Theverat** [comment]
After Dade's latest changes as of commit https://github.com/LuxCoreRender/LuxCore/commit/b3505a2344314756d8c35c52cb9569341f12b397, luxcoreconsole now needs 509 MiB on Linux (built without OpenCL) to render the [testscene](https://github.com/LuxCoreRender/BlendLuxCore/files/2042829/test.zip).

**Comment by Dade916** [comment]
> The average samples/sec after 55 seconds rendertime:
> Previous (one film per thread): 3.97M
> New (shared film): 3.73M

More complex is the scene, less samples/sec there are to splat and smaller is the difference. The difference is also related to the kind of CPU used (some as a more modern/fast support for atomic ops).

A not marginal benefit of a single film is also no more thread film merges (aka film updated is very fast and doesn't requires anymore 30+secs for very high resolutions).
