### ISSUE TITLE
Denoiser Integration

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#153]
My TODO list for the denoiser integration.

* [x] Check which settings can be hidden (probably the lower 3)
* [x] Add a LuxCore panel to the image editor toolshelf
* [x] Add denoiser settings to the panel, with a button to refresh the denoised image
* [x] Remove periodic refresh
* [x] [Descriptions](https://forums.luxcorerender.org/viewtopic.php?f=9&p=3882#p3882)
* [x] Add warning when using Metropolis sampler (because the denoiser does not really work well in this case)
* [x] The refresh buttons should only be visible when a render is running
* [x] Show some stats about last denoiser run in toolshelf (render time, samples, how long it took etc.)
* [x] Sensible max values for the denoiser settings
* ~~Test if it is feasible to reduce Search Window Radius from 6 to 3 (it is much faster and seems like the quality is mostly the same)~~
* ~~Easy mode or some presets for different qualities, if possible~~

Usability Ideas:
* [x] Prevent users from accidentally triggering multiple denoiser calculations in a row
* [x] Add a label to the denoiser panel (both render props and image tools) telling the user where to find the denoised image ("In the image editor, open the rendered image and select the "DENOISED" pass. Make sure that the correct render layer is selected")
* [x] Show a helpful text over the black image that is shown by default in the denoiser pass (something like `Open the tool shelf with [T], go to the "LuxCore" category and press "Run Denoiser"`)

Known issues:
* [ ] The OpenGL font settings are not properly reset by the help text draw function
* [ ] Only the "combined" imagepipeline is updated when the tonemapper or lightgroups are edited, denoiser output and lightgroup imagepipelines are not updated
* [x] Enabling the denoiser after a render was started and pressing refresh leads to problems (film is no longer refreshed). It should be impossible to enable denoiser after final render was started (disable denoiser UI).
* [x] Writing to ID classes in this context is not allowed
```
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/engine/__init__.py", line 36, in render_final
    final.render(self, scene)
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/engine/final.py", line 36, in render
    _render_layer(engine, scene)
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/engine/final.py", line 88, in _render_layer
    utils_render.refresh(engine, scene, config, draw_film=True)
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/utils/render.py", line 53, in refresh
    engine.framebuffer.draw(engine, engine.session, scene, render_stopped)
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/draw/final.py", line 70, in draw
    scene.luxcore.display.refresh = False
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting LuxCoreDisplaySettings.refresh
```

* [x] I think my Python code has some kind of memory leak caused by the buffers. Maybe I just have to delete them manually because GC works too late, or I keep a reference somewhere.

**Comment by Asticles** [comment]
Hi,

I'm getting a much darker denoised image. Cpu path tracing with sobol. Opencl W64 version.

![t1a](https://user-images.githubusercontent.com/25231467/39959262-81441cb0-560f-11e8-9af9-65c01c160ef3.jpg)
![t1b](https://user-images.githubusercontent.com/25231467/39959264-84469cee-560f-11e8-887d-198c7d2a8919.jpg)

Thanks

**Comment by Theverat** [comment]
Please attach the scene.

**Comment by Asticles** [comment]
Pm. on the forum.

**Comment by Dade916** [comment]
Are you using auto-linear tone-mapping or similar adaptive tone-mapping ?

**Comment by Theverat** [comment]
Yes.

**Comment by Dade916** [comment]
Do you have the same problem if you switch to linear tone map ?

This result may be expected because the spike filter and the denoiser will interact with auto-linear computations of average image luminance so you get a different value when using auto and not.

**Comment by Asticles** [comment]
Well, the black screen is about the resolution, as seen on the forum. sSetting scales to 1 don't gives errors, so is about the resolution divider of scales. But changing film resolution to be a multiplier of scales values is a bit nightmare.

I disabled Auto brightness, but now the denoised image is too much clamped:
![t3a](https://user-images.githubusercontent.com/25231467/39988043-a74a7fc8-5766-11e8-9e40-50e89122831c.jpg)

![t3b](https://user-images.githubusercontent.com/25231467/39988051-ace6e7d2-5766-11e8-9b88-bc1ec8197c3c.jpg)

**Comment by Dade916** [comment]
Use the default scale value of 3 and use a resolution that is a multiple of 4. It is quite easy and it will help a bit in your case.

Anyway, there is simple too much noise in the original image, you need a longer rendering time.

**Comment by Dade916** [comment]
> The problem is that I leap from 4096 to 8192 of image resolution.

Uh ? What do you mean ? A multiple of 4, not a power of 2: the leap is from 4096 to 4100.

**Comment by Asticles** [comment]
Sorry, I mean, power of 2.

**Comment by PavelBlend** [comment]
Denoiser began to work differently.
Version 2.1 and 2.1alpha3:
![1](https://user-images.githubusercontent.com/7983249/51180906-c3e4ce00-18da-11e9-82ca-13597719c797.jpg)
My project (animation) was made in version 2.1alpha3.
I rendered hundreds of frames.
Then I updated BlendLuxCore to version 2.1.
Then he continued rendering and got different pictures.

**Comment by Dade916** [comment]
If you post a test scene, I can check what is going wrong.

**Comment by PavelBlend** [comment]
@Dade916, test scene:
[luxtest.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2772663/luxtest.zip)
