### ISSUE TITLE
Blender interface lags a lot when rendering large resolutions

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#157]
When rendering an image with something like 4000x3000, the Blender interface gets very sluggish even when no film refresh is happening.

My tests show that this is most likely caused by our frequent calls to `session.UpdateStats()` (called [once per second](https://github.com/LuxCoreRender/BlendLuxCore/blob/master/engine/final.py#L105)).

We need to do this to check if the halt conditions are met.
Find out if we can reduce how often we call `UpdateStats()`, or maybe introduce a new LuxCore method that only checks the halt conditions without refreshing the film (if this is possible).
We could also reduce how often we call `UpdateStats()` depending on the film size.

**Comment by Dade916** [comment]
We can add a flag to enable/disable film update however there is some stat that can be updated only after a film update (like samples/pixel). Most halt conditions can only be evaluate after a film updated too.

In general, updating the film every second is probably doubling the rendering times in some case (!).

I could add some kind of exponential interval between film updates (and related check):

- every 1sec for the first 60secs;
- every 2sec for 1-2 mins;
- every 4sec for 2-3 mins;
- every 8sec for 3-4 mins;

But it would affect the moment halt conditions are triggered.

**Comment by Theverat** [comment]
> I could add some kind of exponential interval between film updates (and related check):

This sounds good.
It does not require any changes in LuxCore, only in the addon, right?

**Comment by Miaua** [comment]
For me the lag goes away with tile rendering. But with no tile rendering, when i stop render in morning, the render is still not stopped after i'm back in home from work some 9 hours later. In LuxCore stand-alone, it won't allow to change settings, no log message in console what is going on.
BlendLuxCore 2.0 no OpenCL
blender 2.79b
Windows 10
CPU BiDir MLT, CPU Path MLT, BIDIRVMCPU
Film update 3600 sec

**Comment by Theverat** [comment]
I'm now using this formula, which reaches the maximum of 16 seconds interval after 4 minutes:
http://fooplot.com/?lang=de#W3sidHlwZSI6MCwiZXEiOiJtaW4oMl4oeC82MCksMTYpIiwiY29sb3IiOiIjMDAwMDAwIn0seyJ0eXBlIjoxMDAwLCJ3aW5kb3ciOlsiLTEiLCIxMDIwIiwiLTEiLCIxNyJdfV0-
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/engine/final.py#L150
