### ISSUE TITLE
PySide wont install on Blender 2.79b. PySide has been deprecated?

### ISSUE THREAD

**Issue by leonard7e** [LuxCoreRender/BlendLuxCore#158]
I can not install PySide on Blender 2.79b.

#### System Information

Ubuntu 18.04.
Graphics acceleration done by Intel Skylake.

#### Software Version

* Blender version: 2.79b
* LuxCore version: 2.0

#### Error message 
Pushing button "LuxCore Network Render" inside Blender does not reveal an error message. Error shows indirectly, opening dialogue to install PySide again (and again, and again ... )

Trying to install PySide manually, I get this error message. (Using get-pip.py)

> Complete output from command python setup.py egg_info:
>     only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
>     
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iz_m81a6/PySide/

I used Python inside Blender. Using get-pip.py to install pip for Blender's Python build.

#### Short description of error
Actually, Blender 2.79b uses Python version 3.5m. On 
> https://github.com/pyside/PySide

it looks like PySide has been deprecated
 > ATTENTION: This project is deprecated, please refer to PySide2

#### Exact steps for others to reproduce the error
Push button "LuxCore Network Render" inside Blender.

To see error message, I used get-pip.py from
> https://bootstrap.pypa.io/get-pip.py 

... and did
> $PathToBlenderPython/bin/python.5m get-pip.py 

... and after this ...
> $PathToBlenderPython/bin/pip3 install PySide

**Comment by Theverat** [comment]
> I used Python inside Blender. Using get-pip.py to install pip for Blender's Python build.

You should use your system's Python, not the one inside Blender.

@Dade916: We might have to change to PySide2 in this case?

**Comment by Dade916** [comment]
As far as I know, PySide2 has not yet been released. There is no v1.0 available or pre-built binaries, etc. It is the reason why we are still using PySide(1).

Anyway, on Ubuntu, just run from a shell:

sudo pip3 install PySide

**Comment by leonard7e** [comment]
Sorry, same issues if I 

sudo pip3 install PySide

[sudo] Passwort für ***********: 
The directory '/home/leonard/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/leonard/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting PySide
  Downloading https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 129kB/s 
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y_r5qptc/PySide/


---

Atm, I can access these python 3 versions using apt. 

 ~> apt search python --names-only | grep "^python3\.[0-9]/"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3.6/bionic,now 3.6.5-3 amd64  [installiert]
python3.7/bionic 3.7.0~b3-1 amd64

**Comment by Dade916** [comment]
So PySide supports up to v3.4 while your Linux distribution has available only v3.6 or v3.7 ?

I'm afraid there isn't an easy solution. You could try to compile PySide from source but it isn't an easy task (however it is doable: https://stackoverflow.com/questions/47362751/installing-pyside-for-python-3-6?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by Theverat** [comment]
> It installs without an error.
But after I tried blender / LuxCore again. Pushed "LuxCore Network Render". It wont run and asks me again to install pyside

The check in BlendLuxCore is not perfect. You can see what it does here: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/operators/pyluxcoretools.py#L52

Try to do the following:
Open a terminal, cd to BlendLuxCore/bin (usually it is in `~/.config/blender/2.79/scripts/addons/`) and run the following:
```
python3 pyluxcoretools.zip
```

**Comment by leonard7e** [comment]
Thank you for your answers.
The pyluxcoretools work!

**Comment by Dade916** [comment]
I guess we can close this.
