### ISSUE TITLE
BlendLuxCore exports wrong resolution

### ISSUE THREAD

**Issue by Miaua** [LuxCoreRender/BlendLuxCore#159]
BlendLuxCore 2.0RC1
Windows 10
Blender 2.79b

No matter what you select the resolution in BlendLuxCore, the "export only luxcore scene, don't start render in Blender" will render only in 1920x1080 pix when you open exported scene with luxcore standalone.

**Comment by Theverat** [comment]
I can not reproduce wrong resolution settings in the exported files.
luxcoreui auto-adjusts the image to the luxcoreui window, maybe you mean that?

**Comment by Miaua** [comment]
My screen is 3840 x 2160. When i open the scene, then i go in image view (it's camera by default). From there save outputs, they will be HD res, when i don't change resolution by hand in luxcore.

**Comment by Dade916** [comment]
Can you check (or post here) the render.cfg file of the exported scene (in text format) ? It should include 2 lines like:

film.width = 640
film.height = 480

It is the rendering resolution.

BTW, you can start directly in image view mode with the following command:

luxcoreui -D screen.tool.type IMAGE_VIEW render.cfg

**Comment by Miaua** [comment]
film.height = 5430
film.filter.type = "GAUSSIAN"
filesaver.renderengine.type = "PATHCPU"
sampler.sobol.adaptive.strength = 0.69999998807907104
scene.epsilon.min = 9.9999997473787516e-006
sampler.type = "METROPOLIS"
sampler.metropolis.imagemutationrate = 0.10000000000000001
film.width = 3620
path.pathdepth.specular = 128
path.pathdepth.glossy = 128
scene.epsilon.max = 0.00100000001490116
sampler.metropolis.maxconsecutivereject = 128
film.filter.gaussian.alpha = 5
lightstrategy.type = "LOG_POWER"
native.threads.count = 15
path.pathdepth.total = 128
renderengine.type = "PATHCPU"
path.forceblackbackground.enable = 0
filesaver.format = "TXT"
path.pathdepth.diffuse = 128
film.filter.width = 5
renderengine.seed = 1
sampler.metropolis.largesteprate = 0.10000000000000001
batch.haltspp = 0
batch.haltthreshold.stoprendering.enable = 0
batch.haltthreshold = 0.0001
batch.halttime = 0
film.imagepipelines.0.3.type = "GAMMA_CORRECTION"
film.imagepipelines.0.2.name = "Kodachrome_64CD"
film.imagepipelines.0.2.type = "CAMERA_RESPONSE_FUNC"
film.imagepipelines.0.0.type = "NOP"
film.imagepipelines.0.3.value = 2.2000000000000002
film.imagepipelines.0.1.type = "TONEMAP_REINHARD02"
film.imagepipelines.0.1.postscale = 5.5
film.imagepipelines.0.1.burn = 6
film.imagepipelines.0.1.prescale = 0.69999998807907104
film.imagepipelines.0.radiancescales.0.enabled = 1
film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
film.imagepipelines.0.radiancescales.2.globalscale = 1
film.imagepipelines.0.radiancescales.2.rgbscale = 1 1 1
film.imagepipelines.0.radiancescales.1.globalscale = 1
film.imagepipelines.0.radiancescales.1.enabled = 1
film.imagepipelines.0.radiancescales.2.enabled = 1
film.imagepipelines.0.radiancescales.0.globalscale = 1
film.imagepipelines.0.radiancescales.1.rgbscale = 1 1 1
film.outputs.4.filename = "RADIANCE_GROUP.exr"
film.outputs.0.index = 0
film.outputs.4.id = 2
film.outputs.2.id = 0
film.outputs.3.type = "RADIANCE_GROUP"
film.outputs.3.filename = "RADIANCE_GROUP.exr"
film.outputs.1.filename = "RGB.exr"
film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
film.outputs.2.type = "RADIANCE_GROUP"
film.outputs.3.id = 1
film.outputs.0.type = "RGB_IMAGEPIPELINE"
film.outputs.1.type = "RGB"
film.outputs.4.type = "RADIANCE_GROUP"
film.outputs.2.filename = "RADIANCE_GROUP.exr"
scene.file = "scene.scn"

**Comment by Dade916** [comment]
As you see, film.width and film.height are set correctly. It is what B.Y.O.B. wrote in his post: for rendering with a resolution larger than the screen you have to start luxcoreui using " -D screen.tool.type IMAGE_VIEW" or use "pyluxcoretool console" (GUI-less interface).

**Comment by Miaua** [comment]
I see, thank you.
