### ISSUE TITLE
Make it possible to adjust the film after ending the render

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#160]
This could be implemented in several ways:
* Save the film (standalone or as part of the full scene) and write a user-friendly tool that allows to edit the film
* Keep the film of the last render session in memory (extract it from the session somehow) and allow adjustments to it in Blender (this is probably more complicated to get right and bug-free)

**Comment by Dade916** [comment]
I could easily add a pyluxcoretool to load a film and change/apply denoising. You could lunch the app like network rendering after having saved a film.

You can do the same inside Blender (i.e. save a film, load a stand alone film, change the denoiser parameters, re-run the image pipeline, etc.). However, I don't know if Blender has a place where you can plug such a feature.

**Comment by Theverat** [comment]
It seems like the following code works:
```python
    film = engine.session.GetFilm()

    # Clean up
    del engine.session
    engine.session = None

    print(film)
    print(film.GetFilmY())
```
Is this correct?
Or will it cause problems to deleting the session after getting the film reference like this?

**Comment by Dade916** [comment]
Nope, it will likely to lead to an horrible crash because deleting a session will free memory film too.  You can use this:

```
    # ... render ...
    engine.session.Stop()

    # Save the film
     engine.session.GetFilm().SaveFilm(filmFileName)

    # Clean up
    del engine.session
    engine.session = None

    # Load stand alone film
    film = pyluxcore.Film(filmFileName)

    print(film)
    print(film.GetFilmY())
```

**Comment by novacrazy** [comment]
I was going to open a separate issue for what I'm about to suggest, but it coincides with this somewhat.

Would it also be possible to pause an active render to adjust film/lightgroup/camera settings without having to deal with the Blender UI being laggy or unresponsive due to 100% CPU and/or GPU usage?

**Comment by Dade916** [comment]
The API allows to pause the render, do any editing and resume (but assume pause/resume is not yet exposed in BlendLuxCore).

**Comment by Theverat** [comment]
> (but assume pause/resume is not yet exposed in BlendLuxCore).

Indeed.
It should not be too complicated to implement it. @novacrazy open an issue about it and I will look into it the next days.

**Comment by Theverat** [comment]
Thinking about this issue again, Dade already nailed it with his first comment:
> I could easily add a pyluxcoretool to load a film and change/apply denoising. You could lunch the app like network rendering after having saved a film.
> You can do the same inside Blender (i.e. save a film, load a stand alone film, change the denoiser parameters, re-run the image pipeline, etc.). However, I don't know if Blender has a place where you can plug such a feature.

I think it is better to do this sort of thing outside of Blender, the image editor with it's somewhat weird "Rendered Image" mechanics is not suited for it.
