### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by mrfusiontm** [LuxCoreRender/BlendLuxCore#165]
#### System Information

Operating system and graphics card
iMac (late 2017)
 Mac OS High Sierra ver 10.13.4
 NVIDIA GeForce GTX 675MX 1024 MB

#### Software Version

* Blender version:  2.79b
* LuxCore version: 2.0 (latest download)

#### Error message from Blender console

![screen shot 2018-05-24 at 5 06 55 am](https://user-images.githubusercontent.com/6153579/40484711-67dcee7c-5f11-11e8-839d-73452a500304.png)

#### Short description of error

When I try to install the zip file from the User preference panel, I get the traceback in the image above. I get the same error no matter which version I try to install (openCL or CPU mode)

#### Exact steps for others to reproduce the error

Open blender.
Select User Preferences->addons
select Install addon from file
select either openCL or non openCL version 
Toggle on Render:LuxCore
Error window  pops up.

**Comment by Theverat** [comment]
There is no official macos version yet. 
Where did download this?

**Comment by Dade916** [comment]
Are you trying to install the Linux version on MacOS ? It can not work.

**Comment by mrfusiontm** [comment]
No, I downloaded both of the MacOS versions (with and without openCL) and tried both of those.
I get the same error each time I tried to enable it.

**Comment by mrfusiontm** [comment]
Oops, actually now that I looked again I did download the linux one.  So sorry.  That's what I get for trying to tackle this at 5 am.  Ignore this.
