### ISSUE TITLE
Moving Hemi lamp with HDRI changes scene lighting with strange results

### ISSUE THREAD

**Issue by Jgrover111** [LuxCoreRender/BlendLuxCore#168]
Windows 10 Home Version 1803 Build 17134.48

Blender version: 2.79b
LuxCore version: 2.1alpha0

When moving a hemi lamp with a HDRI in the Bidir engine, seemingly unexplainable anomalies happen in the render. The images look as if another light has been added to the scene when only the Hemi exists.

![frame4](https://user-images.githubusercontent.com/23037820/40665129-639e0eda-6354-11e8-9fa5-b6db2445b287.png)
![frame3](https://user-images.githubusercontent.com/23037820/40665130-63bc25fa-6354-11e8-8e43-fa56519787af.png)
![frame2](https://user-images.githubusercontent.com/23037820/40665131-63d955d0-6354-11e8-8c9e-7477180e8628.png)
![frame1](https://user-images.githubusercontent.com/23037820/40665132-64234f50-6354-11e8-96c2-e32821654b39.png)
[Hemi.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2048608/Hemi.zip)

**Comment by Jgrover111** [comment]
Currently testing the latest source and the results seem similar. Will upload images soon.

**Comment by Dade916** [comment]
It should be this fix (https://github.com/LuxCoreRender/LuxCore/commit/7884d6cbcff243565815dc5a5ab2f901e4ac26b6) and may be available only on "v2.0.x" branch (i.e. not yet merged on the master).

The reference issue was LuxCoreRender/LuxCore#106.

**Comment by Jgrover111** [comment]
Tried with LuxCore standalone 2.1alpha0, same result. Will try latest source once I figure out how to build it 😄

**Comment by Jgrover111** [comment]
Brilliant!
