### ISSUE TITLE
Ability to pause render and adjust settings during pause?

### ISSUE THREAD

**Issue by novacrazy** [LuxCoreRender/BlendLuxCore#169]
To quote myself from #160:

Would it be possible to pause an active render to adjust film/lightgroup/camera settings without having to deal with the Blender UI being laggy or unresponsive due to 100% CPU and/or GPU usage?

It would be ideal for the changes to show up in the render image immediately as opposed to having to unpause to see it update.

**Comment by Theverat** [comment]
Done: https://youtu.be/aw5E9B_jMww

**Comment by novacrazy** [comment]
Very nice! Thanks for your hard work on this. LuxCore is quickly becoming my default renderer for projects.
