### ISSUE TITLE
render error

### ISSUE THREAD

**Issue by andreimd87** [LuxCoreRender/BlendLuxCore#171]
Python argument types in
    BlendLuxCore.bin.pyluxcore.ConvertFilmChannelOutput_3xFloat_To_4xFloatList(Film, FilmOutputType, int, int, int, int, bool, bool)
did not match C++ signature:
    ConvertFilmChannelOutput_3xFloat_To_4xFloatList(unsigned int, unsigned int, class boost::python::api::object {lvalue}, unsigned __int64, bool)

**Comment by Dade916** [comment]
You are probably mixing different version of LuxCore DLL and BlendLuxCore plugin. Try to re-install a complete version.

**Comment by andreimd87** [comment]
yes. i updated them. now all works fine. thank you
