### ISSUE TITLE
active camera selection

### ISSUE THREAD

**Issue by andreimd87** [LuxCoreRender/BlendLuxCore#173]
sorry for question, but where is the option for selecting the active camera in scene tab?

**Comment by neo2068** [comment]
The scene section in the scene tab isn't activated in LuxCore because background scenes aren't supported yet.

**Comment by Theverat** [comment]
We could also make our own copy of the panel where we leave out the stuff that is not supported.
In the meantime, you can switch the active camera by selecting a camera and pressing Ctrl+Num 0.

**Comment by Theverat** [comment]
I added the panel.
Background scenes are rather complicated to implement, so I'll leave them unsupported for now: #174 
I made the setting inactive and display a warning if a background scene is selected.

![scrn_2018-06-08_18-58-08](https://user-images.githubusercontent.com/1584761/41170779-201c9ab2-6b4e-11e8-8fbc-ea75fe6cf729.png)
