### ISSUE TITLE
LuxCore

### ISSUE THREAD

**Issue by webleonardo** [LuxCoreRender/BlendLuxCore#177]
LuxCore, I can not install this plugin in Blender. I did from BendLuxCore downloand, I switched to LuxCore by leaving the zip.
As I could not, I uninstalled the zip and I was able to add in Blender but it does not work, that gives error. Init_py does not see addon_utils.py in Blender.

**Comment by Theverat** [comment]
Did you download from here? https://luxcorerender.org/download/

**Comment by webleonardo** [comment]
Yes now I was able to install LuxCore, but it was not that easy. It's kind of weird, but I had to install an OpenCL seo, that's where I got it. I had to open .zip file inside the Blender Addon. It was not that easy and when I get Blender 2.79b it already comes with code errors. The program shows me wanting not to see the other Blender line.

**Comment by Theverat** [comment]
So is it working now?
If not, please post the exact error messages.

**Comment by webleonardo** [comment]
Now your LuxCore plugin is running.

When I went to get Blender, it did not work, it was an error.

The error is as follows, the plugin does not see an application within Blender. There is no such line 331 in / scripts / modules / add_utils and line 13 in _init_.py. I'll have to write down LuxCore so I can show you the code accurately.

**Comment by Theverat** [comment]
To be honest, I don't really understand what you mean.

**Comment by webleonardo** [comment]
OK, one minut.

**Comment by webleonardo** [comment]
![error](https://user-images.githubusercontent.com/20019145/41498171-e0c02aec-713c-11e8-8886-8f3d9b12ccb7.png)

**Comment by webleonardo** [comment]
Não foi possível encontrar o módulo especificado. - The specified module could not be found

**Comment by webleonardo** [comment]
![luxcore](https://user-images.githubusercontent.com/20019145/41498206-dcd3d234-713d-11e8-89bd-e6ea06bb7767.png)

**Comment by Theverat** [comment]
Please test if your OpenCL installation is working (you can use LuxMark for this: http://luxmark.info/).
You could also try to install the Non-OpenCL version, if that works, something in your OpenCL installation is broken.
Try to update your graphics driver.

**Comment by webleonardo** [comment]
Oh, yes, thank you. I'm already able to use it without non-OpenCL.
I just had to reinstall this file with OpenCL to show the problem.
This problem appeared when I went to install Blender 2.79b that already came with an error.
Thanks for everything.

**Comment by Theverat** [comment]
Is everything working now?

**Comment by webleonardo** [comment]
Good morning, Theverat.

Yes, it do. I'm without OpenCL. Thank you very much.
