### ISSUE TITLE
blender not responding

### ISSUE THREAD

**Issue by andreimd87** [LuxCoreRender/BlendLuxCore#178]
![image](https://user-images.githubusercontent.com/19931241/41498147-ae5adc46-716e-11e8-8970-4c8e07edf75c.png)

![image](https://user-images.githubusercontent.com/19931241/41498149-b836d990-716e-11e8-98bf-e5d94a58ae7c.png)

hi. updated to the latest files. after selecting the opencl in viewport settings and changing the view to rendered the blender does not respond anymore. even with an empty scene.

**Comment by andreimd87** [comment]
update:

this is the cmd log:

pyluxcore version: 2.1alpha1
[Engine/Viewport] view_update
[Engine/Viewport] New session
[Exporter] Init
[Exporter] create_session
[SDL][19.625] Camera type: perspective
[SDL][19.640] Camera position: Point[7.91816, -11.466, 6.97543]
[SDL][19.640] Camera target: Point[7.43289, -10.8289, 6.37649]
[SDL][19.640] Camera clipping plane disabled
[SDL][19.640] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][19.671] Configuration:
[LuxCore][19.671]   path.pathdepth.total = 7
[LuxCore][19.671]   path.pathdepth.diffuse = 5
[LuxCore][19.671]   path.pathdepth.glossy = 5
[LuxCore][19.671]   path.pathdepth.specular = 6
[LuxCore][19.671]   rtpath.resolutionreduction.preview = 4
[LuxCore][19.671]   rtpath.resolutionreduction.step = 1
[LuxCore][19.671]   rtpath.resolutionreduction = 1
[LuxCore][19.671]   opencl.code.alwaysenabled = "MATTE ROUGHMATTE MATTETRANSLUCE
NT ROUGHMATTETRANSLUCENT GLOSSY2 GLOSSYTRANSLUCENT GLASS ARCHGLASS ROUGHGLASS MI
RROR METAL2 NULLMAT HAS_BUMPMAPS GLOSSY2_ABSORPTION GLOSSY2_MULTIBOUNCE HOMOGENE
OUS_VOL CLEAR_VOL IMAGEMAPS_BYTE_FORMAT IMAGEMAPS_HALF_FORMAT IMAGEMAPS_1xCHANNE
LS IMAGEMAPS_3xCHANNELS INFINITE TRIANGLELIGHT SKY2 SUN POINT MAPPOINT SPOTLIGHT
 CONSTANTINFINITE PROJECTION SHARPDISTANT DISTANT LASER SPHERE MAPSPHERE"
[LuxCore][19.687]   opencl.cpu.use = 0
[LuxCore][19.687]   opencl.gpu.use = 1
[LuxCore][19.687]   opencl.devices.select = "1"
[LuxCore][19.687]   sampler.type = "TILEPATHSAMPLER"
[LuxCore][19.687]   film.width = 471
[LuxCore][19.687]   film.filter.width = 1.5
[LuxCore][19.687]   scene.epsilon.min = 9.9999997473787516e-06
[LuxCore][19.687]   film.height = 265
[LuxCore][19.687]   lightstrategy.type = "LOG_POWER"
[LuxCore][19.687]   scene.epsilon.max = 0.10000000149011612
[LuxCore][19.687]   renderengine.type = "RTPATHOCL"
[LuxCore][19.687]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][19.687]   path.forceblackbackground.enable = 0
[LuxCore][19.687]   renderengine.seed = 1
[LuxCore][19.687]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][19.687]   film.outputs.0.index = 0
[LuxCore][19.687]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][19.687]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][19.687]   film.imagepipelines.0.1.type = "TONEMAP_AUTOLINEAR"
[LuxCore][19.687]   film.imagepipelines.0.2.type = "TONEMAP_LINEAR"
[LuxCore][19.687]   film.imagepipelines.0.2.scale = 0.5
[LuxCore][19.687]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][19.703]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][19.703]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][19.703]   batch.halttime = 0
[LuxCore][19.703]   batch.haltspp = 0
[LuxCore][19.703]   batch.haltthreshold = 0.0001
[LuxCore][19.703]   batch.haltthreshold.stoprendering.enable = 0
Export took 0.1 s
[LuxCore][19.703] Film resolution: 471x265
[SDL][19.703] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][19.703] Image pipeline: film.imagepipelines.0
[SDL][19.703] Image pipeline step 0: NOP
[SDL][19.703] Image pipeline step 1: TONEMAP_AUTOLINEAR
[SDL][19.703] Image pipeline step 2: TONEMAP_LINEAR
[SDL][19.703] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png
]
[LuxRays][19.703] OpenCL Platform 0: NVIDIA Corporation
[LuxRays][19.703] Device 0 name: NativeThread
[LuxRays][19.703] Device 0 type: NATIVE_THREAD
[LuxRays][19.703] Device 0 compute units: 1
[LuxRays][19.703] Device 0 preferred float vector width: 4
[LuxRays][19.703] Device 0 max allocable memory: 0MBytes
[LuxRays][19.703] Device 0 max allocable memory block size: 0MBytes
[LuxRays][19.703] Device 1 name: GeForce GTX 1060 6GB
[LuxRays][19.703] Device 1 type: OPENCL_GPU
[LuxRays][19.703] Device 1 compute units: 10
[LuxRays][19.718] Device 1 preferred float vector width: 1
[LuxRays][19.718] Device 1 max allocable memory: 6144MBytes
[LuxRays][19.718] Device 1 max allocable memory block size: 1536MBytes
[LuxRays][19.718] Preprocessing DataSet
[LuxRays][19.718] Total vertex count: 0
[LuxRays][19.718] Total triangle count: 0
[LuxRays][19.718] Preprocessing DataSet done
[LuxRays][19.765] Creating 1 intersection device(s)
[LuxRays][19.765] Allocating intersection device 0: GeForce GTX 1060 6GB (Type =
 OPENCL_GPU)
[LuxCore][19.765] OpenCL devices used:
[LuxCore][19.765] [GeForce GTX 1060 6GB Intersect]
[LuxCore][19.765]   Device OpenCL version: OpenCL 1.2 CUDA
[LuxCore][19.765] Native devices used: 0
[LuxRays][19.765] Adding DataSet accelerator: BVH
[LuxRays][19.765] Total vertex count: 0
[LuxRays][19.765] Total triangle count: 0
[LuxRays][19.765] Empty BVH
[LuxCore][19.765] Configuring 1 OpenCL render threads
[LuxCore][19.765] Configuring 0 native render threads
Session created in 0.1 s
[LuxCore][19.905] Tiles initialization time: 0.00 secs
[LuxCore][19.921] [PathOCLBaseRenderEngine] OpenCL max. page memory size: 157286
4Kbytes
[LuxCore][19.921] Compile Geometry
[LuxCore][19.921] Scene geometry compilation time: 0ms
[LuxCore][19.921] Compile 0 Textures
[LuxCore][19.921] Textures compilation time: 0ms
[LuxCore][19.921] Compile 0 Materials
[LuxCore][19.921] Material compilation time: 0ms
[LuxCore][19.921] Compile Lights
[LuxCore][19.921] Lights compilation time: 0ms
[LuxCore][19.921] Compile ImageMaps
[LuxCore][19.921] Image maps page(s) count: 0
[LuxCore][19.921] Image maps compilation time: 0ms
[LuxCore][19.921] Always enabled OpenCL code: MATTE ROUGHMATTE MATTETRANSLUCENT
ROUGHMATTETRANSLUCENT GLOSSY2 GLOSSYTRANSLUCENT GLASS ARCHGLASS ROUGHGLASS MIRRO
R METAL2 NULLMAT HAS_BUMPMAPS GLOSSY2_ABSORPTION GLOSSY2_MULTIBOUNCE HOMOGENEOUS
_VOL CLEAR_VOL IMAGEMAPS_BYTE_FORMAT IMAGEMAPS_HALF_FORMAT IMAGEMAPS_1xCHANNELS
IMAGEMAPS_3xCHANNELS INFINITE TRIANGLELIGHT SKY2 SUN POINT MAPPOINT SPOTLIGHT CO
NSTANTINFINITE PROJECTION SHARPDISTANT DISTANT LASER SPHERE MAPSPHERE
[LuxCore][19.921] Compile Geometry
[LuxCore][19.921] Scene geometry compilation time: 0ms
[LuxCore][19.921] Compile 0 Textures
[LuxCore][19.921] Textures compilation time: 0ms
[LuxCore][19.921] Compile 0 Materials
[LuxCore][19.921] Material compilation time: 0ms
[LuxCore][19.921] Compile Lights
[LuxCore][19.937] Lights compilation time: 16ms
[LuxCore][19.937] Compile ImageMaps
[LuxCore][19.937] Image maps page(s) count: 0
[LuxCore][19.937] Image maps compilation time: 0ms
[LuxCore][19.937] Starting 1 OpenCL render threads
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] RADIANCE_PER_PIXEL_NOR
MALIZEDs[0] buffer size: 1954Kbytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] RADIANCE_PER_PIXEL_NOR
MALIZEDs[0] buffer size: 1954Kbytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] Camera buffer size: 54
48bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] Lights buffer size: 32
8bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] Env. light indices buf
fer size: 4bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] Env. light distributio
ns buffer size: 1028Kbytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] LightsDistribution buf
fer size: 16bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] InfiniteLightSourcesDi
stribution buffer size: 16bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] Ray buffer size: 6144K
bytes
[LuxRays][19.937] [Device GeForce GTX 1060 6GB Intersect] RayHit buffer size: 25
60Kbytes
[LuxCore][19.937] [PathOCLBaseRenderThread::0] Size of a GPUTask: 448bytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] GPUTask buffer size: 5
7344Kbytes
[LuxCore][19.952] [PathOCLBaseRenderThread::0] Size of a GPUTask DirectLight: 72
bytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] GPUTaskDirectLight buf
fer size: 9216Kbytes
[LuxCore][19.952] [PathOCLBaseRenderThread::0] Size of a GPUTask State: 276bytes

[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] GPUTaskState buffer si
ze: 35328Kbytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] GPUTask Stats buffer s
ize: 512Kbytes
[LuxCore][19.952] [PathOCLBaseRenderThread::0] Size of a Sample: 60bytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] Sample buffer size: 76
80Kbytes
[LuxCore][19.952] [PathOCLBaseRenderThread::0] Sample dimensions: 69
[LuxCore][19.952] [PathOCLBaseRenderThread::0] Size of a SampleData: 8bytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] SampleData buffer size
: 1024Kbytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] PathVolumeInfo buffer
size: 5632Kbytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] DirectLightVolumeInfo
buffer size: 5632Kbytes
[LuxRays][19.952] [Device GeForce GTX 1060 6GB Intersect] Pixel Filter Distribut
ion buffer size: 33Kbytes
[LuxCore][19.968] [PathOCLBaseRenderThread::0] Defined symbols:  -D LUXRAYS_OPEN
CL_KERNEL -D SLG_OPENCL_KERNEL -D RENDER_ENGINE_RTPATHOCL -D PARAM_RAY_EPSILON_M
IN=1.000000e-05f -D PARAM_RAY_EPSILON_MAX=1.000000e-01f -D PARAM_LIGHT_WORLD_RAD
IUS_SCALE=1.050000e+00f -D PARAM_ACCEL_BVH -D PARAM_FILM_RADIANCE_GROUP_0 -D PAR
AM_FILM_RADIANCE_GROUP_COUNT=1 -D PARAM_ENABLE_TEX_CONST_FLOAT -D PARAM_ENABLE_T
EX_CONST_FLOAT3 -D PARAM_ENABLE_TEX_IMAGEMAP -D PARAM_ENABLE_TEX_NORMALMAP -D PA
RAM_ENABLE_TEX_FRESNELCOLOR -D PARAM_ENABLE_TEX_FRESNELCONST -D PARAM_ENABLE_MAT
_MATTE -D PARAM_ENABLE_MAT_ROUGHMATTE -D PARAM_ENABLE_MAT_MIRROR -D PARAM_ENABLE
_MAT_GLASS -D PARAM_ENABLE_MAT_ARCHGLASS -D PARAM_ENABLE_MAT_NULL -D PARAM_ENABL
E_MAT_MATTETRANSLUCENT -D PARAM_ENABLE_MAT_ROUGHMATTETRANSLUCENT -D PARAM_ENABLE
_MAT_GLOSSY2 -D PARAM_ENABLE_MAT_GLOSSY2_ABSORPTION -D PARAM_ENABLE_MAT_GLOSSY2_
MULTIBOUNCE -D PARAM_ENABLE_MAT_METAL2 -D PARAM_ENABLE_MAT_ROUGHGLASS -D PARAM_E
NABLE_MAT_CLEAR_VOL -D PARAM_ENABLE_MAT_HOMOGENEOUS_VOL -D PARAM_ENABLE_MAT_GLOS
SYTRANSLUCENT -D PARAM_HAS_PASSTHROUGH -D PARAM_CAMERA_TYPE=0 -D PARAM_HAS_INFIN
ITELIGHT -D PARAM_HAS_CONSTANTINFINITELIGHT -D PARAM_HAS_SKYLIGHT2 -D PARAM_HAS_
SUNLIGHT -D PARAM_HAS_SHARPDISTANTLIGHT -D PARAM_HAS_DISTANTLIGHT -D PARAM_HAS_P
OINTLIGHT -D PARAM_HAS_MAPPOINTLIGHT -D PARAM_HAS_SPOTLIGHT -D PARAM_HAS_PROJECT
IONLIGHT -D PARAM_HAS_LASERLIGHT -D PARAM_HAS_TRIANGLELIGHT -D PARAM_HAS_SPHEREL
IGHT -D PARAM_HAS_MAPSPHERELIGHT -D PARAM_HAS_ENVLIGHTS -D PARAM_HAS_BUMPMAPS -D
 PARAM_HAS_VOLUMES -D SCENE_DEFAULT_VOLUME_INDEX=4294967295 -D PARAM_MAX_PATH_DE
PTH=7 -D PARAM_MAX_PATH_DEPTH_DIFFUSE=5 -D PARAM_MAX_PATH_DEPTH_GLOSSY=5 -D PARA
M_MAX_PATH_DEPTH_SPECULAR=6 -D PARAM_RR_DEPTH=3 -D PARAM_RR_CAP=5.000000e-01f -D
 PARAM_SQRT_VARIANCE_CLAMP_MAX_VALUE=0.000000e+00f -D PARAM_IMAGE_FILTER_TYPE=5
-D PARAM_IMAGE_FILTER_WIDTH_X=1.500000e+00f -D PARAM_IMAGE_FILTER_WIDTH_Y=1.5000
00e+00f -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_X=1 -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_
Y=1 -D PARAM_USE_PIXEL_ATOMICS -D PARAM_SAMPLER_TYPE=3 -D PARAM_RTPATHOCL_PREVIE
W_RESOLUTION_REDUCTION=4 -D PARAM_RTPATHOCL_PREVIEW_RESOLUTION_REDUCTION_STEP=8
-D PARAM_RTPATHOCL_RESOLUTION_REDUCTION=1
[LuxCore][19.983] [PathOCLBaseRenderThread::0] Compiling kernels
[LuxCore][20.217] [PathOCLBaseRenderThread::0] PathOCL kernel compilation error
ERROR clBuildProgram[-9999]:
ptxas application ptx input, line 29422; error   : Call has wrong number of para
meters
ptxas application ptx input, line 29422; error   : Type of argument does not mat
ch formal parameter '%VAParam'
ptxas fatal   : Ptx assembly aborted due to errors

**Comment by Theverat** [comment]
Did you also compile the latest LuxCore sources and replaced the binaries?

**Comment by andreimd87** [comment]
i didnt compile. i just repleaced them in the bin folder. as always do

**Comment by Theverat** [comment]
If you want to use the latest BlendLuxCore (Python) code, you also have to use the latest LuxCore (C++/OpenCL) code.
So you have two options:
* Use only the official releases from https://luxcorerender.org/download/
* Compile the latest LuxCore binaries

**Comment by Theverat** [comment]
See also #104 where someone had the same problem.
