### ISSUE TITLE
Orthographic camera in final render does not match 3D view

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#181]
https://forums.luxcorerender.org/viewtopic.php?f=4&p=4591#p4591

**Comment by neo2068** [comment]
I have fixed the issue when unit scale isn't 1. There is a remaining issue when you change the unit scale with active viewport rendering. Then the view is scaled accordingly but should stay the same.

**Comment by Theverat** [comment]
> There is a remaining issue when you change the unit scale with active viewport rendering.

I would not worry about that. Many other properties are not updated correctly when the unit scale is chagnged during viewport rendering (e.g. the materials/volumes are not updated, objects are not re-exported etc.).
Getting this right would require a lot of work for very little gain - after all, this happens almost never (you should pick a unit scale at the start of a project and stick to it) and if it happens, the user can just restart the viewport render as a workaround.
