### ISSUE TITLE
Starting final and viewport render at the same time leads to errors

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#183]
https://forums.luxcorerender.org/viewtopic.php?f=4&p=4645#p4634

**Comment by Dade916** [comment]
Yes, it is, it should not be a problem as far as you don't share any object like Scene, etc. between different render sessions.

**Comment by Theverat** [comment]
I have done further testing on this:

I can reproduce the AttributeError when setting the suggested clamping property, however there is now a safeguard so the render doesn't end, and in the long run this problem should be solved by not changing any property during render (see #221).

On topic:
When I start a viewport render, wait a bit, then start a final render, the viewport render stops with one of these error messages:
```
Exception ignored in: <bound method LuxCoreRenderEngine.__del__ of <bpy_struct, LuxCoreRenderEngine invalid>>
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/engine/__init__.py", line 59, in __del__
    if getattr(self, "session", None):
ReferenceError: StructRNA of type LuxCoreRenderEngine has been removed
```
```
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/engine/__init__.py", line 117, in view_draw
    if self.session is None:
AttributeError: 'LuxCoreRenderEngine' object has no attribute 'session'
```

The other way around (starting first final render, then viewport render) causes no issues.

**Comment by Theverat** [comment]
I can not reproduce this problem anymore.
