### ISSUE TITLE
Not able to remove the add on (LuxCore Integration)

### ISSUE THREAD

**Issue by mino00** [LuxCoreRender/BlendLuxCore#184]
#### Software Version
Blender 2.79b/BlendLuxCore 2.0 64b w/openCL

**Comment by mino00** [comment]
This is the BlendLux Core OpenCL

**Comment by Theverat** [comment]
If you are not going to fill in the issue template text, can you at least delete it please?

You probably mean that you press the remove button in the Blender user preferences, and it throws an exception, is that correct?
Try to delete the addon manually by opening the addon folder and deleting through the file browser of your OS.

**Comment by mino00** [comment]
@Theverat Thanks for the response and I had to leave abruptly before I was able to finish.

Yes, that is what I mean. And yes, I did manually purge all the files from the OS and it still didn't fix. I was having trouble with the Luxcore engine showing up in the drop down on the console and being able to use it altogether but it seems to be working now. Ended up just deleting Blender and the files altogether and reinstalling.

**Comment by Theverat** [comment]
> I did manually purge all the files from the OS and it still didn't fix.

In that case maybe the addon was also installed in some other location?

By the way, this issue is caused by the fact that the addon loads pyluxcore as a library (DLL).
While a DLL is loaded you can't delete it.
So I'm not sure we can fix this in the addon.
