### ISSUE TITLE
Installation error version 2.1 alpha 2: ImportError: DLL load failed:

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/BlendLuxCore#185]
First, check if your problem was already reported:
Checked, but I did not find any issue related to installation of version 2.1 alpha 2

#### System Information
Betriebssystem: Windows 10 - Business Edition
Version: 10.0.17134
Anwendungsarchitektur: x64
Systemarchitektur: x64
Anzahl logischer Prozessoren: 8
Prozessorgeschwindigkeit: 3.4 GHz
Integrierter Speicher: 32706.1 MB
Platform #0
	Platform Name: AMD Accelerated Parallel Processing
	Platform Vendor: Advanced Micro Devices, Inc.
	Platform Version: OpenCL 2.1 AMD-APP (2580.6)
	Platform Profile: FULL_PROFILE
	Platform Extensions: cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices 
	Number of devices: 3
		Device: #0
			Device Name: Hawaii
			Device Board Name: AMD Radeon (TM) R9 390 Series
			Device Vendor: Advanced Micro Devices, Inc.
			Device OpenCL C Version: OpenCL C 2.0 
			Device Profile: FULL_PROFILE
			Device Version: OpenCL 2.0 AMD-APP (2580.6)
			Device Extensions: cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash 
		Device: #1
			Device Name: Hawaii
			Device Board Name: AMD Radeon (TM) R9 390 Series
			Device Vendor: Advanced Micro Devices, Inc.
			Device OpenCL C Version: OpenCL C 2.0 
			Device Profile: FULL_PROFILE
			Device Version: OpenCL 2.0 AMD-APP (2580.6)
			Device Extensions: cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash 
		Device: #2
			Device Name: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
			Device Vendor: GenuineIntel
			Device OpenCL C Version: OpenCL C 1.2 
			Device Profile: FULL_PROFILE
			Device Version: OpenCL 1.2 AMD-APP (2580.6)
			Device Extensions: cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_spir cl_khr_gl_event 

#### Software Version

* Blender version: 2.79b
version: 2.79 (sub 0), branch: master, commit date: 2018-03-22 14:10, 
* LuxCore version: 2.1 alpha 2
ww_icl_redist_intel64_2018.3.210 is installed

#### Error message from Blender console
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

#### Short description of error
Installation with Blender preferences does not work on my Windows pc.

#### Exact steps for others to reproduce the error
Install luxcorerender version 2.0 from zip file BlendLuxCore-v2.0-win64-opencl with Blender preferences.
Restart Blender.
Update with luxcore addon and restart blender.
Render Engine luxcore is missing.
Luxcore addon is not check marked.
Error will be thrown trying to check mark.

Please advise. Thank you.

**Comment by Theverat** [comment]
Did it work before? What was the last working version?
Have you tried the NoOpenCL-version, does it work?

**Comment by FarbigeWelt** [comment]
The last install working is version 2.1 alpha 0.. (openCl)

 I removed 2.1 alpha 2 manually and installed version 2.0 without openCl and tried to update to 2.1 alpha 2.
 This results with following trace back:

Read prefs: C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
cmolcore imported with success! v1.01
addon_utils.disable: BlendLuxCore not disabled.
Modules Installed (BlendLuxCore) from 'C:\\Users\\Michael\\Downloads\\BlendLuxCore-v2.0-win64.zip' into 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
pyluxcore version: 2.0
=======================================
Changing version to v2.1alpha2
Current version: v2.0

Downloading: https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.1alpha2/BlendLuxCore-v2.1alpha2-win64.zip
Download finished
Extracting zip to C:\Users\Michael\AppData\Local\Temp\tmp0b1oze9f
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll' -> 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll.old'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 208, in execute
    recursive_overwrite(extracted_blendluxcore, blendluxcore_dir)
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 39, in recursive_overwrite
    os.path.join(dest, f))
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 39, in recursive_overwrite
    os.path.join(dest, f))
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 50, in recursive_overwrite
    shutil.move(dest, dest + ".old")
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by Theverat** [comment]
This is caused by a bug in the updater which was fixed after v2.1alpha0: https://github.com/LuxCoreRender/BlendLuxCore/commit/c93e650b9af18106c56ce658c9b936c3458aba69

So you can only use the updater to change the version from anything before v2.1alpha0 to v2.1alpha0, or from v2.1alpha1 to v2.1alpha2.

**Comment by FarbigeWelt** [comment]
And how may I install v2.1alpha1? 

I remember to to try it once but failed. 
Read prefs: C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
cmolcore imported with success! v1.01
pyluxcore version: 2.1alpha0
Updating OpenCL device list
=======================================
Changing version to v2.1alpha1
Current version: v2.1alpha0

Downloading: https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.1alpha1/BlendLuxCore-v2.1alpha1-win64-opencl.zip
Download finished
Extracting zip to C:\Users\Michael\AppData\Local\Temp\tmp152j_q9u
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll' -> 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll.old'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 208, in execute
    recursive_overwrite(extracted_blendluxcore, blendluxcore_dir)
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 39, in recursive_overwrite
    os.path.join(dest, f))
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 39, in recursive_overwrite
    os.path.join(dest, f))
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\operators\update.py", line 50, in recursive_overwrite
    shutil.move(dest, dest + ".old")
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Michael\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by FarbigeWelt** [comment]
Closing was not intended...

**Comment by FarbigeWelt** [comment]
I've tried to install
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.1alpha1/BlendLuxCore-v2.1alpha1-win64-opencl.zip

But after restarting blender I get the following trace back:
Read prefs: C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
cmolcore imported with success! v1.01
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 16, in <module>
    from . import engine, handlers, nodes, operators, properties, ui
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\__init__.py", line 2, in <module>
    from . import final, preview, viewport
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\engine\final.py", line 4, in <module>
    from ..utils import render as utils_render
  File "C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\utils\render.py", line 3, in <module>
    from ..handlers.draw_imageeditor import TileStats
ImportError: No module named 'BlendLuxCore.handlers.draw_imageeditor'

**Comment by Theverat** [comment]
Did you install the intel stuff?
https://software.intel.com/sites/default/files/managed/59/aa/ww_icl_redist_msi_2018.3.210.zip
It was mentioned at the end of this post:
https://forums.luxcorerender.org/viewtopic.php?f=9&p=4706#p4693

**Comment by FarbigeWelt** [comment]
Yes, ww_icl_redist_intel64_2018.3.210 is installed is installed.

**Comment by Dade916** [comment]
> ImportError: No module named 'BlendLuxCore.handlers.draw_imageeditor'

This doesn't look anymore like the original DLL related problem (?)

**Comment by FarbigeWelt** [comment]
Yes, you are right. I tried different approaches now. Installing directly from BlendLuxCore-v2.1alpha2-win64-opencl. DLL related issue seems to be solved. But I get still errors.

Interesting: luxcorerender-v2.1alpha2-win64-opencl, here I get the luxcoreui.exe running from CMD and I am able to chose and render a scene exported with luxcore v2.0.

**Comment by Dade916** [comment]
Any particular reason to use the old alpha1 instead of the now available alpha2 (https://forums.luxcorerender.org/viewtopic.php?f=9&t=472) ?

**Comment by FarbigeWelt** [comment]
No, I don't need alpha 1.

I really like to install alpha2 but installation failed. And I tried different ways. From 2.0, from 2.1alpha1, from zipfile directly after cleaning addon directory.

**Comment by FarbigeWelt** [comment]
Finally, I was able to install Blender addon from zip file BlendLuxCore-v2.1alpha2-win64.  :-)
Addon runs well in View port and renders simple scences. But may crash together with blender in some cases. Because I forgot to save the crashing scence before starting render and lost the scence. I don't know the reason for the crash yet. 
![wooden floor](https://user-images.githubusercontent.com/39385570/42736009-92d506de-885e-11e8-9cf8-0012bacef20f.png)
Denoising is really appreciated.
