### ISSUE TITLE
Light group bug

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#186]
https://forums.luxcorerender.org/viewtopic.php?f=4&p=4707#p4707

Only lights in the default light group seem to be visible, whenever a light is put into another light group, it does not contribute light anymore.

**Comment by neo2068** [comment]
It seems to be a LuxCore bug. When you export the scene and open it with LuxCoreGUI there is the same behaviour. In the example scene only one radiance group is available although two groups are defined.

**Comment by Theverat** [comment]
> It seems to be a LuxCore bug.

Thanks for the investigation, I'm closing this one as invalid then.
