### ISSUE TITLE
Null material with transmission between 1,1,1 and 0,0,0 behaves strange.

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/BlendLuxCore#189]
First, check if your problem was already reported:
Yes, is checked.

#### System Information

Windows 10 Professional
AMD R290
AMD R390x

#### Software Version

* Blender version: (example: 2.79b)
* LuxCore version: 2.0, CPU BiDir

#### Error message from Blender console
None. 

#### Short description of observation
Reduction of opacity reduces visibility of an object with matte material til invisibility.

Exterior and interior volume can be defined. Interior volume seems not to have any effect for matte material. So far material matte behaves with opacity for me as expected.

Null is usefull to have a material which reveals interior volume if transmission color is white. 

If transmission color is black object gets black, this is logical. 
If transmission is grey (50%) interior volume gets more saturated, borders of the object darker and object keeps transparent. The saturation is quite an interssting effect I don't understand. 

B.Y.O.B mentiond opacity is faster than mix with null and should lead to the same result. This is not the case. Opacity does not reveal interior volume for material matte. 

Please see different pictures  here:
https://forums.luxcorerender.org/viewtopic.php?f=2&t=474&start=30#p4928
https://forums.luxcorerender.org/viewtopic.php?f=2&t=474&start=30#p4934

and Blender scene:
https://forums.luxcorerender.org/viewtopic.php?f=2&t=474&p=4950#p4950

There are different layers in the blend file. Please check layer 1 or 2.

**Comment by FarbigeWelt** [comment]
![opacity vs mix with null grey](https://user-images.githubusercontent.com/39385570/42728754-544a9ccc-87c2-11e8-826f-abe897a47c11.png)
![opacity vs mix with null white](https://user-images.githubusercontent.com/39385570/42728755-546c2ebe-87c2-11e8-90fb-0fbd0178e754.png)
[Opacity vs Mix with Null.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2195295/Opacity.vs.Mix.with.Null.zip)

**Comment by Theverat** [comment]
In the example scene, the "MixWithNull" material contains a mistake: The mix material has opacity set to 0.5, it should be 1.

![scrn_2018-07-15_00-14-10](https://user-images.githubusercontent.com/1584761/42728814-466fb6bc-87c4-11e8-8330-028eef3cbb4a.png)

**Comment by FarbigeWelt** [comment]
That is correct you are fast.
Meanhwile I also think Null material behaves actually very predictable.
![null white and null grey](https://user-images.githubusercontent.com/39385570/42728833-b7c1fc62-87c4-11e8-8672-c8d7c580894d.png)

**Comment by FarbigeWelt** [comment]
Glass material reveals volume but different as Null material. Why does glass absorbs light and does not show any specular lights even with transmission and reflection set to white?
![glass with volume and null white](https://user-images.githubusercontent.com/39385570/42728962-fcf14802-87c8-11e8-9777-c0c2168c4f22.png)

**Comment by FarbigeWelt** [comment]
One may close this issue "Null material with transmission between 1,1,1 and 0,0,0 behaves strange. #189". 
Because all observed effects of opacity and Null material are explainable. 
Extended and corrected blender file, see attachment.
[Opacity vs Mix with Null_2.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2195317/Opacity.vs.Mix.with.Null_2.zip)

**Comment by Theverat** [comment]
> Why does glass absorbs light and does not show any specular lights even with transmission and reflection set to white?

Because the IOR of the volume is near 1.
The lower the IOR, the weaker the reflections, with no reflections when IOR = 1.

**Comment by FarbigeWelt** [comment]
I use heterogenous volume for the red scattering effect of the interiour volme. Homogenous volume does not support this effect. It is slower but fancier.

Yes, there is a difference. Do you assume they should behave the same way, opacity and null material?

I assume they really should behave differently. 

For me, opacity should reduce visibility overall including surface and volume. 

Whereas null material is a specific material which does not have any surface this means interior volume is visible. 

I compare using null material with looking at gaseous Brom. There is absorbance in the room but without clear borders . The Brom gas mixes softly with air without any noticable surface effects like reflection  Okay, there may be 3D waves with noise if mixing is turbulent, but this is another topic.

The higher the concentration the smaller  the transmission, the darker interior volme. 
Transmission = 1 - Absorbance. 

Interior volume gets visible in material glass if glass is transparent.
Considering IOR as 1, material should behave like null material. But there is a difference. There is absorbance somewhere.
![glass with volume ior 1 and null white](https://user-images.githubusercontent.com/39385570/42733580-a946fe20-8833-11e8-9b6a-51a2eda8669d.png)
As you mentioned, with higher IOR settings reflection increases. Thank you for the tip. This is clear now for me. Null material has the same interior material but keeps as is beacause there is no surface effect. 
![glass with volume ior 1 5 and null white](https://user-images.githubusercontent.com/39385570/42733642-34822e28-8835-11e8-8aa8-9e8b1fa8a65f.png)

In my opinion glossy coating should be the opposite of null material. This means surface effect but without any internal material per default or the one set as base. But according my observations glossy coating acts different. But this is another topic.
