### ISSUE TITLE
Blender texture wood: Difference in View Port and Render

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/BlendLuxCore#190]
First, check if your problem was already reported:
Yes, is checked.
System Information
Windows 10 Professional
AMD R290
AMD R390x
Software Version
Blender version: (example: 2.79b)
LuxCore version: 2.0, CPU Path
Error message from Blender console
None.
Short description of observation
Blender texure wood is calculated differently in View Port and Render.

**Comment by FarbigeWelt** [comment]
![blender texture wood view port and render](https://user-images.githubusercontent.com/39385570/42733748-3d60cdae-8837-11e8-87a0-4947354844d9.jpg)
[Wood.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2195695/Wood.zip)

**Comment by FarbigeWelt** [comment]
View port is very usefull for finding reasonable parameters for Blender Texture and 3D mapping. View port and render sould be caluclated the same way.

**Comment by Theverat** [comment]
Are you using local 3D mapping?
If yes, it could be this bug: #66 (fixed in v2.1alpha)

**Comment by FarbigeWelt** [comment]
Great, you fixed it!
