### ISSUE TITLE
Light groups don't work or lead to Blender crash, LC 2.1 a2

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/BlendLuxCore#191]
First, check if your problem was already reported:
Yes, is checked. Keywords: area, lights, emission, lightgroups

System Information
Windows 10 Professional
AMD R290
AMD R390x
Software Version
Blender version: (example: 2.79b)
LuxCore version: 2.1 alpha 2, CPU BiDir
Error message from Blender console
None.
Short description of observation
Blender crashes if there are more than 1 light group added when rendering is started.
Addon runs with 1 light group but light group has no effect, lights in this light group keep dark.
Effect observed with area light and emission for material matte. Emission works if there is not any light group set. 
[Wood.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2196068/Wood.zip)

Reproduction steps.
For dark lights: Set light group in material lights.
For Blender crash add further light group.

**Comment by Theverat** [comment]
I can not reproduce any of the problems.
Some observations:
* You say you used CPU BiDir, but in the file, Path is selected as engine
* The denoiser is enabled. Do the problems only happen with denoiser on?

It's also not clear to me if the problems appear in final or viewport render. I only tested final render so far.

**Comment by FarbigeWelt** [comment]
Well, okay, your results are surprising. I have crashes or black lights for both CPU path and bidir. I‘ll try again this evening and load scenes up.

**Comment by FarbigeWelt** [comment]
[Third light groups used for area lights crashes.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2199221/Third.light.groups.used.for.area.lights.crashes.zip)
[Third light group for Sky set crashes.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2199222/Third.light.group.for.Sky.set.crashes.zip)
On my PC both of these blender files crash when starting render. Works more or less in view port, may crash if you zoom in deeper.

**Comment by Theverat** [comment]
Ok this time I made sure to test properly, with version v2.1alpha2.

* I can reproduce both crashes on Windows 7, just by pressing F12.
* I can not reproduce the crashes on Linux, both scenes work.

I remember there was a bug regarding light source initialization, Dade fixed it, so this problem might already be solved in the latest sources.
I am currently compiling on Windows and will check if it still crashes with latest sources.

**Comment by Theverat** [comment]
Meh, compilation failed. I'll try to fix it tomorrow.

**Comment by Theverat** [comment]
I finally fixed my build environment.
The crashes are indeed fixed. I think it was this bug: LuxCoreRender/LuxCore#121
