### ISSUE TITLE
Zooming in render preview

### ISSUE THREAD

**Issue by AndreasReschGFX** [LuxCoreRender/BlendLuxCore#193]
While I'm in render preview and camera view, zooming into the scene enlarges the view but the objects are not zoomed along with the border. They stay the same.
In user view, zooming works well in the render preview.

Windows 7 64-Bit, Blender 2.79b, Luxcore 2.1 Alpha2

Cheers,
Andreas

**Comment by Theverat** [comment]
Can confirm, I also stumbled upon this recently.

**Comment by AndreasReschGFX** [comment]
Well, my unit scale is at 0.01.

**Comment by AndreasReschGFX** [comment]
Yeah - when unit scale is at 1, it works. Seems as if the further you get away from 1, the more obvious the issue is.

**Comment by Theverat** [comment]
I fixed it in commit cd8d961ddbf763ea744e9372bdcb3def5e5d82ce, by the way.

**Comment by AndreasReschGFX** [comment]
It works without render render region. When I have a render region selected, it's not zooming. Have you checked that?
What's the best way to update by addon with the files from Github? I have downloaded the commit as a ZIP file, but when I replace the folder with the files from Github, I get an error when I activate the addon. replacing the files individually works, but it's quite tedious.

**Comment by Theverat** [comment]
Damn, I didn't check border render, this one is still broken.

> What's the best way to update by addon with the files from Github?

Clone the github repo, then also clone the LuxCore repo and the corresponding compilation repo for your OS. Then compile LuxCore. Once you have the latest LuxCore binaries, use the get_binaries script in the BlendLuxCore/bin/ folder. For a more detailed explanation, see https://wiki.luxcorerender.org/Compiling_LuxCore

Your only other option is to wait for the next alpha/beta release.
The Blender addon requires the corresponding LuxCore binaries, you should not mix it with old binaries.

**Comment by AndreasReschGFX** [comment]
Cheers. I'll rather wait then.
