### ISSUE TITLE
UX: avoid all light group off

### ISSUE THREAD

**Issue by canonex** [LuxCoreRender/BlendLuxCore#194]
#### Enhancement:
avoid having all light groups off and thus a black render.

This can be caused by:
- easy case: switching off all light groups and forget to switch, at least one of them, on
- switch off the default group, removing all other group

If you are not paying attention or if you are learning LuxCoreRender you get a black render.

I suggest to prompt a warning or to automatically switch on the default group if it is the only one.

Thank you,
Riccardo

#### Software Version

* Blender version: 2.79
* LuxCore version: 2.1 alpha 2

**Comment by Theverat** [comment]
Thanks for the suggestion!
