### ISSUE TITLE
why reload whole scene for every frame in animation?

### ISSUE THREAD

**Issue by Eddylib** [LuxCoreRender/BlendLuxCore#202]
#### System Information
intel i7
4x Nvidia TITAN Xp
ubuntu 16.04

#### Software Version

* Blender version:   2.79b
* LuxCore version:  2.0

#### Question about how to accelerate animation rendering

After the scene, material, and camera path being set, start animation.
I can see for every single frame, the scene was reloaded to render(export object xxxx), and the openCL kernels was recompiling, finally rendering. 
My scene is large, this process takes lots of time.
If it's necessary that reload scene for every frame (for my case, just camera pose changed)?
If I can do something to avoid reload scene, recompile openCL kernels...?

**Comment by Eddylib** [comment]
Ok... thanks a lot.  I will try to export the scene and utilize the LuxCoreAPI to control camera trajectory.

**Comment by Dade916** [comment]
OpenCL kernel shouldn't be re-compiled if you are moving only the camera, are you sure it is ?
