### ISSUE TITLE
Gain scale in Sky setting and tonemapping

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/BlendLuxCore#203]
I'm testing with tonemapping turned off.
The amount of light is too much for Sky when the gain is set to 1. I have to use 0.00005 for a normal look. People would not notice this when tonemapping is on. But it will distort the other lamps' gain. in the start-up blender scene, if the sky's gain is set to 1 and tonemapping is on, you will not see any change when you change the lamp's gain because sky is too bright even at 1. I know it is not a big deal but for some new users, it is confusing to see there is no way to adjust lamp when sky is set.

**Comment by Theverat** [comment]
See my post here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=534&p=5273#p5268

**Comment by frankyifei** [comment]
So this is about physical correct. OK, I understand now.
