### ISSUE TITLE
[Question] Transparent Shadow

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/BlendLuxCore#208]
How to make transparent shadows, as in this example? For shadows to depend on the thickness of the mesh:
![1](https://user-images.githubusercontent.com/7983249/45234232-c48ea780-b2dd-11e8-9847-8ca018386b26.jpg)

**Comment by Theverat** [comment]
Use a transmissive material, for example glass, but leave all colors white.
Then assign an interior volume and choose the absorption color and depth.
https://wiki.luxcorerender.org/LuxCoreRender_Volumes

Example file and images:
[volumetric_glass.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2362019/volumetric_glass.blend.zip)
![absorption_example](https://user-images.githubusercontent.com/1584761/45235263-98245c80-b2d8-11e8-9397-60bceeb80ec8.jpg)
![2018-09-07_19-58-52](https://user-images.githubusercontent.com/1584761/45235281-ad00f000-b2d8-11e8-8b2f-718dea6a7694.png)

**Comment by PavelBlend** [comment]
In my opinion these are caustics. I turned the sun and the shadows became black. And I need the shadow to be transparent. Like here:
![cycles](https://user-images.githubusercontent.com/7983249/45251743-f93d4600-b353-11e8-963b-13e4c7810215.jpg)
I got this way:
![luxcore](https://user-images.githubusercontent.com/7983249/45251750-15d97e00-b354-11e8-95ae-31f9ff3d37e3.jpg)
Here is the scene:
[luxcore_test_vol.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2363122/luxcore_test_vol.zip)

**Comment by Theverat** [comment]
Considering the material you have there, the second image looks correct to me.
Do you want to fake the effect in the first image? Or do you want to simulate a different material?
How did you create the first image?

**Comment by PavelBlend** [comment]
I want to make an effect like in the first image.
And the first image I made in Cycles. But I want to do the same in LuxCore (+caustics).

**Comment by Dade916** [comment]
You need to use BiDir render engine or an intersectable (and easy to find) light source with Path render engine (like area lights, HDR light, etc.). Otherwise it is not possible to render caustics.

Note: sun is a very small (and hard to find) intersectable light source and you can notice a vague (still correct) caustic on the ground. Cycles results looks like a huge fake (try to render the scene with BiDir to have an idea of the correct result).

**Comment by PavelBlend** [comment]
I think these issue can be closed.
