### ISSUE TITLE
Wrong uv texture color with hair children in new hair export code

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/BlendLuxCore#215]
There is a bug when using hair children and a uv texture.

left: 50000 hair strands
right: 1000 hair strands with 50 child strands
![children bug](https://user-images.githubusercontent.com/17701407/45898955-d8590400-bddb-11e8-8f0e-f074accf1316.png)

IIRC, I had a similar problem when writing the original hair export code but I fixed it. I have to look into the code what is going wrong.

Test file:
[hair_child.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2406520/hair_child.zip)

**Comment by Theverat** [comment]
Thanks for the fix!
