### ISSUE TITLE
BlendLuxCore v2.1alpha4 installation failure

### ISSUE THREAD

**Issue by Filexor** [LuxCoreRender/BlendLuxCore#220]
#### System Information
Windows 7 Professional 64-bits Service Pack 1
NVIDIA GTX1060 6GB

#### Software Version
* Blender version: Local build of 2.79 with Python 3.6.2
* LuxCore version: BlendLuxCore v2.1alpha4 (Non-OpenCL version)

#### Error message from Blender console
```
Read prefs: C:\Users\File_xor\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: F:\blender\Blender_Cloth_Improvements\bin\Release\2.79\python
Imported multifiles
multiple addons with the same name:
  'C:\\Users\\File_xor\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_enhanced_3d_cursor.py
'
  'F:\\blender\\Blender_Cloth_Improvements\\bin\\Release\\2.79\\scripts\\addons_contrib\\space_view3d_enhanced_3d_cursor.py'
Traceback (most recent call last):
  File "F:\blender\Blender_Cloth_Improvements\bin\Release\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\File_xor\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 23, in
<module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed: 謖・ｮ壹＆繧後◆繝｢繧ｸ繝･繝ｼ繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ縲・
```

#### Note
I think BlendLuxCore v2.1 requires Python 3.5.x .
Unfortunately, I cannot install Python 3.5.x because of version conflict with Python 3.6.2 .

**Comment by Theverat** [comment]
> * Blender version: Local build of 2.79 with Python 3.6.2

> I think BlendLuxCore v2.1 requires Python 3.5.x .

Yes, as it says on the download page:
> Custom Blender builds and buildbot builds are not supported.

You have to build LuxCore yourself: https://github.com/LuxCoreRender/WindowsCompile
See the readme for the necessary steps.
It also describes how to build with different Python version: 
> Default build will use Python 3.5, the version embedded in Blender 2.79b.
You can add an option to specify the version of your choice among 3.5, 3.6, 3.7, e.g.:
.\cmake-build-x64.bat /python36

**Comment by Filexor** [comment]
Sorry, I missed that because I directly jumped to release page.

**Comment by Theverat** [comment]
No problem. I guess you understand that because of limited manpower, we can only support official Blender releases.
However, if you compile the binaries yourself and put them into the bin folder of the addon, it should work.
