### ISSUE TITLE
Artifacts in orthographic camera

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#223]
https://forums.luxcorerender.org/viewtopic.php?f=4&p=6730#p6730
[artifacts.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2478552/artifacts.blend.zip)

![artifacts](https://user-images.githubusercontent.com/1584761/46948820-968c4800-d07f-11e8-99e0-cec2ce719a0c.PNG)

**Comment by Dade916** [comment]
As explained in the linked thread, adjusting the min. epsilon is enough to solve the problem.
