### ISSUE TITLE
Negative scale breaks emission

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#225]
Area lights and meshlights don't work properly in final render when they have negative scale on at least one axis.
In viewport, everything is fine.
The difference is caused by the fact that in final render, lights and objects are not instanced, while in viewport everything is instanced. So the negative scale works on instances, but not when this transformation is "baked" into the mesh on export.

Here's a scene where the meshlight in the rear has a scale of (1, 1, -1) and the area light in front has a scale of (-1, -1, -1).
Viewport:
![2018-10-29_13-31-29](https://user-images.githubusercontent.com/1584761/47650004-31f0e300-db7f-11e8-84e8-9c4353283330.png)

Final:
![untitled](https://user-images.githubusercontent.com/1584761/47650069-65337200-db7f-11e8-8a8b-8f95f45ff9c3.jpg)

Scene:
[area_scale_bug.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2525217/area_scale_bug.blend.zip)

**Comment by Dade916** [comment]
I have fixed the problem for the top-left light, it was due to an inconsistency in normal (geometry Vs shade) used triangle lights.

However the problem with the second light is a BlendLuxCore bug: it exports exactly the same mesh (without shading normals) no matter of the XYZ scales. I assume the code just ignore the scales.

**Comment by Theverat** [comment]
I don't define shading normals for area lights, maybe that's the problem?

**Comment by Dade916** [comment]
> I don't define shading normals for area lights, maybe that's the problem?

Yes, if shading normals are not defined, the geometry normal will be used and it is the order of vertices to define the normal direction (counter clockwise Vs clockwise).
