### ISSUE TITLE
DLL load failed: pyluxcore

### ISSUE THREAD

**Issue by steinerlein** [LuxCoreRender/BlendLuxCore#227]
First, check if your problem was already reported:
https://github.com/LuxCoreRender/BlendLuxCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug
Yes, but the proposed solutions didn't resolve my problem

#### System Information
i7 8700k
32GB ram

Operating system and graphics card
Windows 10
nvidia quadro P2000
#### Software Version
Blender 2.79b
BlendLuxCore-v2.0-win64-opencl

#### Error message from Blender console

```  
File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\farid\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: DLL load failed: The specified module could not be found.

```

#### Short description of error

After installing the .zip I try to activate it and get this error.
The prerequisites are all installed.
I can install the same version without OpenCL, but I really would like to use it.

**Comment by Theverat** [comment]
Have you tried the non-opencl version?
If that version works, try to update your graphics driver.

**Comment by steinerlein** [comment]
> 
> 
> Have you tried the non-opencl version?
> If that version works, try to update your graphics driver.

Yes, I updated my original post. Will do and report back.

**Comment by steinerlein** [comment]
@Theverat That did the trick! Thanks for the hint!
