### ISSUE TITLE
Nested duplis are not supported

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/BlendLuxCore#228]
First, check if your problem was already reported:
Check done. Seems to be related somehow to fixed issue: https://github.com/LuxCoreRender/BlendLuxCore/issues/197
and maybe this one
https://github.com/LuxCoreRender/BlendLuxCore/issues/64

#### System Information
Windows 10 Pro

#### Software Version

* Blender version: Blender 2.79
* LuxCore version: LuxCoreRender 2.1 beta 2,

[Test DLSC.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2584081/Test.DLSC.zip)
There are different layers in the file, but I think the file is still quite easy to use.

Reproduce
**On layer [11] or alt+key 2**, there is the grouped object and its instance. The instance is showed completely in wireframe and solid but not in view render or final render F12. 

Please tell us which render engine you used and if it was in OpenCL or CPU mode.
If you were rendering with OpenCL, please test if the error also happens in CPU mode 
and append this information, it can help us to pinpoint the problem faster.

Both.

**Comment by FarbigeWelt** [comment]
[Test DLSC.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2584129/Test.DLSC.zip)

**Comment by Theverat** [comment]
The object in question contains nested duplis: 
The LED bulbs are duplicated via a particle system, and then these duplis are duplicated via the group instance.
Nested duplis are currently not supported by BlendLuxCore.
They will be supported after I port the addon to Blender 2.8 (#166).

**Comment by Theverat** [comment]
Fixed in Blender 2.80 version of the addon (v2.2 or higher).
