### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by TFX18** [LuxCoreRender/BlendLuxCore#232]
#### System Information

Dell G3 3779
Windows 10 Home
nVidia GTX1060 MAx-Q Design
Driver: 417.35
http://gpuz.techpowerup.com/18/12/29/sbr.png

#### Software Version

* Blender version: 2.79b
* LuxCore version: v2.0 opencl

#### Error message from Blender console

Traceback (most recent call last):
  File "C:\Blender\blender-2.79.0-git.111179beb0b1-windows64\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlendLuxCore\__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

I've tried launching LuxMark and it works fine with my graphic card, so it doesnt seem a driver problem...Do you have any suggestions? Thanks

**Comment by Dade916** [comment]
Aside from missing OpenCL DLLs, the other most common cause of "DLL load failed" is the lack of VisualStudio C++ runtime DLLs. 

They are available here: https://www.microsoft.com/en-US/download/details.aspx?id=40784
