### ISSUE TITLE
Number of users of materials

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/BlendLuxCore#233]
Now you can not see how many users of the material.
You need to make a number instead of the icon "id":
![01](https://user-images.githubusercontent.com/7983249/51117406-caae0b00-181e-11e9-8dc5-e69ae545610d.jpg)

**Comment by Theverat** [comment]
I have added a label that shows the number of users (in the lower left).
I cannot show the user number in place of the icon because it would destroy the layout.

![2019-03-21_21-18-33](https://user-images.githubusercontent.com/1584761/54782630-9fc9a400-4c1f-11e9-814a-7fb8ada16620.png)
