### ISSUE TITLE
Cannot activate LuxCore addon on OSX with 2.79b

### ISSUE THREAD

**Issue by melting-wax** [LuxCoreRender/BlendLuxCore#237]
#### System Information
OSX 10.9.5 with GT 650M
#### Software Version

2.79b
2.1

#### Error message from Blender console
```
Traceback (most recent call last):
  File "/Applications/Blender 2.79/Blender/blender.app/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/Users/xxxxx/Library/Application Support/Blender/2.79/scripts/addons/BlendLuxCore/__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: dlopen(/Users/xxxxxx/Library/Application Support/Blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so, 2): Library not loaded: @rpath/libomp.dylib
  Referenced from: /Users/xxxxxx/Library/Application Support/Blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
  Reason: image not found
```

#### Short description of error
While the addon imports successfully, if I try to activate the addon (on either OpenCL or non-OpenCL versions), it fails with the above error.
#### Exact steps for others to reproduce the error
Import LuxCore into Blender and try to activate.

**Comment by melting-wax** [comment]
A similar error also happens when trying to load the standalone OS X build:
```
dyld: Library not loaded: @rpath/libomp.dylib
  Referenced from: /Users/xxxxxx/luxc/luxcorerender-v2.1-mac64/./luxcoreui
  Reason: image not found
[1]    72354 trace trap  ./luxcoreui
```

this is despite the fact that there is a version of libomp.dylib in the folder with luxcoreui in it.

**Comment by Theverat** [comment]
Maybe @rebpdx can help?

**Comment by rebpdx** [comment]
Weird, I can't recall off the top of my head if I changed those to be @rpath or @loaderpath to address this issue. I've had similar problems when I was originally building the packages. I'm wondering if this is 10.9 specific. I'll do some investigation. @melting-wax, do you have a newer MacOS you could try?

**Comment by u3dreal** [comment]
We are now using @executable_path 

This issue should be solved
