### ISSUE TITLE
Cant control brightness of light

### ISSUE THREAD

**Issue by Kumaran7** [LuxCoreRender/BlendLuxCore#247]
Cant control brightness of any light source Environment or lamps in latest version of Blendluxcore .
System: i3,HD 5450.

**Comment by Theverat** [comment]
Have you checked if it's the issue described in the FAQ?
https://wiki.luxcorerender.org/BlendLuxCore_FAQ#When_I_change_the_brightness_of_my_lamp.2C_nothing_happens

**Comment by Kumaran7** [comment]
Yes its working thank you
