### ISSUE TITLE
cloth material gabardine preset is rendered as denim

### ISSUE THREAD

**Issue by Piitas** [LuxCoreRender/BlendLuxCore#254]
#### System Information

Win10, nvidia gtx 960

#### Software Version

Blender 2.79b
LuxCore 2.1

#### Error message from Blender console

no error in console

#### Short description of error
Cloth material wool gabardine preset is rendered as denim. Gabardine is misspelled as Garbardine in pyluxcore.pyd, and that makes it use the default denim instead.
 
#### Exact steps for others to reproduce the error
The attached blend file has both cloth presets. Export the scene with filewriter and check
scene.scn

Same error on CPU and OpenCL

 
[cloth wool gabardine bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3089454/cloth.wool.gabardine.bug.zip)

**Comment by Theverat** [comment]
Thanks for the report, fixed in https://github.com/LuxCoreRender/LuxCore/commit/f2510495de160264b00f0cfa1f9391305dd2a2a1.

**Comment by Piitas** [comment]
Great. Thanks
