### ISSUE TITLE
laser acts strange in viewport render

### ISSUE THREAD

**Issue by Piitas** [LuxCoreRender/BlendLuxCore#256]
#### System Information
Win10, geforce gtx 960

#### Software Version
Blender version 2.79b
LuxCore version 2.2 alpha1

#### Error message from Blender console
no error in console

#### Short description of error
If you use viewport rendering and enable laser on an area light, the area light will still light the scene along with the laser. Moving the area light in the viewport does not move the area light object but the laser emission from the area light does move. The area light emission(non-laser) will not move.

If you enable the laser on the area light BEFORE you enable viewport render, it will work correctly.

#### Exact steps for others to reproduce the error
- enable viewport render
- enable laser on the area light
- move (G) the area light 

Same problem on CPU and opencl

[laser viewport bug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3124846/laser.viewport.bug.zip)

**Comment by Theverat** [comment]
Thanks for the report, it was a regression due to a fix to another bug.
