### ISSUE TITLE
question: run denoiser button grey out

### ISSUE THREAD

**Issue by stansu** [LuxCoreRender/BlendLuxCore#259]
as title, and when i finshed viewport render mode, it show "could not start denoiser:[errno 13] permission denied

**Comment by Theverat** [comment]
The "run denoiser" button is only used during final render, not in viewport renders.

>  when i finshed viewport render mode, it show "could not start denoiser:[errno 13] permission denied

What is your OS?
If you open the folder of the BlendLuxCore addon and then the "bin" folder inside, does it contain one of the following:
* "denoise.exe" (if you are on Windows)
* "denoise" (if you are on Linux) - is it executable?

You could try to remove BlendLuxCore and do a fresh install from the [latest release](https://github.com/LuxCoreRender/BlendLuxCore/releases).

**Comment by stansu** [comment]
i'm using ubuntu 18.04, and i just make denoise executable then it's working!
thanks for your help!

**Comment by Theverat** [comment]
I'm wondering why it was not executable.
How did you install BlendLuxCore? Did you use the integrated updater to upgrade from a previous version?

**Comment by stansu** [comment]
> I'm wondering why it was not executable.
> How did you install BlendLuxCore? Did you use the integrated updater to upgrade from a previous version?

I use integrated updater

**Comment by Theverat** [comment]
Ah ok, I recently fixed a bug in the updater, it was not copying permission bits: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/operators/update.py#L54
So it's already solved, but we have no way to fix this in existing BlendLuxCore installations.

**Comment by JJ-ind** [comment]
hey i fixed this problem by giving permissions manually

but when installing it throught blender we still have to manually give permissions

**Comment by maljos** [comment]
Hi, for linux user execute the comand:
chmod +x denoise
