### ISSUE TITLE
Color bleeding with transparent film + denoiser

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#261]
File: [temp.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3226353/temp.blend.zip)

~~I have a feeling it might be a mismatch between albedo pass and render pass because of the transparent film (because we enable "forceblackbackground" with transparent film - albedo pass should be black as well in this case).~~
I tested this, but the albedo does match the black background.
Maybe it has something to do with premultiplied alpha?

![untitled](https://user-images.githubusercontent.com/1584761/58463254-c9c5a800-8133-11e9-8ee7-b27fa5793aac.png)

**Comment by stansu** [comment]
i know the problem
my camera's gain is too high
when i set camera's gain to 50, the color bleeding is gone.
[temp3.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3226536/temp3.zip)

**Comment by stansu** [comment]
@Theverat I think this issue can close, thank you.

**Comment by Theverat** [comment]
Ok, maybe.
I still think there might be a bug hidden in here, but not sure.
