### ISSUE TITLE
Render Selected

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#263]
Useful feature for archviz, corona and vray also implemented this.

Basicaly if the feature is enabled, then whatever object is seleced in the viewport will be rendered with transparent background.

This allows to re-render only part of the image for example if the texture has an issue or some small change/tweak is required, and then you can just compose this output in 2D editor over existing render.

In attachment you see an example of a client required change, in luxcore I have to re-render whole image again (original image has 4480 pixels on longest edge) so this feature could save a lot of time.

![L1_preview_view_01_hires Edit](https://user-images.githubusercontent.com/43474911/59084032-ed3ddf00-88f9-11e9-8d03-fc0a231aa940.jpeg)

**Comment by Theverat** [comment]
It is already possible to implement this with the features in LuxCore right now, so I moved the issue to the BlendLuxCore repository where the work needs to happen.

We can use the BY_OBJECT_ID and BY_MATERIAL_ID AOVs for this task. They produce exactly what you want for a given object or material ID.

> in luxcore I have to re-render whole image again (original image has 4480 pixels on longest edge)

In some cases, border rendering might help to reduce the area required to re-render.

**Comment by lacilaci** [comment]
Nice, thanks.

**Comment by Dade916** [comment]
Another option would be to use camera invisible objects: if you set all objects to not render as camera invisible, you should get the result you are aiming for.

**Comment by lacilaci** [comment]
Well, if it was automated and if luxcore wouldn't sample transparent pixels it could be useful.

**Comment by Dade916** [comment]
BTW, the OBJECT_ID AOV of the first full rendering can be used to establish the 2D image bounding box of the object to render render to set up border rendering and save a lot of rendering time.

**Comment by Theverat** [comment]
> Another option would be to use camera invisible objects: if you set all objects to not render as camera invisible, you should get the result you are aiming for.

Good idea. You can already do this pretty easily in Blender since I added render layer support:

![2019-06-07_12-02-08](https://user-images.githubusercontent.com/1584761/59097014-ba591280-891c-11e9-9d11-7c6a2febe7be.png)

**Comment by lacilaci** [comment]
Hm, good idea. I wonder how would that work in 2.8 though.

**Comment by Theverat** [comment]
I haven't looked into that yet, but I think there's a similar concept with the new "view layers".

By the way, to prevent transparent pixels from being sampled, enable adaptive sampling: https://github.com/LuxCoreRender/LuxCore/issues/137

**Comment by lacilaci** [comment]
Oh, I see.. so I put object on it's own layer and use adaptivity. Ok, good enough, even better would be if adaptivity worked good enough to be always enabled. But, thanks. I think for now it's enough.

**Comment by Theverat** [comment]
Guess we can close this for now.
