### ISSUE TITLE
previews aren't downsampled in 2.8

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#274]
rendering in viewport in 2.80 always renders full resolution.
reduce first sample resolution is not working.

I'm using 2.81 from buildbots

**Comment by Theverat** [comment]
It works fine on my end, both with CPU and OpenCL (with official 2.80 though).
Can you still reproduce this?

**Comment by lacilaci** [comment]
Hm. Sorry, does seem to be working fine now... Probably something was temporarily broken in some daily build of luxcore or some blender 2.81... I'm always on both latest and assumed that this was an early 2.80 plugin limitation

**Comment by neo2068** [comment]
I can reproduce the issue. When you enable the add lighttracing option then the downsampling is disabled.

**Comment by lacilaci** [comment]
Oh, so maybe the problem affects the other issue too?
https://github.com/LuxCoreRender/BlendLuxCore/issues/279

**Comment by Theverat** [comment]
Lighttracing in viewport requires the PathCPU/PathOCL engine instead of RTPathCPU/RTPathOCL.
Resolutionreduction is only supported by RT engines. So the resolutionreduction option should be greyed out in the UI when lighttracing is enabled in viewport.
