### ISSUE TITLE
adaptivity is by default at 0.95 in 2.8

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#276]
adaptivity was never working in any of my production scenes, quite the oposite, it always made performance worse.

It probably only somewhat works on high power samples, bright areas and caustics and maybe with a scene that is mostly empty background and object.

I would have it completely disabled and notify user in the tooltip that it is a wip feature or something.

**Comment by Theverat** [comment]
This is a hard question for me.
On the one hand I have a couple of scenes here that clearly benefit from adaptive sampling (e.g. my wallpaper scene) or are at least not worse off with adaptivity at .95.
On the other hand you are rendering far more images than me at the moment (and also professional work, not just hobby stuff), so I believe your experience.

Maybe we can do a range of test scenes (indoor, outdoor, caustics) and check which adaptivity values offer the best results. It could turn out that something like 0.5 or 0.3 would be a good compromise.

**Comment by lacilaci** [comment]
I understand. That wallpaper scene is mostly about caustics right? Which is exactly what I always keep saying that this is the only case where adaptivity does help because it focuses in noise in bright samples. 

I think I need to make an example scene to prove this and maybe then something could be done about this barely working feature. Maybe a scene that features both caustics and shadows and then use clamping to see when adaptivity fails to help the rendering...

But until then at least stay away from extreme value like 0.95 cause this can literaly make luxcore stop(almost) from sampling areas with noise in shadows and give the impression that even with ataptivity luxcore can't handle that.

**Comment by Theverat** [comment]
> That wallpaper scene is mostly about caustics right? Which is exactly what I always keep saying that this is the only case where adaptivity does help because it focuses in noise in bright samples.

It contains caustics, but since it's rendered with additional light tracing they are clean very fast. The adaptive sampler actually spends more samples in other noisy parts of the image. I have attached the comparison.

**Adaptive sampling off:**
![adaptive_sampling_off](https://user-images.githubusercontent.com/1584761/64473747-c8f8d500-d16a-11e9-8922-94ffae8e189d.png)

**Adaptive sampling on:**
![adaptive_sampling_on](https://user-images.githubusercontent.com/1584761/64473750-d6ae5a80-d16a-11e9-8e63-5989ef5b3d0f.png)

> I think I need to make an example scene to prove this and maybe then something could be done about this barely working feature. Maybe a scene that features both caustics and shadows and then use clamping to see when adaptivity fails to help the rendering...

Testscenes would be great!

> But until then at least stay away from extreme value like 0.95 cause this can literaly make luxcore stop(almost) from sampling areas with noise in shadows and give the impression that even with ataptivity luxcore can't handle that.

I think I'll set it to 0.5 for now, until we have the data to make a better guess.

**Comment by Theverat** [comment]
I have now again raised the adaptive strength to 0.9 in c9df07fa1fc753aa3c7db68c7886a2e4a7524198, since the noise-detection is now working well since Alpistinho's changes a while back.
