### ISSUE TITLE
viewport device setting is ignored in 2.8

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#279]
It's always the same as rendering device no matter what is selected in the render settings-viewport settings-device

I'm using 2.81 from buildbots

**Comment by Theverat** [comment]
It works fine on my end, both with CPU and OpenCL (with official 2.80 though).
Can you still reproduce this?

**Comment by Theverat** [comment]
It works on my side, can you provide more detailed steps what to do, or a testscene?

**Comment by lacilaci** [comment]
Hm. Sorry, does seem to be working fine now... Probably something was temporarily broken in some daily build of luxcore or some blender 2.81... I'm always on both latest and assumed that this was an early 2.80 plugin limitation

**Comment by Theverat** [comment]
There is one case where this issue indeed shows up: When "add lighttracing" is enabled in viewport, PathCPU is used regardless of the viewport device selection.

Also, in the performance panel, the OpenCL devices are not shown when viewport device is set to OpenCL. The user has to switch the main engine to OpenCL to see them.
(However it's probably a rare case that someone uses CPU for final render and OpenCL for viewport).
