### ISSUE TITLE
cancel render button in 2.8

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#281]
I think it would be nice to have a "cancel", "stop" or "stop redering" button right where pause and refresh buttons are in the image editor luxcore tab in blender 2.8

**Comment by Theverat** [comment]
Good idea. It could have the additional feature that it stops the rendering like a halt condition, which means that Blender will apply compositing on the render result.

**Comment by lacilaci** [comment]
Yes that would be awesome
