### ISSUE TITLE
Smoke shaking, and its reduction in size

### ISSUE THREAD

**Issue by DEBIHOOD** [LuxCoreRender/BlendLuxCore#284]
#### System Information
Windows 10
#### Software Version
Blender 2.8
Luxcore 2.2 beta 3
#### Short description of error
After baking, the smoke has a kind of shaking or trembling
#### Exact steps for others to reproduce the error
It is necessary to bake smoke with an adaptive domain, and after rendering you can see that the smoke shakes or trembles, it also decreases size several times, there is no shaking when the adaptive domain is turned off, but then the baking process takes several times longer

Here is the file, you will need to bake the cache,
[smoke.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3513069/smoke.zip)

Also here are different test renders (video)
[smoke renders.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3513089/smoke.renders.zip)

**Comment by neo2068** [comment]
I can reproduce the problem. It should be fixed in master.
