### ISSUE TITLE
Blender 2.80: Show viewport seems doesn't work

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/BlendLuxCore#285]
#### Software Version

* Blender version: 2.80
* LuxCore version: first release of the 2.80 addon

#### Short description of error
It seems that is not possible to see the image texture loaded by a LuxCore image texture node.

#### Exact steps for others to reproduce the error
If I create a material with just Luxcore nodes, I can't see the image texture I've set for that material regardless of the "show viewport" button on the texture node.
If I create also a material using Cyles and I create a Cycles image texture I can see that.

Both test using the "Texture" option of the workbench viewport mode.

**Comment by Theverat** [comment]
Yes, the "show in viewport" button was not adapted to Blender 2.80 yet.

**Comment by Theverat** [comment]
"Show in viewport" was removed in Blender 2.80, we will need a better implementation based on Eevee nodes instead: #322
