### ISSUE TITLE
Blender Crashes when switching to render mode then does not restart any more

### ISSUE THREAD

**Issue by amryounis** [LuxCoreRender/BlendLuxCore#286]
#### System Information

Win 10, NVIDIA 1050Ti
#### Software Version

* Blender version: 2.8 (official)
* BlendLuxCore v2.2beta3

#### Error message from Blender console
nothing

#### Short description of error
after installing from user preferences and activating, tried to switch to the render-mode of the default scene. Blender then crashes.

when restarting Blender, it crashes before showing the splash screen.

the default scene is still the default one from Blender.

#### Exact steps for others to reproduce the error
i did not change any settings for Lux, just clicked the render mode button

**Comment by Theverat** [comment]
Try starting Blender from the command line: https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html#command-line-launch-index
It should give you an error message telling us why it's not starting.

Maybe you have downloaded the addon for 2.79?
The correct download link for the 2.80 version is https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.2beta3/BlendLuxCore_280_Win64_OpenCL.zip

**Comment by Theverat** [comment]
Closing this until more information is provided.
