### ISSUE TITLE
Crash in viewport when I change light source settings [2.2 beta3]

### ISSUE THREAD

**Issue by OnlyIAmSorda** [LuxCoreRender/BlendLuxCore#287]
Each time I preview, I change the values of color, size, gain, for light sources - point, sun, and others - and move them - the blender crash.

**Comment by Dade916** [comment]
Blender v2.8 or v2.79b ? Are you using CPU or OpenCL pre-view ?

**Comment by OnlyIAmSorda** [comment]
Excuse me. I usually provide more accurate data always :)

2.79b, OpenCL preview, path-engine

**Comment by Theverat** [comment]
Corresponding forum thread: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1370&p=16060#p15998

**Comment by Theverat** [comment]
Without a scene, this report is pointless.
I have never experienced a crash related to the settings mentioned in the first post, wether in CPU or GPU viewport render, on Linux or Windows.
If you still have this issue, please reopen and upload a testscene.
