### ISSUE TITLE
blendluxcore installation

### ISSUE THREAD

**Issue by pramujadi** [LuxCoreRender/BlendLuxCore#289]
First, check if your problem was already reported:
https://github.com/LuxCoreRender/BlendLuxCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abug

#### System Information

Operating system and graphics card

#### Software Version

* Blender version: (example: 2.79, see splash screen)
* LuxCore version: (see BlendLuxcore addon entry in Blender user preferences)

#### Error message from Blender console

* On Linux: start Blender from a terminal to see the error messages:
  cd /path/to/blender
  ./blender
* On Windows: open Blender > "Window" menu > "Toggle System Console"

If possible, include a traceback of the error messages.
Paste it into this code block:
```
(Example output, please delete)
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/export/light.py", line 123, in convert
    raise NotImplementedError("Area light not implemented yet")
NotImplementedError: Area light not implemented yet
```

#### Exact steps for others to reproduce the error
Based on a (as simple as possible) attached .blend file with minimum amount of steps

Please tell us which render engine you used and if it was in OpenCL or CPU mode.
If you were rendering with OpenCL, please test if the error also happens in CPU mode 
and append this information, it can help us to pinpoint the problem faster.

Thank you for supporting the development!
Please replace or delete all text in this template that is not a #### heading, including this text.

**Comment by Theverat** [comment]
Please add information that can help us track down the problem, for example an error message.

**Comment by pramujadi** [comment]
Below is the message that I've got
![Capture](https://user-images.githubusercontent.com/578276/64066918-ba437880-cbd4-11e9-9822-1a87c340f45a.PNG)
![Capture2](https://user-images.githubusercontent.com/578276/64066923-c596a400-cbd4-11e9-8e66-16c637a2ce06.PNG)

**Comment by DEBIHOOD** [comment]
> Below is the message that I've got

Use addon version for 2.8, instead of 2.79
![image](https://user-images.githubusercontent.com/54025271/64067923-560ecc00-cc49-11e9-8244-f70d1213b182.png)

**Comment by DEBIHOOD** [comment]
Or just click on the link and you will start downloading:
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.2beta3/BlendLuxCore_280_Win64_OpenCL.zip

**Comment by Theverat** [comment]
As DEBIHOOD says, you need BlendLuxCore v2.2beta3 for 2.8 instead of v2.1.

**Comment by pramujadi** [comment]
Thanks !
