### ISSUE TITLE
Incorrect image when using border rendering (final render)

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#29]
See screenshot and scene:
![border_2](https://user-images.githubusercontent.com/1584761/34565881-cfadabb8-f15c-11e7-9ad4-2bcf01770d5b.png)
[border_2.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1603454/border_2.blend.zip)
Only happens with some resultions/border settings.

**Comment by neo2068** [comment]
It should be fixed with commit 87eb3966382343d3e5649fc978309fef3c0e3166
