### ISSUE TITLE
Use photonGI cache on material

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/BlendLuxCore#290]
It might be useful to have the option to enable/disable photongi for materials even when photongi is disabled in the render settings.

While building scene, assets and materials it is not worth it to enable photongi due to it's toll on render initialization time. But if I later in the process start using photongi I do need to go back and disable it on materials I don't want it on.

So it might be useful to have the setting available under the nose without the need to enable the cache beforehand.

**Comment by Theverat** [comment]
Implemented.
