### ISSUE TITLE
Can't "Show in viewport" object linked textures for data-linked objects (Blender 2.79)

### ISSUE THREAD

**Issue by thima2017** [LuxCoreRender/BlendLuxCore#302]
To reproduce:
1) Create an object with a material that linked to object. Material should have a texture.
2) Duplicate the object with <Alt>+<D>.
3) Unlink Materials and Textures with U -> Materials+Tex
4) Duplicate a material of one of the objects and make it linked to Object instead of Data. Do the same relinking for the second object too. (Probably you will need to delete the material slot, create the new one, set it linked to Object and choose a material from the already existing materials list to make it work properly.)
5) Change the texture of the new material
The "Show in viewport" button on the Image texture nodes will not show different textures in the ViewPort for different object with a different materials. It looks like "Show in ViewPort" acts like the materials are linked to Data. But I'm not sure.

**Comment by Theverat** [comment]
Thanks for the report!
I assume you are using Blender 2.79?

The "show in viewport" button was always a bit of a sketchy solution.
In Blender 2.80 I want to use Eevee nodes for material preview eventually.

Since I won't work on the version for 2.79 anymore and this issue only concerns 2.79, I hope you don't mind when I close it.

**Comment by thima2017** [comment]
I mind a little because I don't have a Tool Shelf in 2.80. Maybe just rename this issue by adding 2.79 to the end? What if someone else will want to fix it?

**Comment by Theverat** [comment]
Ok, no problem, we'll keep it open.

> I don't have a Tool Shelf in 2.80

What do you mean exactly?
If you are talking about the image editor tool shelf, it was moved to the properties (N-panel) in 2.80.

**Comment by thima2017** [comment]
I think the removing of Tool Shelf wasn't a good idea itself. The place, where I lack the Tool Shelf mostly is Composite/Shading. I even made an expressive and dramatic bug report about that https://developer.blender.org/T68783. But I'm not sure now that I was so right as thought. Because I didn't count the mouse paths to the buttons on Tool Shelf. I think an ability to pin the popup menus would solve all my problems, and seems one of Blender devs liked that idea, but I don't know if it even planned. Seems no. So it's my home protest or something. I know I will loose...

**Comment by Theverat** [comment]
Since this is about Blender 2.79, which is not supported by newer versions of our addon for quite a while now, I'll close this issue.
If a developer comes around who wants to fix it, feel free to re-open it.
