### ISSUE TITLE
Dragging value in recommended range of dispersion feature of glass material.

### ISSUE THREAD

**Issue by Bernize** [LuxCoreRender/BlendLuxCore#303]
Hi, there is too much limits in values has to be typed manually, like IOR and eye depth or light depth. I would welcome, and i think it is most needed in dispersion settings. It is not well good read those values (its range) so one selected dragging only recommended value, typing possible anything. Disabling it back to 0 or left value here intact.
First post on github ever, so if anything wrong, so sorry.
Thank you for reading this.

**Comment by Theverat** [comment]
Can you make concrete suggestions what the new ranges should be?

* Dispersion: min and max, soft min and soft max
* Eye depth: min and max, soft min and soft max
* Light depth: min and max, soft min and soft max
* IOR: min and max, soft min and soft max

(soft min/max is the range where the user can drag, values outside of this range have to be typed in after clicking the property)

**Comment by Bernize** [comment]
Hi,
there are, when focused on value in dispersion properties, but hard to orient. Those values are realistic.
![_LC_dispersion](https://user-images.githubusercontent.com/36054873/65705353-8f8bf900-e088-11e9-8f77-3e1359888b00.png)
I hope i did it right. Also you mentioned ior, i would like to be able IOR <1, for some caustics effects and trying. Should i open new issue about it?
Thank you for reply!

**Comment by Theverat** [comment]
So for dispersion, you propose: 
* soft min = 0.00345
* soft max = 0.01342

Do I understand that correctly?

**Comment by Bernize** [comment]
Yes, just not limit it hard to those values. Just if realistic is what is in popup, could be nice that soft min max limited to this. I got not best eyes and those values one isn't sure if in realistic values. too small numbers. There is soft limit actually, Just keep it realistic could be nice. Who know what is doing can type in any number in any case.

**Comment by michelchafouin** [comment]
Soft_min of 0.00345 would require the default value to also be set to 0.00345, otherwise it won't work as expected.
Does turning on dispersion by default sounds like a good idea? I think LuxCore philosophy is to aim for realism so I would say yes, but what do you guys think?

**Comment by Theverat** [comment]
> Does turning on dispersion by default sounds like a good idea?

No, it should be off by default, because it's not needed in most cases, increases the noise at same sample count, and can cause the glass to appear yellow when clamping is used.
