### ISSUE TITLE
Expose more details about OpenCL devices in python

### ISSUE THREAD

**Issue by iszotic** [LuxCoreRender/BlendLuxCore#304]
* Operating system: Linux 4.15.0-64-generic #73-Ubuntu
* Devices: Dual Vega 56, gfx 900
* Blender version: version: 2.81 (sub 11), branch: master, commit date: 2019-09-12 22:20, hash: 8d12c2a83658, type: Release build date: 2019-09-13, 01:02:16
* LuxCore version: 2.2 RC1

In N GPU identical settings GPUs become indistinguishable because luxcoreblender only exposes the name in clinfo, at the UI is easy to switch between the GPU you want, but at script level these devices can only be set by their load order, not sustainable because this order can change, It would be nice to expose the Device Topology that is pretty much unique to each device

**Comment by Theverat** [comment]
I use pyluxcore's `GetOpenCLDeviceList()` to retrieve information about the OpenCL devices.
It does not really tell me much more than what is visible in the UI.
If you want to know which OpenCL device has which corresponding index in the device list, you can use this function as well (or my wrapper `scene.luxcore.opencl.get_opencl_devices()`), and based on the info in this list (e.g. the name) you can choose to enable or disable devices:

```python
>>> C.scene.luxcore.opencl.get_opencl_devices()
[('      Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz', 'OPENCL_CPU', 8, 8, 8250183680, 2062545920)]

>>> C.scene.luxcore.opencl.devices[0].name
'      Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz'

>>> C.scene.luxcore.opencl.devices[0].enabled
True
```

Does this help you?

**Comment by Dade916** [comment]
I can add additional info to the list returned by GetOpenCLDeviceList(), I can include any information reported by clinfo however none of them looks useful to identify identical devices. The only one may be:

>   Device Vendor ID                                0x10de

however an hex ID doesn't seem particularly easy to understand.

Note: as far as I know the, the order of device listed can change only if you change the hardware or re-install the software.

**Comment by iszotic** [comment]
@Theverat I have to use the order in which these devices appear too now.
@Dade916 Device Vendor ID is the same on both cards
`Device Vendor ID                                0x1002`
The only different thing is Device Topology
here's in the first card
`Device Topology (AMD)                           PCI-E, 0f:00.0`
here's in the second card
`Device Topology (AMD)                           PCI-E, 0c:00.0`

Oh I see, `pyluxcore.GetOpenCLDeviceList` is a luxcore function at https://github.com/LuxCoreRender/LuxCore/blob/master/src/luxcore/pyluxcore.cpp

**Comment by Dade916** [comment]
If you want, I (or you) can add the topology field to the list of returned information, we have only to check if it is consistent across different vendor (for instance NVIDIA and Intel).

**Comment by Theverat** [comment]
I'm closing this for now. @iszotic if you still require this feature, please comment and we can reopen this anytime.
