### ISSUE TITLE
DefineBlenderMesh: python args type did not match c++ signatures. 

### ISSUE THREAD

**Issue by bartoszek** [LuxCoreRender/BlendLuxCore#307]
I'm havin a problem with blener-2.8 integrator. I've got this error when enabling viewport preview.
```
ERROR: Python argument types in                                                                                                                                           
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, int, NoneType)
did not match C++ signature:   
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned
 long, unsigned long, unsigned long, unsigned long)
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned
 long, unsigned long, unsigned long, unsigned long, boost::python::api::object)
```
Error originate here:
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/mesh_converter.py#L38
Sysinfo: {Os:archLinux, blender:2.80(hash: f6cb5f54494e), python:3.7,luxcore:2.2,blendluxcore:2.2}

**Comment by Theverat** [comment]
Are you using some kind of custom build? There was someone else with a very similar error message here: #306 
Try the official binaries.

By the way, this error indicates a mismatch between Python and C++ code.

**Comment by bartoszek** [comment]
It's strange as previous to `2.2` the code works fine with Arch's blender-2.79 and boost-1.69. I'll try work this out...

**Comment by Theverat** [comment]
I think I know what the problem is (it's on our end): The blender2.8 branch of the LuxCore repo was not yet merged into master.

**Comment by bartoszek** [comment]
Yep, thank for the tip.
Now `mesh_convert.py` fits `pyluxcoreforblender.cpp`
```python
        mesh_definitions = luxcore_scene.DefineBlenderMesh(mesh_key, loopTriCount, loopTriPtr, loopPtr,
                                                           vertPtr, polyPtr, loopUVsPtr, loopColsPtr,
                                                           material_count, mesh_transform)
```
```python
boost::python::list Scene_DefineBlenderMesh1(luxcore::detail::SceneImpl *scene, const string &name,
		const size_t loopTriCount, const size_t loopTriPtr,
		const size_t loopPtr,
		const size_t vertPtr,
		const size_t polyPtr,
		const size_t loopUVsPtr,
		const size_t loopColsPtr,
		const u_int materialCount,
		const boost::python::object &transformation) {
```

**Comment by bartoszek** [comment]
@Theverat btw. why is that so `blender2.80` wasn't merged, if I may ask?

**Comment by Theverat** [comment]
> btw. why is that so blender2.80 wasn't merged, if I may ask?

I simply forgot about it. Until recently we had separate builds for Blender 2.80, and these were built from the blender2.80 branch. I have now merged the branch into master and everything should work again.
Thanks for your report!
