### ISSUE TITLE
Emission node problems

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#308]
https://forums.luxcorerender.org/viewtopic.php?f=4&t=1476&p=17301#p17301

> I am experiencing weird behavior when using emission nodes. I have attached a small test scene. Maybe I am doing something wrong.  
Problem is that different kind of node setups disable the effect of other nodes parameters. There might be more cases like this, but for now these 2 caught my eye.  
Also there is a slight brightness difference when using only one channel from remap node or using combine rgb to make it 3 channels.

[emission_problems.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3711294/emission_problems.zip)

**Comment by neo2068** [comment]
I have looked into the problem. There were a problem in the Blender addon which used the gain value all the time. After changing the scheme the code distinguishes two cases:
1, simple mode (artistic) : use gain and color. The emission strength can be adjusted by color value and/or gain.
2. advanced mode (scientific) : use power, efficacy and color. In this mode the emission color is normalized. Only color hue is used. The emission strength can be adjusted by power and/or efficacy.

In the file there is still a bug in the first node tree path where you multiply a color with a scalar value.
