### ISSUE TITLE
Checkbox to hide/unhide power&efficacy

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/BlendLuxCore#309]
As written here
https://forums.luxcorerender.org/viewtopic.php?f=4&t=1476#p17331

I suggest a checkbox in the emission node in material editor where you can choose to activate or not the "power&efficacy" settings. If not activate, those settings should be greyed-out or invisible.
the option should be called something like "realistic gain option"

same approach should be probably adopted for lights objects.

**Comment by michelchafouin** [comment]
Visibility of these settings should be decided by a "Unit" drop down menu.
