### ISSUE TITLE
ies light not rotating according to the rotation of light object

### ISSUE THREAD

**Issue by nocivo72** [LuxCoreRender/BlendLuxCore#310]
Hi,
In the image bellow, I have set an IES light (on the right) with an IES file downloaded from ERCO webpage. The IES file corresponding to a wallwasher that have an asymmetrical light distribution. More intense on botton and less intense on top. I rotated it to 35 degree on Y axis, as it should been. All it's ok, the result it is correct.
Then I duplicate the light, move it on left side and rotate it on Z axis by 180 degree. As you can see on render, the light now is inverted.
it seems that the start IES orientation is not linked to light object,and it changes random or on every 90 degree step.
I also tried to rotate (not duplicate) the same light and the result it's the same.

I attach also the blender scene.

Thanks

![ies-orientation](https://user-images.githubusercontent.com/56474439/66700243-64143a00-ed29-11e9-8f80-d71d32b5fc83.jpg)

[spot-lens_2.zip](https://github.com/LuxCoreRender/LuxCore/files/3720634/spot-lens_2.zip)

**Comment by nocivo72** [comment]
> 1. if you replace the area light with point light, it should work because the light transformation is used as expected. @nocivo72 can you try?

yes it's true, using point light have correct transformation. but the ies point light, using the same intensity, it's very less strong than with area light (maybe other bug?)

>2. ...... If I'm correct, adding UV definitions to the area light triangles will solve the problem.

This is not true. I tried with IES light using geometry with UV, but we have the same error, with wrong transformation.

Thanks

**Comment by Theverat** [comment]
> I tried with IES light using geometry with UV, but we have the same error, with wrong transformation.

Interesting. Does LuxCore rely on the object transformation in this case? (In the addon, area lights are not created as instances in final render, so there's no object transformation).
Does it work correctly in viewport render (where area lights are instances)?

**Comment by nocivo72** [comment]
for instances, you mean using Alt+D or using the duplivert (instances on object panel)? I'm using the luxcore 2.8 addon.

Anyway, the actual way to make ies light it is not intuitive and it's impossible to control. If apply an IES file to an area light (not geometry light), and then you rotate it, the IES has to rotate consequently. Maybe, by logic, you have to link IES texture UV to the normal of area light with U=X V=Y, then apply the transform based on location and rotate. I'm not a programmer, I don't know the description of scene of luxcore, but have to be a way to do, using a user friendly way in blender interface.

Thanks

**Comment by nocivo72** [comment]
Moreover, I don't know how to make instances in luxcore using the blender addon. I cannot find any documentation about that. I know that in the old luxrender the only way to do instances was to use the duplivert. it remain the same? or I can use also the blender link objects (alt+a)?

**Comment by Theverat** [comment]
Just test it in the viewport render, everything's an instance there.

> Moreover, I don't know how to make instances in luxcore using the blender addon.

The rules for instancing are the same as in Cycles:
- Objects sharing the same mesh (Alt+D copies) are only instanced if there are no mesh-editing modifiers on them
- Collection instances are instanced
- Particles are instanced
- Dupliverts/faces/etc. are instanced

**Comment by nocivo72** [comment]
Hi,
I tested in viewport, and there is the same wrong orientation. I also test using geometry light and with duplivert. Always the same.  
I attach the scene.

Thanks
Massimo
[spot-lens_3.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3721931/spot-lens_3.zip)

**Comment by Theverat** [comment]
Ok, thanks for checking it.

**Comment by Dade916** [comment]
I should have found the source of the problem: I was doing the tests on CPU and it works fine while it is the GPU code to have a problem. It looks like it hasn't been updated with some of patches applied to CPU code. I'm working on it.

@nocivo72 IES light sources are points, it is the way the vast majority of IES file are generated. Using the IES files with a mesh light is an artistic way to have some penumbra, it is allowed but not accurate.

IES mesh lights have their intensity divided by the mesh area because it is like having an infinite number of IES point light sources so that explain the lower intensity when compared to a point light.

**Comment by Dade916** [comment]
I should have fixed the problem of mesh light sources with rotations on GPUs. @nocivo72 you can check the fix when the automatic build is ready (in 2-3 hours at https://forums.luxcorerender.org/viewtopic.php?f=9&t=736).

**Comment by Dade916** [comment]
It does since last Alpistinho's pull request, I guess the problem is likely to be there. Checking.

**Comment by Dade916** [comment]
Yes, there were 2 uninitialized variables, I should have fixed the problem.

**Comment by nocivo72** [comment]
>  I was doing the tests on CPU and it works fine while it is the GPU code to have a problem.

Thanks for fix the problem. I will try the change tomorrow, but in my past test (made with last release 2.2 stable) I had the same wrong result with all engines and device (CPU+path, CPU+bidir and GPU+path). You are sure about that?

> @nocivo72 IES light sources are points, it is the way the vast majority of IES file are generated. Using the IES files with a mesh light is an artistic way to have some penumbra, it is allowed but not accurate.

That the majority of IES file are point light, it's true. But you have to start not from how to IES are made and how it are usually used in other software, but from how is the effect of real light. In real light, based on modern LED (but also for common source light (bulb, linear halogen, etcc. ), always have an area  of source (not point). After the light pass through a lens that spread the light based on what you want (wide, flood, spot or narrow angle), or also to change the direction of light to have an asymmetrical projection, like for wallwhasher. In the real situation always there are soft shadows, because the source light is an area (a lot of led diod put in an surface and after concentrate with lens). For this is better to use an area light instead of point light source, like spot or point light. This to explain that the luxcore have the best IES implementation (respect to other programs that I tested), because there is the way to make IES light casting soft shadow, that is the best representation of a light that is possible. In other render engine that I tested, The IES light, always there are the hard shadows that are not a physically correct representation.
the actual luxcore implementation of IES light with area light is perfect at 90%. Missing only that the source ligth are visible to the eye (but not influence the global illumination). With this last feature, it could be the best way to represent a light.
Moreover represent some light are not possible without IES light, like the wallwasher that I puted in the test render. Is asymetrical and to make I have to create lens as in the real light.

https://www.erco.com/products/indoor/swf-3circuit/opton-5116/it/

Thanks
I will going to test your changes

**Comment by nocivo72** [comment]
I tested new version with correction. Now the transformation for area light work, with all engines and device. 
With geometry light with UV still not working the transformation. but for the moment this is ok.

Thanks
Massimo Ciani

**Comment by Dade916** [comment]
> The actual luxcore implementation of IES light with area light is perfect at 90%. Missing only that the source ligth are visible to the eye (but not influence the global illumination). With this last feature, it could be the best representation of light.

Not sure to understand: do you want the area light invisible ? A light source always influence the global illumination (and with PhotonGI indirect cache there is no additional cost per light source).

> I tested new version with correction. Now the transformation for area light work, with all engines and device.
> With geometry light with UV still not working the transformation. but for the moment this is ok.

I have pushed few minutes ago a huge rework of internal light and mesh interface to align OpenCL and CPU results and to fix some issue with instanced and motion blurred area light sources. You may want to retry when the binaries are ready.

**Comment by Dade916** [comment]
BTW, you know you can use sphere light source with IES (i.e. a point light with radius): they cast penumbras like area lights but are more suited to the spherical profile of IES data.
