### ISSUE TITLE
Impossible to activate BlendLuxCore v2.2

### ISSUE THREAD

**Issue by LMA-PX** [LuxCoreRender/BlendLuxCore#313]
#### System Information
Intel Xeon X3450
8Go ram
Win10 64 bits
NVIDIA GeForce 9500 GT (will be replaced by newer in a few days)

#### Software Version
Blender version 2.80
LuxCore version 2.2

#### Error message from Blender console
Read prefs: C:\Users\Z200\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Z200\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\auto_load.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Z200\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\auto_load.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Z200\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\auto_load.py'
addon_utils.disable: BlendLuxCore not disabled
Modules Installed (BlendLuxCore) from 'C:\\Users\\Z200\\Desktop\\BlendLuxCore-v2.2-blender2.80-win64-opencl(2).zip' into 'C:\\Users\\Z200\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Z200\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\BlendLuxCore\__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed: Le module sp├®cifi├® est introuvable.

#### Short description of error
Installation of blender OK
Download zip of luxcorerender
Install add-on luxcorerender OK
Error message above apprears when trying to activate.

I installed the required software:
    Microsoft Visual C++ Redistributable for Visual Studio 2017
    Intel C++ redistributable

Thank you very much for an advice if you know where this error comes from!

**Comment by Theverat** [comment]
It could be a problem with your OpenCL installation.
You can try to reinstall your GPU driver.
If that does not help, try if you can run LuxMark, or try to install the no-opencl version of BlendLuxCore.

**Comment by Theverat** [comment]
Could you solve the problem?

**Comment by LMA-PX** [comment]
The GPU driver was up to date.
But somehow I think it was a problme linked with the hardware. The computer+ graphic card are quite old.
I'm running it now on a newer computer without problem
Thank you very much anyway for your help
