### ISSUE TITLE
Installation prompt error

### ISSUE THREAD

**Issue by hgq123** [LuxCoreRender/BlendLuxCore#315]
![TIM截图20191022125830](https://user-images.githubusercontent.com/17998446/67260053-c6103480-f4cb-11e9-9da5-8fec8e122ace.png)
![TIM截图20191022125830](https://user-images.githubusercontent.com/17998446/67260083-e50ec680-f4cb-11e9-9905-270d4b9dde29.png)

**Comment by Theverat** [comment]
Which Blender version are you using?

**Comment by Theverat** [comment]
Closing until the reporter adds the requested information.
