### ISSUE TITLE
Pc/Blender freezes when rendering this scene with luxcore

### ISSUE THREAD

**Issue by silenttoaster7** [LuxCoreRender/BlendLuxCore#317]
[LuxcoreCrashesAtCursedInfiniteCube.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/3762322/LuxcoreCrashesAtCursedInfiniteCube.zip)

**Comment by Dade916** [comment]
Your scene is 474,533.19668 meters high and you are using Env. Light Visibility Cache (with a radius of 26 centimeters).
You would need a really LARGE amount of ram to store all that cache entries.

Just disable the Env. Light Visibility Cache and the scene will render fine.
