### ISSUE TITLE
Viewport color does not work if both Cycles and LuxCore have node trees

### ISSUE THREAD

**Issue by happysmash27** [LuxCoreRender/BlendLuxCore#323]
#### System Information

Gentoo Linux, RX 480. 

#### Software Version

* Blender version: 2.79
* LuxCore version: 2.2

#### Error message from Blender console

None

#### Short description of error

If one has a material in LuxCore, switches to cycles and adds a material for cycles, then switches back to LuxCore, the material will say "Node <none>" on the right and all the beautiful colours will be a boring white :( 

#### Exact steps for others to reproduce the error
Simple Blend file which does this: https://happysmash27.me/Upload/nocolour.blend. 

With the material selected, switch to cycles render, then press "Use Nodes".

**Comment by Theverat** [comment]
The procedure you describe works as expected in the 2.80 version of the addon (I think even with Lux v2.2, but I have only tested it with the latest sources).

The Blender 2.79 version of the addon will not receive further development, all future efforts go into the 2.80+ version. We can leave this issue open if you want (maybe another developer wants to fix this for Blender 2.79) but I would not hold my breath.

**Comment by happysmash27** [comment]
Blender 2.80 has even more bugs for me, with [the rendered viewport not working properly](https://github.com/LuxCoreRender/BlendLuxCore/issues/325), lots of single core CPU usage which makes exporting my scene take much, much longer, and random segmentation fault crashes.

**Comment by happysmash27** [comment]
In testing to file a bug report, I figured out that apparently, the segmentation fault was caused by rendering while in the particle editor, and apparently it happens with Eevee too, so is an issue with Blender 2.8 itself rather than LuxCore.
