### ISSUE TITLE
Add support for "indirect only" visibility mode.

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#327]
This is the 2.8 version of the old exclude layer feature in the old render layers.

![Capture2](https://user-images.githubusercontent.com/1584761/69478696-97042000-0df5-11ea-8125-94315bf04e8c.PNG)

**Comment by thiagodesul** [comment]
Hello @Theverat! I'd love to know if you made any progress making Lux compatible with Blender's Collection visibility system. Have a great day

**Comment by Theverat** [comment]
This particular feature was not yet implemented. Or do you mean something else?

**Comment by thiagodesul** [comment]
No, just it! Because it's pretty easy to set up different view layers to render, for example, only shadows, the object, and the background. And it would be a great addition! But no problem! =) Thank you!!

**Comment by Noah-ok** [comment]
+1
