### ISSUE TITLE
Denoiser executable not found

### ISSUE THREAD

**Issue by omgold** [LuxCoreRender/BlendLuxCore#328]
Viewport gets not denoised because OIDN executable is not found. It seems the problem is here in draw/viewport.py:

```
        current_dir = os.path.dirname(os.path.realpath(__file__))
        self._denoiser_path = os.path.join(os.path.dirname(current_dir), "bin", "denoise")
```

I don't understand the reasoning for this code. Is the executable supposed to be at <blender_config_dir>/scripts/addons/luxcorerender/draw/bin/denoise? In any case the executable is on my system at /usr/bin/denoise, which the above won't resolve to.

#### System Information

Arch Linux

#### Software Version

* Blender version: 2.81
* LuxCore plugin version: 2.2.r44.gdb179bb

#### Error message from Blender console

```
Could not start denoiser: Binary not found.
```

**Comment by Theverat** [comment]
> I don't understand the reasoning for this code. Is the executable supposed to be at <blender_config_dir>/scripts/addons/luxcorerender/draw/bin/denoise?

No, it is supposed to be in /scripts/addons/BlendLuxCore/bin/.
Calling `os.path.dirname` on a directory path is like `cd ..` in a shell, it goes up one level in the hierarchy.

I guess you compiled LuxCore and the addon yourself?
You can check which files you need and where to place them by looking at the release script (or just execute it): https://github.com/LuxCoreRender/BlendLuxCore/blob/db179bb63f33615dfd16d877e6e92063782ae672/release/package_releases.py#L43

**Comment by omgold** [comment]
No, I didn't compile the addon (is there anything to compile?) but used the AUR package blender-plugin-luxcorerender-git. During build of the package neither package_releases.py seems not to be executed, but it rather relies on the executables being in the system paths. Apparently that works for everything except the denoise executable. 

About the dirname, ah, sorry, I missed that it is called 2 times.

Okay, so maybe it can be fixed in the PKGBUILD. Will contact the maintainer.

**Comment by Theverat** [comment]
> No, I didn't compile the addon (is there anything to compile?)

Only in the sense of "putting everything in the right place".

**Comment by Theverat** [comment]
It looks to me like this is not an issue on our side, so I'm closing this, correct?
