### ISSUE TITLE
Integrate Sharlybg's LuxCore Object Library [$80]

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#337]
About the LOL: https://blenderartists.org/t/luxcore-online-library/1189258

**Comment by neo2068** [comment]
How is the integration intended? Is there a server were we can log in and get a list of models to download, e.g. like it is done with the blender cloud addon?

**Comment by neo2068** [comment]
There also is a BlenderKit asset library, which we could use as a template.
[Demo video](https://www.youtube.com/watch?v=1hVgcQhIAo8)

**Comment by Theverat** [comment]
> How is the integration intended? Is there a server were we can log in and get a list of models to download, e.g. like it is done with the blender cloud addon?

Something like that, yes. You will have to contact Sharlybg to ask for the specific details.

**Comment by neo2068** [comment]
After the first version is published I will close this issue and add new dedicated feature requests if something is missing.
