### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by thiagodesul** [LuxCoreRender/BlendLuxCore#360]
Hey! Thank you for all the effort you're doing to develop LuxCore! I'm in Love with the engine!

I'd like to know if it's planned to add support for persistent data in Lux. For example, cache geometry and textures in animations, and only-reload the ones that were changed from one frame to another.

In Octane it used to has two kinds of meshes (now it's automatic), for example: 

*Static ones: We tell the engine the mesh won't be changed during all animation and the render engine loads it only one time.
*Animated ones: Well tell the engine it needs to reload the mesh every frame because it's animated.

The same for textures, any chance to cache it? Even in .tx format? 

It would be of great help to us creating animations with Lux!

Thank you and have a great day!

**Comment by Dade916** [comment]
I transferred the issue to the BlendLuxCore repository because it is technically a BlendLuxCore new feature, not a LuxCore one.

**Comment by thiagodesul** [comment]
Thank you for your Reply! Yeah! I know it's not an easy task, but to create animations it's a very necessary feature!  

For example, we were doing an animation at @Lightfarm using cycles that the geometry and texture load took more than render itself (seven minutes only to load everything. And most parts of the assets were static ones. Because of that, we needed to change the whole project back to Redshift! 

No intention to push you guys! I'm truly enjoying LuxCore!

**Comment by Theverat** [comment]
I'd really like to have this, but it's a big project (I estimate).
We already have issue #59 about this topic, so I'll close this one.
For complicated feature requests like this one, bounties would be welcome.

**Comment by thiagodesul** [comment]
> I'd really like to have this, but it's a big project (I estimate).
> We already have issue #59 about this topic, so I'll close this issue (but comments are welcome in #59).
> For complicated feature requests like this one, bounties would be welcome.

Ok, Theverat! How much do you think a bounty for this task would cost?

**Comment by Theverat** [comment]
Hard to say, it's not really a requirement, just a motivation and encouragement for the one who implements it (at least that's how I see it).
