### ISSUE TITLE
Blender 2.81 crash.

### ISSUE THREAD

**Issue by chririz** [LuxCoreRender/BlendLuxCore#367]
I mac 4,2 ghz intel core i7 quad-core
16 gb 2400 mhz ddr4
radeon pro 575 4gb

When I activate the add-on on blender preferences it does not activate and gives me an error message, many times it completely turns off blender. where I find the correct Luxcore installation procedure. the Pyluxcore folder where should I place it?

**Comment by Theverat** [comment]
Hi, when you download the [latest build](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest), everything should already be included - it should only be necessary to install the addon via Blender's user preferences.

Which macOS version do you have?

>  gives me an error message

What does it say exactly?

**Comment by chririz** [comment]
Solved thanks!.

Il giorno gio 23 gen 2020 alle ore 22:57 Simon Wendsche <
notifications@github.com> ha scritto:

**Comment by Renderfreund** [comment]
Same here. I tried to install LuxCore in Blender 2.81. and 2.82. When i try to aktivate Luxecore Blender crashes whithout an error.

Mac OSX 10.14.6

**Comment by vonvanzu** [comment]
> Hi, when you download the [latest build](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest), everything should already be included - it should only be necessary to install the addon via Blender's user preferences.
> 
> Which macOS version do you have?
> 
> > gives me an error message
> 
> What does it say exactly?

Hello I install this version and works fine but tell me an Alpha0 warning, is it bad? how I can solve it? thanks for the info.
![Screenshot 2020-05-24 at 11 56 04](https://user-images.githubusercontent.com/65814250/82751610-a79f4e00-9db8-11ea-99d6-bdf2ac7c2d08.png)

**Comment by Theverat** [comment]
Alpha0 just means that it's an unstable in-development version.
