### ISSUE TITLE
Can't install on Mac -- Mac Pro 8 core 2013 - OS 10.14.6

### ISSUE THREAD

**Issue by teamoffsite** [LuxCoreRender/BlendLuxCore#376]
Crashes blender on install. Desperately need mac version.
We install the zip for the addon, select addon, crash on checkbox.
Tried Blender 2.81, 2.82b

**Comment by Theverat** [comment]
Possibly a duplicate of #372?

**Comment by zebus3d** [comment]
I have the same issue.

**Comment by u3dreal** [comment]
2.3 should now work with Mojave and Catalina . Use up to Blender 2.81a for 2.3 release.
updated now
[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3](url)
