### ISSUE TITLE
Blendluxcore cancel render if using a slot higher than 8.

### ISSUE THREAD

**Issue by Daymani** [LuxCoreRender/BlendLuxCore#377]
#### System Information

Windows 10 Home

Nvidia GTX 980 ti + 960

#### Software Version

* Blender: 2.81.16
* LuxCore version: 2.3 beta 1

#### Error message from Blender console

```
"Traceback (most recent call last):
  File "C:\Users\Demani\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlendLuxCore_2_3_daily\ui\image_tools.py", line 139, in draw
    stats = statistics_collection[active_index]
  File "C:\Users\Demani\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlendLuxCore_2_3_daily\properties\statistics.py", line 265, in getitem
    return self.slots[slot_index]
IndexError: list index out of range

location: <unknown location>:-1"
```

#### Short description of error

Luxcore stops instantly the render/compilation if using a slot number higher than 8.
I found a temporary way of "fixing" it by replacing the value 8 in the 226th line "slots = [LuxCoreRenderStats() for i in range(8)]" of the file located at "C:\Users\Demani\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\BlendLuxCore_2_3_daily\properties\statistics.py"
 by an higher one.

#### Exact steps for others to reproduce the error

Add a new render slot in rendering tab, switch to it and start render.

**Comment by Theverat** [comment]
Is this feature (more slots than 8) available in the official 2.81 or do I need a later version (daily builds or 2.82)?

**Comment by Daymani** [comment]
It is available since blender 2.80, so it should be in 2.81 official.

**Comment by Theverat** [comment]
Ah yeah, found it, thanks.

**Comment by Daymani** [comment]
Glad I could help !
