### ISSUE TITLE
very slow render all of a sudden

### ISSUE THREAD

**Issue by Rogerapb** [LuxCoreRender/BlendLuxCore#384]
10 sec viewport rendering
![bug](https://user-images.githubusercontent.com/61160150/74676471-69d9ca80-51b6-11ea-996a-98008bbe39fd.jpg)

**Comment by Theverat** [comment]
Can you post a testscen that shows the issue, with steps how to reproduce?

**Comment by Rogerapb** [comment]
Intel 12 thread and a gtx1070.. Tried the latest blenluxcore with latest vanilla blender2. 82 fresh install. Both render in viewport and f12 render is very slow.. Also navigating in renderedviewport is slow, almost freezes. Tried a lot of different combinations of blender 2.80 2.81 2.82 with blenluxcore 2.2 and 2.3 alfa beta and soforth. And no difference with bidir or pathtrace.. opencl, cpu is no difference.

**Comment by Rogerapb** [comment]
screengrab of cpu usage while rendering: should be 100% but is not?
![threads](https://user-images.githubusercontent.com/61160150/74713467-f02ef480-5228-11ea-8c64-a832511cd54d.jpg)
![cpu_usage](https://user-images.githubusercontent.com/61160150/74713475-f329e500-5228-11ea-8449-b2135de86932.jpg)

**Comment by Dade916** [comment]
If you open Blender, select LuxCore as render engine and press F12, how many samples/sec do you get ?

Try also to run LuxMark, there may be a problem with your OpenCL driver, it is not uncommon.

**Comment by Theverat** [comment]
I'll close this for now, please reopen after Dade's questions are answered.
