### ISSUE TITLE
Auto Smooth setting not recognized

### ISSUE THREAD

**Issue by tcheng00** [LuxCoreRender/BlendLuxCore#39]
#### System Information

Ryzen 1800x, RX480 8GB

#### Software Version

* Blender version: 2.79
* LuxCore version: 2.0 Alpha 1

#### Short description of error

My polygon with hard edges are now smooth and round. Should have hard define edges. 

#### Exact steps for others to reproduce the error

Use Suzanne and messing with Auto Smooth and degree threshold.  Doesn't seem to do anything.

**Comment by Theverat** [comment]
You can use an edge split modifier instead.
This is something we can look into at a later time. I think LuxCore would need to get auto smooth support (split edges on mesh loading).

**Comment by Theverat** [comment]
Note for the future: we could probably also implement the edge splitting into the DefineBlenderMesh() function in pyluxcoreforblender.
However, this is really low priority.

**Comment by Theverat** [comment]
I implemented support for auto smooth by adding a temporary edge split modifier to the object during export.
