### ISSUE TITLE
Can't Install: Could not import pyluxcore

### ISSUE THREAD

**Issue by tushantin** [LuxCoreRender/BlendLuxCore#395]
#### System Information

Ubuntu 18.04.4 LTS (64-bit) 
AMD® Fx(tm)-8320 eight-core processor × 8 
GeForce GTX 750 Ti/PCIe/SSE2

#### Software Version

* Blender version: 2.82a
* LuxCore version: 2.3

#### Short description of error

I'm trying to install LuxCore for the first time on Blender. Both the LuxCore package and the Blender package I've freshly downloaded from their particular websites. However, while the LuxCore package seems to import into Blender correctly, I'm unable to enable it, and instead given an error. 

I've posted the error below, copied from the Terminal. 

#### Error message from Blender console

```
Traceback (most recent call last):
  File "/home/cyan/Blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/cyan/.config/blender/2.82/scripts/addons/BlendLuxCore/__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: libOpenCL.so.1: cannot open shared object file: No such file or directory
```

#### Additional Notes

This problem seems to have been reported before, but under varying conditions and different workarounds. Those don't seem to be the right solutions for me. 

For example: I can't just update my drivers because Ubuntu already does it for me. I also would prefer not to use the non-OpenCL version, because I don't like putting additional loads on my CPU. I'm really hoping to get the OpenCL version working on my system for this reason.

**Comment by Theverat** [comment]
It seems your OpenCL installation is broken somehow.
Are other OpenCL programs working? (Cycles in OpenCL mode, LuxMark)
You might have to consult the Ubuntu documentation on how to fix the OpenCL installation, maybe an additional package is needed?

**Comment by tushantin** [comment]
Your comment helped me fix this. Apparently the drivers that come with Ubuntu directly don't seem to directly work with OpenCL. I looked around for info, and it looks like I needed to install the  "Nvidia CUDA Toolkit", and that seems to have worked with OpenCL. BUT... 

Running "clinfo" gives me: 
`  ICD loader Profile                              OpenCL 2.1`

I'm not sure what that means, but I'm assuming my graphics card can't support higher OpenCL versions, which is why even Cycles isn't running on OpenCL mode, no matter what I tried. 

But LuxCore now installed just fine. :) Thanks. 

I'll close this issue. 

(P.S.: This seems to be a common issue, I think it's worth making a wiki entry about it on the website.)

**Comment by tushantin** [comment]
EDIT: Sorry for the double-post, but it seems like LuxCore, even if I disable CPU processing, jacks up my CPU load and temperature a whole lot compared to Cycles, and renders slower (as if it is, in fact, rendering on my CPU, and not GPU). 

That's despite the fact that I clicked on "Update OpenCL device list" and input the right settings. 

Any ideas? 

I know this probably isn't the right place to ask this, but this would be very helpful.

**Comment by Theverat** [comment]
During rendering, BlendLuxCore will put a bit of load on one core to update the rendered image, the stats in the UI etc. even if you are rendering purely on the GPU. Is that what you are observing, or are all cores being used?

**Comment by tushantin** [comment]
Yeah, just now I confirmed that it does. All the cores go full 100% use, even if I'm using OpenCL / GPU.

**Comment by Theverat** [comment]
Please do the following:

* Start Blender from a terminal
* Render a scene that shows the behaviour you described
* Close Blender, and post the whole terminal output here
