### ISSUE TITLE
LuxCore crash on activation

### ISSUE THREAD

**Issue by neosushi68** [LuxCoreRender/BlendLuxCore#398]

**Comment by Dade916** [comment]
It looks like you are using the version for Blender v2.8x with Blender v2.79 (?)

**Comment by neosushi68** [comment]
> It looks like you are using the version for Blender v2.8x with Blender v2.79 (?)

I'm using the version for 2.8x and I tried in with Blender 2.81, 2.82 and 2.82a none of the really worked for me.

**Comment by Dade916** [comment]
I guess your original message is an un-edited cut&paste: you have to fill relevant information (OS, error, etc.).

**Comment by neosushi68** [comment]
Process:               Blender [26773]
Path:                  /Applications/Blender 2.82a.app/Contents/MacOS/Blender
Identifier:            org.blenderfoundation.blender
Version:               2.82a (2.82a 2020-03-12)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Blender [26773]
User ID:               502

Date/Time:             2020-03-20 16:28:00.320 +0100
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)

**Comment by Theverat** [comment]
Probably related to #372

**Comment by neosushi68** [comment]
> Probably related to #372
> (possibly a duplicate)

This helped to get it running using Blender 2.81

https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-581070700

**Comment by melMass** [comment]
#372 solution worked for me too ! (2.81 on Mojave).

This should be stated somewhere I think

**Comment by melMass** [comment]
Also some files (denoiser) are not 777 by default resulting in a permission error

**Comment by zohozer** [comment]
Same here. Using the latest BlendLuxCore downloaded from here and installed into the stable Blender 2.82a on MacOS 10.14.6 Mojave. I do have a crash when activating the add-on. I do tried different versions of the BlendLuxCore, all of them are crashing Blender. 

I do launched Blender from console so I can have a feedback and this is the cause of crash:
```
BlendLuxCore 2.4alpha0 registered (with pyluxcore 2.4alpha0)
Bus error: 10
```

If somebody knows a way to fix this issue, please post.

**Comment by zohozer** [comment]
Searching on internet about the "Bus error:10", this seems to be a compilation problem?

**Comment by melMass** [comment]
@zohozer 2.82 is not supported on Mac for now

**Comment by zohozer** [comment]
Even the standalone version of LuxCore is crashing on my Mac. Simply I can't use any of the newest builds.

**Comment by zohozer** [comment]
I thing that is more of a compilation problem of the binery, see the "Bus error: 10" that I do have in the console.

**Comment by Dade916** [comment]
> Even the standalone versions of LuxCore is crashing on my Mac. Simply I can't use any of the newest builds.

Is the MacOS SIP related problem described here https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-579989560 ?

Or do you have a very old CPU ? Some SSE instruction is not supported on some very old CPU (10+ years old).

**Comment by DaveSledz** [comment]
Guys I still have the same problem as you have (Bus Error 10) when I want to enable newest Lux (2.3). I could do that with beta version on Blender 2.81 but now I just can't do that.

Of course you can disable SIP and do that but it is not a workaround. Normal user should not touch that functionality. Any idea how we can enable Lux on MacOS?

**Comment by melMass** [comment]
@DaveSledz @zohozer Did you follow the instructions there https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-581070700 ?

Works flawlessly on my end, I had to `chmod +x BlendLuxCore/bin/denoise` aswel

**Comment by DaveSledz** [comment]
@melMass please tell me - what you did exactly with denoise file? You pasted this command into terminal?

**Comment by DaveSledz** [comment]
Tried your chmod command but still Blender crashes when I want to enable that

**Comment by melMass** [comment]
Did you download Embree binaries and replaced them in the bin folder ? That's what solves the crash, the denoise bin is optional for Lux to work

**Comment by DaveSledz** [comment]
Sure I replaced three files - libembree3.3, libtbb, libtbbmalloc. Also did the chmod +x - the denoise file changed into executable. Then run from terminal, enable and crash.

**Comment by zohozer** [comment]
> Is the MacOS SIP related problem described here [#372 (comment)](https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-579989560) ?
> 

Give-me a minute, I need to read how to read how to install as described in the tutorial.

> Or do you have a very old CPU ? Some SSE instruction is not supported on some very old CPU (10+ years old).

This are the specs of my machine:
![About_Mac](https://user-images.githubusercontent.com/5983791/77226746-98aade00-6b72-11ea-9608-5997af6ef12a.png)

**Comment by zohozer** [comment]
Now both of the BlendLuxCore and the LuxCore standalone are working. I used the tutorial from here:  [#372 (comment)](https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-579989560) ?

I think that the issue was the missing Intel Embree library. I do installed this libraries in my system and replaced the ones on the BlendLuxCore and now everything works fine.

<img width="1437" alt="BlendLuxCore_LuxCore" src="https://user-images.githubusercontent.com/5983791/77227178-23d9a300-6b76-11ea-8781-f7a961dc1282.png">

**Comment by DaveSledz** [comment]
Did everything as you said and Blender still crashes : - Have you installed that on clean Blender or you have other addons? Also - is there any additional step you're doing to run Lux?

**Comment by jamespa16** [comment]
If I read the crash dumps correctly, this is _**not**_ a signature error like last time. A `SIGBUS` error (this `Bus 10` bit falls under this) is when a program attempt to allocate a memory address that simply does not exist. So this is not a quick-fix-able problem. An error like this is most likely a problem in Blender, though 2.83 latest also suffers. Until Blender gets fixed, it is unlikely that there will be any solution other than downgrade to 2.81, follow my original solution in #372 and wait.

**Comment by DaveSledz** [comment]
Ok, can we somehow inform Blender devs about that problem? But they can say that it is a Lux devs problem. How can we properly introduce that issue to them?

**Comment by u3dreal** [comment]
You might consider 
[https://www.bountysource.com/issues/90847808-sign-released-macos-binaries-files](url)

I still don't undestand why this #372 works ... i also just copy the latest embree libs during build ...

**Comment by u3dreal** [comment]
I think i solved it.

2.3 osx release has been updated and should work with Mojave/Catalina now 
[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3](url)

**Comment by neosushi68** [comment]
I'll give it a shot and send feedback

**Comment by u3dreal** [comment]
perfect thanks !

**Comment by neosushi68** [comment]
After deleting the previous version. I cleaned up my addons folder, restarted blender (no addons) downloaded the latest version. Installation went fine. No crash, no hick-ups. Thanks !!!

**Comment by u3dreal** [comment]
great to hear !!!

**Comment by u3dreal** [comment]
great to know and here !
