### ISSUE TITLE
No OpenCL device selected or available

### ISSUE THREAD

**Issue by garryFromGermany** [LuxCoreRender/BlendLuxCore#399]
#### System Information

Debian GNU/Linux 10 (buster)
Intel HD Graphics 620

#### Software Version

Blender 2.81
BlendLuxCore-v2.3-linux64-opencl

#### Error message from Blender console

`Traceback (most recent call last):`
`  File "/home/garry/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/base.py", line 84, in render_final`
`    final.render(self, depsgraph)`
`  File "/home/garry/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/final.py", line 49, in render`
`    _render_layer(engine, depsgraph, statistics, layer)`
`  File "/home/garry/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/final.py", line 61, in _render_layer`
`    engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)`
`  File "/home/garry/.config/blender/2.81/scripts/addons/BlendLuxCore/export/__init__.py", line 222, in create_session`
`    return pyluxcore.RenderSession(renderconfig)`
`RuntimeError: No OpenCL device selected or available`
`ERROR: No OpenCL device selected or available`

#### Short description of error

I am not able to render using the graphics card. 

#### Exact steps for others to reproduce the error

*Blender was downloaded manually from the [official website](https://www.blender.org/)
*LuxCore was downloaded from the [official website](https://luxcorerender.org/download/)
 and extracted into my home folder.
*LuxCore as an add-on to blender was installed from BlendLuxCore-v2.3-linux64-opencl.zip
*Before I was able to enable the add-on I followed instructions from [askubuntu](https://askubuntu.com/questions/796770/how-to-install-libopencl-so-on-ubuntu), namely I typed into the terminal:
`sudo apt update`
`sudo apt install ocl-icd-opencl-dev`
*The error occurs when trying to render blenders default cube using the settings:
Render Engine: LuxCore
Device: OpenCL
Engine: Path

Any help is appreciated.

**Comment by Theverat** [comment]
Did you enable you graphics card in the render properties > performance panel > GPU devices subpanel?
Intel OpenCL devices are disabled by default because they notoriously cause crashes due to their bad OpenCL drivers.

**Comment by garryFromGermany** [comment]
Under the performance panel was only a warning "No OpenCL Devices available." 
After following OpenCL installing instructions from another page of [askubuntu](https://askubuntu.com/questions/850281/opencl-on-ubuntu-16-04-intel-sandy-bridge-cpu/850594#850594) : 
`sudo apt install ocl-icd-libopencl1`
`sudo apt install opencl-headers`
`sudo apt install clinfo`
`sudo apt install beignet`
I have the option: Intel(R) HD Graphics Kabylake ULT GT2
When I enable that and try to render, blender crashes as you predicted. I do not know which of the many lines of the output are important, but the last lines are:
`ASSERTION FAILED: (isa<AllocaInst>(ptr) || ptrCandidate.empty()) && "storing/loading pointers only support private array"
  at file /build/beignet-jdrO6z/beignet-1.3.2/backend/src/llvm/llvm_gen_backend.cpp, function void gbe::GenWriter::findPointerEscape(llvm::Value*, std::set<llvm::Value*>&, bool, std::vector<llvm::Value*, std::allocator<llvm::Value*> >&), line 1004
Trace/breakpoint trap
`

**Comment by Theverat** [comment]
Unfortunately there's nothing we can do about this. You could try to report it as a bug to the developers of the OpenCL driver.
