### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by fadhil0305** [LuxCoreRender/BlendLuxCore#400]

**Comment by Theverat** [comment]
Please fill in some information so we can help you.

**Comment by fadhil0305** [comment]
I'm having trouble installing LuxCoreRender in Blender.
It gives me this error when I try to activate it.
Can someone help me?
Blender 2.79b
LuxCoreRender v2.0 stable but same problem with LuxCoreRender v2.1alpha1
Windows 10

**Comment by Theverat** [comment]
I guess you're talking about the error in the picture you posted here: https://forums.luxcorerender.org/viewtopic.php?f=4&p=20887#p20887

You have installed the BlendLuxCore version for Blender 2.8x in Blender 2.79.
