### ISSUE TITLE
Luxcore 2.3 installation issue

### ISSUE THREAD

**Issue by adenirantayo** [LuxCoreRender/BlendLuxCore#401]
Hello,
I wasn't able to install luxcore 2.3 on b3d 2.83, although, I have the beta version of luxcore 2.3 running on 2.83. 
I did installed the redistributables being told to install.
![luxcore Capture](https://user-images.githubusercontent.com/25295202/77227137-41ab0600-6b7e-11ea-8be4-8063afe7bc07.PNG)

**Comment by Theverat** [comment]
Your installation might be broken somehow.
Remove the addon folder and re-install the addon.

**Comment by adenirantayo** [comment]
Already did that, today was my 4th attempt. In fact, I reinstalled (repair) the redistributables

**Comment by Theverat** [comment]
Does it work with other Blender versions? 2.83 is not officially supported yet as it is still in development. Does it work with 2.82a?

**Comment by adenirantayo** [comment]
I installed luxcore 2.3 on blender 2.8.2. I don't know the beta version worked and the final version didn't

**Comment by Theverat** [comment]
So it doesn't work in 2.82 either?

**Comment by adenirantayo** [comment]
I checked on the folder(user/appdata/roaming/blenderfoundation/blender/2.82/scripts/addons) for the newlyrics installed luxcore and i realized that there were only 4 folders and everything was about 41MB in size. Must be a corrupt download. Thanks for the assistance
