### ISSUE TITLE
Render: LuxCore crashes when activated. Blender 2.82. macOS Catalina 

### ISSUE THREAD

**Issue by Ibo0o0o** [LuxCoreRender/BlendLuxCore#403]
#### System Information

Operating system and graphics card
MacOS Catalina Radeon Pro 560 4 GB

#### Software Version

* Blender version: 2.82
* LuxCore version: 2.3

#### Error message from Blender console

---

#### Short description of error

Blender crashes when activated (add-ons)

#### Exact steps for others to reproduce the error

Just install.

Please tell us which render engine you used and if it was in OpenCL or CPU mode.

Just CPU mode

Thank you

**Comment by Theverat** [comment]
please fill in or delete the issue template text.

**Comment by Ibo0o0o** [comment]
System Information

Operating system and graphics card
MacOS Catalina Radeon Pro 560 4 GB

Software Version

Blender version: 2.82
LuxCore version: 2.3
Error message from Blender console

Short description of error

Blender crashes when activated (add-ons)

Exact steps for others to reproduce the error

Just install.

Please tell us which render engine you used and if it was in OpenCL or CPU mode.

Just CPU mode

Thank you

**Comment by Theverat** [comment]
Probably related to #372
(possibly a duplicate)
See also #398

**Comment by u3dreal** [comment]
The Problem with Blender 2.82+ should be solved now
[https://devtalk.blender.org/t/blender-2-82-crashing-on-osx-only-when-activating-blendluxcore/12397](url)

Still there might be the codesigning issue in Mojave and Catalina
