### ISSUE TITLE
Support hair

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#41]
Todo:
* [x] Implement hair export
* [ ] Test and verify
* [ ] Prevent "singular matrix in matrixinvert" error (can happen with kempt hair, probably when a hair strand is compressed into a single point) - maybe add a small epsilon to all hair coordinates?

* ~~Accelerate with LuxCore C++ function?~~
Seems like accelerating this with C++ is a lot of work, because we need the co_hair() method of the particle system class.
We would either have to link against blender (haha) or re-implement this function in our code.

**Comment by Dade916** [comment]
LuxCore Python API has a Scene::DefineStrands() method to export an "hair" shape. There is an example here: https://github.com/LuxCoreRender/LuxCore/blob/80488effc7501d564c0dbc19f5987f4456cc68bb/samples/pyluxcoredemo/pyluxcoredemo.py#L272

**Comment by neo2068** [comment]
How do I add properties to the particles panel in the UI? I think, I have all code there but the properties aren't shown. I will push the code into the export_dupli branch this afternoon when I am at home.

**Comment by neo2068** [comment]
Thank you. Yes, that is what I meant. It was a stupid copy&paste error. I accidently added the properties into another panel.

**Comment by neo2068** [comment]
I pushed the code for initial hair export. It is based on the old code which iterates through the hair strand data with psys.co_hair. It is rather slow. 1.4 seconds for 30000 strands and 6.5 seconds for 100000 strands. 

```
[Plane: ParticleSystem] Exporting hair
[LuxCore][521.204] Refining 29999 strands
[LuxCore][521.407] Strands mesh: 105180 triangles
[LuxCore][521.422] Strands shape uses colors
[LuxCore][521.438] Refining time: 0.234 secs
[SDL][521.438] Texture definition: 1453513604200
[SDL][521.438] Reading texture map: F:\Temp\hairtest_material\tiger.jpg
[SDL][521.454] Material definition: 1453524219752
[SDL][521.454] Scene objects count: 1
[Plane: ParticleSystem] Hair export finished (1.449s)
```
```
[Plane: ParticleSystem] Exporting hair
[LuxCore][737.391] Refining 100000 strands
[LuxCore][738.672] Strands mesh: 1493738 triangles
[LuxCore][738.719] Strands shape uses colors
[LuxCore][738.860] Refining time: 1.45 secs
[SDL][738.875] Texture definition: 1453513604200
[SDL][738.875] Reading texture map: F:\Temp\hairtest_material\tiger.jpg
[SDL][738.922] Material definition: 1453524219752
[SDL][738.922] Scene objects count: 1
[Plane: ParticleSystem] Hair export finished (6.506s)
```

**Comment by Theverat** [comment]
There was a weird code duplication, some code was simply doubled (see my last commits).
https://github.com/LuxCoreRender/BlendLuxCore/commit/b8a2eed77a6dcb858ff520e229cd8fa0c66da1a7
Is this the result of some faulty merge somewhere?
I hope there are no other spots where it happened.

**Comment by neo2068** [comment]
Yes, my git made a mess in the last commit. I will look into the diffs if there is more code duplication. Suprisingly, the code syntax seems to be correct because the code works in blender. Should we merge the dupli/particle code into the trunk, if the code works properly?

**Comment by Theverat** [comment]
Yes, let's merge it.
We are in alpha anyway :)

**Comment by Theverat** [comment]
I merged it.
By the way I noticed that the last segment of the hair is not exported, see images.
You can best see it in the bottom left corner if you switch between the images.

![ogl](https://user-images.githubusercontent.com/1584761/35039556-7e68f060-fb7e-11e7-86b3-4b348d2b987f.jpg)
![untitled](https://user-images.githubusercontent.com/1584761/35039557-7e870168-fb7e-11e7-92f3-8f1664fe122e.jpg)

**Comment by neo2068** [comment]
I can't reproduce the problem. In my test the hair seems to export correctly. See images.
![grafik](https://user-images.githubusercontent.com/17701407/35068181-943e2510-fbd6-11e7-97ea-a6ae639fe342.png)
![grafik](https://user-images.githubusercontent.com/17701407/35068196-9e57f332-fbd6-11e7-9bcf-d894503df503.png)

**Comment by Theverat** [comment]
It only happens in final render, viewport is ok.
Btw. you posted 2 times the same image.

**Comment by neo2068** [comment]
I could trigger a situation where it happens here, too. Even in preview render. I think it is a indexing proprem of the point array. I will look into it.
