### ISSUE TITLE
Crash when I try to activate Luxcore in Blender 2.8

### ISSUE THREAD

**Issue by rubenbox** [LuxCoreRender/BlendLuxCore#415]
I can install the add-on, but when I try to activate it Blender crashes

**Comment by Theverat** [comment]
What OS are you on?

**Comment by rubenbox** [comment]
OS Ojave 10.14.6

—
[image: Design&Practice Creative Agency Amsterdam]
<http://www.designandpractice.com/>

—
Ruben de la Rive Box
Founder | Director

—
T +31 (0)20 368 23 50
M +31 (0) 6 4126 5327
—
designandpractice.com <http://www.designandpractice.com/> —
Silodam 112
1013 AS Amsterdam

**Comment by exanprime** [comment]
Same issue for me
OS: macOS 10.15.3 (19D76)
Blender v 2.82a (2.82a 2020-03-12)
MacBook Pro (16-inch, 2019)

**Comment by u3dreal** [comment]
MacOS 10.14 and higher introduced notarization of apps. So since we have no AppleDeveloperLicense we can not do that for now. So SIP will simply kill BlendLuxCore. Either disable SIP.(Google that)
You might also consider ...
[https://www.bountysource.com/issues/90847808-sign-released-macos-binaries-files](url)

It is best for now to stay on High Sierra ... still CUDA support (that might come into LuxCore sooner or later ) and no Signing Notarizing shabam.

**Comment by exanprime** [comment]
Thank you for your email.

I tried the way with disabling SIP. And it's still not working.

I sent some bounty to speed up the process.

Thank you,
Alex

**Comment by u3dreal** [comment]
I updated the 2.3 release it should work now on Mojave and Catalina ...
Only with Blender 2.81a.

[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3](url)

**Comment by exanprime** [comment]
Hi,

Don't see any new commits here
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3
<http://url/>

Looks like it was not the OS related issue, but the Blender version.
I tried the previous release version of LuxCore with Blender 2.81a and it
works fine and it's crashing with 2.83
So  2.83 is not supported on MacOS

Thank you,
Alex

**Comment by u3dreal** [comment]
2.83 only works with 2.4alpha since there were some changes in Blender.

"I tried the previous release version of LuxCore with Blender 2.81a and it
> 
> works fine“

The 2.3 release files have been updated yesterday.
Now they work with Mojave and up.

> Am 10.04.2020 um 19:29 schrieb Alex Nefedov <notifications@github.com>:
> 
> 
> Hi,
> 
> Don't see any new commits here
> https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3
> <http://url/>
> 
> Looks like it was not the OS related issue, but the Blender version.
> I tried the previous release version of LuxCore with Blender 2.81a and it
> works fine and it's crashing with 2.83
> So 2.83 is not supported on MacOS
> 
> Thank you,
> Alex
>

**Comment by Theverat** [comment]
Can we close this issue? Is it resolved?

**Comment by u3dreal** [comment]
Yes it should work with lates luxcore release..
