### ISSUE TITLE
Can't activate in KDE Neon

### ISSUE THREAD

**Issue by BojanBekic** [LuxCoreRender/BlendLuxCore#416]
Trying to install gives the error message in the screenshot.
Blender 2.82a, Blender 2.83, BlendLuxCore v2.3, BlendLuxCore latest
Linux, Serbian localization
Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
Kernel Version: 5.3.0-45-lowlatency
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15,5 GiB

![Screenshot_20200404_211505](https://user-images.githubusercontent.com/48101283/78459540-051cf580-76ba-11ea-8315-fce4abe8ff29.jpeg)

Thanks!

**Comment by Theverat** [comment]
Does the no-opencl version work?
If yes, it might be a problem with the OpenCL driver.

**Comment by BojanBekic** [comment]
Thanks, will try now

**Comment by BojanBekic** [comment]
That's it! CPU only version works!
But how can I solve this, if anyone can help? I actually tried opencl version a week ago and since it didn't work, I updated the drivers from an NVIDIA ppa, but it didn't go smoothly, and this is my situation now.

![slika](https://user-images.githubusercontent.com/48101283/78460333-33053880-76c0-11ea-9d1b-cb1634989fc0.png)

My system thinks I'm using nouveau driver and doesn't let me enable 440 (the recommended one), but NVIDIA settings says it's 440.64 and Cycles works normally. 
Is there a problem somewhere here?

**Comment by BojanBekic** [comment]
I have purged and reinstalled the driver. If I choose the 440 recomended driver, it switches to nouveau. It only lets me use the 435 version. Either way, blendluxcore opencl fails to install.
Any ideas?
I'll try to find out why I cant use 440, but I'm not sure these two things (driver version in use and blendluxcore install error) are related...

**Comment by Theverat** [comment]
Try to run LuxMark. If it works, the problem is probably in LuxCore, if it doesn't, it's still a driver problem.

**Comment by BojanBekic** [comment]
Thanks for suggestions.
I have reinstalled the whole system and kept the drivers untouched, now it uses 435 version.
I have downloaded **LuxMark** and **LuxCore standalone** tar.bz2 archives and extracted them into their respectable folders. 
Running luxmark.bin, or luxcoreui does not start the programs.
So, it's a driver problem? Does anyone use Neon, or has some idea?
![Screenshot_20200405_171535](https://user-images.githubusercontent.com/48101283/78502383-3c92ad00-7761-11ea-88fa-58d83aee1cab.jpeg)

**Comment by Paulo077** [comment]
Hello BojanBekic,
I have the same graphic card  GTX960M / Blender 2.82 / Lux 2.3 / Pop OS 19.10 / Nvidia 440.64
I have the same issue with LibOpenCL.so.1.

I try:
sudo apt update
sudo apt install ocl-icd-opencl-dev
and it's OK for me. (LibOpenCL.so.1 is create and Lux use Nvidia 440.64 to identify my card)

Rem: Performance with OPENCL (CPU+GC) vs CPU only is little for me.
 Have a good day

**Comment by BojanBekic** [comment]
Hi Paulo,
Thank you very much, your solution **fixed the problem!**
Everything is working now, I'm running test scenes and I'm very excited with the results :)
Thanks everybody for the effort.
