### ISSUE TITLE
Random Per Object Node

### ISSUE THREAD

**Issue by zareami10** [LuxCoreRender/BlendLuxCore#417]
Or in general something like Cycles' "Object Info" node, as it currently seems impossible to randomize shaders/textures when dealing with a lot of similar objects (there seems to be a random node in master but it seems... different?).

**Comment by Theverat** [comment]
Add Node > Utils > Object ID
Switch to "normalized" for values in range 0 to 1.

**Comment by zareami10** [comment]
> Add Node > Utils > Object ID
> Switch to "normalized" for values in range 0 to 1.

Thanks, yes I had tried that but my perception from my tests was that what I was getting wasn't really random compared to cycles' node, but then I gave all the `obj.luxcore.id`'s a random number and then remapped via nodes and got a pretty similar result in terms of "randomness". I'm not sure whether there actually is a problem or not anymore, so I guess I better close this issue.

**Comment by Theverat** [comment]
BlendLuxCore uses a very similar method as Cycles to create the "random" object IDs: the object name is hashed and the lower 4 bytes are interpreted as the ID. 
You can see that by changing the name of an object: both in Cycles and BlendLuxCore, it will change the random value per object.
