### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by b91b** [LuxCoreRender/BlendLuxCore#419]
hello,
I'm having a setup problem. When I want to activate the addon, I get a window saying:" ImportError: libOpenCL.so.1: cannot open shared object file: No such file or directory
Sincerely
![Capture du 2020-04-10 15-30-02](https://user-images.githubusercontent.com/19393197/78996205-6888a680-7b44-11ea-92f5-790b3ab5de9d.png)

**Comment by Theverat** [comment]
Your OpenCL installation is probably broken.

**Comment by Theverat** [comment]
https://forums.luxcorerender.org/viewtopic.php?f=4&t=2065#p21931 might help you.
