### ISSUE TITLE
wrong export of area lights in final render

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/BlendLuxCore#42]
System Information

windows 10, NVIDIA GTX 1080 + GTX 780

Software Version

Blender version: 2.79, 850f736, 
LuxCore version: 2.0 alpha1, 9b3ae9168be1495395e8057165eb1948c79b444b

Short description of error
The plane of an area light is not exported correctly in final render mode. In viewport rendering everything is fine.

Exact steps for others to reproduce the error
Add an area light visible in the camera view and hit F12.
Viewport render:
![arealight1](https://user-images.githubusercontent.com/17701407/34916330-030b7076-f937-11e7-8721-33fbdfb3ad97.jpg)

Final render:
![grafik](https://user-images.githubusercontent.com/17701407/34916351-64160a5c-f937-11e7-8e3f-712a637fe806.png)

**Comment by neo2068** [comment]
Could that error be related with the change of the transform matrix code for motion blur in LuxCore?

**Comment by Theverat** [comment]
I can't find those commit hashes in the LuxCore repo.
Did you try recompiling with the latest commit?

**Comment by Dade916** [comment]
I'm trying to reproduce the problem here but it works fine. Can you post the .blend ?

**Comment by Dade916** [comment]
Ok, it is a lamp => area, not a mesh area light.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by neo2068** [comment]
Sorry, commit hash came from BlendLuxCore. Dade fixed the issue in the meantime.
