### ISSUE TITLE
Blender 2.82a Mac crashes when switching on BlenderLuxCore 2.3 in add-ons

### ISSUE THREAD

**Issue by jjfabien** [LuxCoreRender/BlendLuxCore#420]
I have "installed" (basically copied the downloaded files from Blenderluxcore 2.3 into the add-ons directory of Blender for MAC). When going under add ons, the blenderluxcore file is present but when I select it, it crases blender. 
OS : Catalina 10.15.4
Core I7
32Gb Memory
Radeon Pro 580 8 Gb

How to sort out this issue?
Your help would be greatly appreciated.

Kind regards

**Comment by nauutilus** [comment]
Exactly same problem here. 

I have run Blender in debug mode and I have a warning, not sure is related:

`Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'`

I use Blender 2.82a

OS: Catalina 10.15.5
Core i7
32GB RAM 
Radeon RX 580 8GB

**Comment by nauutilus** [comment]
For some reason, after I installed latest build, now I'm able to even able to enable the stable 2.3. @jjfabien You can do like me: remove 2.3 -> install latest build: https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest  -> remove latest -> install again 2.3 and should work.

**Comment by Theverat** [comment]
@u3dreal Is this already fixed now?

**Comment by u3dreal** [comment]
2.3 does not work with Blender 2.82 and up ! Use 2.81a.

**Comment by jjfabien** [comment]
hello there,

I followed the tips - erased the blenderluxcore and replaced it by the most recent addition and now there is an error message. Unfortunately, cannot copy the message since it disappears when I move the cursor. When I click to enable blender, it starts with a message (traceback (most recent call last..) and at a stage it says :"could not import pyluxcore"
