### ISSUE TITLE
Color Management ?

### ISSUE THREAD

**Issue by melMass** [LuxCoreRender/BlendLuxCore#428]
HI,

I don't understand how does LuxCore handles color management, I use OCIO only since quite a long time inside Blender Cycles.
I've been testing Lux for two weeks now and I've just realized all my renders look strange and that the image node of LuxCore does not contain color profile information besides gamma neither does the settings.

Can you explain how it's handled? Do you support OCIO or the builtin Filmic for instance?

Thanks

**Comment by Theverat** [comment]
Not sure if this is a LuxCore or addon issue, @Dade916?

**Comment by Dade916** [comment]
> Not sure if this is a LuxCore or addon issue, @Dade916?

It is all related how the image pipeline is configured. LuxCore works in sRGB and it will output untouched values with an empty pipeline.

Try to export the scene in text format and to render with LuxCore standalone if you want to check directly the LuxCore output.

"Strange" is also a big vague as term, we need a test scene showing some kind of problem.

**Comment by melMass** [comment]
> "Strange" is also a big vague as term, we need a test scene showing some kind of problem.

For sure, sorry it's completely subjective (and I could be wrong), I just wanted more info on the color pipeline.
What I don't get is how textures are handled as they have no option to interpret the input as Image nodes in a vanilla blender do.

I'll try to come up with a more precise test soon

**Comment by Dade916** [comment]
> What I don't get is how textures are handled as they have no option to interpret the input as Image nodes in a vanilla blender do.

Image maps are assumed in sRGB color space and reversed gamma according the declared image map gamma value (i.e. default = 2.2, untouched if gamma is 1.0).

**Comment by Theverat** [comment]
Can we close this? Or is something still unclear?

**Comment by melMass** [comment]
Yes, sorry, the solution is I just don’t use ACES with Lux anymore
