### ISSUE TITLE
Enabling BlendLuxCore-v2.3 Add-on crashes Blender Mac 2.82a 

### ISSUE THREAD

**Issue by mayaviews** [LuxCoreRender/BlendLuxCore#429]
The BlendLuxCore-v2.3-mac64-opencl.zip file can be installed in the Blender Add-On Preferences. 

But checking the box to enable Render: LuxCore immediately crashes Blender Mac 2.82a (2020-03-12).

**Comment by melMass** [comment]
It's been answered in #398 and #372 

Try the solution from https://github.com/LuxCoreRender/BlendLuxCore/issues/372#issuecomment-581070700 and give a more detailed report if you still have an issue.

**Comment by u3dreal** [comment]
2.3 only works with 2.81a and earlier. Plz use 2.81a with 2.3
