### ISSUE TITLE
Packed materials switches

### ISSUE THREAD

**Issue by BlurnKek** [LuxCoreRender/BlendLuxCore#431]
.blend file: Works with any blend file with a few textures

Steps to reproduce: add a few objects, create different materials on them, add textures on each material, tweak objects a bit and then start to ctrl+z few times 

Screenshots or rendered images:
![unknown](https://user-images.githubusercontent.com/63809051/79571833-0f8db500-80e6-11ea-81c1-37f4e0ed8cf1.png)

Error message from Blender console: No error blender thinks that everything fine

OS:  Windows 10
Blender version: tested 2.81 2.83 (2.83 without any other addons, completely clean)
LuxCore version: 2.2 2.3

I find that when I "unpack all into files" or reload textures on each broken material everything turns back to normal
+ if I don't use textures then nothing wrong happens.
+ not only Base colors switch with each other but also a base color can be switched with a normal map.

BTW sorry for my English

**Comment by Theverat** [comment]
Can you upload a small scene showing the problem?
Something like two planes with two materials.

**Comment by BlurnKek** [comment]
Blend file + video
[matswitchbug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4496231/matswitchbug.zip)
