### ISSUE TITLE
disable blender color management when lookdev activated

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/BlendLuxCore#437]
I've installed Photographer addon and this to change the exposure modifies the "exposure" value in the blender color management. panel.
This change modify how the lookdev appears so my suggestion is to dissable or change temporary that Blender exposure value to get the "right" color of the textures.
Otherwise you could get burned viewport or very dark one clearing the useful of the lookdev mod.

I think that, this it could be useful not just when you have Photographer addon installed but also if someone use something "different" as color management.

**Comment by Theverat** [comment]
In v2.4, our material/textures shading mode (I guess you mean this with lookdev?) already compensates for the color management exposure.
