### ISSUE TITLE
Vector T

### ISSUE THREAD

**Issue by zorianpl** [LuxCoreRender/BlendLuxCore#438]
bpy.context.space_data.context = 'RENDER'
bpy.data.window_managers["WinMan"].addon_search = "lux"
bpy.context.scene.render.engine = 'LUXCORE'
vector<T> too long
bpy.context.area.ui_type = 'INFO'

Whatever it mean. Tried to create a render with linked objects and caustics from waterpool above the ceiling. It was rendering quite well, and after few times get this problem. OpenCL (GTX 1080+RT|X2080TI) stopped work a lond time ago. wanted to use CPU (i7-6800k) 128GB Ram Tried versions 2,3 and 2,4

**Comment by zorianpl** [comment]
![image](https://user-images.githubusercontent.com/28535367/80894805-e6247a00-8cde-11ea-873c-3693c7d60f78.png)

**Comment by Theverat** [comment]
Can you upload a simplified scene that still shows the problem?

**Comment by zorianpl** [comment]
Not really, I cannot even reproduce it by myself on the same scene - now it started quite wel. 
![image](https://user-images.githubusercontent.com/28535367/80894916-ea04cc00-8cdf-11ea-83dc-56cdeba072bd.png)

**Comment by Theverat** [comment]
If you can reproduce it in the future, please reopen this issue, for now I'm closing it.
