### ISSUE TITLE
How to get .bcf Extension on blender ( network render on luxcore render)

### ISSUE THREAD

**Issue by fadhil0305** [LuxCoreRender/BlendLuxCore#440]
![image](https://user-images.githubusercontent.com/52478779/81002365-4c420600-8e73-11ea-876f-c114b51858d8.png)

![image](https://user-images.githubusercontent.com/52478779/81002056-d9d12600-8e72-11ea-88aa-d324dbd2640f.png)

hai, everyone. I need your help. I want to make a network render with luxcorerender in blender. but i cant to get bcf extension while export in the blender. help me, please. how to get bcf extension on blender export.

**Comment by Theverat** [comment]
In the render properties, open the "LuxCore Tools" panel, enable filesaver, change from text to binary and hit F12.
![Screenshot from 2020-05-04 21-32-45](https://user-images.githubusercontent.com/1584761/81005868-e5aaf100-8e4e-11ea-848f-6bb1e8418ad7.png)

**Comment by fadhil0305** [comment]
next step??

**Comment by Dade916** [comment]
After you press f12, the .bcf file will be created in the directory you have selected ("/tmp/" in the above screenshot).

**Comment by Theverat** [comment]
I guess this is answered?
