### ISSUE TITLE
Hiding from the sun closes Blender or directly freezes

### ISSUE THREAD

**Issue by Noah-ok** [LuxCoreRender/BlendLuxCore#442]
Play the bug
1. transform point to sun
2. Attach to Sky
3. Use Ground Color
4. Activate all restriction toggles
5. Hide all
<a href="https://imgbb.com/"><img src="https://i.ibb.co/mqFJrGQ/2020-05-05-224329.png" alt="2020-05-05-224329" border="0"></a>
6. Render

Blender 2.82a Luxcore2.4alpha0

**Comment by Dade916** [comment]
I assume this is a BlendLuxCore issue.

**Comment by Theverat** [comment]
Please upload a testscene.

**Comment by Noah-ok** [comment]
The problem is also that when the file is saved you don't see the error.
It is "solved" when you save.

**Comment by Theverat** [comment]
The thing is, I don't know how your startup.blend looks like and if maybe one of the settings you got in there triggers the bug.
Please upload a .blend file that I can open, then I'll follow the steps you describe to reproduce the problem.

**Comment by Noah-ok** [comment]
Ah! you're right excuse me
[mydefaultblender.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4597107/mydefaultblender.zip)

**Comment by Acrivec** [comment]
It happens if you have render view turned on and hide any light source from rendering/viewport (eye icon, monitor icon, camera icon, the monitor icon is causing this).

**Comment by Theverat** [comment]
@Acrivec With latest daily build?
Does it happen with CPU only as well, or only with GPU rendering?

**Comment by Acrivec** [comment]
@Theverat I can't reproduce it on the lastest daily build + 2.90.

It looked to me like a pointer to light source wasn't removed, but the place it pointed to - was.
Possibly fixed.

**Comment by Theverat** [comment]
I can't reproduce this issue with the latest v2.5 and Blender 2.83. 
If the issue still happens on your end, please re-open it.
