### ISSUE TITLE
Fireflies remains with OIDN in 2.4 Alpha

### ISSUE THREAD

**Issue by cgvirus** [LuxCoreRender/BlendLuxCore#443]
.blend file:
[truslucence Test.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4589144/truslucence.Test.zip)

Step:
Render with 2.3>Firefly not visible.
Render with 2.4a>Firefly visible

Screenshots or rendered images:
2.3
![2 3](https://user-images.githubusercontent.com/22106885/81221817-251b3e00-9005-11ea-9a24-ae7eb1736e01.jpg)
2.4 Alpha
![2 4a](https://user-images.githubusercontent.com/22106885/81221828-28aec500-9005-11ea-98dc-7ade6bc1b49d.jpg)

OS: Debian 10 Sid
Blender version: 2.82a
LuxCore version: 2.4 Alpha

**Comment by Theverat** [comment]
Can you show the noisy input images? If they are the same, the difference is probably caused by changes in OIDN (and it would make sense to open a bug report in the [OIDN bug tracker](https://github.com/OpenImageDenoise/oidn/issues)).

**Comment by cgvirus** [comment]
Sure. I am re downloading the latest build now and will let all know in a moment.

2.3 Combined
![2 3](https://user-images.githubusercontent.com/22106885/81820659-b97c2800-9552-11ea-9f72-1ca95168bcdc.png)

2.4 Alpha Combined
![2 4 Alpha](https://user-images.githubusercontent.com/22106885/81820717-c8fb7100-9552-11ea-8240-7dddcfe216d9.png)

**Comment by cgvirus** [comment]
2.4 Alpha 13.3.2020 remains same as well.

**Comment by Dade916** [comment]
I can reproduce the problem here but the raw render between v2.3 and v2.4 looks the same so I assume the problem is in new Intel OIDN v1.1.

I will  put together a bug report for OIDN.

**Comment by Dade916** [comment]
Note, you can easily solve the problem at sources by enabling variance clamping:

path.clamping.variance.maxvalue = 75

This will remove the fireflies from the original render and Intel OIDN v1.1 will play nicely with it.

**Comment by cgvirus** [comment]
Hi thanks for the input. Max clamp works fair but not as smooth as 2.3 or the viewport of 2.4 Alpha though. How does viewport is denoising perfectly BTW? Do they have two different configurations?

**Comment by Dade916** [comment]
View port uses RTPATHCPU while final render uses whatever render engine you have selected (+ caches + light tracing + etc.).
Plain path tracing can not render some kind of light paths (and relative fireflies), for instance caustics of a point light, etc.

**Comment by cgvirus** [comment]
Got it. Thanks.
