### ISSUE TITLE
Textures can't be loaded.

### ISSUE THREAD

**Issue by picorisuzuki** [LuxCoreRender/BlendLuxCore#444]
LuxcoreVer　2.3
BlenderVer　2.80　2.82
Windows10Home　64bit　IntelCorei5 8400　RAM20.0GB　GPU　GTX10603GB　
Dragging and dropping textures into the Node Editor does not load them.
Also, even if a texture image is loaded manually, it is displayed as "Image file doesn't exist" and not rendered. The preview is also not displayed.
It reappears when I remove the texture image.

**Comment by Theverat** [comment]
Please upload an example scene and texture that shows the issue.

> Dragging and dropping textures into the Node Editor does not load them.

This is due to a Blender API limitation and out of our control.

**Comment by picorisuzuki** [comment]
The scene in question.
https://www.datadeliver.net/receiver/file_box.do?fb=558fe2ccbbb14669bef6a1c5e6972330&rc=d9606182e5644e0db29ee5859e7614ab&lang=ja
Isee,Yes, sir.＞This is due to a Blender API limitation and out of our control.

**Comment by picorisuzuki** [comment]
I forgot to enter my password.
Password:LUX
I'm sorry for the Japanese site. I later came up with the idea of using Google Drive. This way, sir.
https://drive.google.com/file/d/1kW-NQTKi01UgCFzBWq5fKySw9AwU_Ott/view?usp=sharing
You can use it here.

**Comment by Theverat** [comment]
I can not access the linked file, please make sure you set the permissions correctly.

**Comment by picorisuzuki** [comment]
https://drive.google.com/file/d/1kW-NQTKi01UgCFzBWq5fKySw9AwU_Ott/view?usp=sharing
My apologies, I fixed the permissions to "everyone who knows the link".

**Comment by Theverat** [comment]
The scene loads and renders fine on my end.
It sounds like an issue with your Blender installation, or maybe your HDD? It's a bit unclear what would cause such a problem.

If the issue still happens on your end, please re-open it with detailed steps how to reproduce the problem. I have only tried opening the file with Blender 2.83 and latest BlendLuxCore (v2.5dev) and pressing F12, and the texture shows up fine if I do that.

**Comment by picorisuzuki** [comment]
Thank you. The problem is occurring just by double clicking on the relevant Blend file and pressing F12, so it may be an installation or HDD problem. I'll try the latest version of BlendLuxCore (v2.5dev) and others. Thanks for the answer.
