### ISSUE TITLE
Issue with Random Color and Instanced Collections with Multiple Objects

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [LuxCoreRender/BlendLuxCore#446]
I'am getting strange behavior when using nodes to create Random Color for objects.

I've created the same material and used for all my test:
![blender_aHrmfeEZSA](https://user-images.githubusercontent.com/64398828/81467556-0b831d80-91e2-11ea-9200-67f24cbb2bff.png)

Will explain what the issue is below. Let's start with cases when everything works es expected.

Just single Suzanne object. Everything works as expected:
![image](https://user-images.githubusercontent.com/64398828/81466985-53a04100-91de-11ea-8be8-c12903b699e9.png)![image](https://user-images.githubusercontent.com/64398828/81466990-5a2eb880-91de-11ea-9f2a-6cda6abb5b52.png)

Suzanne with Array Modifier used twice to create multiple copies. Everything works fine as well:
![image](https://user-images.githubusercontent.com/64398828/81467031-9cf09080-91de-11ea-9d9c-5d80fec509cc.png)
![image](https://user-images.githubusercontent.com/64398828/81467053-be517c80-91de-11ea-9ef1-c09e5d6299b4.png)
![image](https://user-images.githubusercontent.com/64398828/81467059-c6112100-91de-11ea-8c26-452ac0d10647.png)

Ok, just to make sure I applied array modifiers and created multiple copies of the Suzanne. Works fine as well. Colors are randomly distributed:
![image](https://user-images.githubusercontent.com/64398828/81467125-34ee7a00-91df-11ea-9c23-3a6f8c3a0cc6.png)
![image](https://user-images.githubusercontent.com/64398828/81467130-3b7cf180-91df-11ea-8fe1-42a978d0b7dc.png)

Then I created Instanced Collections. I expected to begin getting issues here but it worked fine:
![image](https://user-images.githubusercontent.com/64398828/81467172-9a426b00-91df-11ea-825f-304928aa1790.png)
![image](https://user-images.githubusercontent.com/64398828/81467190-b940fd00-91df-11ea-91e3-412de57d8d98.png)

Now we're getting into strange behavior territory. I broke Suzanne into 3 separate pieces: head and each eye. Still using the same material for all:
![image](https://user-images.githubusercontent.com/64398828/81467224-01601f80-91e0-11ea-997e-5660fa7eee43.png)

Now it works not as I would expect but _probably_ correct:
![image](https://user-images.githubusercontent.com/64398828/81467258-497f4200-91e0-11ea-8928-b7360268387e.png)

Then I Instanced Collections:
![image](https://user-images.githubusercontent.com/64398828/81467314-995e0900-91e0-11ea-9eec-6a4b3f9877db.png)
![image](https://user-images.githubusercontent.com/64398828/81467324-9f53ea00-91e0-11ea-8c7f-d8e68105a5d4.png)

I think it's _probably_ a correct behavior but I would expect it to be different with instanced collections.

You quite often use one collection to build something with multiple objects in it. Then create collection instances to multiply the object. But use material to create randomness with some parts of the original object. I would expect material to take into account the collection instances as objects and randomize accordingly but it's not happening now.

Please have a look at this behavior.

Use the scene to see the issue: 

[Random_Color.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4602936/Random_Color.zip)

OS: Windows 10 1909
Blender version: 2.82a
LuxCore version: 2.4 Alpha0

**Comment by Theverat** [comment]
![Screenshot from 2020-05-09 12-47-41](https://user-images.githubusercontent.com/1584761/81471713-4c376280-91f3-11ea-9ddf-c27d76e1e67b.png)

The random per island value is a mesh attribute, so if the mesh is instanced, all instances will have the same values. In your case the result of the random per island + colorramp combination is 0, and by multiplying with the other random values it eventually sets everything to 0.

As a side note, using just the normalized output of the Object ID node gives a better random distribution in this example, at better performance (the random node is costly, I should add a note in the UI about this).

**Comment by AlexeyAdamitsky** [comment]
> The random per island value is a mesh attribute, so if the mesh is instanced, all instances will have the same values. In your case the result of the random per island + colorramp combination is 0, and by multiplying with the other random values it eventually sets everything to 0.

You're right of course. I was confused by some sucess when I was testing it on a **Suzanne.ArrayGrid** in may example. It gave me good example of randomness in this setup.
![image](https://user-images.githubusercontent.com/64398828/81481208-04d2c580-9237-11ea-926a-be93af5df1e4.png)
![image](https://user-images.githubusercontent.com/64398828/81481215-1025f100-9237-11ea-8e10-06311764e49b.png)
 So I thought it would be a good idea to randomize it even further with **Object ID** node's result. Which obviously doesn't work as I expected for the reasons you pointed out.

> As a side note, using just the normalized output of the Object ID node gives a better random distribution in this example, at better performance (the random node is costly, I should add a note in the UI about this).
Ok, noted about Random node. Thank you.

> It looks to me like there is no bug at work here.
It works well now in test scene after I corrected the material based on you advice. The thing is I'm working on a project and I used now the same setup and it doesn't work there. I'm not sure what I'm missing.

Is there a way to send the project privately for you to have a look if I can't figure out what's going on why it doesn't work in my working scene?

**Comment by Theverat** [comment]
> Is there a way to send the project privately for you to have a look if I can't figure out what's going on why it doesn't work in my working scene?

You can send a PM to me on discord or in the forum.

**Comment by AlexeyAdamitsky** [comment]
I've found the issue.

If you go to **Suzanne.Head** and change the **Object ID** to anything other than default **-1** randomization stops working.
![image](https://user-images.githubusercontent.com/64398828/81482659-6b5ce100-9241-11ea-8eb2-7ea551b219c1.png)
![image](https://user-images.githubusercontent.com/64398828/81482689-9c3d1600-9241-11ea-9f5e-111ed1d97814.png)
I understand why it's happening. Every instance now has set Object ID.

I changed it in my working scene to 2 to and some other objects as well to output Object ID mask. Is there a way to make it work together so I can have a random color material and set Object ID for AOV?

Just in case a .blend file:
[Random_Color_001.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4604332/Random_Color_001.zip)

**Comment by Theverat** [comment]
No, since the randomization uses the object ID, it is not possible to use both of these features together.

We could store the "random per object" value separately, but it would increase the memory usage on GPUs (always, not just when the feature is used).

**Comment by AlexeyAdamitsky** [comment]
Ok, I understand. It's a bit unfortunate but I get the limitation. Maybe I'll find a workaround to get masks I need or hopefully there is cryptomatte available in the near future.

> As a side note, using just the normalized output of the Object ID node gives a better random distribution in this example, at better performance (the random node is costly, I should add a note in the UI about this).

I was playing around with randomization and I find Object ID in Raw mode plus Random node is helpful to generate different material distribution and stop at what I like.

How costly is this setup? Is there a way to quantify the performance hit?

**Comment by Theverat** [comment]
I'm not sure. You could do one render with the random node and another one where you replace it with a constant value and check the render time difference at same amount of samples. Should be a longer render though to eliminate effects of CPU/GPU auto-overclocking, other programs using CPU/GPU time etc.

**Comment by AlexeyAdamitsky** [comment]
Ok, thank you for your help. Consider the issue solved.
