### ISSUE TITLE
Collection Level Visibility Checks Don't Work in Render Preview Mode

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [LuxCoreRender/BlendLuxCore#447]
When using visibility checks on Collection level it doesn't work as it supposed to in Blender and Cycles.
![image](https://user-images.githubusercontent.com/64398828/81483198-0905df80-9245-11ea-8bbd-259057d2eb36.png)

Video file:
[VideoDemonstrationOfTheBug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4604368/VideoDemonstrationOfTheBug.zip)

It works correctly though at individual objects level.

.blend file: 
[CollectionsVisibilityBug.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4604344/CollectionsVisibilityBug.zip)

OS: Windows 10 1909
Blender version: 2.82a
LuxCore version: 2.4 Alpha0

**Comment by Theverat** [comment]
This is fixed by the changes in the https://github.com/LuxCoreRender/BlendLuxCore/tree/feature/local_view branch. Will have to finish that branch at some point.
