### ISSUE TITLE
Unsupported Blender version 2.81a or lower is required error

### ISSUE THREAD

**Issue by ptfdln** [LuxCoreRender/BlendLuxCore#449]
Hey, I'm on Blender version 2.82a. I downloaded BlendLuxCore 2.3 from the website, but when I install it in Blender preferences it says I need Blender 2.81a or lower, even though LuxCore says it does support version 2.82a... what should I do here? Thx.

![image](https://user-images.githubusercontent.com/57077614/81522870-e46f3d80-9300-11ea-99d1-49cf0911e10b.png)

**Comment by Theverat** [comment]
I guess you're using macOS? The situation is a bit different there, that's why we put these messages in place.
@u3dreal can probably explain more.

**Comment by u3dreal** [comment]
Code in Blender changed so 2.3 is not compatible anymore.
Plz use Blender 2.81a or try the latest 2.4alpha from GitHub BlendLuxCore release page.
