### ISSUE TITLE
render freezes while opencl kernels are being compiled, luxcore v2.3

### ISSUE THREAD

**Issue by mrnadmor** [LuxCoreRender/BlendLuxCore#453]
Recently I experience a lot of render freezes using Luxcore v2.3 and blender 2.82a
Actually since I use Luxcore about two months ago I experience stability issues (not only while rendering).
This time I experience render freeze at 80% of render attempts, right after the massage "compiling openCL kernels" appears. Rendering with CPU only appears to work fine. Render with OpenCL (GPU+CPU or with GPU only) is problematic. my graphics card is Radeon RX 580 4GB, with latest software version 20.4.2,

by freeze I mean that I can still use the computer: the mouse cursor is stil active, I can surf the internet etc., but regarding Blender- I have to shut down the application using ctrl+alt+del.

OS Name Microsoft Windows 10 Pro
Version 10.0.18363 Build 18363
Other OS Description Not Available
OS Manufacturer Microsoft Corporation
System Manufacturer Gigabyte Technology Co., Ltd.
System Model B360M H
System Type x64-based PC
System SKU Default string
Processor Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. F12, 3/14/2019
SMBIOS Version 2.8
Embedded Controller Version 255.255
BIOS Mode Legacy
BaseBoard Manufacturer Gigabyte Technology Co., Ltd.
BaseBoard Product B360M H
BaseBoard Version x.x

**Comment by Theverat** [comment]
A freeze during the kernel compilation is normal. How long did you wait before killing Blender?
If your scene uses complex material setups, it can easily take a couple of minutes to compile the kernels.

**Comment by mrnadmor** [comment]
I posted this issue also at this link at the luxcorerender User Support forum here:
https://forums.luxcorerender.org/viewtopic.php?f=4&t=2184

The issue sometimes takes 20 or more min. after that amount of time I terminate Blender, load it again and try to render again. I fail in 50% of the time (which means this problem does  not systematically appear)

**Comment by Theverat** [comment]
It's a bit unclear if this issue was solved, but I'm closing it for now (we can always re-open).

**Comment by pencilcheck** [comment]
For me, on blender 2.90, the basic cube scene kernel compilation takes a long time (CVMCompiler process takes more than 100% CPU), and I don't know how long I need to wait but if a cube takes that long to compile then this plugin is unusable. Is there a way to know why it takes that long to compile?

**Comment by Theverat** [comment]
The scene complexity does not matter at all. The kernels are compiled once for any kind of scene.
> Is there a way to know why it takes that long to compile?

Ask the developers of the OpenCL/CUDA compilers.

**Comment by pencilcheck** [comment]
I just left it overnight and let it finish compiling. Fortunately this is only a one time thing. The second time around is so much faster, I thought the initial compilation will take place every time rendering happens. Thanks for the comment regardless.
