### ISSUE TITLE
Blendluxcore won't enable

### ISSUE THREAD

**Issue by Ingapambi** [LuxCoreRender/BlendLuxCore#454]
.blend file: 

Steps to reproduce:Download either with/without version from download page;
Install,
clock enable box
read error box "Blender version 2.81 or lower required"

Screenshots or rendered images:

Error message from Blender console:

OS: MacOS Catalina 10.15.4
Blender version:2.83.16
LuxCore version:Latest

**Comment by Theverat** [comment]
The error message is correct.

**Comment by Theverat** [comment]
See also #449 for more details.
