### ISSUE TITLE
MacOS 10.15.3: Can't enable LuxCore Plugin anymore

### ISSUE THREAD

**Issue by thamich** [LuxCoreRender/BlendLuxCore#455]
I had Luxcore 2.4 Alpha 0 installed for quite a few days and it worked pretty well. Without doing any changes to blender or my OS Luxrender became unavailable, seems it got automatically disabled by MacOS. Trying to enable it again gives me the following error in the screenshot. Guess it got problems with signing the luxcore.so!?

Any help or advice would be appreciated. Thanks
<img width="1478" alt="Bildschirmfoto 2020-05-17 um 09 08 07" src="https://user-images.githubusercontent.com/5184709/82138271-891cde00-981f-11ea-9d26-e52cad5b5fb1.png">
<img width="631" alt="Bildschirmfoto 2020-05-17 um 09 18 16" src="https://user-images.githubusercontent.com/5184709/82138273-8c17ce80-981f-11ea-8e8a-aa4fd7609257.png">

**Comment by iaian7** [comment]
I'm getting the same thing now! I blamed it on a recent upgrade to Mojave, but it sounds like something else is going on. The older 2.4 alpha I'd been running successfully no longer works, and attempting to use the latest build results in the same error.

**Comment by iaian7** [comment]
Details:
- 2015 iMac, 4Ghz i7, 32GB ram, AMD Radeon R9 M395X 4GB
- MacOS Mojave 10.14.6
- Blender 2.82a
- LuxCore 2.4 Alpha 0 (tested with a version I downloaded several weeks ago, and was working back then, and the latest build from today, which hasn't worked once)

**Comment by thamich** [comment]
Same here. I couldn't use the 2.3 at all because it couldn't be installed, but the 2.4 could be installed and ran for a while, but now I get this error. 

What surprises me is that there were no updates at all lately and the plugin doesn't work anymore. My guess is that it is because of the non-existent Apple Developer Key, to my knowledge the programmers don't have one.

**Comment by u3dreal** [comment]
There seems to be something wrong with the codesigning 
But there is no error thrown in azure. Will check this evening.

**Comment by u3dreal** [comment]
Should be fixed in next azure build of LuxCore 
[https://github.com/LuxCoreRender/LuxCore/releases/tag/latest](url)
wait it will take some time. Just copy the pyluxcore dir to your Blender addons BlendLuxCore bin dir

**Comment by u3dreal** [comment]
Should be solved now
[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest](url)

**Comment by thamich** [comment]
Solved! Everything back to normal. Thank you!

**Comment by u3dreal** [comment]
Great Thanks for testing and reporting back !
