### ISSUE TITLE
render LuxCore2.1Benchmark files crash on windows 10

### ISSUE THREAD

**Issue by fuchenw** [LuxCoreRender/BlendLuxCore#456]
When I test the benchmark files, I can preview it normally, but render image will cause blender crash , plese fix.
win10 lastest ver, opencl gpu

**Comment by Theverat** [comment]
I can not reproduce a crash with this scene.
Does it still happen with the latest build on your end?

**Comment by Theverat** [comment]
Please re-open if the crash still happens.
