### ISSUE TITLE
Material not updated if name changed during viewport render

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#46]
> Open viewport render preview change your material name (eg "Or" to "gold") then play with node settings it wann't update in the viewport preview

We are using the material.name property as a key.
Maybe we can use something else that does not change when the material is renamed.
Maybe the memory address? It changes only on undo/redo, but in this case the whole viewport render is deleted and re-started anyway.

**Comment by Dade916** [comment]
I recently introduced the usage of UUID in LuxCore for unique identifiers (instead of memory address): https://docs.python.org/3.2/library/uuid.html?highlight=uuid

They are pretty good for this kind of tasks.

**Comment by Theverat** [comment]
I would need a get_uuid method in bpy_struct: https://docs.blender.org/api/2.79/bpy.types.bpy_struct.html#bpy.types.bpy_struct.as_pointer
I mean I could create a uuid from the memory address but that's kinda pointless.

**Comment by Dade916** [comment]
You need to use material.UUID as key instead of the user defined name. You assign an UUID to the material the first time you create the object. Just that.

Using material.UUID instead of material.name would solve the renaming problem (as far as I have understood from the first post).

**Comment by Theverat** [comment]
Ah ok I see what you mean. 
But I think the memory address also works, because we don't need to track the name across undo/redo (where the address is changed).
Adding a uuid property to the material could create a lot of new issues, so I'd rather avoid it.
