### ISSUE TITLE
Support new LUT imagepipeline plugin

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#460]

**Comment by Theverat** [comment]
It would be great to have a set of 
* input image
* .CUBE file
* output image

That is known to be correct, so we can test if everything's right.

**Comment by Theverat** [comment]
From what I can see reading up on this .CUBE format, the input color space is not specified. Each file can require a different input color space.
Since it's not really possible in a clean way to disable the Blender color processing that is applied on the render result (including gamma correction, filmic etc.) I would just say that we put the LUT plugin at the end of the pipeline, and put a tooltip in that says what input color space the LUTs need to expect to work like intended (linear sRGB I guess?).
I can also optionally add the gamma plugin in front, in which case the user would have to find out how to disable the Blender gamma correction. But I guess users who use LUTs would know how to do that anyway.

**Comment by lacilaci** [comment]
AFAIK you don't need to switch off srgb as a display device in blender. You only need to set view Transform to RAW.
This way rendering has linear view transform and you can use gamma and lut settings on top of it while opengl viewport still shows everything as srgb (this is how I use it in octane without any issues)

If the users switches the sRGB display to none then everything including openGL viewport turns dark/linear.

So setting only view transform to RAW should be better option (unless there is some issue I don't know of?) than turning off srgb for the whole app.

**Comment by lacilaci** [comment]
By the way, not sure if it helps,

But here you can download an input image, lut and output result:
https://wetransfer.com/downloads/ac0518aca758cd69b8702398d196a65920200519043246/9729508f83161a155737ae5ededac6c520200519043305/c05680

it's 16 bit png's and I tested the lut also in luminar to see if it produces same result as octane in blender with the lut and it does.

The provided lut in the zip is from a freebie pack from Fabio Ciliberti:
https://www.c4dzone.com/en/shop/octane-packs-27/lut-collection-by-fabio-ciliberti-293.htm
rendering was done same way I'd imagine it could work in luxcore:
1.raw view transform
2.srgb - applied in octane settings
3.highlight compression - octane settings
4.LUT applied - at 100% strenght

**Comment by Theverat** [comment]
I have added the plugin.

> But here you can download an input image, lut and output result:

Thanks. I am getting the same result when I use view transform = "Raw" and gamma = 1, with gamma correction performed in the LuxCore imagepipeline in front of the COLOR_LUT plugin.
I have added a button to the UI to apply these settings for the user.
