### ISSUE TITLE
BlendLuxCore-latest-linux64-cuda.zip not updated

### ISSUE THREAD

**Issue by SteffenDuenner** [LuxCoreRender/BlendLuxCore#463]
Hi there,

I regularly download the very latest releases from https://github.com/LuxCoreRender/BlendLuxCore/releases but it looks like the BlendLuxCore-latest-linux64-cuda.zip hasn't been updated since 5 days or so while the other Linux builds are fine and up-to-date.

**Comment by Theverat** [comment]
I disabled packaging of the cuda build, currently it crashes in cuInit(). I'll re-enable it once we fixed that.
Not sure why the old zip package stayed up, I'll try to remove it.

**Comment by SteffenDuenner** [comment]
Good to know. Thanks!
