### ISSUE TITLE
[Bug] "AddDllDirectory" not found in E-Cycles ver. 2.83 LuxCore v2.4

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/BlendLuxCore#464]
Error message: AddDllDirectory not found
Blender version: E-Cycles 2.83 (in official it doesnt work too)
LuxCore version: v2.4 (latest)
OS: Win7 x64

**Comment by Dade916** [comment]
I don't think we support Windows 7 anymore in v2.4 (the new support for CPUs with more than 64 cores requires Windows 10, as afar as I remember).

**Comment by Theverat** [comment]
> (the new support for CPUs with more than 64 cores requires Windows 10, as afar as I remember).

No, according to the author it works on Win7 and above: https://github.com/LuxCoreRender/LuxCore/pull/348

@odil24 You could try the solution here: 
https://stackoverflow.com/questions/54985803/function-adddlldirectory-not-found-while-importing-pytorch

**Comment by odil24** [comment]
> > (the new support for CPUs with more than 64 cores requires Windows 10, as afar as I remember).
> 
> No, according to the author it works on Win7 and above: [LuxCoreRender/LuxCore#348](https://github.com/LuxCoreRender/LuxCore/pull/348)
> 
> @odil24 You could try the solution here:
> https://stackoverflow.com/questions/54985803/function-adddlldirectory-not-found-while-importing-pytorch

Thank you. :1st_place_medal: 
It was worked after I downloaded and installed that Win update from the service. The problem has been disappeared! ;)

**Comment by odil24** [comment]
The bug has been solved. The problem has been solved after this update:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=26764
