### ISSUE TITLE
Unsupported Blender version 2.81a or lower is required

### ISSUE THREAD

**Issue by Dazzzz** [LuxCoreRender/BlendLuxCore#466]
Installing version 2.3 of LuxeCore on an mid 2011 iMac running macOS High Sierra 10.13.6.

The above error message comes up when trying to enable add-on. I am running version 2.82a of Blender.

![Screenshot 2020-05-21 11 42 42](https://user-images.githubusercontent.com/22819015/82514153-4a0cc680-9b58-11ea-97b3-695e0a7687c6.png)
![Screenshot 2020-05-21 11 42 29](https://user-images.githubusercontent.com/22819015/82514156-4d07b700-9b58-11ea-9e63-74a392a87b3f.png)

**Comment by Theverat** [comment]
See #454 and #449.
We will support later Blender versions on macOS with version v2.4, as far as I know.
