### ISSUE TITLE
LOL: Asset bar position not reset when changing categories

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#467]
Steps to reproduce:
* Click on category "All"
* Scroll all the way to the right in the asset bar
* Click on category "Furniture" (or any other category with less items than "All")
* The asset bar will now appear blank, because it is scrolled too far to the right for the new category

I think it would make sense to reset the scroll position when the category is changed.

Images:

![a](https://user-images.githubusercontent.com/1584761/82676681-1361a980-9c47-11ea-93c0-451562ceec6f.png)

![b](https://user-images.githubusercontent.com/1584761/82676705-1ceb1180-9c47-11ea-9ead-bfa7e3f76a13.png)

**Comment by neo2068** [comment]
Yes, I now these kind of errors. There are more, e. g. Arrows disappear one asset before end. It is in the blenderkit code. I don't had the time to resolve the buggy code basis but you all wanted to merge it into master in this early unfinished phase.

**Comment by Theverat** [comment]
I'm just documenting what I find so we can fix it.
If you don't have time, that's OK.
