### ISSUE TITLE
LOL: Download table of contents only once

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#468]
`utils.download_table_of_contents(self, context)` at https://github.com/LuxCoreRender/BlendLuxCore/blob/8c43eb875e1db5a84b2ec358192cb8248bdc964b/operators/lol/assetbar.py#L605 is executed every time the asset bar is opened, closed, or the category is switched.
I don't expect the table of contents to change very often, so I would suggest we download it once when the asset bar is first opened, then store it in memory. It is a quite lengthy operation (0.7 seconds on my system/connection).

**Comment by neo2068** [comment]
Yes, it is a good point. We should only update it at first load. Another point would be to update preview images in the cache. This is not done yet.

**Comment by neo2068** [comment]
This has been implemented in commit 9201a32

**Comment by Theverat** [comment]
Having a blocking download call that takes about 1 second [in load_post](https://github.com/LuxCoreRender/BlendLuxCore/blob/7e3f8134a5699cc197bca8a56c028131f5f8bbdc/handlers/load_post.py#L29) is not acceptable.
It should either be non-blocking or moved to the place where the asset bar is first opened.

**Comment by neo2068** [comment]
Ok. It make no subjective difference on loading blender on my system but I will load the table of contents when the assetbar is activated the first time.

**Comment by juangea** [comment]
Not to reopen the case, but I have a question, what happens when you don’t have internet connection?
No matter if it’s loaded when Blender loads, or the first time the bar is loaded, will there be a delay or something like that?

**Comment by Theverat** [comment]
@neo2068 Thanks, much better to do this on-demand.
Together with some import optimizations I did it makes a big difference in iteration times when testing, because I have to restart Blender each time.
