### ISSUE TITLE
Don't work in Blender 2.82 / 2.81a Mac Catalina version

### ISSUE THREAD

**Issue by vonvanzu** [LuxCoreRender/BlendLuxCore#471]
Im working in Catalina, and It tell me try a blender version as 2.81a or lower but when I try 2.81a other error: Cant import a file named pyluxcore.so
![Screenshot 2020-05-23 at 14 08 09](https://user-images.githubusercontent.com/65814250/82730304-ea045480-9cfe-11ea-91c5-92d87cc46aec.png)

**Comment by thamich** [comment]
Are you using the latest Luxcore version? 2.4 Alpha? Go download the latest Update and install it, the problem should be solved there. At least for me it got solved.

**Comment by vonvanzu** [comment]
> Are you using the latest Luxcore version? 2.4 Alpha? Go download the latest Update and install it, the problem should be solved there. At least for me it got solved.

Thanks for the quote, Its finally works with the latest release from:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest

But tell me an Alpha0 warning when activate it:
![Screenshot 2020-05-24 at 11 56 04](https://user-images.githubusercontent.com/65814250/82751534-32337d80-9db8-11ea-97c7-e092846a7580.png)
