### ISSUE TITLE
Latest BlendLuxCore crashes Blender in preview / GPU

### ISSUE THREAD

**Issue by SteffenDuenner** [LuxCoreRender/BlendLuxCore#474]
.blend file: 
Default cube

Steps to reproduce:
- Switch renderer to LuxCore
- Switch to Path / GPU
- Preview render viewport -> crash, both with CUDA and OpenCL. CPU is fine, final rendering is fine as well

OS: Linux Mint 19.3
Blender version: 2.83 and 2.90
LuxCore version: https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest

Versions from a few hours ago were perfectly fine. I think the problem started somewhere around this commit: https://github.com/LuxCoreRender/LuxCore/commit/b99dc2f81371dc0dc6975138fa9e26d4a4f51964

EDIT: Tiled rendering also crashes.

**Comment by Dade916** [comment]
I should have fixed the problem with view port rendering.

However it is not related to Tiled rendering and Tiled was already working fine here (?).
