### ISSUE TITLE
Point Light shows falloff banding (size values between 0.0001 ~ 0.1)

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/BlendLuxCore#477]
.blend file (w/ LuxCore exports): 
[PointLightBanding-BUG.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4728948/PointLightBanding-BUG.zip)

Steps to reproduce:
1. Open attached file.
2. Set/Check render engine.
3. See rendered viewport or render still (f12) 

Screenshots or rendered images:
Cycles:
![LuxCore_PointLight_Banding-CYC](https://user-images.githubusercontent.com/61623470/83739603-1a7cb480-a656-11ea-9f42-a6b4a169b7e0.jpg)
BlendLuxCore:
![LuxCore_PointLight_Banding-BLC](https://user-images.githubusercontent.com/61623470/83739689-38e2b000-a656-11ea-8b8f-4c2075cb088d.jpg)

Error message from Blender console: **none**

Error message from LuxCoreUI console: `RenderConfig loading error:
bad lexical cast: source type value could not be interpreted as target`

OS: Windows10
Blender version: 2.83
LuxCore version: 2.4beta (latest from 2020-06-04)

**Comment by Dade916** [comment]
> Error message from LuxCoreUI console: `RenderConfig loading error: bad lexical cast: source type value could not be interpreted as target`

This error comes from this:

> scene.materials.Material1942792493976.id = 13,398,304
> ...
> scene.objects.19434461667760.id = 3,772,660,237

You C library printing integer numbers with ",".

I'm looking in bands problem.

**Comment by Dade916** [comment]
I should have fixed the banding problem. As expected, it was a numerical precision problem due to very small light radius.

**Comment by kintuX** [comment]
> 
> 
> I should have fixed the banding problem. As expected, it was a numerical precision problem due to very small light radius.

I confirm, the banding isssue with small Point Light radius is gone.

BTW (&Note to self), the LuxCoreUI error sprouts from BlendLuxCore when Object and/or Material IDs have negative values. In this case both were set to -1. 
Am I right to assume it's BlendLuxCore bug & report the issue?
