### ISSUE TITLE
lock view cause crashing!

### ISSUE THREAD

**Issue by atticus-lv** [LuxCoreRender/BlendLuxCore#481]
2.83 lst version
2.4 alpha 0 (6/12 build)
newest studio driver (2080s)
when add a camera in the gpu(cuda) mode ,it cost a long time to wait. Then go to the cam view, the view sample become strange,when I try to lock cam view or switch the environment to none ,it crash

**Comment by Theverat** [comment]
Please upload a .blend file that shows the issue.
More detailed steps how to reproduce would also be appreciated, with exact keyboard shortcuts to press.
A video or some screenshots would be good as well.

**Comment by atticus-lv** [comment]
[2020-06-18 11-25-13.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4796110/2020-06-18.11-25-13.zip)
something like this，when adding a camera or light(most time )

**Comment by Theverat** [comment]
I can not reproduce the problem.
I suspect it was similar to these:
* https://github.com/LuxCoreRender/LuxCore/issues/398
* https://github.com/LuxCoreRender/LuxCore/issues/399

Can you try again with the latest build and check if the problem is fixed?

**Comment by atticus-lv** [comment]
yes, it is the same problem.It fixed!
however, it crash when try to change the timeline to the luxcoreshader editor/set the world environment to none. (2.83.1,quick render setting: no cycles,studio,caustic,no caustic cache ) the same platform(windows) and hardware&nbsp;
&nbsp;

Best Regards,Atticus&nbsp;吕
———&nbsp; &nbsp;
E-mail:&nbsp; 1029910278@qq.com
Wechat: lv3628800








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simon Wendsche"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 晚上11:43
收件人: "LuxCoreRender/BlendLuxCore"<BlendLuxCore@noreply.github.com&gt;; 
抄送: "atticuslv"<1029910278@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LuxCoreRender/BlendLuxCore] lock view cause crashing! (#481)





 
I can not reproduce the problem.
 I suspect it was similar to these:
  
LuxCoreRender/LuxCore#398
 
LuxCoreRender/LuxCore#399
  
Can you try again with the latest build and check if the problem is fixed?
