### ISSUE TITLE
As long as render window is open in Blender 2.83 CPU Cycles are at 100%

### ISSUE THREAD

**Issue by arvindhal** [LuxCoreRender/BlendLuxCore#483]
Hello,
   Thank you for your great renderer! When I installed the add on under Blender 2.83 and render the default cube my CPU goes to 100% and stays there. I tried adjusting the Viewport update down to 2 seconds and the Update to 600 seconds as per the Wiki but the problem persists. As soon as I close the Render window the CPU usage drops to 1%. I've tried this repeatedly and can confirm the CPU pegs at 100% while the render window is open. It appears to be continuously rendering the scene in an infinite loop of sort. Thank you for your time.

OS: Windows 7 64 Bit
Video Accelerator Detected Correctly. Nvidia.
Render occurs properly (Except for CPU Burn) with Both CPU (8 threads) or OpenCL.
Problem is repeatable and constant on my machine.
Problem occurs if render window is a new window or render to Image Window is selected.
Problem occurs even after restart.

**Comment by Dade916** [comment]
This is the normal LuxCoreRender behavior (i.e. "infinite" render). You need to set halt condition to tell LuxCore when to stop or it will continue forever to improve the quality (i.e. reduce the noise).
The most common type of halt condition is based on samples per pixel (for instance, stop after have rendering at least 512 samples per pixel).

**Comment by arvindhal** [comment]
Hello David,
   Thank you very much for taking the time to deal with my issue! I re-downloaded LuxCore, reinstalled the plugin and using the information you provided was able to quickly find the settings you mentioned under the "Halt Condition"  section of the configuration menus and it was good to also see the render would respond to the "ESC" key to manually stop the render. I didn't even think to try that. I just got flustered when I saw all the cores on my CPU pegged at 100% for many seconds just rendering the default cube in Disney Green :-) With the changes applied I can fine tune the renders exactly to my tastes!
      I look forward to putting LuxCore through its paces. I have quite a unique production pipeline I use for stuff ranging from art to research data visualization. I wanted something that could handle complex light paths and caustics better than Cycles which I find needs me to bump up the quality too much and therefore runs too slowly to give me an accurate idea of the final output in my workflows. I use a step wise refinement process and need accuracy as early in the render as I can get it. Luxcore seems to have the chomps for doing just that! Thanks again for your help! I am very excited now to throw some light through multiple refractive indexes with LuxCore and see what pops out the other end :-) Enjoy the rest of your day/night.

Sincerely,Arvind

    On Tuesday, June 16, 2020, 5:47:49 PM GMT-4, David Bucciarelli <notifications@github.com> wrote:  
 
 


This is the normal LuxCoreRender behavior (i.e. "infinite" render). You need to set halt condition to tell LuxCore when to stop or it will continue forever to improve the quality (i.e. reduce the noise).
The most common type of halt condition is based on samples per pixel (for instance, stop after have rendering at least 512 samples per pixel).

**Comment by arvindhal** [comment]
The LuxCore Blender Plugin team have delivered better customer service than some commercial offerings on the market. Thanks, everything works beautifully now.
