### ISSUE TITLE
Material ID Color AOV changes colors per frame in animation

### ISSUE THREAD

**Issue by giacometti777** [LuxCoreRender/BlendLuxCore#484]
Is this the expected behavior or am I missing something basic? I would love to use this AOV for animation!

**Comment by Dade916** [comment]
Did you explicitly set the ID ? Otherwise, it may be initialized with random values.

**Comment by giacometti777** [comment]
I could have sworn I tested this with IDs properly set but it turns out I am an idiot. Thanks for enlightening me and sorry for wasting your time *bows down*
