### ISSUE TITLE
Blender freezes after switching back from GPU viewport render

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/BlendLuxCore#485]
Steps to reproduce:
Switch to GPU and start viewport render, e.g. on startup scene. After the render has finished switch back to wireframe. After that Blender freezes and doesn't respond anymore. Perhaps it is related to the new RTPath GPU engine and is a problem in LuxCore.

Error message from Blender console:
No error messages.

OS: Windows 10
graphics cards: NVIDIA Geforce GTX 1080 and GTX 780
Blender version: 2.82 and 2.83
LuxCore version: 2.4 alpha0  commit 240dd579d2fc7a89a21ac648af413377f8e4e59e
LuxCore version: 2.4 alpha0  commit 1aa31a465fd188d3ac2b5bfc9ad500dfbd042f75 => ok, no freeze

**Comment by SteffenDuenner** [comment]
Had something very similar just happen to me. I tried to reproduce it but it seems it's not happening reliably so far.

Linux Mint 19.3
GTX 1080ti

**Comment by Dade916** [comment]
I'm trying to replicate the problem here but everything works fine. Is the problem still there ?

**Comment by Dade916** [comment]
Are you using multiple GPUs ? If yes, does it happen with a single GPU too ?

**Comment by neo2068** [comment]
It still happens with latest code. I tried with one and two GPUs and it happens all the time. Did you wait until the denoiser has finished before switching back? Are you testing under linux or windows?

**Comment by Dade916** [comment]
> It still happens with latest code. I tried with one and two GPUs and it happens all the time. Did you wait until the denoiser has finished before switching back? Are you testing under linux or windows?

Yes, under Linux. Anyway I should have fixed the problem: there was a lock when stopping RTPATHOCL while in pause mode.

**Comment by neo2068** [comment]
Your fix seems to have solved the problem. I will close the issue. Thanks!
