### ISSUE TITLE
LUXCORERENDER Configuration/Blendluxcore

### ISSUE THREAD

**Issue by fadhil0305** [LuxCoreRender/BlendLuxCore#486]
![Untitled](https://user-images.githubusercontent.com/52478779/85052322-e6130780-b1c2-11ea-8bde-03279369b2ed.png)
![Untitled1](https://user-images.githubusercontent.com/52478779/85052333-e9a68e80-b1c2-11ea-9200-e7d8a96256ed.png)
![Untitled3](https://user-images.githubusercontent.com/52478779/85052813-c203f600-b1c3-11ea-8a5a-1dd5bf58efc8.png)

hi, everyone, I have problems in doing network rendering using luxcore rendering. the problem faced is when the task is run, then what works is limited to the command as seen in the picture. what is done to overcome this? because after a long wait but there was no response from the process. and if the tool merge film is pressed, the process turns into not responding. Please help. thanks again for your time. Please guide me. I need your help

**Comment by Dade916** [comment]
As far as I remember, it is a Windows problem: just start network rendering tool by hand (not from inside Blender) and it should work.

**Comment by fadhil0305** [comment]
**which one that u mean**
![image](https://user-images.githubusercontent.com/52478779/85207537-a16aa600-b353-11ea-803c-893e4af32e96.png)
 **lux core ui** or **pylux tool.**

**Comment by Dade916** [comment]
pyluxcoretools.exe, it should popup a form where you can pick the tool to run (netconsole in your case).

**Comment by fadhil0305** [comment]
ok i will to try
