### ISSUE TITLE
Resizing Lamp/sun triggers an update

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#49]
#### System Information
W10 / HD7970 /i7 6700k
#### Software Version

* Blender version: 2.79
* LuxCore version: 2.0 alpha 1

#### Short description of error
*Nothing special the viewport preview just get an useless update

#### Exact steps for others to reproduce the error
Just resize your sun or lamp (area lamp not considered) in while render preview is working

**Comment by Theverat** [comment]
It would make the object update code overly complicated to check for cases like this one.
