### ISSUE TITLE
Custom normals don't work in Blender 2.83

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#491]
The cause could be a change in the Blender mesh datastructure layout.
Probably requires changes in our mesh conversion C++ code.

**Comment by SteffenDuenner** [comment]
Reported this a while ago. Was postponed because 2.83 wasn't the final release back then.
https://github.com/LuxCoreRender/BlendLuxCore/issues/451

**Comment by Theverat** [comment]
Duplicate of #451
