### ISSUE TITLE
OIDN denoiser crashes Blender

### ISSUE THREAD

**Issue by Blempis** [LuxCoreRender/BlendLuxCore#493]
Blender 2.83 crashes after rendering if OIDN denoiser is selected.

[WithTheseSettingsItCrashes_4517_autosave.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4824834/WithTheseSettingsItCrashes_4517_autosave.zip)

Blender 2.82 can handle the same file.

Ubuntu 18.04

**Comment by Dade916** [comment]
I assume this is a duplicate of #423
