### ISSUE TITLE
BlendLuxCore 2.3 crashes Blender 2.8x without messages

### ISSUE THREAD

**Issue by joc11** [LuxCoreRender/BlendLuxCore#494]
Blender 2.81, 2.82, 282a crash whenever I launch render, viewport shading or even open material preview with v2.3 whereas v2.2 works fine in CPU and GPU rendering.

Same issue in Blender 2.83 and v2.4alpha0
Terminal output:

```
BlendLuxCore 2.3 registered (with pyluxcore 2.3)
Updating OpenCL device list
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
==================================================
[Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][50.404] Camera type: perspective
[SDL][50.404] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][50.404] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][50.404] Camera clipping plane disabled

```
I have no idea what features of 2.3 might cause this.
I run the original NVIDIA driver, CPU supports SSE3.

Operating System: openSUSE Tumbleweed 20200622
KDE Plasma Version: 5.19.1
KDE Frameworks Version: 5.71.0
Qt Version: 5.15.0
Kernel Version: 5.7.2-1-default
OS Type: 64-bit
Processors: 4 × AMD Phenom(tm) II X4 955 Processor
Memory: 7,8 GiB Arbeitsspeicher
Graphics Processor: GeForce GTX 770/PCIe/SSE2

**Comment by Dade916** [comment]
Your AMD CPUs are very old (10+ years) and it doesn't support SSE4.1 instruction set. For instance, SSE4.1 is a requirement of Intel OIDN denoiser (introduced in v2.3). I think Embree may require SSE4.1 too. We have seen in the past (another user had the same problem), of SSE4.1 instructions used by newer Boost library for memory/string copying.

You could try to work around OIDN and Embree (i.e. use a configuration where they are not used) and to compile form the source to avoid the usage of SSE4.1 elsewhere but it is a lot of complicate work with an uncertain result.

**Comment by joc11** [comment]
Thanks a lot, I did'nt Know about this SSE4.1-restriction. So this may close the issue.
