### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by bartoszek** [LuxCoreRender/BlendLuxCore#498]
Could we have `pipreqs` generated list of non blender related python modules in `requirements.txt`.

**Comment by Theverat** [comment]
I have no use for such a list, so I'm reluctant to do it.
But if you can generate and maintain it, a pull request is welcome.

**Comment by Theverat** [comment]
Closing this for now. If someone wants to volunteer to create and maintain such a list, feel free to re-open this issue.
