### ISSUE TITLE
Automatically find best clamp value

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#50]
https://forums.luxcorerender.org/viewtopic.php?f=4&t=39#p539

**Comment by Theverat** [comment]
@Dade916: problem is:
```
image size 384x216
0.0%
12.1%
24.1%
36.2%
48.2%
60.3%
72.3%
84.4%
96.5%
Y computed in 35.6s
Suggested variance clamp value: 6.609041061024917
```
Can we maybe get the value from a C++ function?

**Comment by Dade916** [comment]
Yes, indeed, bloody hell if it is slow !

**Comment by Dade916** [comment]
I have added the Film::GetFilmY() method to LuxCore API. It takes 1.5ms at 384x216, it is not even worth a multi-thread version ^^

**Comment by Theverat** [comment]
> it is not even worth a multi-thread version ^^

Maybe for larger films?

It's like a textbook example for OpenMP reduction:
https://en.wikibooks.org/wiki/OpenMP/Reductions
```cpp
#include <stddef.h>  // for size_t

float sum(const float *a, size_t n)
{
    float total = 0.;

    #pragma omp parallel for reduction(+:total)
    for (size_t i = 0; i < n; i++) {
        total += a[i];
    }
    return total;
}
```
