### ISSUE TITLE
Don't open

### ISSUE THREAD

**Issue by maguilar72G** [LuxCoreRender/BlendLuxCore#500]
![Screen Shot 2020-06-30 at 11 39 56 PM](https://user-images.githubusercontent.com/20142797/86203253-3034ab00-bb2a-11ea-8f1b-632e32665f4d.png)

**Comment by maguilar72G** [comment]
![Screen Shot 2020-06-30 at 11 39 56 PM](https://user-images.githubusercontent.com/20142797/86203322-5b1eff00-bb2a-11ea-8266-5d25ecbfa738.png)
![Screen Shot 2020-06-30 at 11 41 06 PM](https://user-images.githubusercontent.com/20142797/86203323-5bb79580-bb2a-11ea-9353-28456e10555b.png)

**Comment by hansnolte** [comment]
Hi maguilar72G,

you have Blender 2.9 installed, then you have to take LuxCore 2.4.
https://github.com/LuxCoreRender/BlendLuxCore/releases
(BlendLuxCore latest build)

In your last picture, last line, the error is described.
