### ISSUE TITLE
Viewport Denoiser doesn't start

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/BlendLuxCore#501]
Steps to reproduce:
Just start rendered viewport with Denoiser on.
Final rendering works OK.

Screenshots or rendered images:
![BLC_RTPT-OIDN-bug](https://user-images.githubusercontent.com/61623470/86304724-0f468580-bc10-11ea-8d2d-df8472d01bef.jpg)

Error message from Blender console: none

OS: W10
Blender version: 2.83.1
LuxCore version: 2.4beta1(latest daily)

**Comment by Theverat** [comment]
I suspect this will be fixed once the next auto-build is triggered.

**Comment by MetinSeven** [comment]
I'm encountering the same issue. Hope it will be fixed in the next build.

**Comment by kintuX** [comment]
> 
> 
> I suspect this will be fixed once the next auto-build is triggered.

Indeed, issue is gone with new daily :)
