### ISSUE TITLE
Sun too bright when gain=1.0

### ISSUE THREAD

**Issue by foreachthing** [LuxCoreRender/BlendLuxCore#503]
This is Blender default:
(also, when adding a new sun, gain is set to 0.00002)
![image](https://user-images.githubusercontent.com/10420187/86349750-ec44c180-bc61-11ea-9713-cc290ed1edb9.png)

This is with sun gain 1.0:
![image](https://user-images.githubusercontent.com/10420187/86349798-0088be80-bc62-11ea-8ee0-0186264e45fe.png)

Blender: 2.83.0
LuxCore: 2.4b1

**Comment by foreachthing** [comment]
Ok. Here's an old render, rendered in luxrender:
(Gain was set to 1.0 in each and every lightgroup)
![image](https://user-images.githubusercontent.com/10420187/86365766-3afe5580-bc7a-11ea-9982-fedba02bae35.png)
I let it render for 10 minutes.

And this is the old .blend file opened in Blender 2.83 (LuxCore 2.4b1):
![image](https://user-images.githubusercontent.com/10420187/86365904-6da84e00-bc7a-11ea-9030-b143f03c8e35.png)

You can clearly see, that the new image is waaaaaaay too dark.
Textures are missing to... this can be fixed easily! But the sun has not the same impact as it used to.

By the way: WOW on the denoiser! And the overall progress of LuxCore!

This image has **hundreds** of hours behind it:
(rendered on luxrenderer)
![image](https://user-images.githubusercontent.com/10420187/86366568-3a19f380-bc7b-11ea-9ae7-7eccf430ab23.png)

**Comment by foreachthing** [comment]
> I have the feeling you guys are mixing up two separate issues here.
> @foreachthing Please check if your lights and tonemapper have the same brightness settings as in old Lux. If the issue persists, please open a new issue here.

Where would I find the tonemapping settings in Blender 2.83?

**Comment by Theverat** [comment]
> Where would I find the tonemapping settings in Blender 2.83?

Camera settings, imagepipeline panel.

**Comment by foreachthing** [comment]
I had to download Blender 2.78 again :-\
So, here it is; same scene, nothing changed except auto brightness in Blender 2.81:

Blender 2.81:
![image](https://user-images.githubusercontent.com/10420187/86794404-c6a62680-c06c-11ea-9ec8-38aef052acd8.png)

Brightness is Ok .. but what happened to the colors!?

Blende 2.78:
![image](https://user-images.githubusercontent.com/10420187/86794484-df164100-c06c-11ea-9396-f33f7461a08b.png)
_(Why is there furniture missng?! Anyways...)_

**Comment by foreachthing** [comment]
This is more of an "for your information".
After tweaking a lot of things, I got something useful out of BlenderLuxCore....

After the setting was change to auto brightness (amongst other things), it got better. This is with Blender 2.81 and latest BlendLuxCore.
![image](https://user-images.githubusercontent.com/10420187/86973508-f9d3dd00-c174-11ea-8485-da5a0952bbef.png)

I got the materials working, not tuned yet, or did not update them at all.
But I don't like how the sun is much brighter, less yellow, than with the old Luxrender. Also, all the light-groups would have to be remade completely (I removed some light sources not used - Light-groups was fun with the old Luxrenderer!).
I, however, love the denoiser! I let the above image run for 1 minute and the one below ran for 15 minutes on 4 cores each.

This is with Blender 2.78 and Luxrenderer 1.6.
![image](https://user-images.githubusercontent.com/10420187/86968623-c5f4b980-c16c-11ea-922e-70de36507d0b.png)

Maybe one can explain, why the lighting is so much different?

**Comment by Theverat** [comment]
Without having the scenes, I can only advise you to check all your light source settings to make sure they are the same in both versions, and check the tonemapper settings to make sure they are the same. Disable auto brightness, it will just make it harder to spot where the difference comes from.

**Comment by Theverat** [comment]
If there's still a problem, please upload a testscene that demonstrates the problem, and re-open the issue.
