### ISSUE TITLE
4x GPUs problem.

### ISSUE THREAD

**Issue by Txamo** [LuxCoreRender/BlendLuxCore#505]
Good night,

I am testing with version 2.4 and I find unexpected closings of Blender, the problem reproduces when I activate more than 2 GPUs, I have 4x 2080ti.
The scene is nothing special, with any scene this happens, in my case I have tried with a simple box and a light and Blender always closes when using more than two GPUs.

Tell me if you need anything so I can help you.

Kepa.

OS: Win 10
Blender version: 2.83.1 and 2.90 Alpha
LuxCore version: 2.4 Alpha

**Comment by Dade916** [comment]
Does it happen only when doing view port rendering ?

You can find an ongoing discussion about RTPATHOCL (i.e. viewport rendering) multi-GPUs support bugs in latest sources here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=2309

**Comment by Txamo** [comment]
Good morning,

It only happens to me in rendering by viewport, when I launch the final render with the 4GPUs Blender does not close.

I add my comment to the thread that you have attached below.

Good job, Dade.

**Comment by Txamo** [comment]
Hi Dade,

Sorry I just downloaded the latest version a couple of hours ago, now with the 4xGPUs Blender does not close in the render by viewport.

I will keep testing it, excellent work Dade.

If you need me to do a multi GPU test, tell me and I will help you.

Regards.

**Comment by Dade916** [comment]
Ok, this problem should be solved according all reports.
