### ISSUE TITLE
BlendLuxCore Materials: Car Paint Presets are broken

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/BlendLuxCore#507]
[Car Paint Documentation](https://wiki.luxcorerender.org/LuxCoreRender_Materials_Car_Paint)

Blend file: [CarPaintPresetsBroken.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4881181/CarPaintPresetsBroken.zip)

Steps to reproduce: 
Switch through Carpaint presets and observe preview.
Specifically:
- 2k Acrylack
- Blue Matte
- Ford F8
- Opel Titan
- Polaris Silber
They all pick paint set in Manual Settings

Screenshots or rendered images: 
![CarPaintPresetsBroken](https://user-images.githubusercontent.com/61623470/86642756-72536600-bfdc-11ea-8a31-a014543b7d3a.jpg)

Error message from Blender console: none

OS: W10
Blender version: 2.83.1
LuxCore version: 2.4beta1 (latest daily)

**Comment by Theverat** [comment]
Thanks for the report!
