### ISSUE TITLE
Can't enable LuxCore Add-On under Mac OS X Mojave

### ISSUE THREAD

**Issue by bloomingbridges** [LuxCoreRender/BlendLuxCore#509]
Had to roll all the way back to blender v2.81 (higher versions were somehow recognised as 2.83). The Add-On installs just fine using the zip (same result for opencl-support and without), but upon activation I get the following error message: 

> Traceback (most recent call last):
>   File "/Users/.../Downloads/Blender.app/Contents/Resources/2.81/scripts/modules/addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "/Users/.../Library/Application Support/Blender/2.81/scripts/addons/BlendLuxCore2/__init__.py", line 32, in <module>
>     raise Exception(msg + "\n\nImportError: %s" % error) from None
> Exception: 
> 
> **Could not import pyluxcore.**
> 
> ImportError: dlopen(/Users/.../Library/Application Support/Blender/2.81/scripts/addons/BlendLuxCore2/bin/pyluxcore.so, 2): **no suitable image found**.  Did find:
> 	/Users/.../Library/Application Support/Blender/2.81/scripts/addons/BlendLuxCore2/bin/pyluxcore.so: **code signature invalid** for '/Users/.../Library/Application Support/Blender/2.81/scripts/addons/BlendLuxCore2/bin/pyluxcore.so'

OS: 10.14.6
Blender version: 2.81
LuxCore version: 2.3

**Comment by u3dreal** [comment]
Those issues with code signing are really annoing. I fixed this some timw ago. Which version did you try ? opencl or cpu ?

**Comment by u3dreal** [comment]
I looks like the code cert from High Sierra does not work for Mojave.
Plz test
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.4beta1

Or otherwise make your own dev account and sign it with your cert.
2.4beta will also work with blender 2.82 and up. So i suggest to upgrade to 2.4
