### ISSUE TITLE
How to know if render has Finished using farm rendering (luxcore stand alone)

### ISSUE THREAD

**Issue by fadhil0305** [LuxCoreRender/BlendLuxCore#512]
Hi all. I need your help with my case. I tried rendering the farm rendering system using luxcore rendering 2.3. but I don't know when the rendering is complete. because no process is displayed during execution. after a few hours of waiting for execution, I was able to see the results of the rendering, the compilation process was still ongoing with an estimated time of the next 32 hours (due to the computer being turned off). but after I saw the results nothing has changed from the results I found before. is that really the process? Please guide me

![IMG_1990](https://user-images.githubusercontent.com/52478779/87241941-4c054e80-c452-11ea-8dc6-d220c18d55cc.jpg)
![IMG_1991](https://user-images.githubusercontent.com/52478779/87241942-4e67a880-c452-11ea-8377-02bf97e3380a.jpg)

**Comment by Dade916** [comment]
I'm not totally sure to understand the question. The rendering is stopped when one of the halt conditions is met.

The problem for you is how to establish a good halt condition ? Or is how to check the progress of the rendering with command line tools ?

In the first case, you can do a test on your local PC at a very low resolution to fast check what is a good samples/pixel halt condition. In the second case, you can enable periodic rendering saving so the rendering is saved, for instance, every 10 minutes so you can check the saved image.
