### ISSUE TITLE
Can't enable the BlendLux addon on Linux

### ISSUE THREAD

**Issue by BojanBekic** [LuxCoreRender/BlendLuxCore#513]
.blend file: 

Steps to reproduce: 

Install BlendLux addon the usual way. Try to enable it - it fails with an error message

Error message from Blender console:

Traceback (most recent call last):
  File "/home/bojan/.Programs/blender/blender-2.83.2-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/bojan/.config/blender/2.83/scripts/addons/BlendLuxCore/__init__.py", line 68, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /home/bojan/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/libOpenImageDenoise.so.0: undefined symbol: _ZN3tbb10interface78internal15task_arena_base24internal_max_concurrencyEPKNS0_10task_arenaE

OS:

Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-62-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: GeForce GTX 960M/PCIe/SSE2

Blender version: 2.83.2
LuxCore version: v2.4beta1 latest build

**Comment by maljos** [comment]
You can check the python dependencies are installed, if they are, then update the dependencies with pip or sudo update or upgrade. I have linux with python 3.7, numpy, pyside, scipy, etc. Then reinstall blendlux and activate it

**Comment by BojanBekic** [comment]
Thank u for the quick reply. You are probably right, since I was previously unable to install dependencies required for network rendering (pip, pyside stuff). I may have made a mess then. I'll look into it and probably I'll need some help, will ask here.
Thanks!

**Comment by s-leger** [comment]
Same error here,
undefined symbol error in a lib does not looks like a dependency issue, there is something wrong in code.

**Comment by Theverat** [comment]
It sounds a bit like the libOpenImageDenoise.so is the wrong version.
Maybe you installed the addon over a previous version and it was not properly overwrittten?
Try to delete the addon completely and do a fresh re-install from the zip archive.

**Comment by BojanBekic** [comment]
Thanks, tried that just now and it fails with the same message.

**Comment by s-leger** [comment]
looks like the libOpenImageDenoise.so.0 shipped with the add-on is the wrong version.

**Comment by Dade916** [comment]
> looks like the libOpenImageDenoise.so.0 shipped with the add-on use a declared symbol without actual implementation.

I have checked and the BlendLuxCore archive includes the right OIDN v1.2.1 binary:

```
david@Desktop-3900x:~/Desktop/BlendLuxCore/bin$ md5sum libOpenImageDenoise.so.0 libtbbmalloc.so.2 libtbb.so.2
0d1cc787de55664f59ca954fcaabbae2  libOpenImageDenoise.so.0
6a5c66a88bff8047638c52a5bc7da184  libtbbmalloc.so.2
999ecd6cca7410a82083cabf597a3a09  libtbb.so.2
```

Check if you your md5sum matches mine. You may not overwriting the file for some reason (rights ?) or you may use another copy of the file somewhere else ?

**Comment by s-leger** [comment]
Md5 does match yours.
```
md5sum libOpenImageDenoise.so.0 libtbbmalloc.so.2 libtbb.so.2
0d1cc787de55664f59ca954fcaabbae2  libOpenImageDenoise.so.0
6a5c66a88bff8047638c52a5bc7da184  libtbbmalloc.so.2
999ecd6cca7410a82083cabf597a3a09  libtbb.so.2
```

```
> ldd libOpenImageDenoise.so.0 
	linux-vdso.so.1 (0x00007ffe92f93000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb3097f6000)
	libtbb.so.2 => /home/xxx/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libtbb.so.2 (0x00007fb309593000)
	libtbbmalloc.so.2 => /home/xxx/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libtbbmalloc.so.2 (0x00007fb30933b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb309335000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb309154000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb309003000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb308fe8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb308df6000)
```

**Comment by Dade916** [comment]
Well, they works so the only possible explanation is that inside your Blender a different Intel TBB library is used.

Try to run:

```
david@Desktop-3900x:~/projects/luxrender/mercurial/luxrays$ cd ~/.config/blender/2.83/scripts/addons/BlendLuxCore/bin
david@Desktop-3900x:~/.config/blender/2.83/scripts/addons/BlendLuxCore/bin$ python3
Python 3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyluxcore
>>> pyluxcore.Version()
'2.4rc1'
>>> 
```

Does it works ?

**Comment by s-leger** [comment]
Maybe related to the pyhton interpreter not being the blender's one by default ?
```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyluxcore
>>> pyluxcore.Version()
'2.4rc1'
```

**Comment by Dade916** [comment]
How did you installed Blender ? Downloading from blender.org or with some kind of virtualization like Snap, etc. ?

**Comment by s-leger** [comment]
portable version downloaded from bf.

**Comment by s-leger** [comment]
```
>ldd pyluxcore.so 
	linux-vdso.so.1 (0x00007ffe1dfb7000)
	libembree3.so.3 => /home/xxx.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libembree3.so.3 (0x00007f6df06f1000)
	libOpenImageDenoise.so.0 => /home/xxx/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libOpenImageDenoise.so.0 (0x00007f6ded93f000)
	libtbb.so.2 => /home/xxx/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libtbb.so.2 (0x00007f6ded6dc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6ded684000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6ded67e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ded52f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f6ded4eb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6ded4d0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ded2de000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6df5c9a000)
	libtbbmalloc.so.2 => /home/xxx/.config/blender/2.83/scripts/addons/BlendLuxCore/bin/./libtbbmalloc.so.2 (0x00007f6ded086000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6decea5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6dece9a000)
```

**Comment by Dade916** [comment]
Do you have some kind of system wide installation of Intel TBB library ?

**Comment by s-leger** [comment]
Ok got it, 
there is a conflict with blenderBIM also using libtbb.so.2

**Comment by Dade916** [comment]
Ok, good.

**Comment by BojanBekic** [comment]
Thanks. Is there a solution better than disabling BlenderBIM?

**Comment by s-leger** [comment]
Disable and remove blenderbim, restart blender, setup and enable luxcore, then reinstall blenderbim.

**Comment by BojanBekic** [comment]
Great, thanks, I was about to do it now. Really glad this is sorted :)

**Comment by s-leger** [comment]
As temporary workaround, copy

/home/xxx/.config/blender/2.8x/scripts/addons/BlendLuxCore/bin/libtbb.so.2
to 
/home/xxx/.config/blender/2.8x/scripts/addons/blenderbim/libs/libtbb.so.2

@Dade916 Could you rename this issue to something like "conflict with blenderbim" ?

**Comment by s-leger** [comment]
Would like to solve this issue on blenderbim side.

How to explain the missing symbol in our (blenderbim) version for a lib like this one (i guess it is a standard lib ?)

**Comment by Dade916** [comment]
> How to explain the missing symbol in our (blenderbim) version for a lib like this one (i guess it is a standard lib ?)

They need to update the version of Intel TBB library they use. Their old version is likely to brake the Intel denoiser in Blender too (even when not having LuxCore).
The minimum TBB version should 2017.0: https://github.com/OpenImageDenoise/oidn/blob/cdfbc7b15c6b7428dde88c3645ca1111a28391fb/CMakeLists.txt#L74
