### ISSUE TITLE
LuxCore v2.4 RC1 cannot be enabled in Blender 2.83.2 on macOS

### ISSUE THREAD

**Issue by JohJakob** [LuxCoreRender/BlendLuxCore#516]
Trying to enable LuxCore v2.4 RC1 in Blender 2.83.2 throws an error on macOS

**Steps to reproduce**
1. Download [BlendLuxCore v2.4 RC1](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.4rc1) for macOS
2. Install addon from file in Blender 2.83.2
3. Enable addon

**Screenshots or rendered images**

<img width="737" alt="Error report in Blender 2.83.2" src="https://user-images.githubusercontent.com/9888537/87937673-70d27500-ca95-11ea-8747-20e0b3c2fb00.png">

**Error message from Blender console**

```
File "/Applications/Blender.app/Contents/Resources/2.83/scripts/modules/addon_utils.py", line 351, in enable
  mod = __import__(module_name)
File "/Users/username/Library/Application Support/Blender/2.83/scripts/addons/BlendLuxCore/__init__.py, line 50, in <module>
  if not os.access(denoiser_path, os.X_OK):
TypeError: access: path should be string, bytes or os.PathLike, not NoneType
```

OS: macOS Catalina 10.15.6
Blender version: 2.83.2 LTS
LuxCore version: 2.4 RC1

**Comment by Dade916** [comment]
@u3dreal: there may bea filename to fix in BlendLuxCore or MacOS packing ?

**Comment by u3dreal** [comment]
I'll have a look

**Comment by u3dreal** [comment]
indeed denoise seems to be missing in the Blendluxcore download..

You might get it here and copy it from the pyluxcore folder. Here all seems fine.
[https://github.com/LuxCoreRender/LuxCore/releases](url)

**Comment by u3dreal** [comment]
MAC_FILES = [
    "libembree3.3.dylib", "libomp.dylib", 
    "libOpenImageDenoise.1.2.1.dylib", "libOpenImageIO.1.8.dylib",
    "libcuda.dylib", "libnvrtc.dylib",
    "libtbb.dylib", "libtbbmalloc.dylib", "libtiff.5.dylib", 
    "pyluxcore.so", "pyluxcoretools.zip", "oidnDenoise"
]

I guess this should be "denoise" and not "oidnDenoise" here .... no idea how that changed.

**Comment by u3dreal** [comment]
Should be fixed now.
[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest](url)

**Comment by u3dreal** [comment]
@Theverat Should denoise be renamed to work with BlendLuxCore now ???

**Comment by u3dreal** [comment]
Oh i see will have to update oidn ..

**Comment by u3dreal** [comment]
should be fixed now

[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest](url)

**Comment by JohJakob** [comment]
Thank you, guys!
