### ISSUE TITLE
LuxCore v2.4 RC1 compiling OpenCL render kernels causes Blender to not respond on macOS

### ISSUE THREAD

**Issue by JohJakob** [LuxCoreRender/BlendLuxCore#519]
The latest version of BlendLuxCore (v2.4 RC1) causes Blender on macOS to not respond when compiling OpenCL render kernels. It does not finish compiling and freezes Blender completely. I tested v2.4 beta 1 which took only a few seconds to compile the kernels.

I also noticed that the addon will not be enabled when Blender is closed and re-opened and that changing the compute device from CPU to GPU will show an exclamation mark icon on the “Devices” panel, forcing the user to update the device list. This does not happen in v2.4 beta 1.

CPU rendering works fine though.

**Steps to reproduce**

1. Install [BlendLuxCore v2.4 RC1](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)
2. Enable addon
3. Enable rendered mode in viewport

OS: macOS Catalina 10.15.6
Graphics Card: AMD Radeon 560 (4 GB)
Blender version: 2.83.2
LuxCore version: 2.4 RC1

**Comment by Dade916** [comment]
Just wait, it can take several minutes. Beta1 is likely to take few seconds only because the result has already been cached.

It takes 90 seconds on my 3900X and NVIDIA drivers while with MacOS half broken drivers and a slow CPU, it can take 15 minutes.

**Comment by JohJakob** [comment]
Alright, it took almost exactly an hour to compile on my machine. Blender showed the rendered viewport for a few seconds and then crashed. After re-opening Blender, I had to enable the addon again, but the kernels had been cached. However, Blender crashes when switching back to the solid view.

**Comment by u3dreal** [comment]
What gfx do you have ?

**Comment by JohJakob** [comment]
I have an AMD Radeon 560 (4 GB) in my MacBook Pro 15" from 2017.

**Comment by u3dreal** [comment]
Do you have any internal gfx ?

**Comment by JohJakob** [comment]
Oh, yes, that’s an Intel HD Graphics 630 (1536 MB).

**Comment by u3dreal** [comment]
quote Dade:
"No, it is the OpenCL drivers to be broken and the hardware to be very limited: on Windows/Linux we don't touch Intel "GPUs", not even with a 2 meters long stick. They are explicitly avoided by BlendLuxCore."

So plz disable it otherwise you get the 1h timeout and an error in OpenCL compilation.

**Comment by u3dreal** [comment]
report back so we can close this issue

**Comment by JohJakob** [comment]
I did that. When I update the device list, the Intel GPU is automatically disabled and the AMD GPU is enabled. This was the state when I started the render kernel compilation.

**Comment by u3dreal** [comment]
Can you just run luxcorerender from the command line ? standalone ? 
Or run Blender from terminal and post the error plz.

**Comment by JohJakob** [comment]
Well, that’s weird. I just opened Blender, but I didn’t have to re-enable LuxCore and all the other issues (forced device update, crash when switching back to Solid view) are gone as well. I can’t reproduce the error.

Sorry for the trouble! My computer might have just behaved weirdly.
