### ISSUE TITLE
Disable sun's indirect light visibility for PATH engines

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#52]
> BTW, another simple solution to the water "fireflies" is to disable visibility of the sun in indirect specular paths. Simon, it should be probably be default setting for any *PATH* render engine as the Sun is just fireflies generator for anything but BIDIR.
https://forums.luxcorerender.org/viewtopic.php?f=2&p=661#p661

**Comment by michelchafouin** [comment]
I have a patch for this one, changing default value and fixing the UI a bit. I can pull request after my other pull request gets accepted.

**Comment by Theverat** [comment]
This is a tricky subject, which is the reason why this issue is very old and still not closed.

Maybe the best way to solve it would be to add an additional property `sun_visibility_indirect_specular` with `default=False` that is only shown in the UI if the light type is "sun" and replaces the usual `visibility_indirect_specular`.
We could sync these properties on edits to prevent weird behaviour when switching between light types, with update functions like this:

```python
def update_visibility_indirect_specular(self, context):
    self["sun_visibility_indirect_specular"] = self.visibility_indirect_specular

visibility_indirect_specular: BoolProperty(name="Specular", default=True, description=VIS_INDIRECT_SPECULAR_DESC, update=update_visibility_indirect_specular)

def update_sun_visibility_indirect_specular(self, context):
    self["visibility_indirect_specular"] = self.sun_visibility_indirect_specular

sun_visibility_indirect_specular: BoolProperty(name="Specular", default=False, description=VIS_INDIRECT_SPECULAR_DESC, update=update_sun_visibility_indirect_specular)
```

The `self["..."] = ...` assignment is used because it doesn't trigger the update function of the property that is assigned to, thus preventing endless recursion.
