### ISSUE TITLE
Cannot enable 2.4 RC1

### ISSUE THREAD

**Issue by Ingapambi** [LuxCoreRender/BlendLuxCore#520]
<img width="2560" alt="Screen Shot 2020-07-21 at 5 12 57 PM" src="https://user-images.githubusercontent.com/44510383/88119543-a64e8f80-cb75-11ea-842c-1ef8c55256ad.png">

**Comment by Dade916** [comment]
Can't you click on checkbox before "Render: LuxCore" ?

**Comment by Ingapambi** [comment]
It doesn't enable when clicked

John 

    On Wednesday, July 22, 2020, 03:04:47 AM PDT, David Bucciarelli <notifications@github.com> wrote:  
 
 


Can't you click on checkbox before "Render: LuxCore" ?

**Comment by Theverat** [comment]
What's your OS?
What is the exact error mesage from Blender? You can find it in the terminal, on Windows in the menu Window -> Toggle System Console.

**Comment by Theverat** [comment]
Does it work with the final v2.4?
If not, it would be good if you could answer the questions above.
