### ISSUE TITLE
Enable 2.4

### ISSUE THREAD

**Issue by Ingapambi** [LuxCoreRender/BlendLuxCore#525]
2.4 Mac OS 10.15.6 

It installs fine. When enabling get this error msg.

<img width="2560" alt="Screen Shot 2020-07-27 at 12 24 53 PM" src="https://user-images.githubusercontent.com/44510383/88583523-3886e580-d005-11ea-927e-aa0da073a475.png">

**Comment by Theverat** [comment]
This was an old bug that is fixed since a while.
Maybe you did overwrite an older installation, and it didn't work correctly?
Try to delete the addon and re-install it, and make sure you downloaded the final release from http://luxcorerender.org/download/

**Comment by Ingapambi** [comment]
Thanks,It was blender 2.82 and seems to have turned on.
John 

    On Monday, July 27, 2020, 01:30:20 PM PDT, Simon Wendsche <notifications@github.com> wrote:  
 
 


This was an old bug that is fixed since a while.
Maybe you did overwrite an older installation, and it didn't work correctly?
Try to delete the addon and re-install it, and make sure you downloaded the final release from http://luxcorerender.org/download/

**Comment by Theverat** [comment]
I have to admit I'm not sure what you mean.
Is the issue solved?
