### ISSUE TITLE
LuxCore 2.4 in Blender 2.83.3 is not possible to enable

### ISSUE THREAD

**Issue by salukim** [LuxCoreRender/BlendLuxCore#528]
When I install the new LuxCore 2.4 in the new Blender 2.83.3 Windows 64, only the information that the module has been installed is displayed, but it is not in the list of add-ons. Until now, I have worked without problems with LuxCore 2.3 on Blender 2.83.2. When I tried back the lower version I had the same problem.
Please help me?

**Comment by Theverat** [comment]
Are there any error messages in the Blender console after you install the addon?
Did you try to delete the old installation before installing v2.4?

**Comment by Theverat** [comment]
Please add the requested information so we can help you, and re-open the issue.
