### ISSUE TITLE
API PTX Cuda error

### ISSUE THREAD

**Issue by maljos** [LuxCoreRender/BlendLuxCore#537]
.blend file:

Steps to reproduce:

Screenshots or rendered images:
![Captura de pantalla_2020-08-04_17-44-01](https://user-images.githubusercontent.com/3738917/89348473-9c9b5080-d67a-11ea-9a0c-57c1057c60a3.png)

Error message from Blender console:

OS: Linux Xubuntu 18.04
Blender version: 2.83.3
LuxCore version: 2.5 Pre-Release

**Comment by Theverat** [comment]
You probably need to update your driver, 450+ is required in v2.5.

**Comment by maljos** [comment]
Ok
