### ISSUE TITLE
Vertex color in glass material absorption is not apparent

### ISSUE THREAD

**Issue by MetinSeven** [LuxCoreRender/BlendLuxCore#539]
Hi,

I noticed that if I plug a vertex color channel filled with green into a clear volume's Absorption map slot, the color is not visible in the glass. But when I unplug the vertex color and enter the exact same color in the solid color swatch of the clear volume, the color becomes visible.

I've attached a comparison. It's the sphere's glass on top of the raygun. Maybe the vertex colors are being gamma corrected by Lux or BlendLuxCore?

![vertex color in glass absorption](https://user-images.githubusercontent.com/18738261/89205899-be340380-d5b8-11ea-9805-a0720b9a6524.png)

Note: The scene lighting is not finished yet, hence the darkness.

**Comment by Theverat** [comment]
There was already a warning in place about 2D textures, I have improved it with an explicit list of nodes that don't make sense on volumes in 779f27118695a1f9eec25a3080a880736072846e.

![sdfsdf](https://user-images.githubusercontent.com/1584761/90175240-6a3ed100-dda7-11ea-8a95-271497de5797.PNG)
