### ISSUE TITLE
Volume gets random Mat color ID

### ISSUE THREAD

**Issue by EgertKanep** [LuxCoreRender/BlendLuxCore#540]
When using volume together with glass shader it does not get specified material id color. It should be red as is arch glass
![mat id color volume](https://user-images.githubusercontent.com/41080633/89581279-5fcc8680-d83f-11ea-8a27-3bdb3a563ced.JPG)

**Comment by Theverat** [comment]
I have implemented it. Note that you need a separate volume node tree with volume output to be able to specify a volume ID.
