### ISSUE TITLE
nO module named certifi

### ISSUE THREAD

**Issue by littleantlive** [LuxCoreRender/BlendLuxCore#541]
```
Traceback (most call last)
File "/usr/share/blender/2.83/scrippts/modules/addon-utils.py",line 351, in enable
mod = _import_(module_name)
File="home/ant/.config/blender/2.83/scripts/addons/BlendLuxCore/_init_.py",line 44, in<module> import cetifi
ModuleNot Found Error No module named 'certifi'
```

**Comment by Theverat** [comment]
Are you using Blender with a custom Pyhton installation instead of the one bundled with Blender?

**Comment by littleantlive** [comment]
Sorry, I don't know how to use python, but the system itself has it. I don't know what the situation is. I use ArchLInux. What package is installed to make the program work normally?



发自我的小米手机
在 Simon Wendsche <notifications@github.com>，2020年8月13日 下午9:44写道：

Are you using Blender with a custom Pyhton installation instead of the one bundled with Blender?

**Comment by Theverat** [comment]
Did you install the BlendLuxCore addon from our zip package, or through the package manager of your distribution?
If the latter is the case, you will have to ask the creator of the package for support. It is probably their responsibility to ensure that all dependencies are installed correctly.

If you use our official zip package, you should not have any problems, as it will use Blender's bundled Python which has all necessary dependencies already included.

**Comment by littleantlive** [comment]
I tred install python-certifi. The program is running normally.Thank you for your reply. It may be that I think the problem is complicated.



发自我的小米手机
在 Simon Wendsche <notifications@github.com>，2020年8月14日 下午8:53写道：

Did you install the BlendLuxCore addon from our zip package, or through the package manager of your distribution?
If the latter is the case, you will have to ask the creator of the package for support. It is probably their responsibility to ensure that all dependencies are installed correctly.

If you use our official zip package, you should not have any problems, as it will use Blender's bundled Python which has all necessary dependencies already included.
