### ISSUE TITLE
Missing light sources when rendering on GPU

### ISSUE THREAD

**Issue by giacometti777** [LuxCoreRender/BlendLuxCore#542]
.blend file: 
https://we.tl/t-x3IyXaFrDj

Steps to reproduce:
Render cam2 view layer with CPU then GPU. On Light Group 3 the reflections of the lit torus disappear entirely when using GPU (OpenCL or CUDA). I'm going to try reverting back to luxcore 2.3 after a week of failed renders due to this to see if the issue persists.

Edit: I tried the scene in 2.3 with OpenCL and it works as it should but I need thin film interference for this scene so its unrenderable for me until this issue is fixed.

Screenshots or rendered images:
CPU:
![luxcore 2 4 cpu](https://user-images.githubusercontent.com/26721413/89676228-2a0bba00-d8a0-11ea-86c8-ced446cd3629.jpg)
GPU (OpenCL or CUDA):
![luxcore 2 4 gpu (cuda or opencl)](https://user-images.githubusercontent.com/26721413/89676235-2d9f4100-d8a0-11ea-9f3a-4392561f9a98.jpg)

Note the missing white stripe of light across the fingers. This is coming from an emissive torus that goes missing.

Error message from Blender console:
N/A

OS: Windows 10
Blender version: 2.83
LuxCore version: 2.4

**Comment by giacometti777** [comment]
I came to realize this is happening because of the Light Tracing "Glossiness Threshold". When it is set too low the emissive torus reflection disappears but only in GPU renders. Is this expected behavior?

**Comment by Dade916** [comment]
Can you reproduce the problem in a simple scene ? Something like a cube over a plane ?
