### ISSUE TITLE
2.5alpha pointer not working

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/BlendLuxCore#545]
.blend file: 
[pointer_test.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5051251/pointer_test.zip)

Steps to reproduce:
Use the scene attached. The mesh with the pointer is rendered black.

Screenshots or rendered images:

Error message from Blender console:

OS: win10
Blender version: 2.9beta
LuxCore version: 2.5 alpha

**Comment by CodeFHD** [comment]
I traced it back and found the issue to stem from [this](https://github.com/LuxCoreRender/BlendLuxCore/blob/master/nodes/base.py#L352) line.

Not returning the passed-in name leads to [this](https://github.com/LuxCoreRender/BlendLuxCore/blob/master/nodes/materials/output.py#L170) fallback condition being met and thus the object shaded black. The pointed material is additionally exported as a "nameless" material (i.e. id only) that is not assigned to any object.

Commenting out the first line I quoted seems to make it work, while not breaking the usual use of volume pointers in a simple test scene. However, there is a comment suggesting that this was done explicitly for some reason, which of course I can't judge, or what scenarios need to be tested to ensure proper function. Hopefully this helps to decide what needs to be fixed.

**Comment by Theverat** [comment]
Fixed in ad32043d96c4dd73729d6a0c28ff9350a5b42b8c

I came to the same conclusion as @CodeFHD (at least I assume that, the first link is not a permanent one and currently points to some non-relevant section of the code).

**Comment by Theverat** [comment]
@CodeFHD side note, you should use permanent links to refer to lines of code:

![Capture](https://user-images.githubusercontent.com/1584761/90142079-3a2e0880-dd7c-11ea-997a-ddecc25d6ddc.PNG)

**Comment by CodeFHD** [comment]
ok, thanks for the info. I was indeed not aware of this, although it makes a lot of sense.
