### ISSUE TITLE
Need: 1 Node group, 2 cycles style colorramp, 3 layer node+switch node, 4 blur node

### ISSUE THREAD

**Issue by jiabaoyu** [LuxCoreRender/BlendLuxCore#553]
1. Node group:
   Node group can improve the management and clearity of the whole material, as well as reuse and can be used as asset.
   Blender's native implement is a good reference. Though, due to blender's image node don't have a image input.

2. Cycles style colorramp node:
   It's just more intuitive and user-friendly.

3. Layer node+switch node:
   Like in arnold render: layer node has upto 10 color input along with 10 opacity input. It enables user to mix images inside the 
   shader editor. While switch node, just like the keyword "swtich" in lots of programming language, is a special layer node which 
   has a "fac(float) or id(int)" input and several color input. The fac/id input determines which color input (or some mix of them) 
   should be piped to the output.

4. Blur node
    It has a image input, a blur method(interpolation) chooser, a blur radius input and output a blurred image result.
   It's pretty useful when: to achieve a smooth transition in bump or displacement, sharp images can be blurred then plugged 
   into bump and displacement. 
   Blur method(interpolation) chooser can be used to change the transition curve. Even, we could have a curve widget to 
   manually draw the transition curve.

**Comment by Theverat** [comment]
1. node groups already have an issue here: #127 

2. It's not possible for Blender addons to create color ramps. Could be worked around by #362 though.

3. Please open a separate issue about this (every issue should have only one topic). Include a link to existing documentation on this feature, e.g. in another renderer, if possible.

4. Again, please open a separate issue about this.

**Comment by jiabaoyu** [comment]
> 1. node groups already have an issue here: #127
> 2. It's not possible for Blender addons to create color ramps. Could be worked around by #362 though.
> 3. Please open a separate issue about this (every issue should have only one topic). Include a link to existing documentation on this feature, e.g. in another renderer, if possible.
> 4. Again, please open a separate issue about this.
> 
> Thanks for the feature suggestions.

Thank you. I'll do that as long as I have spare time.

**Comment by Theverat** [comment]
> Though, due to blender's image node don't have a image input.

I'm not sure if I interpret this correctly, but if you mean that Blender image nodes don't show an image thumbnail: There's an addon for that: https://blendermarket.com/products/image-node-preview

**Comment by jiabaoyu** [comment]
> I'm not sure if I interpret this correctly, but if you mean that Blender image nodes don't show an image thumbnail: There's an addon for that: https://blendermarket.com/products/image-node-preview

No. Consider that situation: In cycles shader editor, you make a node group wihich contains a image node. Then you want to change the image, instead of plug a image to the node group, now you have no choice but have to go inside the node group to edit the image node inside. Hope this example will make you understand.

**Comment by Theverat** [comment]
Ah, I see.

I'll close this issue since there now exist separate issues for each topic in this one.
