### ISSUE TITLE
Syntax error in texture name: *numbers*Color

### ISSUE THREAD

**Issue by Mirxku** [LuxCoreRender/BlendLuxCore#554]
So, i dont even have this texture, and also if i trying to render not in viewport, i got like billions of memory usage (1250 M), and the same error. Why? Also in some scenes it is trying to render without textures, all just white. Any help pls)

**Comment by Mirxku** [comment]
> When I press "Use Cycles settings" and try to render, I get the error you probably also got:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\base.py", line 87, in render_final
>     final.render(self, depsgraph)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 48, in render
>     _render_layer(engine, depsgraph, statistics, layer)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 60, in _render_layer
>     engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\export\__init__.py", line 143, in create_session
>     luxcore_scene.Parse(scene_props)
> RuntimeError: Syntax error in texture name: 1874786963496Color
> ```
> 
> It is most likely a bug in the Cycles node reader. I'll check.

Seems similar

**Comment by Mirxku** [comment]
> When I press "Use Cycles settings" and try to render, I get the error you probably also got:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\base.py", line 87, in render_final
>     final.render(self, depsgraph)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 48, in render
>     _render_layer(engine, depsgraph, statistics, layer)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 60, in _render_layer
>     engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
>   File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\export\__init__.py", line 143, in create_session
>     luxcore_scene.Parse(scene_props)
> RuntimeError: Syntax error in texture name: 1874786963496Color
> ```
> 
> It is most likely a bug in the Cycles node reader. I'll check.

What chances that this will be fixed?

**Comment by Theverat** [comment]
Fixed in 572ea78a03e1955f4a448fb7b10aeb3b56dca1e3.
