### ISSUE TITLE
Luxcore Blender 2.83

### ISSUE THREAD

**Issue by Ibo0o0o** [LuxCoreRender/BlendLuxCore#561]
I have the following error :  OpenCL driver API error (code -30, file:/Users/runner/work/1/s/src/luxrays/utils/ocl.cpp, line: 366): CL_INVALID_VALUE

Don't know what to do

**Comment by CodeFHD** [comment]
Sounds like a duplicate of [LuxCore Issue #439](https://github.com/LuxCoreRender/LuxCore/issues/439)

You can try to reinstall the GPU driver. If you have an Nvidia card, you can switch to using CUDA instead of OpenCL in the addon preferences.

**Comment by Ibo0o0o** [comment]
Working on macOS. No Nvidia for me

**Comment by Dade916** [comment]
Does LuxMark work ?

**Comment by Ibo0o0o** [comment]
No. It doesn’t, The strange thin is that LuxCore has worked.

**Comment by Dade916** [comment]
Some time OS updates/security patches can break GPU driver installation (it has happened more the once on Windows). You should try to re-install GPU driver (if there is such thing on MacOS).

**Comment by Ibo0o0o** [comment]
Thanks I wil trie
