### ISSUE TITLE
why have the settings from light groups been removed in that panel can we only control it with that node now?

### ISSUE THREAD

**Issue by bestman8** [LuxCoreRender/BlendLuxCore#562]
i usually pause the render to change the light groups and is that still possible in the latest 2.5 builds. 
if we have to use that node why can't we cange the color temprature anymore.
it was this [https://cdn.discordapp.com/attachments/553598078947426316/754382780133015682/light_groups_now_.png](url) it is was this  [https://cdn.discordapp.com/attachments/553598078947426316/754382781068607568/light_groups_old.png](url) 
it had a lot of usefull features.
i'm only wondering why that has been removed and if it will get back to how it was.

**Comment by Theverat** [comment]
It's explained here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2468

> if we have to use that node why can't we cange the color temprature anymore.

It was too much hassle so I didn't do it yet.
You can do reach the same results with the RGB color multiplier, as a workaround.
