### ISSUE TITLE
LuxCore Image Pipeline Node in Blender Compositor 

### ISSUE THREAD

**Issue by onegobo** [LuxCoreRender/BlendLuxCore#564]
From what I understand currently the LuxCore Image Pipeline is located with the camera object. I would think most Blender users of LuxCore will do most things image correction inside the compositor. Therefore it could be helpful to have one (or several) LuxCore Image Pipeline Node(s) to work with in the compositor. Use case would be ie adding several light group element combinations, and afterwards running one through Reinhard and one through Isocurves, which is not possible at this point.

**Comment by Theverat** [comment]
I don't see a way to integrate the LuxCore imagepipeline into the Blender compositor like this.

> Use case would be ie adding several light group element combinations, and afterwards running one through Reinhard and one through Isocurves, which is not possible at this point.

You can use a new node group in upcoming Lux v2.5 to achieve something like this: https://youtu.be/vqigKhwWxIs
But you will be limited to Blender's compositor nodes to manipulate the lightgroup mix result. The LuxCore imagepipeline must always be run and completed before the image is fed into Blender, and as far as I know Blender's API does not make it possible to add custom nodes running custom code which could be used in the middle of a compositing node tree.
