### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by riteshcrudani30682** [LuxCoreRender/BlendLuxCore#565]
im using blender 2.83/2.85/2.91 and im trying to install luxcore render dut error is showing 
![errore in luxCore](https://user-images.githubusercontent.com/45712641/93668046-b0263d80-faa7-11ea-9cc8-6b39dc343758.png)

**Comment by Dade916** [comment]
Blender v2.9x is not officially yet supported, you should use v2.83 LTS.

What LuxCoreRender version are you trying to install ? Have you installed the required libraries (http://wiki.luxcorerender.org/BlendLuxCore_Installation) ?
