### ISSUE TITLE
OpenCL driver API error -1001

### ISSUE THREAD

**Issue by EntityinArray** [LuxCoreRender/BlendLuxCore#566]
.blend file: 
Default cube scene

Steps to reproduce:
- Open scene in blender 2.83.6
- Switch to rendered preview or try to render anything

Screenshots or rendered images:
![Screenshot_20200920_110836](https://user-images.githubusercontent.com/18554021/93706719-a6491c80-fb31-11ea-9c91-eb80b5c125a1.png)

Error message from Blender console:
```
BlendLuxCore 2.4 registered (with pyluxcore 2.4)
Traceback (most recent call last):
  File "/home/entityinarray/.config/blender/2.83/scripts/addons/BlendLuxCore/handlers/load_post.py", line 59, in handler
    updated = scene.luxcore.devices.update_devices_if_necessary()
  File "/home/entityinarray/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 41, in update_devices_if_necessary
    device_props = self.get_device_props()
  File "/home/entityinarray/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 99, in get_device_props
    return pyluxcore.GetOpenCLDeviceDescs()
RuntimeError: OpenCL driver API error (code: -1001, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/devices/ocldevice.cpp, line: 72): -1001
```

OS: Linux Kubuntu 20.04 64bit
Blender version: 2.83.6
LuxCore version: 2.4

**Comment by Dade916** [comment]
You are likely to have installed only the OpenCL ICD and not an OpenCL driver for your GPU. You need to fix OpenCL installation before to run BlendLuxCore.
Run LuxMark to check if your OpenCL support is working fine or has a problem.

If you don't want to use the GPU at all, you can install the CPU-only version of LuxCoreRender.
