### ISSUE TITLE
Cuda driver api error

### ISSUE THREAD

**Issue by Mohsyn** [LuxCoreRender/BlendLuxCore#568]
.blend file: 
Any

Steps to reproduce:
Change rendering engine to gpu

Screenshots or rendered images:

Error message from Blender console:
Cuda driver api error CUDA_ERROR_INVALID _PTX CODE 128, FILE D:\a\1\luxcore\src\luxrays\utils\cuda.cpp, line 190: a ptx jit compilation failed

OS: windows 10
Blender version: 2.83.2
LuxCore version: 2.4

**Comment by Dade916** [comment]
You need to install latest NVIDIA drivers, the NVIDIA compiler included in LuxCore is newer than the driver you are using and you end with that error because the generated CUDA JTX code has some new op not supported by your driver.

**Comment by Mohsyn** [comment]
> You need to install latest NVIDIA drivers, the NVIDIA compiler included in LuxCore is newer than the driver you are using and you end with that error because the generated CUDA JTX code has some new op not supported by your driver.

Even If I disable Nvidia Card - it still gives error on Intel HD Graphics Card 5500 as follows:
OPENCL driver API Error - ( code: -5, file D:\a\1\luxcore\luxrays\devices\ocldevice.cpp, line: 45) CL_OUT_OF_RESOURCES

**Comment by Dade916** [comment]
This is a different problem: Intel GPU are too limited to run a complex GPU computing task like rendering and the are disabled by default in BlendLuxCore exactly for that reason.
Like I wrote before, just update your NVIDIA drivers.
