### ISSUE TITLE
UI Polish

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [LuxCoreRender/BlendLuxCore#569]
Below I gather some smaller things I noticed in the UI that makes it inconsistent with Blender UI conventions.

Note. I'm using final 2.4 LuxCore for Blender release.

**Camera Object Data Image Pipeline Menu**

![image](https://user-images.githubusercontent.com/64398828/94546237-47348780-0256-11eb-8cbb-995e4bbc2102.png)

Currently the **pipeline** starts with lower case **p**. It should be Image **P**ipeline with upper case **P** to match naming conversions in Blender.

**View Layer Properties and OAVs**

I suggest to rename **LuxCore Arbitrary Output Variables (AOVs)** to short version **LuxCore AOVs**.
![image](https://user-images.githubusercontent.com/64398828/94546654-dfcb0780-0256-11eb-9825-3e2436470012.png)
![image](https://user-images.githubusercontent.com/64398828/94554290-8d8fe380-0262-11eb-92f4-0dd0511f88f7.png)

There are two major reasons for that:
1. It's much easier to scan for this information. Especially for new users to LuxCore. While it's nice that you use proper full technical description here (Arbitrary Output Variables). It's too long to read. The fact that you have to put easily recognizable abbreviation in the parenthesis makes it even harder for user to search for.
2. I've never heard anyone using the full description for AOV in production environment so I highly doubt we loose any functionality by leaving just LuxCore AOVs. It'll read cleaner in the UI and fully recognizable in professional environment.

The best rule in the design if something can be simplified without loosing it's functionality then it should be simplified.

There is also something wrong with the design of the rest of AOV panel. It never shows the names fully no matter how you stretch it.
![TSOJUOAgIk](https://user-images.githubusercontent.com/64398828/94548783-e6a74980-0259-11eb-809a-56b25517da5c.gif)

**P.S.** I think this might have been solved in the 2.5 build but I don't use alpha/beta builds for now because of production cycle. So I'm not sure.

Please make the naming convention and style match exactly in Compositing workspace to what is in LuxCore AOVs panel.
![image](https://user-images.githubusercontent.com/64398828/94549359-c0ce7480-025a-11eb-8e83-da570b3fe8b1.png)

Again, it'll follow good naming conventions that are already in Blender. It's bad design decision to use ALL CAPS and extra characters without a strong reason. Unless it's technically impossible to use the same naming scheme as in AOVs panel we should do it to keep consistency and keep UI clean.

Thank you.

**Comment by Theverat** [comment]
1. The image pipeline name has been fixed
2. The AOV panel name has been changed
3. The issues with the AOV checkboxes had been fixed for a while, but in Blender 2.90 checkboxes are now drawn differently than before, and there are again problems with names not showing, also the checkboxes now have enormous whitespace to the left. The best way to fix this would be to use the new `heading` feature of columns, like the Cycles passes UI does, but this would break compatibility of the addon with Blender versions < 2.90, so I'm holding off on that for a while.
4. The advantage of having a weird all-uppercase naming scheme for our AOVs is that you can never confuse them with Cycles passes that might be left enabled in a ported Cycles scene. Because of this, and because of compatibility with the past, and because I don't see it as a big problem I will leave them like they are now.

**Comment by AlexeyAdamitsky** [comment]
Thank you for paying attention to this.

> 3. The best way to fix this would be to use the new heading feature of columns, like the Cycles passes UI does, but this would break compatibility of the addon with Blender versions < 2.90, so I'm holding off on that for a while.

I understand. Since it doesn't cause any bugs but have only visual issues I think it's reasonable to hold off updating to new format if it breaks compatibility with older versions. Maybe you'll revisit this issues with 2.6 version.

> 4. The advantage of having a weird all-uppercase naming scheme for our AOVs is that you can never confuse them with Cycles passes...

I get the reasoning but I still wish there was a more elegant UI solution. The current one seems a bit crude. Unfortunately I don't have anything in mind right now to offer as an alternative but since I understand what caused the initial implementation I'll keep it in mind and if I come up with anything worth exploring I'll write about it in a new suggestion.
