### ISSUE TITLE
(Linux) Enable addon on blender 2.90 fails with "No module named 'certifi'"

### ISSUE THREAD

**Issue by Stromberg90** [LuxCoreRender/BlendLuxCore#572]
Error message from Blender console:
```
Traceback (most recent call last):
  File "/usr/share/blender/2.90/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/stromberg/.config/blender/2.90/scripts/addons/BlendLuxCore/__init__.py", line 44, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'
```

OS: Manjaro(Linux) 64-Bit
Blender version: 2.90.1
LuxCore version: 2.4

**Comment by Stromberg90** [comment]
This might be a duplicate of #565

**Comment by Theverat** [comment]
This might hint to some problems with your Blender installation. How did you install it?

**Comment by Stromberg90** [comment]
via the package manager.

**Comment by Theverat** [comment]
Try to use the zip from the official blender site.

**Comment by Stromberg90** [comment]
It does indeed work when using the portable zip from the blender website.

**Comment by Theverat** [comment]
I guess when the package manager is installing Blender, it makes it use the system Python, but doesn't ensure that all modules that are supposed to be pre-installed in Blender's bundled Python are installed to the system Python. I would report this to the author of the package.

**Comment by E-Bachman** [comment]
What python module do you need to install globally to make it work?
