### ISSUE TITLE
Lux 2.5 - Halt Condition

### ISSUE THREAD

**Issue by lsohele** [LuxCoreRender/BlendLuxCore#574]
Halt Condition isn´t working. 
I´m using Blender 2.90.1 and Windows 10.

**Comment by Theverat** [comment]
Were you using the "samples" halt condition together with light tracing?
I have modified how the sampling statistics are shown in this case, to make it less confusing (old behaviour was to add eye + light traced samples and only show the total, but use only eye samples for halt conditions).

Can you still reproduce the problem with the latest build?
If yes, please upload a testscene that shows the problem.

**Comment by lsohele** [comment]
Thank you, Theverat. It´s working!
