### ISSUE TITLE
Session is not deleted after viewport render window resize, leading to a memory leak

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#577]
Blender/BlendLuxCore is doing something very strange:

- when I resize the view port, the current LuxCore RenderSession is stopped but not deleted.
- a new session is created after the view port resize and the new rendering is started;
- when you switch back to wire frame view port rendering, all pending RenderSession(s) will be deleted (and a crash will occur).

In theory this may even work but: every pending RenderSession will keep a full copy of the scene in ram. You can just keep resizing the view port and the memory usage will increase and increase

From: https://forums.luxcorerender.org/viewtopic.php?f=4&t=2309&p=25206#p25205

**Comment by Theverat** [comment]
It looks like this bug is present since the port to Blender 2.80.
Not sure wether it's a bug in Blender or in the addon, needs investigation.

**Comment by Theverat** [comment]
Happens with:
* Blender 2.83 and Lux v2.5
* Blender 2.90 and Lux v2.5
* Blender 2.90 and Lux v2.3
* Blender 2.90 and Lux v2.2
* Blender 2.92 alpha and Lux v2.5

**Comment by Dade916** [comment]
I should have found a fix for the Optix crash related to this problem.

**Comment by Theverat** [comment]
It's actually kind of cool how these two bugs uncovered each other.

**Comment by Theverat** [comment]
I am still investigating this problem, unfortunately I haven't found out much more so far.
Re-exporting everything and starting a completely new render session works around the problem, but would obviously be very expensive in complex scenes, so it would be the very last resort.

**Comment by Theverat** [comment]
Since I could not find the cause of the memory leak, I implemented the workaround of re-exporting the scene.
