### ISSUE TITLE
Full Blender crash with any AOV except the Caustics AOV

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/BlendLuxCore#580]
.blend file:

[test_causticas_AOV.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5435860/test_causticas_AOV.zip)

 it happens with any .blend, BlendLuxCore build from 24/10/2020, Blender 2.83 and 2.90 tested

Steps to reproduce:
- Open the .blend
- Press render, all Light AOV's are enabled and Blender crash with an error message.

Error message from Blender console:

```
[LuxCore][14.239] Starting 1 OpenCL render threads
Traceback (most recent call last):
  File "/home/jgea/.config/blender/2.83/scripts/addons/BlendLuxCore/engine/base.py", line 87, in render_final
    final.render(self, depsgraph)
  File "/home/jgea/.config/blender/2.83/scripts/addons/BlendLuxCore/engine/final.py", line 48, in render
    _render_layer(engine, depsgraph, statistics, layer)
  File "/home/jgea/.config/blender/2.83/scripts/addons/BlendLuxCore/engine/final.py", line 72, in _render_layer
    engine.session.Start()
RuntimeError: OutputSwitcherPlugin supports only CAUSTIC FilmOutputs::FilmOutputType: 0
ERROR: OutputSwitcherPlugin supports only CAUSTIC FilmOutputs::FilmOutputType: 0
```

OS: Linux 
Blender version: 2.83LTS and 2.90
LuxCore version: 2.5 from 24/10/2020

**Comment by juangea** [comment]
Another user (Plasmapeppers) tested it, it seems to fail with GPU but it works with CPU, I use CUDA with a GTX1080

**Comment by jamespa16** [comment]
I also am seeing failures on OpenCL only, CPU works - but it seems that all the info AOVs (basic info, mat/obj info, shadow info, render info) work fine. Every Light Info AOV crashes except Caustic. Caustic + the others works fine as well. 

Software info
macOS 10.15.7 Catalina, Radeon VII eGPU for OpenCL
compiled on machine Blender, master branch as of right now
compiled on machine LuxCore + BlendLuxCore, master branch as well

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by juangea** [comment]
Great, I'll test it as soon as there is a new build on git :)

**Comment by Theverat** [comment]
Seems indeed fixed, testing with the scene in the first post.
