### ISSUE TITLE
if out off core enable on gpu it seems to still be enabled on cpu compute

### ISSUE THREAD

**Issue by bestman8** [LuxCoreRender/BlendLuxCore#582]
.blend file: 
any blend file even the default cube 

Steps to reproduce: swith to gpu compute enable out off core render for 1 sec (rendering might not be needed) switch to cpu compute (render stopped or still going doesn't matter) and you will notice how it renderes like out of core not like it normally does.

Screenshots or rendered images:
![afbeelding](https://user-images.githubusercontent.com/35968731/97329771-b7472500-1877-11eb-859b-0807af1205ae.png)
![afbeelding](https://user-images.githubusercontent.com/35968731/97329817-c4fcaa80-1877-11eb-9ee2-7ffa0737f5db.png)
![afbeelding](https://user-images.githubusercontent.com/35968731/97329847-ccbc4f00-1877-11eb-8203-416384f4d354.png)

Error message from Blender console:
no error message because it didn't give a error.

OS: windows 
Blender version: 2.83
LuxCore version: 2.4 and 2.5 2.5 build tried it on the build from a few days ago

**Comment by jamespa16** [comment]
I think fixing this only requires checking for CPU when out-of-core is set in export/config.py (line 291). There might be a better way to do it that is more in line with the rest of the project though, not too familiar with the code base.
