### ISSUE TITLE
The "V" value in the Constant Color noode

### ISSUE THREAD

**Issue by Dez1gner** [LuxCoreRender/BlendLuxCore#583]
The brightness value does not match

![FHdP6ZR](https://user-images.githubusercontent.com/1584761/97695529-7bdd6e00-1aa4-11eb-8d3d-dd4a3004e53c.png)

**Comment by Theverat** [comment]
It looks like you're using the HSL model for the color picker.
Use the HSV model to match the HSV value inputs.

![Capture](https://user-images.githubusercontent.com/1584761/97695502-6f591580-1aa4-11eb-8c10-a59ddeb596ed.PNG)

**Comment by Dez1gner** [comment]
Thanks.
I am sure this question will arise among users.
I suggest making a message below if the settings are HSL: "set the Color Picker Type interface to HSV mode in the interface settings"
https://i.imgur.com/YDo0AXh.png

**Comment by Theverat** [comment]
If the question comes in again, I'll consider it.
