### ISSUE TITLE
Materials from online library aren't being downloaded

### ISSUE THREAD

**Issue by Asticles** [LuxCoreRender/BlendLuxCore#585]
.blend file: 
Any

Steps to reproduce:
On an empty scene, or without an object selected, download any library material.
It will get stuck at an arbitrary %.

Screenshots or rendered images:
![librarybug](https://user-images.githubusercontent.com/25231467/98360291-d6894380-2029-11eb-8e69-ae0eb11c7a8c.jpg)

Error message from Blender console:
`Download asset
Downloading: https://luxcorerender.org/lol/material/Marble.zip
Download finished
Extracting zip to C:\Users\Usuario\LuxCoreOnlineLibrary_data\material
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\handlers\lol\timer.py", line 49, in timer_update
    utils.append_material(bpy.context, asset, d['target_object'], d['target_slot'])
  File "C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\utils\lol\utils.py", line 356, in append_material
    if len(bpy.data.objects[target_object].material_slots) == 0:
KeyError: 'bpy_prop_collection[key]: key "" not found'`

OS: Win10
Blender version: 2.83
LuxCore version: 2.4

**Comment by neo2068** [comment]
I should have fixed this in the latest version. (commit 33d3d25)
