### ISSUE TITLE
Add support for nearest neighbor sampling in the image texture node

### ISSUE THREAD

**Issue by happysmash27** [LuxCoreRender/BlendLuxCore#592]
I would like to add support for nearest neighbor sampling in LuxCoreRender, as I am tired of using the workaround of making textures way too big. It seems that to implement this properly, I would also need to add integration to BlendLuxCore. I am therefore creating an issue for it, to go along with [the LuxCoreRender](https://github.com/LuxCoreRender/LuxCore/issues/160) I have also made. I intend to fix this issue myself, first on LuxCoreRender 2.2 and Blender 2.79, and later on a newer version.

**Comment by Theverat** [comment]
Ok, once the code on the LuxCore side is done, we can get into the specifics of the addon (shouldn't be much to do).
