### ISSUE TITLE
No backfacing rendering with Translucen materials

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/BlendLuxCore#603]
No backface rendering when using Translucent material, it's key for things like Grass

.blend file: 

[translucent_not_backfacing.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5635598/translucent_not_backfacing.zip)

[Glossy_translucent_not_backfacing.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5635603/Glossy_translucent_not_backfacing.zip)

Steps to reproduce:
Just open any of the files and enable viewport render, no matter if CPU or GPU, and no matter if you enable Double Sided or not in the Glossy Transllucent

Screenshots or rendered images:
Matte Translucent
![image](https://user-images.githubusercontent.com/20524718/101001263-2f7fc500-355f-11eb-9940-26746fabc09f.png)

Glossy Translucent:
![image](https://user-images.githubusercontent.com/20524718/101001292-38709680-355f-11eb-954b-fc841cdd986c.png)

Error message from Blender console:

No erro

OS: Linux Mint
Blender version: 2.91 (I think a coworker told me that it also happens in 2.90)
LuxCore version: 2.5 latest build from 27/11/2020

**Comment by juangea** [comment]
BTW I tested with the Two Sided material, as soon as you connect a translicent material to it the back material has no effect, and it shows up as in the upper pictures.

It's like any translucent material kill the backface rendering

**Comment by juangea** [comment]
It seems to be related to this:

https://github.com/LuxCoreRender/LuxCore/issues/427

As soon as I add a world volume the backface works again:

![image](https://user-images.githubusercontent.com/20524718/101012268-1ed14e00-3563-11eb-923f-0bc1a4ece491.png)

**Comment by juangea** [comment]
BTW it does not work in a consistent way, in a production scene I had to add an internal volume node to the material for this to work, and sometimes it goes crazy and decides to not work

**Comment by Dade916** [comment]
I can not reproduce the problem but I think it was the result of this regression: https://forums.luxcorerender.org/viewtopic.php?f=4&t=2859 (fixed today).

**Comment by juangea** [comment]
Ok, will test it as soon as we have a new BlendLuxCore build ready on git, the latest one is from 7 days ago :)

**Comment by juangea** [comment]
It seems that the linux build is not compiling, or at least is not under releases

**Comment by Dade916** [comment]
The build should be now up.

**Comment by Dade916** [comment]
I assume we can close this one.

**Comment by juangea** [comment]
Yep, I tested it and it seems to be fixed 👍
