### ISSUE TITLE
Not working in Blender 2.9

### ISSUE THREAD

**Issue by monkshoodtv** [LuxCoreRender/BlendLuxCore#605]
Hope this is useful, I have looked for Luxrender but can only find Luxcorerender, which has no install capability. Also, if I try to include this BlendLuxCore in Blender2.9 it fails to install?

**Comment by Theverat** [comment]
Please provide more info. What's your OS, which error messages show up in the console, etc.?

**Comment by dave7895** [comment]
Blender 2.90 is not officially supported by any of the stable versions, so I tried if maybe the latest version works. Both v2.4 and latest could not be activated, but the 2.5beta1 did work, although it does warn that it isn't officially supported.
