### ISSUE TITLE
Real world scale UV

### ISSUE THREAD

**Issue by Nicknroll** [LuxCoreRender/BlendLuxCore#608]
It is very handy just type known map size instead of tweaking abstract scale. 
I saw a lot of requests for cycles, but since Lux is more user-friendly, hope to see it there. 

![Screenshot_3](https://user-images.githubusercontent.com/74839903/102131382-cd766800-3e5a-11eb-9ba5-06f4e2a1f898.jpg)

Thank you!
Nick

**Comment by Theverat** [comment]
Hey, sorry for not getting back to you earlier.
This feature needs to be implemented in LuxCore itself (and even there I'm not sure if the required information would be available in the texture mapping context). You could open an issue in the LuxCore tracker and describe in detail how the feature should work.

**Comment by Nicknroll** [comment]
Hi, no problem, thx for reply!
Actually i found Triplanar Mapping can be used for real world scale texturing. 
He ignores object scale only when 3D mapping node connected, so i can multiply 3d scale to real texture size.
