### ISSUE TITLE
blender 2.83 wont enable luxcore

### ISSUE THREAD

**Issue by dreamerose** [LuxCoreRender/BlendLuxCore#612]
![屏幕快照 2020-12-20 上午4 24 40](https://user-images.githubusercontent.com/76229949/102698962-4838ec00-427c-11eb-9f5f-5c77b9422cb4.png)

mac mojave 10.14.6
i have two versions of blender, 
2.91 and recently downloaded 2.83.9 version for this render engine
same when uninstall the 2.91 blender, deleted hidden files and reinstall
tried other 2.83.x versions as well

**Comment by u3dreal** [comment]
Which version of LuxCore do you use ?

**Comment by dreamerose** [comment]
> Which version of BlendLuxCore do you use ?
> Did you install into default addon dir or in a seperate script dir ?
hi,
version: BlendLuxCore-v2.4-mac64
tried both default dir and user prefs script dir, manually move file to folder, none works

default
![default](https://user-images.githubusercontent.com/76229949/102702485-42540280-429e-11eb-9be1-c7a9a6e4fc81.png)

user pref
![usr pref](https://user-images.githubusercontent.com/76229949/102702493-4c760100-429e-11eb-9ea8-656662b54184.png)

**Comment by u3dreal** [comment]
Ah the release was broken and i fixed it yesterday. There were some codesigning isues.
Get the fixed version from [here.](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.4)
