### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by rodrigotrovao** [LuxCoreRender/BlendLuxCore#613]
![image](https://user-images.githubusercontent.com/13493529/102836663-b5fa2a80-43d8-11eb-9239-9c31b6729269.png)
luxcore version 2.5 
blender 2.91
For some reason, its showing this.

**Comment by Deadwing888** [comment]
I am also having this issue.

**Comment by Dade916** [comment]
There is probably something gone wrong during the installation and you are mixing different versions of BlendLuxCore python code and LuxCore python binary (pyluxcore.pyd).
The solution is to delete the BlendLuxCore directory and re-install the addon from scratch. The directory to delete is something like ""C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\2.87\scripts\addons\BlendLuxCore".

**Comment by Theverat** [comment]
If you're still having issues with a correct installation, please post a testscene and re-open.
