### ISSUE TITLE
Can not remove or add this addon!

### ISSUE THREAD

**Issue by kamalbhainarola** [LuxCoreRender/BlendLuxCore#616]
I wanted to update to the new version so I tried to remove it from the preferences but it shows me this error
![image](https://user-images.githubusercontent.com/77237747/104126565-2b607780-5355-11eb-92ba-5adf0e915eef.png)

please help me out to remove it completely so I can add the new version.

Thank you in advance!

**Comment by foreachthing** [comment]
Try this:
1. Close Blender
2. Locate your Addon (most likely in `%appdata%\Blender Foundation\Blender\2.91\scripts\addons\`
3. Delete folder `BlendLuxCore`
4. Restart Blender

On another note: are you starting Blender as Admin? Or is your username Admin?
You got a `permission denided` in `c:\users\Admin\AppData\Blender Foundation\Blender\2.91\`.

**Comment by Theverat** [comment]
Check the installation instructions on the luxcorerender wiki.
