### ISSUE TITLE
Add support for default world volume

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#62]

**Comment by Dade916** [comment]
I'm going to add also a camera properties for assigning a volume to camera rays (while the default world volume is still the volume used when one is not specified).

**Comment by Dade916** [comment]
I added the support for new camera properties:

- scene.camera.volume => define the initial volume rays will travel in;

- scene.camera.autovolume.enable => automatically try to discover scene.camera.volume (it works like autofocus, a ray is traced in the middle of the screen and the exterior volume of the hit object is used or the default world volume otherwise).

With "scene.camera.autovolume.enable = 1" (and a well-formed scene), there should never be the need to set scene.camera.volume.

**Comment by Theverat** [comment]
Ok, cool. 
Can't say when I'll implement it, university tests are coming up.

> (and a well-formed scene)

A rare animal, only rumored to exist ;)

**Comment by Theverat** [comment]
I guess autovolume will only work if all objects, materials and volumes are already defined when the camera is being defined, correct?
This leads to some kind of circular dependency in my export code, because the camera needs to be defined when hair is defined (for tesselation). See https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/__init__.py#L52

So it seems like I'll have to do the export like this:
* define camera
* export objects/hair/materials/volumes
* define the camera again with autovolume enabled

**Comment by Dade916** [comment]
Nope, there is no need. LuxCore parse the properties for groups: https://github.com/LuxCoreRender/LuxCore/blob/cccdc0eed4219bc033deb826c741ec53233760f9/src/slg/scene/scene.cpp#L355

So the order is not important among different groups (it is only inside the same group: for instance with a material referencing another material).

Side note: autovolume is done a scene pre-processing time like autofocus (i.e. not during the parsing), during the session start.

**Comment by Theverat** [comment]
> Side note: autovolume is done a scene pre-processing time like autofocus (i.e. not during the parsing), during the session start.

Ah of course. Thanks for clearing it up.

**Comment by Theverat** [comment]
Currently trying to add the camera volume feature and I'm getting a crash in this scene:
[cam_volume_crash.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1687417/cam_volume_crash.zip)

**Comment by Dade916** [comment]
The attached scene includes 2 syntax errors:

- scale texture "140119424009736_scale" is defined before the references textures;

-  scene.camera.volume = "" and scene.camera.autovolume.enable = 0.

I can not say what was the source of the 2 problems without the .blend.

**Comment by Theverat** [comment]
I'm pretty sure it's a bug in BlendLuxCore, but still it should not crash LuxCore (should get an error message).
Maybe it's crashing somewhere in the scene parser?

**Comment by Dade916** [comment]
I assume LuxCore throws a syntax error exception, it is ignored/not caught and then the BlendLuxCore code continue like if there wasn't an exception but objects are uninitialized and/or NULL. This lead to the crash.

Just add a try/catch when you create the RenderConfig and when you Session.Start() and handle correctly the errors, it should fix the problem.

**Comment by Theverat** [comment]
Both update() and render() are enclosed in try/catch:
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/engine/__init__.py#L31

And usually they catch RuntimeErrors like "no light source in scene" etc.

**Comment by Theverat** [comment]
The crash also happens with a clear volume where no scale texture is defined.

It seems like my export code is setting a material for the camera volume:
`scene.camera.volume = "Surface_sphere_material_139728608642568"`
Maybe this triggers the crash?

[cam_volume_crash2_LuxCore.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1689187/cam_volume_crash2_LuxCore.zip)

**Comment by Dade916** [comment]
Here, the attached scene gives this error:

`RUNTIME ERROR: Camera volume is a material: Surface_sphere_material_139728608642568`

This happens because you are not "translating" volumes names (but only materials one). The volume is defined as:

```
scene.volumes.139728609050888.type = "clear"
scene.volumes.139728609050888.absorption = "Implicit-ConstFloatTexture3-b9cd0a54-ee88-4007-ab0b-2550d44e46d1"
scene.volumes.139728609050888.priority = 0
scene.volumes.139728609050888.ior = "Implicit-ConstFloatTexture-1216e47a-2737-49fa-a3ac-345f9bfdbfac"
scene.volumes.139728609050888.id = 6728256
```

So if I fix the volume name by hand from:

`scene.camera.volume = "Surface_sphere_material_139728608642568"`

to

`scene.camera.volume = "139728609050888"`

It works fine here, is it crashing for you ?

**Comment by Theverat** [comment]
I have not the slightest clue how my code puts a material as camera volume.
When I print the scene properties during export, all is correct (volume name assigned to camera volume).
Only when I export with filesaver the material is attached to the camera volume.

Here is a full export log from Blender, final render mode.
I added prints of the camera and scene properties.
The camera properties are parsed before object export because hair tesselation needs a camera, see https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/__init__.py#L54
```
exporter init
create_session
cam volume node tree: <bpy_struct, luxcore_volume_nodes("sphere_volume")>
luxcore_name: 140664011692488
active output: <bpy_struct, LuxCoreNodeVolOutput("Volume Output")>

==================================================
Camera props:
scene.camera.up = 0.40807029604911804 0.42949053645133972 0.80561560392379761
scene.camera.lookat.target = -0.53285109996795654 0.048959255218505859 1.5988845825195312
scene.camera.fieldofview = 75.190465327165526
scene.camera.clippingplane.enable = 0
scene.camera.lookat.orig = 0.022017670795321465 0.63302874565124512 1.0064460039138794
scene.camera.screenwindow = -1 1 -0.14250001311302185 0.98249998688697815
scene.camera.type = "perspective"
scene.volumes.140664011692488.absorption = 0 0 0
scene.volumes.140664011692488.emission = 0 0 0
scene.volumes.140664011692488.ior = 1.5
scene.volumes.140664011692488.type = "clear"
scene.camera.volume = "140664011692488"
scene.camera.autovolume.enable = 0
==================================================

[SDL][3.241] Volume definition: 140664011692488
[SDL][3.244] Camera type: perspective
[SDL][3.244] Camera position: Point[0.0220177, 0.633029, 1.00645]
[SDL][3.244] Camera target: Point[-0.532851, 0.0489593, 1.59888]
[SDL][3.244] Camera clipping plane disabled

==================================================
Scene props
scene.volumes.140664011692488.absorption = 0 0 0
scene.volumes.140664011692488.emission = 0 0 0
scene.volumes.140664011692488.ior = 1.5
scene.volumes.140664011692488.type = "clear"
scene.materials.Surface_sphere_material_140664011240968.volume.interior = "140664011692488"
scene.materials.Surface_sphere_material_140664011240968.kt = 1 1 1
scene.materials.Surface_sphere_material_140664011240968.kr = 1 1 1
scene.materials.Surface_sphere_material_140664011240968.type = "glass"
scene.materials.Surface_sphere_material_140664011240968.shadowcatcher.enable = 0
scene.objects.Mesh_Sphere__002_140664271257096000.material = "Surface_sphere_material_140664011240968"
scene.objects.Mesh_Sphere__002_140664271257096000.shape = "Mesh-Mesh_Sphere__002_140664271257096000"
scene.lights.__WORLD_BACKGROUND_LIGHT__.samples = -1
scene.lights.__WORLD_BACKGROUND_LIGHT__.importance = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.glossy.enable = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.specular.enable = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.gain = 1 1 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.diffuse.enable = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.dir = -0.40774756669998169 0.008580322377383709 0.91305440664291382
scene.lights.__WORLD_BACKGROUND_LIGHT__.groundalbedo = 0.5 0.5 0.5
scene.lights.__WORLD_BACKGROUND_LIGHT__.ground.enable = 0
scene.lights.__WORLD_BACKGROUND_LIGHT__.ground.color = 0.5 0.5 0.5
scene.lights.__WORLD_BACKGROUND_LIGHT__.turbidity = 2.2000000476837158
scene.lights.__WORLD_BACKGROUND_LIGHT__.type = "sky2"
==================================================

[SDL][3.247] Volume definition: 140664011692488
[SDL][3.264] Material definition: Surface_sphere_material_140664011240968
[SDL][3.267] Scene objects count: 1
[SDL][3.267] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][3.269] Configuration: 
[LuxCore][3.269]   path.pathdepth.total = 7
[LuxCore][3.269]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][3.269]   path.pathdepth.specular = 6
[LuxCore][3.269]   renderengine.type = "PATHCPU"
[LuxCore][3.269]   film.width = 1152
[LuxCore][3.269]   film.height = 648
[LuxCore][3.269]   sampler.type = "SOBOL"
[LuxCore][3.269]   film.filter.width = 1.5
[LuxCore][3.269]   renderengine.seed = 1
[LuxCore][3.269]   path.pathdepth.glossy = 5
[LuxCore][3.269]   path.pathdepth.diffuse = 5
[LuxCore][3.269]   path.forceblackbackground.enable = 0
[LuxCore][3.269]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][3.269]   film.outputs.0.filename = "image.png"
Export took 0.0s
[LuxCore][3.269] Film resolution: 1152x648
[SDL][3.272] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][3.273] Film output definition: RGB_IMAGEPIPELINE [image.png]
[LuxRays][3.273] Device 0 name: NativeThread
[LuxRays][3.273] Device 0 type: NATIVE_THREAD
[LuxRays][3.273] Device 0 compute units: 1
[LuxRays][3.273] Device 0 preferred float vector width: 4
[LuxRays][3.273] Device 0 max allocable memory: 0MBytes
[LuxRays][3.273] Device 0 max allocable memory block size: 0MBytes
[LuxRays][3.273] Preprocessing DataSet
[LuxRays][3.273] Total vertex count: 482
[LuxRays][3.273] Total triangle count: 960
[LuxRays][3.273] Preprocessing DataSet done
[LuxRays][3.296] Creating 8 intersection device(s)
[LuxRays][3.296] Allocating intersection device 0: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 1: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 2: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 3: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 4: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 5: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 6: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Allocating intersection device 7: NativeThread (Type = NATIVE_THREAD)
[LuxRays][3.296] Adding DataSet accelerator: EMBREE
[LuxRays][3.297] Total vertex count: 482
[LuxRays][3.297] Total triangle count: 960
[LuxRays][3.301] EmbreeAccel build time: 4ms
[LuxCore][3.301] Configuring 8 CPU render threads
Session created in 0.1s
[SDL][3.336] Image pipeline: film.imagepipeline
[SDL][3.336] Image pipeline step 0: NOP
[SDL][3.336] Image pipeline step 1: TONEMAP_AUTOLINEAR
[SDL][3.337] Image pipeline step 2: TONEMAP_LINEAR
Writing: /tmp/cam_volume_crash2.crash.txt
fish: Job 1, './programs/blender-2.79a-rc-linux-glibc219-x86_64/blender' durch Signal SIGSEGV (Adressbereichsfehler) beendet
```

**Comment by Theverat** [comment]
When I do not attach the volume to the sphere material, it does not crash and works like expected.

**Comment by Dade916** [comment]
If I run the debug version I get an assertion failure because you are calling RenderSession::Parse() before RenderSession::Start().

RenderSession::Parse()  can be called only between a RenderSession::BeginSceneEdit() and RenderSession::EndSceneEdit().

If you want to edit the scene before the session Start(), you have to use RenderSession.GetRenderConfig().GetScene().Parse().

**Comment by Dade916** [comment]
You can probably replace your current RenderSession::Parse() with something like:

if RenderSession::IsStarted():
  RenderSession::BeginSceneEdit()
  RenderSession::Parse()
  RenderSession::EndSceneEdit()
else
  RenderSession.GetRenderConfig().GetScene().Parse()
endif

**Comment by Theverat** [comment]
I'm using it to parse the imagepipeline: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/__init__.py#L129

`RenderSession.GetRenderConfig().GetScene().Parse()`
This does not seem to work for setting the imagepipeline.
I'll think of a different solution.
We are discovering quite the load of bugs here :)

**Comment by Theverat** [comment]
Wait a second. I thought RenderSession.Parse() was explicitely able to be called without a SceneEdit?
Because it can be used to adjust the imagepipeline during final render?

**Comment by Dade916** [comment]
Yes but it **must** called after a RenderSession::Start() and you are calling before.

**Comment by Dade916** [comment]
To recap, before a RenderSession::Start():

- call RenderConfig::Parse() or Scene::Parse();

after:

- call RenderSession::Parse() (Scene related properties require to call the Parse() between a RenderSession::BeginSceneEdit() and RenderSession::EndSceneEdit());

**Comment by Theverat** [comment]
I think you have the first one backwards:
Before a RenderSession::Parse(), call RenderSession::Start()

**Comment by Dade916** [comment]
Uh ? I wrote "it must called **after a RenderSession::Start()** and you are calling **before**", it is correct (?)

**Comment by Theverat** [comment]
Sorry, I confused Render*Config* and Render*Session*.

**Comment by Theverat** [comment]
Ok, I should have fixed the session.Parse() problem.
Now back to the volume problem.
My findings so far:
* When I define the volume in **camera export** and use it only in the **camera**, it works
* When I define the volume only in **camera export** and use it in both **camera** and **_material_**, it works
* When I define the volume in **camera export** and use it in the **camera** and then re-define the volume in **_material export_** and use it in the _**material**_, it crashes

**Comment by Theverat** [comment]
When I set the camera properties into the scene properties after step 3 of the export, it does not crash anymore (see the commit above).

**Comment by Dade916** [comment]
I understand the bug:

1) you define a scene with a camera pointing to volume "A";

2) you re-define the volume "A" (it doesn't matter if the definition is the same you are just erasing the old definition and binding "A" to a new one).

3) camera is still pointing to to the old definition of "A" (a memory area that has been freed).

4) BOOM !

Now, I need not only to update the volume references in materials but also in camera. Going to fix this.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
