### ISSUE TITLE
Sun Temperature doesn't work for Distant and Hemi type.

### ISSUE THREAD

**Issue by michelchafouin** [LuxCoreRender/BlendLuxCore#624]
.blend file:  https://pasteall.org/blend/6a6d3fb1d45d49abbac41fe4692805df

Steps to reproduce: 
- Add a sun in the scene. Set it to Distant or Hemi. Set its color mode to Temperature and change the Temperature color.
- Notice that it doesn't do anything. Only the Color affects the Distant or Hemi sun and overrides the Temperature value.

Screenshots or rendered images:
![image](https://user-images.githubusercontent.com/25534823/105316476-bf141e00-5b75-11eb-8fa0-4c16b7dc9cce.png)
![image](https://user-images.githubusercontent.com/25534823/105316580-ec60cc00-5b75-11eb-98ed-9bf8f7c9daf1.png)

Error message from Blender console: None

OS: Windows
Blender version: 2.92
LuxCore version: 2.5 beta 19/01/21 build

**Comment by Dade916** [comment]
It may be a BlendLuxCore bug because if I export the scene, the temperature property is set to "-1", not the value on the UI.

**Comment by michelchafouin** [comment]
Yes, if you look at the export/light.py, the sun light type, unlike other lights, doesn't run the function _define_brightness_and_color where temperature is set. It only uses color.

**Comment by Theverat** [comment]
Fixed in 43852c608d617afff842f9a43daaff9862777927, please test.

**Comment by michelchafouin** [comment]
Fix confirmed, thank you.
