### ISSUE TITLE
Optix on Ampere is not working / errors out 

### ISSUE THREAD

**Issue by jamespa16** [LuxCoreRender/BlendLuxCore#626]
Did some LuxCore testing with a pair of 3080s - but it seemed that enabling Optix on the latest daily ran into `OptixAccel CUDA program compilation error`. Using the Beta 1 release saw no errors but also no speedup - I expected at least some since 2x3080 have quite a few RTX cores, but it actually ended up being _slower_ by a touch. This behavior has been confirmed by another Discord user with a 3090.

Steps to reproduce: 
Get an Ampere card - difficult, admittedly
Run LuxCore's beta 1 build and daily build, observe errors
Run LuxCore's beta 1 build and compare speed on a scene with and without Optix 

OS: Windows 10, latest drivers from Nvidia
Blender version: 2.9x
LuxCore version: 2.5 Beta 1 & Daily 
Hardware i7-7820x 96GB + 2x3080 (anecdotally, 1x3090 as well)

**Comment by Dade916** [comment]
I have downloaded latest stable Blender (v2.91.2) and latest stable NVIDIA drivers (v460.39) for my RTX2070SUPER but everything seems to run fine here. Try to check the console/logs there should be some more detail about the error.

**Comment by jamespa16** [comment]
Ah right the console - forgot about that, sorry! It says `nvrtc: error: invalid value for --gpu-architecture (-arch)`, gives the traceback and then provides the error `RuntimeError: MergeSampleBuffersOCL CUDA program compilation error`.  Perhaps it is misconfigured for Ampere? 

Traceback:
  ```
File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\engine\base.py", line 124, in view_draw
    viewport.view_draw(self, context, depsgraph)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\engine\viewport.py", line 158, in view_draw
    framebuffer.update(engine.session, scene)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\draw\viewport.py", line 229, in update
    luxcore_session.GetFilm().GetOutputFloat(self._output_type, self.buffer)
```

**Comment by Dade916** [comment]
Mmm, ok: NVIDIA driver doesn't include NVIDIA RTC (Run Time Compiler) so we had to ship CUDA 10 NRTC with LuxCore however it supports only up to Turing (v7.5) architecture (specific Ampere v8.0 instructions are not supported). So I have to bound the required architecture in order to not get an error (by asking for the support for a GPU architecture the NVRTC doesn't know).

If you download the latest build (when is ready, in couple of hours), it should now work.

**Comment by jamespa16** [comment]
OK, gave it a try and it looks like it works! Thanks!
