### ISSUE TITLE
Adaptive subdivision based on individual faces instead of objects

### ISSUE THREAD

**Issue by nate-brs** [LuxCoreRender/BlendLuxCore#635]
Hi!
Would it be possible to implement an adaptive subdivision method based on the distance of each face from the camera instead of the distance between the camera and entire objects? It would save a lot of trouble (and geometry) when subdividing ground planes for example.

Thanks!

**Comment by Dade916** [comment]
It is already possible by using "simplify", see https://github.com/LuxCoreRender/LuxCore/issues/499#issuecomment-779958572

**Comment by nate-brs** [comment]
Oh awesome! We talked about it on the Discord and I thought I understood it wasn't possible
Thanks!
