### ISSUE TITLE
Light Tracing Preview doesn't work when Using GPU rendering

### ISSUE THREAD

**Issue by michaelharmonart** [LuxCoreRender/BlendLuxCore#637]
Steps to reproduce: Set Luxcore to GPU mode, with Path tracing, and Enable Light Tracing. Even with The preview light rays turned on they don't appear until render.

This is particularly strange, because if you begin rendering the "Underwater Paintings" demo scene as it is currently set up, it has light tracing enabled. If you turn light tracing off, and back on again, suddenly the light tracing is no longer previewed. This seems to be a problem with the blender addon, and not Luxcore itself, since clearly that blend file is configured in a way that it's possible, it's just that the setting gets reset or overridden or something.

OS: Kubuntu
Blender version: 2.92
LuxCore version:2.4

**Comment by Theverat** [comment]
I can't reproduce this here with the latest v2.5 build.
Can you test with v2.5, maybe it was fixed already?

**Comment by michaelharmonart** [comment]
I'll give V 2.5 a shot

**Comment by michaelharmonart** [comment]
The issue seems to be gone in BlendLuxCore v2.5beta1
thanks for all the work on luxcore everyone!
