### ISSUE TITLE
Metropolis sampling is not available in the Blender plugin with GPU path tracing

### ISSUE THREAD

**Issue by michaelharmonart** [LuxCoreRender/BlendLuxCore#638]
This is strange because when using the standalone Luxcore, you can set the engine to the OpenCL path tracer, and in the sampler dropdown, there's an option for metropolis. And it works. This should be available in the blender plugin as well.

OS: Kubuntu 20.04 
Blender version: 2.92
LuxCore version: 2.4

**Comment by Theverat** [comment]
luxcoreui is a developer tool where everything is possible, even configurations that make little sense to use in practice.
Metropolis on GPUs has been removed in the Blender addon because Dade recommended to do that, as Metropolis is problematic on GPUs.

**Comment by michaelharmonart** [comment]
Disabling features just because they don't make sense in combination with something doesn't really seem right in my opinion. Maybe you display a warning or something, but flat out hiding the feature seems detrimental. And using Metropolis light transport on the GPU is clearly helpful in certain circumstances. I got about 1.1 Million Samples per second on the CPU path tracer with Metropolis, and about 2.2 Million Samples per second with the GPU path tracer and metropolis while testing yesterday. That's over double the performance, and I noticed no problems.

Once again though, I don't know all the technical details behind this, I just would like to have it at least be an option, perhaps with a warning if used with the GPU.

**Comment by Theverat** [comment]
We put warnings in place when there is legitimate use for something but it can be problematic sometimes, and the problematic cases can't be auto-detected. But this was not one of those situations.

I tried searching around a bit on the forum for the post where Dade recommended to remove Metropolis access for GPU rendering, but I couldn't find it. 

If you absolutely want to use it, you can edit this line: https://github.com/LuxCoreRender/BlendLuxCore/blob/227a4ddc18ddac2fafd246b8406b8fa4beacb3a0/properties/config.py#L392
to the following:
```
return self.sampler
```

**Comment by Dade916** [comment]
The convergence of Metropolis on GPUs is thousands of times slower than on CPUs. As proof just try to render something hard for a path tracer (like a simple caustic) with CPU and than with GPU (and the same number of samples per pixel). The CPU version will be far better.

**Comment by michaelharmonart** [comment]
Oh interesting, I'll definitely go test that. Just for the sake of curiosity though, why is that? I'd love to understand what makes metropolis light transport hard to parallelize, or at least ineffective on GPUs with the current implementation.

**Comment by michaelharmonart** [comment]
Huh, yeah, I never would have guessed. 
Here's five minutes on just the CPU path tracing engine with metropolis sampling
![CPUPathMetropolis](https://user-images.githubusercontent.com/15620900/109170424-ff028e00-773d-11eb-99e1-0308a445eb4a.png)

And here's five minutes on the OpenCL path tracer and metropolis sampling, with the GPU and CPU
![OpenCLPathMetroplolis](https://user-images.githubusercontent.com/15620900/109170439-0164e800-773e-11eb-9d1a-1da50ef82b2b.png)

I never would have guessed, but it seems you're right. 
I'll close the issue.

As a side question: Is this a pretty universal problem for GPU based metropolis light transfer, or is it just due to how luxcore has implemented it? Is this something that could be improved in the future?

**Comment by Dade916** [comment]
Metropolis is an inherently serial algorithm. It isn't a big deal when you have 16 threads (or 32, etc.) like on most CPUs but it becomes dramatic when you have 500,000 threads like on GPUs: the difference between 1 and 16 is small while 16 and 500,000 is really huge.
