### ISSUE TITLE
luxcore OpenCL error

### ISSUE THREAD

**Issue by whitequill** [LuxCoreRender/BlendLuxCore#649]
.blend file: None needed

Steps to reproduce:
Install Blender though the snap store and choose version 2.83lts/stable on Fedora 33.
After which download LuxCore from the [Linux download](https://luxcorerender.org/download/) page and install the plugin as normal.
There are no errors during the installation or activation of the add-on.
To get the error open the render window. It will show up when you press F12 or press the render button

Screenshots or rendered images:
nothing to see here!
![Screenshot from 2021-03-14 13-43-57](https://user-images.githubusercontent.com/5000697/111078363-630dac00-84cb-11eb-822d-470d7137324b.png)

Error message from Blender console:
OpenCL driver API error (code: -1001, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/devices/ocldevice.cpp, line: 72): -1001

OS: 
Blender version: 2.83lts
LuxCore version: 2.4

If there is more info I can give let me know.

**Comment by Dade916** [comment]
You have an OpenCL ICD installed but no OpenCL platform is available (i.e. you don't have installed an OpenCL driver for your GPU).  Install a GPU driver with OpenCL support or remove the OpenCL ICD (and you will able to do CPU-only renderings).
