### ISSUE TITLE
Blender crashes when changing Tonemapper settings

### ISSUE THREAD

**Issue by AndreasReschGGL** [LuxCoreRender/BlendLuxCore#654]
OS: Windows 10
Blender version: 2.91/2.92
LuxCore version: 2.5RC1

While being in Render Preview mode, Blender crashes when you meddle with the Tonemapper in the Camera setting. Simply turning it ON and OFF again is enough. Also changing the settings of the Reinhard tone mapper will result in a crash.

**Comment by Theverat** [comment]
I can't reproduce this here.
Does it also happen after you switch the film device to CPU in the addon preferences?
What's your GPU model? Does a graphics driver update help?

**Comment by AndreasReschGGL** [comment]
I was using CPU when I reported it. But it also happens with the GPU. I use a GTX 1060 - i can try it on my other machine that uses a GTX 980 Ti later.

But this one isn't too important (for me). Usually I wouldn't meddle with the Tonemapper. Just reporting it. It doesn't keep me from using Luxcore for production like the other issues (Out of core, bump map height issue).

**Comment by Theverat** [comment]
Can you upload a simple testscene that shows the problem?

**Comment by AndreasReschGGL** [comment]
You can use the scene that I've sent you via the forum yesterday. It happens in all my scenes.

**Comment by Theverat** [comment]
I can't reproduce it with that scene, so I can't investigate it further.
Since nobody else seems to have this problem, it might be a problem specific to your PC. Maybe try if the problem still happens if you start Blender in factory-settings mode (so all other addons are disabled) - it could be another addon.

**Comment by AndreasReschGGL** [comment]
OK. I'll observe it and will eventually report any news. As I said, it's one of the less crucial bugs for me. Cheers for investigating.

**Comment by AndreasReschGGL** [comment]
I tested the issue on my other PC (Windows 10, GTX 980 Ti) and Blender also crashes when checking/unchecking the Tonemapper settings in Render Preview mode. So it's not specific to one PC.

**Comment by Theverat** [comment]
But maybe you have the same addons installed?
Can you try it with no addons loaded (start Blender from command line with `--factory-startup`, then only enable BlendLuxCore. Don't forget to disable auto-saving of user preferences to not mess up your existing addon settings).

**Comment by AndreasReschGGL** [comment]
This in my dedicated rendering PC. Luxcore is the only addon installed there.

**Comment by AndreasReschGGL** [comment]
With the latest version from an hour ago, it seems to work now.

**Comment by Theverat** [comment]
Strange. Glad it's working for you now.
