### ISSUE TITLE
When using local 3D mapping, viewport and final render do not match

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#66]
[3d_local_mapping_bug.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/1692630/3d_local_mapping_bug.blend.zip)
![scrn_2018-02-04_10-19-01](https://user-images.githubusercontent.com/1584761/35776029-12e30ac2-0995-11e8-916f-ec6125ece600.png)

**Comment by neo2068** [comment]
The difference between preview and final rendering is that in preview rendering the objects are exported as an instance with `.transformation` and in final render with applied transformation in the mesh data.
preview render:
```
scene.objects.1867928661512000.material = "1868274685128"
scene.objects.1867928661512000.shape = "Mesh-1867928661512000"
scene.objects.1867928661512000.transformation = 1 0 0 0 0 1 0 0 0 0 1 0 0 3.5761885643005371 0 1
```
final render:
```
scene.objects.Mesh_Cube__002_1867928661512000.material = "Surface_Material_1868274685128"
scene.objects.Mesh_Cube__002_1867928661512000.shape = "Mesh-Mesh_Cube__002_1867928661512000"
```

**Comment by Theverat** [comment]
Yes, I suspected the same (should have added it to the description).
I'm not sure how to fix this. Two ideas:
* We could export objects with a material with "Local" mapping always as instances, but this might mean a slight performance hit for final renders (however I did not test it - not sure how expensive instances actually are).
* Or we can maybe "bake in" a reversal of the object transformation into the 3D mapping for final renders.

**Comment by neo2068** [comment]
I think we should export all meshes with their local coordinate system, i.e. without applied transformation, and do the local to world transformation with .transformation of the shape. Are there any drawbacks with that procedure?

**Comment by Dade916** [comment]
Don't, instances should be used only for real instances. Using instances force to use MBVH instead of BVH and it is slower.
Just multiply the the texture transformation matrix for the inverse of the one used to transform vertices. It will compensate the transformation applied to vertices.

**Comment by neo2068** [comment]
Ok, thank you for the explanation.

**Comment by Theverat** [comment]
> Just multiply the the texture transformation matrix for the inverse of the one used to transform vertices. It will compensate the transformation applied to vertices.

What if two objects share the same material?

**Comment by neo2068** [comment]
I started to fix it the other day but I am not as far as that I can push it. We had a working local mapping in the old Luxrender but I don't know how it has done these days. The second approach would be more elegant.

**Comment by Dade916** [comment]
I would use:

> Or we can maybe "bake in" a reversal of the object transformation into the 3D mapping for final renders.

Until when I don't have the time to add the support local object space texturing.

**Comment by Theverat** [comment]
> Until when I don't have the time to add the support local object space texturing.

I don't really understand this sentence, I think it's missing a few words?

What about the issues I mentioned: 
* If a texture with local mapping is used on many objects, we need to create a separate copy of that material for each object, so we can apply the reverse transformation to the texture.
* In a scene with a lot of objects sharing one material, this would create a lot of materials. Possibly a problem? 

If you think that my proposal could work, I can try to implement it in LuxCore:
> Maybe LuxCore could store the original transformation matrix of the object and use it only for texture evaluation?

**Comment by neo2068** [comment]
I looked into the old luxrender code and the only difference is that it stores the object with local coordinates in the ply file and define a transformation in front of the shape definition and only one texture is exported.
During viewport rendering the procedure is the same for Luxcore but this is enabling instancing. During final rendering Luxcore performs a local2global transformation before ply export and use no object transformation. That's the reason why it doesn't work. Is it possible to store the local2global transformation inside the object data to use it in the texture hitpoint evaluation?

**Comment by neo2068** [comment]
The old Luxrender stored the mesh in local coordinates and used a transformation in front of the shape definition but in Luxcore this enables instancing. 
As Simon said, I think we should store the local2global transformation in the object data to use it during texture hitpoint evaluation.

**Comment by Dade916** [comment]
If you want write the solution to this problem, sure, go on.

**Comment by Theverat** [comment]
I have pushed a fix on a branch: https://github.com/LuxCoreRender/LuxCore/commit/eb54c5d0b165be76992c58709f93aabff742a95e
So far I have done only the C++ code, I'll do the OpenCL part if you approve.

I had to introduce a new Transform member to the HitPoint structure, I hope this is OK.

The way I have done it is that ExtTriangleMesh now keeps track of all transformations applied to it, and uses them for LocalMapping3D::Map().
This behaviour fits my needs perfectly, but you have to say if this is OK or not.
Maybe for other applications it would be better to have an explicit object property?

**Comment by neo2068** [comment]
Hi!
You are faster than me. It looks ok for me. I would have done it in a similar way. Let's wait what David has to say to the fix. Is the worse memory footprint of the hitpoint structure due to the transform significant? Should we find another solution?

**Comment by Dade916** [comment]
I see at least 2 problems:

1) OpenCL stores 2 HitPoint structures for each thread. So adding an additional Transformation uses 2x2x4x4xsizeof(float) = 256 bytes. Multiplied for 500,000 threads is an noticeable increase of memory foot print. On some old GPU, memory allocation will simply fail because there is a limit in the max. size of a single block of referenced memory (for instance the AMD 5870 has a max. of 256Mbytes, I don't remember the HD7970 limit but there is still one).

2) There is also the problem that now particles (i.e. high number of triangle mesh objects) will use a lot more memory.

While I don't see how to fix 2, 1 is avoidable. Just do not touch the HitPoint structure, there is already the localToWorld Transformation and it is all you need: in LocalMapping3D::Map() you transform HitPoint.p from absolute coordinate back to local using Inverse(HitPoint.localToWorld) and you can than apply LocalMapping3D transformation.

In BSDF::Init(), you don't need "mesh->GetUnappliedLocal2World()" but just to implement mesh->GetLocal2World()" for normal mesh to return your "unappliedTrans".

I would also rename unappliedTrans in worldToLocal or localToWord (or appliedTrans because it is exactly what it is).

**Comment by Theverat** [comment]
Thanks for the review.

> While I don't see how to fix 2, 1 is avoidable. Just do not touch the HitPoint structure, there is already the localToWorld Transformation and it is all you need: in LocalMapping3D::Map() you transform HitPoint.p from absolute coordinate back to local using Inverse(HitPoint.localToWorld) and you can than apply LocalMapping3D transformation.

This is how I implemented it first, in this small patch:
https://gist.github.com/Theverat/5cafa9152ed66f2de98eacafc8c7ff4e
However I thought it would be bad to "abuse" the local2world and write wrong information to it.
But if you say it's ok, I will add a comment that in the case of ExtTriangleMesh the local2world is not the identity matrix.

> I would also rename unappliedTrans in worldToLocal or localToWord (or appliedTrans because it is exactly what it is).

Yes I also realized that the name is bad.

**Comment by Theverat** [comment]
I'm stuck on the OpenCL part.
I tried the following: [compilegeometry.cpp#L175](https://github.com/LuxCoreRender/LuxCore/blob/843e7b557a1d781ebfa580b2ecf6624fb4dcc5f8/src/slg/engines/pathoclbase/compilegeometry.cpp#L175)
```cpp
// Previously this was just the identity matrix
Transform t;
mesh->GetLocal2World(0.f, t);
memcpy(&currentMeshDesc.trans.m, &t.m, sizeof(float[4][4]));
memcpy(&currentMeshDesc.trans.mInv, &t.mInv, sizeof(float[4][4]));
```
The local mapping is correct if I do this, but the lighting is affected (the mesh has wrong self-shadowing etc.).
I guess that the `mesh.trans` matrix is used for shading as well?
How should we handle this?
* Add an extra transformation -> memory cost
* Add a flag that the transformation matrix should only be used for local mapping, not for lighting -> performance cost
* Something else?

**Comment by Dade916** [comment]
I should have fixed the problem here: https://github.com/LuxCoreRender/LuxCore/commit/5d1d109fccd1eeabd9efa3ee9d034d7720c69c0e

**Comment by Dade916** [comment]
I added the support for Scene::SetMeshAppliedTransformation() to LuxCore API: https://github.com/LuxCoreRender/LuxCore/commit/69bcd7d5dafafb0c976cf952acdb989bd7c6296d

It has to be used for strands and particles (i.e. DuplicatedObjects()).

**Comment by Theverat** [comment]
Thanks Dade.

**Comment by neo2068** [comment]
Thank you both for the fix.
