### ISSUE TITLE
Denoiser is not working

### ISSUE THREAD

**Issue by johndow16** [LuxCoreRender/BlendLuxCore#662]
Hello, 

For some reason denoiser (OIDN) is not working during the final render, but it does work in the viewport.  See pics below:

![luxcore_01a](https://user-images.githubusercontent.com/75545135/113542071-2590d000-95ec-11eb-9944-305abd220452.jpg)
![luxcore_01b](https://user-images.githubusercontent.com/75545135/113542079-288bc080-95ec-11eb-9607-532cf7dff4af.jpg)

Windows 10 x64 (2004 19041.867)
Blender 2.92
BlendLuxCore v2.5RC1
GTX1660 (465.89)

**Comment by juangea** [comment]
Are you looking at the DENOISED render pass? 
In final render the denoised version is not in the main pass, it’s an additional render pass.

**Comment by johndow16** [comment]
I didn't know about that. I was looking at the combined render pass.  IMHO: Denoised should be the main pass if denoiser enabled.

**Comment by mroy-mmc** [comment]
You need to go to the compsotior and connect the DENOISED link to the output node's image input 

![comp](https://user-images.githubusercontent.com/81921384/113591812-fda86900-95f9-11eb-8ffe-247ba9771c76.png)

**Comment by Theverat** [comment]
>IMHO: Denoised should be the main pass if denoiser enabled.

This is planned since a while: #364 
But I didn't get around to it yet. It would also break compatibility with old scenes and we'd need a solution for that.
