### ISSUE TITLE
Viewports Shandings

### ISSUE THREAD

**Issue by aboim2** [LuxCoreRender/BlendLuxCore#665]
I can't switch to rendered view in Layout and Modeling viewport mode.
Blender crashes!

Is it a bug? 

sys info:
  Model Name:	iMac
  Model Identifier:	iMac18,3
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  System Firmware Version:	429.80.1.0.0
  SMC Version (system):	2.41f2

**Comment by Theverat** [comment]
Please upload a simplified testscene that shows the problem.
