### ISSUE TITLE
Luxcore 2.5 

### ISSUE THREAD

**Issue by Dez1gner** [LuxCoreRender/BlendLuxCore#688]
Steps to reproduce:
Trying to activate in the addon list

Error message from Blender console:
https://i.imgur.com/i4fAqd2.png

OS: Linux
Blender version: 293 LTS
LuxCore version: 25

**Comment by Dade916** [comment]
It is expected, Blender v2.93 uses a newer Python version so LuxCore v2.5 works only up to Blender v2.92. You need to use a daily LuxCore v2.6 build if you want to use the latest Blender.

**Comment by Dez1gner** [comment]
ok. thx
