### ISSUE TITLE
Error when trying to install BlendLuxCore 2.6 devel on Blender 2.93 release (Linux)

### ISSUE THREAD

**Issue by Fuzzillogic** [LuxCoreRender/BlendLuxCore#690]
Steps to reproduce:

1. Grab official Linux .tar.xz Blender 2.93 from blender.org.
2. Unpack and run.
3. Grab [latest BlendLuxCore release](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)  (currently using commit [d239f15](https://github.com/LuxCoreRender/BlendLuxCore/commit/d239f15176db4908d5cc76a3fd025b47f9dd1740))
4. In Blender, install BlendLuxCore add-on.
5. Upon enabling BlendLuxCore, installation fails with error message.

Error message from Blender console:

```
Traceback (most recent call last):
  File "/home/user/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.93/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: libtbb.so.2: cannot open shared object file: No such file or directory
```

OS: Kubuntu 21.04
Blender version: 2.93 release
LuxCore version: 2.6 devel

[Edit] Of course, the second I hit the submit button, I thought of looking if the missing library is in the default Ubuntu repository. And indeed: installing libtbb2 solved it, i.e. `sudo apt install libtbb2`. So, the "fix" is to document this dependency/requirement.

**Comment by Dade916** [comment]
Thanks, I have added libtbb.so.2 to the list of files to include in Linux BlendLuxCore release.
