### ISSUE TITLE
Regression: New material not applied during viewport render in Blender 2.93

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#693]
Steps to reproduce:

* Open Blender 2.93
* Create a cube
* Start a viewport render
* Go to the material properties and create a new material. This material will not be visible on the cube for the rest of the viewport render session, it will stay the default grey matte. Only after a restart of the viewport render, it will be used.

This bug does not happen in 2.92 (with the exact same addon code). I suspect something in the depsgraph update report changed, but there's nothing about it in the Blender Python API release notes.

**Comment by frank040057** [comment]
open blender 2.93.0,apply a new material to default cube(with a texture),start viewport rendering,then change the uv mapping,viewport rendering automatically upadtes,but if i shift+d duplicate the cube,any changes to the cube will no longer automatically upadate in viewport rendering.i tried alt+d duplicate,everything works fine.that is what i found.
