### ISSUE TITLE
wrong Filename in standalone-Version

### ISSUE THREAD

**Issue by 0xfadead** [LuxCoreRender/BlendLuxCore#698]
Hello,

in the standalone version of Luxcore 2.5 is a File called "**pyluxcore.pyd**"
but it has to be called "**pyluxcore.py**" otherwise you can't load any scene.

**Comment by Dade916** [comment]
Nope, "pyluxcore.pyd" is the correct name for a binary python library (https://docs.python.org/3/faq/windows.html#is-a-pyd-file-the-same-as-a-dll). ".py" are Python source text files.

What OS are you using ?

**Comment by ProjektOpensource** [comment]
Hello,

I'm using Windows. When I opened the standalone Version I couldn't load any file in there (I could click on the load button but in the explorer there were no filetypes to choose from) and when I changed the name to "pyluxcoretools.py" it worked.

PS: Sorry for the late reply.

-------- Original-Nachricht --------
