### ISSUE TITLE
Unable to activate Luxcore 2.5 on Blender2.93.0

### ISSUE THREAD

**Issue by samiulislamsharan** [LuxCoreRender/BlendLuxCore#699]
This error appears while activating the addon and I've installed all the prerequisites.
![Screenshot (519)](https://user-images.githubusercontent.com/57093421/121966420-6fd2c200-cd90-11eb-9c09-2608cb828420.png)

**Comment by Dade916** [comment]
Blender v2.93 uses a newer Python version. You can use LuxCoreRender v2.5 up to Blender v2.92 or the under development v2.6 with Blender v2.93: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736
