### ISSUE TITLE
Complete Material Export

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#7]

**Comment by Theverat** [comment]
Do I see it right that we now have all materials supported?
Can we close this issue?

**Comment by neo2068** [comment]
Yes, the materials should be complete. We have to check the carpaint material because the render in full_export.blend looks different compared to old Luxrender.

**Comment by Theverat** [comment]
Is it using a preset or custom settings? 
Because I changed the defaults of the custom settings a bit I think.
