### ISSUE TITLE
LuxCore Texture Node is missing

### ISSUE THREAD

**Issue by sandyadr** [LuxCoreRender/BlendLuxCore#703]
I don't know if this bug or not, but on the latest build since Image Resize Policy is added, the LuxCore Texture Node Editor is gone, and when I tried to add texture nodes to the light, it throws an error.

I'm using the latest windows build on win 10 with Blender 2.93.0.
![image](https://user-images.githubusercontent.com/33363676/122770386-96808380-d2cf-11eb-8d8d-4e4bc560a7d0.png)
![image](https://user-images.githubusercontent.com/33363676/122770440-a4ce9f80-d2cf-11eb-8df7-6a00d1413f3b.png)

Thanks!

**Comment by sandyadr** [comment]
oh, so it's really a bug then @Theverat , I hope it will get fixed soon,

and BTW, I think I found another bug, in display render preview mode, if I connect/disconnect something to the colour socket on emission node, Blender suddenly crashed, this doesn't happen in the stable release (2.5) on Blender 2.92.

Should I open another issue? or is there already someone else reporting it?

Thx.

**Comment by Theverat** [comment]
Please open a separate issue for that.

**Comment by sandyadr** [comment]
will do! thx

**Comment by sandyadr** [comment]
Hello, is there any planned fix for this bug?
