### ISSUE TITLE
LuxCoreRender v2.6 for Blender 2.93 - Cannot select/press buttons or spoilers of Blender UI when rendering

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/BlendLuxCore#706]
Steps to reproduce:
open project hit render and when rendering is run i cant do nothing in Blender UI

OS: win 10 x64
Blender version: 2.93 official
LuxCore version: latest build

**Comment by Theverat** [comment]
Do you have Blender's "lock UI" feature enabled?

**Comment by odil24** [comment]
> Do you have Blender's "lock UI" feature enabled?

No. But it freezes anyway

**Comment by Theverat** [comment]
Please post a testscene.
