### ISSUE TITLE
Add support for "nearest" image map filtering

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#709]
See https://forums.luxcorerender.org/viewtopic.php?f=5&p=31330#p31330
Should only require very small changes to nodes/textures/imagemap.py

**Comment by Theverat** [comment]
When done with this, also close #592.

**Comment by DEBIHOOD** [comment]
Without knowing almost anything about writing code with python, and don't knowing anything on how to write python code for blender, this defenitely was quite fun experience :)
It was fun to look at code, try to understand what it does, and then writing my own lines of code and look how it will response.
One thing that i can't understand is why i need to restart viewport to see the changes, changing other parameters doesn't require to restart viewport.
