### ISSUE TITLE
Cannot Enable Pixel Filtering with "Path" Engine

### ISSUE THREAD

**Issue by rrubberr** [LuxCoreRender/BlendLuxCore#713]
While pixel filtering works as expected with the "Bidir" engine selected, I am unable to enable it with "Path" selected. This remains true no matter which pixel filter is selected (Gaussian, Sinc, etc.) and is true for both GPU and CPU rendering, and is not sampler-dependent. No caches are enabled, and the denoiser is disabled, leading me to believe this is a bug rather than the intended behavior. 

The screenshot below shows my render settings, as well as the rendered image, which clearly does not have pixel filtering applied. A lack of pixel filtering support with the "Path" engine makes it difficult to render an image without use of the denoiser.

I am unable to tell if pixel filtering works with the "Path" engine in LuxCoreUI as scaling issues with a 4K display make it difficult to discern. I am using Blender 2.93.1 and BlendLuxCore 2.6 alpha 0, however this behavior is repeatable using 2.90 and BlendLuxCore 2.5 as well.

![Screenshot from 2021-07-23 08-02-05](https://user-images.githubusercontent.com/11138056/126801419-65ac3ca0-9efe-4f35-87f6-4e77a6a1f1cc.png)

**Comment by Dade916** [comment]
BiDir and Path uses 2 very different kinds of pixel filtering (Path one is a lot faster but not possible to use with BiDir/Light tracing). However, on the long run, they produce similar (good) results.

Select Path tracing and try to render a classic checkered large plane (the one producing a very visible morie effect) with different pixel filters (including none). You will see as Path tracing pixel filtering works fine.

If you use a  (very) large filter widths, you will see also as the image starts to loose focus/be blurred.

Note: you can use image mode view with LuxCoreUI to not have the image scaled to fit the window.

**Comment by rrubberr** [comment]
This is interesting. After running a few renders on a test scene I threw together with old assets, it is apparent that filtering is being applied. The behavior of filtering with Bidirectional is in line with what I expected using Gaussian, however path appears much sharper in all cases.

![filtercompare](https://user-images.githubusercontent.com/11138056/126827178-c7da7f91-b51c-4f20-8dec-f04463c51afc.jpg)

The issue I am experiencing is specifically with high sample counts, like in the scene below. Here, individual pixels do not appear to be filtered, however in better resolved areas the filtering is visible. You can see there are over 2,000 samples per pixel. I am using Gaussian with width=4.

![Screenshot from 2021-07-23 11-29-52](https://user-images.githubusercontent.com/11138056/126826065-4d3ebd7f-ffe3-41d7-9272-3cd701e0ea24.png)

From your explanation it seems that the solution is to use Bidir for this scene. You mentioned that Path uses faster pixel filtering, would it be possible to allow users to toggle between the faster and slower methods to overcome issues like I am experiencing?

**Comment by Dade916** [comment]
Path pixel filter has noise at the start while BiDir pixel filter is blurred at the start but they both converge to the same solution on  the long run. A sample with Path filter affects only one pixel while BiDir filter affects many (up to 16 with a 4 width filter): this is the reason why path filtering is a lot faster.

I'm not sure to understand the problem with this specific rendering: I just see a bit of noise here and there, Why do you think BiDir pixel filtering would be better ? And where ?

**Comment by rrubberr** [comment]
![compare](https://user-images.githubusercontent.com/11138056/126943914-00dd29c1-1d1b-4e54-9332-c1c4e3a32979.jpg)

In certain areas of the scene, like on the surface of the apples and behind the whisky bottle, path's pixel filtering is a clear disadvantage, while in other areas the difference is smaller. Overall, manipulating other settings like the sampler seems to have a greater effect on image quality. I will mark the question as closed.
