### ISSUE TITLE
How to make this kind of Velvet shadet?

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/BlendLuxCore#719]
I'm so confused and so tired from how on make this kind of Velvet shader like really easy in Corona render for Max or for C4D? Here for an example of english sofa:
https://zeelproject.com/ru/25040-modern-sofa-set.html

@Dade916 
@Theverat 
@u3dreal 
@BeheadedKamikaze 
@Alpistinho 
@acasta69

**Comment by DionXein** [comment]
Maybe you should use Velvet shader? Shift + A in material editor > Material > Velvet

**Comment by u3dreal** [comment]
PLZ head over to the forum for such kind of questions. This is for issues only.
