### ISSUE TITLE
Internal OpenImageDenoise Utterly Broken...?

### ISSUE THREAD

**Issue by chromosthete** [LuxCoreRender/BlendLuxCore#721]
I know I am supposed to include the blend file and steps and stuff, but this happens to any file I use and there aren't any steps I take. The console also shows no errors.
Here's a screenshot:
<img width="1153" alt="Screen Shot 2021-08-07 at 12 22 17 AM" src="https://user-images.githubusercontent.com/43423221/128592225-84544013-b1d5-4ba1-95b8-609e2694746c.png">

This is the denoised pass of the render, it happens on every render so I usually just resort to using the compositor denoise node. I am not entirely sure what to do because I have found no one else with this weird glitch and I'm not very savvy when it comes to fixing this kind of thing.

Note: A clean install did not seem to help.

OS: macOS Big Sur 11.3.1
Blender version: 2.92
LuxCore version: 2.5

**Comment by rrubberr** [comment]
I had this same issue under Big Sur 11.3 on a system with an i7-1068NG7, but do not have this issue with a different machine running Big Sur 11.3 with an i7-9980HK. I was unable to use OIDN entirely on the 1068NG7 system with any version of LuxCore. I was not able to replicate this issue on the “older” hardware. What system are you using?

**Comment by odil24** [comment]
@rrubberr @chromosthete Can are you try this builds with 2.93 also?
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-mac64.zip

**Comment by chromosthete** [comment]
It seems the issue is not present in 2.93. Kinda frustrating considering some plugins don't support it but that's ok. Closing the issue.
