### ISSUE TITLE
Can't Install Luxcore on Blender 

### ISSUE THREAD

**Issue by FroyoFire** [LuxCoreRender/BlendLuxCore#724]
Screenshots or rendered images:
![messageImage_1629865686535](https://user-images.githubusercontent.com/89502861/130726790-02be0972-ea11-436f-9e56-03457f7d6c1b.jpg)

Error message from Blender console:

OS:  Windows 10
Blender version: 2.93.3
LuxCore version: 2.5

i have install the c++ package but it still don't work

**Comment by Dade916** [comment]
LuxCore v2.5 is compatible up to Blender v2.92. You need to use under development v2.6 for Blender v2.93: https://luxcorerender.org/download/
