### ISSUE TITLE
Denoising Not Working In Final Render

### ISSUE THREAD

**Issue by KrytiN** [LuxCoreRender/BlendLuxCore#732]
Denoising doesn't appear to be working on the final rendered image, but works in the preview.

**Comment by KrytiN** [comment]
Is there a setting that I am missing or is there something that is actually broken?

**Comment by DionXein** [comment]
![Deniser](https://user-images.githubusercontent.com/75082591/139583877-6a1876e5-59d9-47fa-a501-c08ff839e392.jpg)
Make sure you enable Denoiser

**Comment by KrytiN** [comment]
> ![Deniser](https://user-images.githubusercontent.com/75082591/139583877-6a1876e5-59d9-47fa-a501-c08ff839e392.jpg) Make sure you enable Denoiser

Ohhhhh okay. I actually found out I could also do it through the compositor as well last night, but thank you for showing for showing me this as well!
