### ISSUE TITLE
Blendluxcore has (probably) un-necessary dependency on cycles renderer.

### ISSUE THREAD

**Issue by Deadwing888** [LuxCoreRender/BlendLuxCore#733]
**Steps to reproduce:**
If one uninstalls cycles renderer and tries to use LuxCore, Luxcore will spit out the following error: "Object has no attribute 'cycles_visibility'"

If cycles is re-installed this error will go away.

Error message from Blender console:
"Object has no attribute 'cycles_visibility'"

OS: Windows 10
Blender version: 2.92
LuxCore version: 2.5

**Comment by Theverat** [comment]
I consider this a very very niche use case.
You are welcome to submit a pull request with changes to surround all access to Cycles properties with `hasattr(path, "propertyname")` checks though.

**Comment by useranty** [comment]
I have the same bug but with the latest  blendeluxrcore and blender 3.0 on debian 11 64 bit
![image](https://user-images.githubusercontent.com/62706434/145036099-3d566455-174f-4462-a34c-d9937cdfd232.png)

**Comment by Theverat** [comment]
Why do you disable the cycles addon?

**Comment by marcatec** [comment]
I have the same issue, but never disabled cycles.
Latest BlendLuxCore from Dec. 5th on Manjaro 64 bit.

**Comment by useranty** [comment]
I don't disabled cycles, it was a new blender and blenderluxcore

**Comment by tolozine** [comment]
the same issue，and enable cycles

**Comment by marcatec** [comment]
With the latest release form today it works under Blender 3.0.
Thanks.

**Comment by Deadwing888** [comment]
Good stuff guys :)
