### ISSUE TITLE
Unable to install in 3.0

### ISSUE THREAD

**Issue by atticus-lv** [LuxCoreRender/BlendLuxCore#735]
.blend file: 

Steps to reproduce:

Screenshots or rendered images:
![image](https://user-images.githubusercontent.com/64118610/143407735-7e783049-799e-49dd-9de4-15339e67e1dd.png)

Error message from Blender console:

OS: 
Blender version:
latest 3.0 build
LuxCore version:
latest build

**Comment by matsbtegner** [comment]
Same result with Blender 3.0.0 Stable:
blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release

**Comment by neo2068** [comment]
It should work with the latest release.
