### ISSUE TITLE
Apple Silicon M1 computers not supported?

### ISSUE THREAD

**Issue by brainstorm** [LuxCoreRender/BlendLuxCore#736]
When clicking the checkbox to enable the plugin, the following traceback pops up:

![Screen Shot 2021-11-29 at 10 34 28 pm](https://user-images.githubusercontent.com/175587/143861402-42aaaabd-1a86-4ed8-ab2f-ed38a2577cf6.png)

OS: 
OSX Monterey 12.0.1
Blender version: 2.93.5
LuxCore version: Latest from today

**Comment by Theverat** [comment]
Indeed, we don't provide builds for M1 yet.
You can start Blender in "intel mode" to run the addon.

**Comment by brainstorm** [comment]
Thanks, I'll come back to this when ARM64 builds are shipped then, not interested in switching to intel roseta2 emulation, not urgent (to me).
