### ISSUE TITLE
Crash when trying to render using BlendLuxCore in Blender 3.0

### ISSUE THREAD

**Issue by helsharif** [LuxCoreRender/BlendLuxCore#739]
Hello,
Upon installing BlendLuxCore (latest build) into Blender 3.0, Blender crashes instantly when trying to render anything. I also tried downloading an example LuxCore scene and Blender 3.0 crashes instantly when I try to render it.

.blend file: 
https://github.com/LuxCoreRender/LuxCoreTestScenes/releases/download/v2.3/UnderwaterPaintings.zip

Steps to reproduce:
Installed latest build (experimental) of BlendLuxCore to latest stable release of Blender 3.0 (https://www.blender.org/download/release/Blender3.0/blender-3.0.0-windows-x64.msi/)

Downloaded UnderwaterPaintings example screen.
Opened example scene in Blender, pressed Render.
Blender 3.0 instantly crashed

Error message from Blender console:

OS: Windows 11 64-bit
Blender version: 3.0 (stable release: https://www.blender.org/download/release/Blender3.0/blender-3.0.0-windows-x64.msi/ )
LuxCore version: latest build available on Github (https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip)

**Comment by Derny1** [comment]
me too

**Comment by SlincHD** [comment]
yea saeme only on win 10

**Comment by odil24** [comment]
Me too  like other have. Here my log:
`# Blender 3.0.0, Commit date: 2021-12-02 18:35, Hash f1cca3055776

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FFBEB3CFA8A
Exception Module      : python39.dll
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000008


Stack trace:
python39.dll        :0x00007FFBEB3CFA80  PyDict_GetItemWithError
_multiarray_umath.cp39-win_amd64.pyd:0x00007FFBEA81F363  Symbols not available


Loaded Modules :
0x00007FF731AB0000 3.0.0.0              blender.exe D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\blender.pdb 
0x00007FFC2F590000 10.0.19041.1288      ntdll.dll  
0x00007FFC2E3C0000 10.0.19041.1348      KERNEL32.DLL  
0x00007FFC2CD30000 10.0.19041.1348      KERNELBASE.dll  
0x00007FFC2DDB0000 10.0.19041.1202      USER32.dll  
0x00007FFC2D3F0000 10.0.19041.1320      win32u.dll  
0x00007FFC0C8F0000                      tbbmalloc.dll  
0x00007FFC0C8A0000                      tbb.dll  
0x00007FFC2D5E0000 10.0.19041.1202      GDI32.dll  
0x00007FFC2D2E0000 10.0.19041.1110      gdi32full.dll  
0x00007FFC2D0B0000 10.0.19041.789       msvcp_win.dll  
0x00007FFC2D150000 10.0.19041.789       ucrtbase.dll  
0x00007FFC2E480000 10.0.19041.1320      SHELL32.dll  
0x00007FFC1FB50000 14.28.29910.0        VCRUNTIME140.dll  
0x00007FFC2CCE0000 10.0.19041.1151      CFGMGR32.dll  
0x00007FFC2E340000 10.0.19041.546       WS2_32.dll  
0x00007FFC0BE10000 14.28.29910.0        MSVCP140.dll  
0x00007FFC2D610000 10.0.19041.1288      RPCRT4.dll  
0x00007FFC2DC80000 10.0.19041.1052      ADVAPI32.dll  
0x00007FFC2DB60000 7.0.19041.546        msvcrt.dll  
0x00007FFBF6E70000 8.0.1.0              openvdb.dll  
0x00007FFC2E2A0000 10.0.19041.906       sechost.dll  
0x00007FFC2DF60000 10.0.19041.1202      ole32.dll  
0x00007FFC02E30000 10.0.19041.1081      OPENGL32.dll  
0x00007FFC2D740000 10.0.19041.1348      combase.dll  
0x00007FFC2EEE0000 10.0.19041.546       PSAPI.DLL  
0x00007FFC2DD30000 10.0.19041.1023      SHLWAPI.dll  
0x00007FFBEAAA0000 58.76.100.0          avformat-58.dll  
0x00007FFBE6870000 58.134.100.0         avcodec-58.dll  
0x00007FFC2EBC0000 10.0.19041.1320      shcore.dll  
0x00007FFC2EEF0000 10.0.19041.546       IMM32.dll  
0x00007FFC15300000 58.13.100.0          avdevice-58.dll  
0x00007FFBEB290000 3.9.7150.1013        python39.dll  
0x00007FFC2E170000 10.0.19041.985       OLEAUT32.dll  
0x00007FFBEAFC0000 56.70.100.0          avutil-56.dll  
0x00007FFC0BD70000 5.9.100.0            swscale-5.dll  
0x0000000070440000 1.0.28.0             libsndfile-1.dll  
0x00007FFBF9B60000 1.20.1.0             OpenAL32.dll  
0x00007FFBF9180000 2.0.12.0             SDL2.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FFC28850000                      tbbmalloc_proxy.dll  
0x00007FFC2EF20000 10.0.19041.1237      SETUPAPI.dll  
0x00007FFC27690000 14.28.29910.0        VCRUNTIME140_1.dll  
0x00007FFC16E20000 6.10.19041.1110      COMCTL32.dll  
0x00007FFC28190000 10.0.19041.546       VERSION.dll  
0x00007FFC0BD40000 10.0.19041.1         AVIFIL32.dll  
0x00007FFC0BCC0000 10.0.19041.1081      GLU32.dll  
0x00007FFC14430000 10.0.19041.867       dbghelp.dll  
0x00007FFC0E4C0000 10.0.19041.546       Secur32.dll  
0x00007FFC04180000 3.9.100.0            swresample-3.dll  
0x00007FFC0C520000 10.0.19041.1         AVICAP32.dll  
0x0000000070680000                      libfftw3-3.dll  
0x00007FFC2CCB0000 10.0.19041.1023      bcrypt.dll  
0x00007FFC23ED0000 10.0.19041.546       WINMM.dll  
0x00007FFC0F020000 10.0.19041.1         MSACM32.dll  
0x00007FFC02E00000 10.0.19041.1         MSVFW32.dll  
0x00007FFC181D0000 10.0.19041.1         winmmbase.dll  
0x00007FFC2CB70000 10.0.19041.1266      SSPICLI.DLL  
0x00007FFC2ADB0000 10.0.19041.546       kernel.appcore.dll  
0x00007FFC2ADD0000 10.0.19041.1320      windows.storage.dll  
0x00007FFC2C690000 10.0.19041.1320      Wldp.dll  
0x00007FFC2A6D0000 10.0.19041.1266      uxtheme.dll  
0x0000014CAA0F0000 10.0.19041.1348      bcryptPrimitives.dll  
0x00007FFC2CBF0000 10.0.19041.844       profapi.dll  
0x00007FFC2EC70000 2001.12.10941.16384  clbcatq.dll  
0x00007FFC256F0000 10.0.19041.1023      MMDevApi.dll  
0x00007FFC2CA50000 10.0.19041.1151      DEVOBJ.dll  
0x00007FFC0ECB0000 10.0.19041.1023      AUDIOSES.DLL  
0x00007FFC2C750000 10.0.19041.546       powrprof.dll  
0x00007FFC2C730000                      UMPDC.dll  
0x00007FFC2EDC0000 10.0.19041.1202      MSCTF.dll  
0x00007FFC26A30000 10.0.19041.1288      AppXDeploymentClient.dll  
0x00007FFBE3D50000 30.0.14.7168         nvoglv64.dll  
0x00007FFC28B30000 10.0.19041.546       WTSAPI32.dll  
0x00007FFC2C890000 10.0.19041.546       msasn1.dll  
0x00007FFC275C0000 10.0.19041.906       cryptnet.dll  
0x00007FFC2D420000 10.0.19041.1320      CRYPT32.dll  
0x00007FFC24900000 10.0.19041.1320      drvstore.dll  
0x00007FFC2C5A0000 10.0.19041.546       cryptbase.dll  
0x00007FFC2D580000 10.0.19041.1266      WINTRUST.dll  
0x00007FFC2B9A0000 10.0.19041.546       ntmarta.dll  
0x00007FFC25EF0000 10.0.19041.546       dxcore.dll  
0x00007FFC2A910000 10.0.19041.746       dwmapi.dll  
0x00007FFC2C5E0000 10.0.19041.546       WINSTA.dll  
0x00007FFC0D180000 10.0.19041.1151      dataexchange.dll  
0x00007FFC29920000 10.0.19041.1266      dcomp.dll  
0x00007FFC290F0000 10.0.19041.1202      d3d11.dll  
0x00007FFC2B790000 10.0.19041.1266      dxgi.dll  
0x00007FFC272D0000 10.0.19041.964       twinapi.appcore.dll  
0x00007FFC233A0000 10.0.19041.1320      textinputframework.dll  
0x00007FFC29B10000 10.0.19041.546       CoreUIComponents.dll  
0x00007FFC2A1F0000 10.0.19041.746       CoreMessaging.dll  
0x00007FFC288C0000 10.0.19041.1348      wintypes.dll  
0x00007FFC0CF00000 10.0.19041.1023      explorerframe.dll  
0x00007FFC281A0000 7.0.19041.1023       propsys.dll  
0x00007FFC2C580000 10.0.19041.546       CRYPTSP.dll  
0x00007FFC2BD10000 10.0.19041.1052      rsaenh.dll  
0x00007FFC27620000 3.9.7150.1013        python3.DLL  
0x00007FFC0BD20000 3.9.7150.1013        _bz2.pyd  
0x00007FFC02DD0000 3.9.7150.1013        _lzma.pyd  
0x00007FFC0BC30000 3.9.7150.1013        _socket.pyd  
0x00007FFC2C080000 10.0.19041.546       IPHLPAPI.DLL  
0x00007FFC27600000 3.9.7150.1013        select.pyd  
0x00007FFC02DA0000 3.9.7150.1013        _ctypes.pyd  
0x00007FFC18B10000                      libffi-7.dll  
0x00007FFBE2370000                      pyluxcore.pyd  
0x00007FFC02D70000 14.28.29910.0        VCOMP140.DLL  
0x00007FFBDD9A0000 3.12.2.0             embree3.dll  
0x00007FFBDAA10000 1.4.1.0              OpenImageDenoise.dll  
0x00007FFC02C90000                      tbb12.dll  
0x00007FFBEA7B0000                      _multiarray_umath.cp39-win_amd64.pyd  
0x00007FFC03120000                      _multiarray_tests.cp39-win_amd64.pyd  
0x00007FFC02C00000                      lapack_lite.cp39-win_amd64.pyd  
0x00007FFBEA580000                      _umath_linalg.cp39-win_amd64.pyd  
0x00007FFC02F90000                      _pocketfft_internal.cp39-win_amd64.pyd  
0x00007FFBFFD60000                      mtrand.cp39-win_amd64.pyd  
0x00007FFC02D40000                      bit_generator.cp39-win_amd64.pyd  
0x00007FFC01AD0000                      _common.cp39-win_amd64.pyd  
0x00007FFC02B90000 3.9.7150.1013        _hashlib.pyd  
0x00007FFBEA230000 1.1.1.12             libcrypto-1_1.dll  
0x00007FFC01660000                      _bounded_integers.cp39-win_amd64.pyd  
0x00007FFC008A0000                      _mt19937.cp39-win_amd64.pyd  
0x00007FFC00880000                      _philox.cp39-win_amd64.pyd  
0x00007FFBFFD40000                      _pcg64.cp39-win_amd64.pyd  
0x00007FFBFFD20000                      _sfc64.cp39-win_amd64.pyd  
0x00007FFBFA230000                      _generator.cp39-win_amd64.pyd  
0x00007FFC16AE0000 3.9.7150.1013        _uuid.pyd  
0x00007FFBF7E30000 3.0.1.0              OpenCL.dll  
0x00007FFBE9F60000 30.0.14.7168         nvcuda.dll  
0x00007FFBD9230000 30.0.14.7168         nvcuda64.dll  
0x00007FFBD82A0000 6.14.11.9000         nvrtc64_101_0.dll  
0x00007FFC20800000 30.0.14.7168         nvapi64.dll  
0x00007FFBCA370000 7.4.0.0              nvoptix.dll  
0x00007FFBE9AF0000 2.2.8.0              RadeonProRender64.dll  
0x00007FFBF9B00000                      __rpr.cp39-win_amd64.pyd  
0x00007FFBFA0F0000                      _cffi_backend.cp39-win_amd64.pyd  
0x00007FFBF6D10000 2.2.8.0              RprLoadStore64.dll  
0x00007FFBFFD00000 0.9.11.0             RadeonML.dll  
0x00007FFBE98C0000 1.7.1.0              RadeonImageFilters.dll  
0x00007FFBFFB40000                      __imagefilters.cp39-win_amd64.pyd  
0x00007FFBF9AD0000                      RPRBlenderHelper.dll  
0x00007FFBC8F20000 2.2.3.0              Tahoe64.dll  
0x00007FFBC8250000 2.2.0.0              Hybrid.dll  
0x00007FFC28C90000 10.0.19041.868       D3DCOMPILER_47.dll  
0x00007FFBF9AB0000 10.0.19041.1266      d3d12.dll  
0x00007FFBF8470000 1.2.170.0            vulkan-1.dll  
0x00007FFBC5FF0000 2.2.8.0              Northstar64.dll  
0x00007FFBC4C60000 30.0.14.7168         nvopencl64.dll  
0x00007FFBF9940000 3.9.7150.1013        _elementtree.pyd  
0x00007FFBF93E0000 3.9.7150.1013        pyexpat.pyd  
0x00007FFBF99C0000 3.9.7150.1013        _ssl.pyd  
0x00007FFBF8720000 1.1.1.12             libssl-1_1.dll  
0x00007FFC2C390000 10.0.19041.546       mswsock.dll  
0x00007FFC16350000 3.9.7150.1013        _queue.pyd  
0x00007FFBF9390000 3.9.7150.1013        _decimal.pyd  

**_# Python backtrace
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\utils\__init__.py", line 124 in create_props
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\export\camera.py", line 35 in convert
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\export\caches\__init__.py", line 37 in diff
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\export\__init__.py", line 98 in create_session
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\engine\final.py", line 56 in _render_layer
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\engine\final.py", line 44 in render
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\engine\base.py", line 91 in render_final
  File "D:\Softwares\Blender\versions\blender-3.0.0-stable+v30.f1cca3055776-windows.amd64-release\3.0\scripts\addons\BlendLuxCore\engine\base.py", line 82 in render_**
`

**Comment by dracon80** [comment]
I'm also getting the exact same thing.
System Info

====================================
= Blender 3.0.0 System Information =
====================================


Blender:
====================================

version: 3.0.0, branch: master, commit date: 2021-12-02 18:35, hash: f1cca3055776, type: release
build date: 2021-12-03, 00:44:02
platform: 'Windows-10-10.0.19044-SP0'
binary path: 'C:\\Program Files\\Blender Foundation\\Blender 3.0\\blender.exe'
build cflags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj /Zc:inline -openmp   
build cxxflags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3  /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive- /Zc:twoPhase- -openmp /Zc:__cplusplus   
build linkflags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
build system: CMake

Python:
====================================

version: 3.9.7 (default, Oct 11 2021, 19:31:28) [MSC v.1916 64 bit (AMD64)]
file system encoding: utf-8:surrogatepass
paths:
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\startup'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\modules'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\python39.zip'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\DLLs'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\lib'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\lib\\site-packages'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\freestyle\\modules'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\addons\\modules'
	'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\modules'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\addons'
	'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\addons_contrib'

Python (External Binary):
====================================

binary path: 'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\python\\bin\\python.EXE'
version: Python 3.9.7

Directories:
====================================

scripts:
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\modules'
	'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts'
	'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts'
user scripts: 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts'
pref scripts: None
datafiles: 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\datafiles'
config: 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\config'
scripts : 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts'
autosave: 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\autosave'
tempdir: 'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\blender_a26596\\'

FFmpeg:
====================================

avcodec:   '58, 134, 100'
avdevice:  '58, 13, 100'
avformat:  '58, 76, 100'
avutil:    '56, 70, 100'
swscale:   ' 5,  9, 100'

SDL:
====================================

Version: 2.0.12
Loading method: linked (WITH_SDL_DYNLOAD=OFF)

Other Libraries:
====================================

OpenColorIO:  2,  0,  0
OpenImageIO:  2,  2, 15
OpenShadingLanguage:  1, 11, 14
OpenSubdiv:  0,  0,  0
OpenVDB:  8,  0,  0
Alembic:  1,  7, 16
USD:  0, 21,  2

GPU:
====================================

renderer:	'Intel(R) UHD Graphics 620'
vendor:		'Intel'
version:	'4.5.0 - Build 27.20.100.8681'
extensions:
	GL_3DFX_texture_compression_FXT1
	GL_AMD_depth_clamp_separate
	GL_AMD_vertex_shader_layer
	GL_AMD_vertex_shader_viewport_index
	GL_ARB_ES2_compatibility
	GL_ARB_ES3_1_compatibility
	GL_ARB_ES3_compatibility
	GL_ARB_arrays_of_arrays
	GL_ARB_base_instance
	GL_ARB_bindless_texture
	GL_ARB_blend_func_extended
	GL_ARB_buffer_storage
	GL_ARB_cl_event
	GL_ARB_clear_buffer_object
	GL_ARB_clear_texture
	GL_ARB_clip_control
	GL_ARB_color_buffer_float
	GL_ARB_compressed_texture_pixel_storage
	GL_ARB_compute_shader
	GL_ARB_conditional_render_inverted
	GL_ARB_conservative_depth
	GL_ARB_copy_buffer
	GL_ARB_copy_image
	GL_ARB_cull_distance
	GL_ARB_debug_output
	GL_ARB_depth_buffer_float
	GL_ARB_depth_clamp
	GL_ARB_depth_texture
	GL_ARB_derivative_control
	GL_ARB_direct_state_access
	GL_ARB_draw_buffers
	GL_ARB_draw_buffers_blend
	GL_ARB_draw_elements_base_vertex
	GL_ARB_draw_indirect
	GL_ARB_draw_instanced
	GL_ARB_enhanced_layouts
	GL_ARB_explicit_attrib_location
	GL_ARB_explicit_uniform_location
	GL_ARB_fragment_coord_conventions
	GL_ARB_fragment_layer_viewport
	GL_ARB_fragment_program
	GL_ARB_fragment_program_shadow
	GL_ARB_fragment_shader
	GL_ARB_fragment_shader_interlock
	GL_ARB_framebuffer_no_attachments
	GL_ARB_framebuffer_object
	GL_ARB_framebuffer_sRGB
	GL_ARB_geometry_shader4
	GL_ARB_get_program_binary
	GL_ARB_get_texture_sub_image
	GL_ARB_gl_spirv
	GL_ARB_gpu_shader5
	GL_ARB_gpu_shader_fp64
	GL_ARB_half_float_pixel
	GL_ARB_half_float_vertex
	GL_ARB_indirect_parameters
	GL_ARB_instanced_arrays
	GL_ARB_internalformat_query
	GL_ARB_internalformat_query2
	GL_ARB_invalidate_subdata
	GL_ARB_map_buffer_alignment
	GL_ARB_map_buffer_range
	GL_ARB_multi_bind
	GL_ARB_multi_draw_indirect
	GL_ARB_multisample
	GL_ARB_multitexture
	GL_ARB_occlusion_query
	GL_ARB_occlusion_query2
	GL_ARB_pipeline_statistics_query
	GL_ARB_pixel_buffer_object
	GL_ARB_point_parameters
	GL_ARB_point_sprite
	GL_ARB_polygon_offset_clamp
	GL_ARB_post_depth_coverage
	GL_ARB_program_interface_query
	GL_ARB_provoking_vertex
	GL_ARB_query_buffer_object
	GL_ARB_robust_buffer_access_behavior
	GL_ARB_robustness
	GL_ARB_robustness_isolation
	GL_ARB_sample_shading
	GL_ARB_sampler_objects
	GL_ARB_seamless_cube_map
	GL_ARB_seamless_cubemap_per_texture
	GL_ARB_separate_shader_objects
	GL_ARB_shader_atomic_counter_ops
	GL_ARB_shader_atomic_counters
	GL_ARB_shader_bit_encoding
	GL_ARB_shader_draw_parameters
	GL_ARB_shader_group_vote
	GL_ARB_shader_image_load_store
	GL_ARB_shader_image_size
	GL_ARB_shader_objects
	GL_ARB_shader_precision
	GL_ARB_shader_stencil_export
	GL_ARB_shader_storage_buffer_object
	GL_ARB_shader_subroutine
	GL_ARB_shader_texture_image_samples
	GL_ARB_shading_language_100
	GL_ARB_shading_language_420pack
	GL_ARB_shading_language_packing
	GL_ARB_shadow
	GL_ARB_spirv_extensions
	GL_ARB_stencil_texturing
	GL_ARB_sync
	GL_ARB_tessellation_shader
	GL_ARB_texture_barrier
	GL_ARB_texture_border_clamp
	GL_ARB_texture_buffer_object
	GL_ARB_texture_buffer_object_rgb32
	GL_ARB_texture_buffer_range
	GL_ARB_texture_compression
	GL_ARB_texture_compression_bptc
	GL_ARB_texture_compression_rgtc
	GL_ARB_texture_cube_map
	GL_ARB_texture_cube_map_array
	GL_ARB_texture_env_add
	GL_ARB_texture_env_combine
	GL_ARB_texture_env_crossbar
	GL_ARB_texture_env_dot3
	GL_ARB_texture_filter_anisotropic
	GL_ARB_texture_float
	GL_ARB_texture_gather
	GL_ARB_texture_mirror_clamp_to_edge
	GL_ARB_texture_mirrored_repeat
	GL_ARB_texture_multisample
	GL_ARB_texture_non_power_of_two
	GL_ARB_texture_query_levels
	GL_ARB_texture_query_lod
	GL_ARB_texture_rectangle
	GL_ARB_texture_rg
	GL_ARB_texture_rgb10_a2ui
	GL_ARB_texture_stencil8
	GL_ARB_texture_storage
	GL_ARB_texture_storage_multisample
	GL_ARB_texture_swizzle
	GL_ARB_texture_view
	GL_ARB_timer_query
	GL_ARB_transform_feedback2
	GL_ARB_transform_feedback3
	GL_ARB_transform_feedback_instanced
	GL_ARB_transform_feedback_overflow_query
	GL_ARB_transpose_matrix
	GL_ARB_uniform_buffer_object
	GL_ARB_vertex_array_bgra
	GL_ARB_vertex_array_object
	GL_ARB_vertex_attrib_64bit
	GL_ARB_vertex_attrib_binding
	GL_ARB_vertex_buffer_object
	GL_ARB_vertex_program
	GL_ARB_vertex_shader
	GL_ARB_vertex_type_10f_11f_11f_rev
	GL_ARB_vertex_type_2_10_10_10_rev
	GL_ARB_viewport_array
	GL_ARB_window_pos
	GL_ATI_separate_stencil
	GL_EXT_abgr
	GL_EXT_bgra
	GL_EXT_blend_color
	GL_EXT_blend_equation_separate
	GL_EXT_blend_func_separate
	GL_EXT_blend_minmax
	GL_EXT_blend_subtract
	GL_EXT_clip_volume_hint
	GL_EXT_compiled_vertex_array
	GL_EXT_direct_state_access
	GL_EXT_draw_buffers2
	GL_EXT_draw_range_elements
	GL_EXT_fog_coord
	GL_EXT_framebuffer_blit
	GL_EXT_framebuffer_multisample
	GL_EXT_framebuffer_object
	GL_EXT_geometry_shader4
	GL_EXT_gpu_program_parameters
	GL_EXT_gpu_shader4
	GL_EXT_multi_draw_arrays
	GL_EXT_packed_depth_stencil
	GL_EXT_packed_float
	GL_EXT_packed_pixels
	GL_EXT_polygon_offset_clamp
	GL_EXT_rescale_normal
	GL_EXT_secondary_color
	GL_EXT_separate_specular_color
	GL_EXT_shader_framebuffer_fetch
	GL_EXT_shader_integer_mix
	GL_EXT_shadow_funcs
	GL_EXT_stencil_two_side
	GL_EXT_stencil_wrap
	GL_EXT_texture3D
	GL_EXT_texture_array
	GL_EXT_texture_compression_s3tc
	GL_EXT_texture_edge_clamp
	GL_EXT_texture_env_add
	GL_EXT_texture_env_combine
	GL_EXT_texture_filter_anisotropic
	GL_EXT_texture_integer
	GL_EXT_texture_lod_bias
	GL_EXT_texture_rectangle
	GL_EXT_texture_sRGB
	GL_EXT_texture_sRGB_decode
	GL_EXT_texture_shared_exponent
	GL_EXT_texture_snorm
	GL_EXT_texture_storage
	GL_EXT_texture_swizzle
	GL_EXT_timer_query
	GL_EXT_transform_feedback
	GL_IBM_texture_mirrored_repeat
	GL_INTEL_conservative_rasterization
	GL_INTEL_fragment_shader_ordering
	GL_INTEL_framebuffer_CMAA
	GL_INTEL_map_texture
	GL_INTEL_multi_rate_fragment_shader
	GL_INTEL_performance_query
	GL_KHR_blend_equation_advanced
	GL_KHR_blend_equation_advanced_coherent
	GL_KHR_context_flush_control
	GL_KHR_debug
	GL_KHR_no_error
	GL_KHR_texture_compression_astc_hdr
	GL_KHR_texture_compression_astc_ldr
	GL_NV_blend_square
	GL_NV_conditional_render
	GL_NV_primitive_restart
	GL_NV_texgen_reflection
	GL_SGIS_generate_mipmap
	GL_SGIS_texture_edge_clamp
	GL_SGIS_texture_lod
	GL_SUN_multi_draw_arrays
	GL_WIN_swap_hint
	WGL_EXT_swap_control

Implementation Dependent GPU Limits:
====================================

Maximum Batch Vertices:	1048576
Maximum Batch Indices:	1048576

GLSL:
Maximum Varying Floats:	64
Maximum Vertex Attributes:	16
Maximum Vertex Uniform Components:	4096
Maximum Fragment Uniform Components:	4096
Maximum Vertex Image Units:	32
Maximum Fragment Image Units:	32
Maximum Pipeline Image Units:	192

Cycles:
====================================


CPU device capabilities: SSE2 SSE3 SSE41 AVX AVX2

Enabled add-ons:
====================================

io_anim_bvh (version: (1, 0, 0), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_anim_bvh\__init__.py)
io_curve_svg (version: (), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_curve_svg\__init__.py)
io_mesh_ply (version: (), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_mesh_ply\__init__.py)
io_mesh_stl (version: (1, 1, 3), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_mesh_stl\__init__.py)
io_mesh_uv_layout (version: (1, 1, 1), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_mesh_uv_layout\__init__.py)
io_scene_fbx (version: (4, 27, 0), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\__init__.py)
io_scene_gltf2 (version: (1, 7, 33), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\__init__.py)
io_scene_obj (version: (3, 8, 1), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_obj\__init__.py)
io_scene_x3d (version: (2, 3, 0), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_x3d\__init__.py)
cycles (version: (), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\cycles\__init__.py)
pose_library (version: (2, 0), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\pose_library\__init__.py)
add_curve_extra_objects (version: (0, 1, 5), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\add_curve_extra_objects\__init__.py)
materials_library_vx (version: (0, 6, 0), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\materials_library_vx\__init__.py)
node_wrangler (version: (3, 38), path: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\node_wrangler.py)

**Comment by JkyProgrammer** [comment]
Just to keep this thread alive, this exact crash still happens on the latest '3.0-supporting' alpha build.

**Comment by neo2068** [comment]
This is an bug in one of the dependencies blender and luxcore uses. We implemented a workaround in the latest build. It should work in most cases. Please check if it works for you.

**Comment by helsharif** [comment]
Hello, just installed the latest blendluxcore build that was released today into Blender 3.0 on Windows and it looks like it is working! Thanks

**Comment by JkyProgrammer** [comment]
Yup. works for me as well. Awesome!
