### ISSUE TITLE
Hi ,I have installed all files which on the list of announcement page ,but the luxcore still can not activate

### ISSUE THREAD

**Issue by markli1983** [LuxCoreRender/BlendLuxCore#741]
Hi ,I have installed all files which on the list of announcement page ,but the luxcore still can not activate
![image](https://user-images.githubusercontent.com/60761544/146033823-023c5885-a4be-46b1-a515-4f8136438d0f.png)

**Comment by JkyProgrammer** [comment]
This is a 3.0 issue. BlendLuxCore isn’t updated for blender 3.0 yet.

**Comment by neo2068** [comment]
The first fixes for Blender 3.0 are available in the daily build. There are still some incompatibilities of dependencies under windows which leads to a crash.
