### ISSUE TITLE
BlendLuxCore 2.6 still shows alpha0

### ISSUE THREAD

**Issue by matsbtegner** [LuxCoreRender/BlendLuxCore#743]
bl_info = {
    "name": "LuxCore",
    "author": "Simon Wendsche (B.Y.O.B.), Michael Klemm (neo2068), Philstix",
    "version": (2, 6),
    "blender": (2, 80, 0),
    "category": "Render",
    "location": "Info header, render engine menu",
    "description": "LuxCore integration for Blender",
    "warning": "alpha0",
    "wiki_url": "https://wiki.luxcorerender.org/",
    "tracker_url": "https://github.com/LuxCoreRender/BlendLuxCore/issues/new",

**Comment by Dade916** [comment]
Efff, I checked the '"version": (2, 6)"' and I missed the '"warning": "alpha0"'. Going to fix it.

**Comment by Dade916** [comment]
Ok, it should be now fixed.
