### ISSUE TITLE
LuxCore Hides 'Format' Panel in Output Properties

### ISSUE THREAD

**Issue by PhlixFer** [LuxCoreRender/BlendLuxCore#746]
Steps to reproduce:
1. Activate the LuxCore add-on and switch the renderer to LuxCore

Screenshots or rendered images:
<img width="295" alt="Screenshot 2022-01-01 at 14 31 29" src="https://user-images.githubusercontent.com/33190165/147846074-ab92ce29-6032-4a99-82e0-0394e9b145d3.png">

Error message from Blender console:
none :P

OS: macOS Monterey 12.1
Blender version: 3.1 Alpha (rB6844304dda49)
LuxCore version: Latest build (dff6011)

P.S. I know 3.x versions aren't supported, I'm making this issue just to raise awareness

**Comment by SteffenDuenner** [comment]
I can confirm this on Linux in Blender 3.0 release and 3.1 master.

**Comment by neo2068** [comment]
Hi! It should be fixed in latest release. If you find more missing panels, please report them.

**Comment by neo2068** [comment]
Fixed by commit fc3b7ad345c02c1a789940d81516fea0f685bf6f
