### ISSUE TITLE
[Solved] How fix on Linux error: OptixAccel CUDA program compilation error

### ISSUE THREAD

**Issue by Axelaredz** [LuxCoreRender/BlendLuxCore#749]
Error message from Blender console:
OptixAccel CUDA program compilation error

Fix:
in terminal or file manager open path
cd /home/USER/.config/blender/VERSION/scripts/addons/BlendLuxCore/bin/

Coppied all libnvrtc*.* files to /usr/lib
sudo cp libnvrtc*.* /usr/lib

OS: Linux all
Blender version: all
LuxCore version: all

**Comment by neo2068** [comment]
Issue has been solved
