### ISSUE TITLE
Black image in specific scene

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#77]
See: https://forums.luxcorerender.org/viewtopic.php?f=4&p=1733#p1728

I noticed that it seems to render fine when unit scale in scene settings is changed to 1.

**Comment by neo2068** [comment]
There has been a bug in LuxCore which lead to wrong results with power based sampling. ([url]https://github.com/LuxCoreRender/LuxCore/commit/ad7481f0bc36d10d99f01c018628e1872540ba5b[/url]) When I try the test scene with latest build, it renders correctly. That specific scene should render fine now.
