### ISSUE TITLE
Luxcore node material

### ISSUE THREAD

**Issue by AndrAlb** [LuxCoreRender/BlendLuxCore#782]
When I add a panel between two nodes this is not inserted automatically but must be connected manually. For example if I have a matte material with an image linked to diffuse color, I add an hsv between the two to control the colors this does not automatically insert between the two but I have to link it manually.

Blender 3.0, Luxcore 2.61 on mac
![Schermata 2022-07-17 alle 16 14 29](https://user-images.githubusercontent.com/109461438/179402499-0aa7a07d-6986-46ee-b139-256b4827cd64.png)
.

**Comment by odil24** [comment]
It works fine for me
