### ISSUE TITLE
Cannot activate LuxCore addon

### ISSUE THREAD

**Issue by svorotilo** [LuxCoreRender/BlendLuxCore#792]
Hello! 
I cannot launch the add-on. I'm using the latest Blender version and I've installed the recommended distributives. 

<img width="497" alt="Untitled" src="https://user-images.githubusercontent.com/71875849/199136654-c27cf40c-4ca3-4b89-a6ad-7997bdb482a3.png">

**Comment by odil24** [comment]
> Hello! I cannot launch the add-on. I'm using the latest Blender version and I've installed the recommended distributives.
> 
> <img alt="Untitled" width="497" src="https://user-images.githubusercontent.com/71875849/199136654-c27cf40c-4ca3-4b89-a6ad-7997bdb482a3.png">

https://github.com/odil24/BlendLuxCore/releases/tag/v2.62.1a
