### ISSUE TITLE
Node Shader textures or renders

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [LuxCoreRender/BlendLuxCore#793]
.blend file: 

Steps to reproduce:

Screenshots or rendered images:

Error message from Blender console:

OS: 
Blender version:
LuxCore version:

**Comment by Snoiteandthesv3ndwarves** [comment]
<img width="2048" alt="Screenshot 2022-11-02 at 11 18 54 AM" src="https://user-images.githubusercontent.com/107887495/199572367-28f25683-235d-4cc6-832d-bc8f4dd37a7d.png">
Luxcore 3'2.2
MacOs 13
Luxcore will not render or provide shader image textures.

**Comment by odil24** [comment]
You should install this build:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.6alpha1
