### ISSUE TITLE
Probleme installation Luxcore Blender

### ISSUE THREAD

**Issue by MaxBused** [LuxCoreRender/BlendLuxCore#795]
Hello,
Je n'arrive pas à installer Luxcore sur Blender. J'ai le message d'erreur en PJ :(
Quelqu'un a la solution ?
<img width="646" alt="CleanShot 2022-11-18 at 10 48 53@2x" src="https://user-images.githubusercontent.com/118524556/202672752-815b44d1-6e9a-4b68-9f7e-607dc1c84c0f.png">

**Comment by 240db** [comment]
Je pense que ce probleme arrive parce que vous utilisez Blender 3.3 je pense que ça ne va pas marcher...
peut-etre essayez Blender 2.93... 
bonne chance

**Comment by odil24** [comment]
> Hello, Je n'arrive pas à installer Luxcore sur Blender. J'ai le message d'erreur en PJ :( Quelqu'un a la solution ? <img alt="CleanShot 2022-11-18 at 10 48 53@2x" width="646" src="https://user-images.githubusercontent.com/118524556/202672752-815b44d1-6e9a-4b68-9f7e-607dc1c84c0f.png">

Hi. Try this build:
https://github.com/odil24/BlendLuxCore/releases/tag/v2.62.1a
