### ISSUE TITLE
I cant enable luxcore addon 

### ISSUE THREAD

**Issue by thentity** [LuxCoreRender/BlendLuxCore#798]
Hello, I downloaded LuxCore and I can't enable it. I'm on Arch Linux with Blender it gives me this error:

"Traceback (most recent call last):
  File "/usr/share/blender/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference"

**Comment by odil24** [comment]
> Hello, I downloaded LuxCore and I can't enable it. I'm on Arch Linux with Blender it gives me this error:
> 
> "Traceback (most recent call last): File "/usr/share/blender/3.4/scripts/modules/addon_utils.py", line 333, in enable mod = **import**(module_name) File "/home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/**init**.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Could not import pyluxcore.
> 
> ImportError: /home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference"

Hi, which version of LC and OS?

**Comment by ArsenoL** [comment]
Hey! you guys are in the wrong version of blender! if you want to use LuxCore, I would suggest downloading blender 3.93. 
You can find it here: [https://www.blender.org/download/lts/2-93/](url) 

Hope this helps!

**Comment by odil24** [comment]
> Hello, I downloaded LuxCore and I can't enable it. I'm on Arch Linux with Blender it gives me this error:
> 
> "Traceback (most recent call last):
>   File "/usr/share/blender/3.4/scripts/modules/addon_utils.py", line 333, in enable
>     mod = __import__(module_name)
>   File "/home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
>     raise Exception(msg + "\n\nImportError: %s" % error) from None
> Exception: 
> 
> Could not import pyluxcore.
> 
> ImportError: /home/lexiq/.config/blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference"
> 
> 
> 
> 

Download this build:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.6alpha1
