### ISSUE TITLE
Blender crashes when initial LuxCore material is previewed

### ISSUE THREAD

**Issue by raphaelmatto** [LuxCoreRender/BlendLuxCore#799]
.blend file: 

No blend file is necessary.

Steps to reproduce:

1. Start a new scene in Blender 3.4
2. Enable the LuxCore addon
3. Switch to the LuxCore renderer
4. Choose the material tab and select "Preview"
5. Blender crashes for me

Screenshots or rendered images:

None necessary.

Error message from Blender console:

Can't retrieve it.

OS: MacOS 13.1
Blender version: 3.4.0
LuxCore version: pre-release build from May 29th

**Comment by odil24** [comment]
> .blend file:
> 
> No blend file is necessary.
> 
> Steps to reproduce:
> 
> 1. Start a new scene in Blender 3.4
> 2. Enable the LuxCore addon
> 3. Switch to the LuxCore renderer
> 4. Choose the material tab and select "Preview"
> 5. Blender crashes for me
> 
> Screenshots or rendered images:
> 
> None necessary.
> 
> Error message from Blender console:
> 
> Can't retrieve it.
> 
> OS: MacOS 13.1 Blender version: 3.4.0 LuxCore version: pre-release build from May 29th

Hi. You can install BlendLuxCore v2.6x _**only**_ for Blender v3.4alpha with (_Hash:_ **_ff048f5d27c4_**)
https://builder.blender.org/download/daily/blender-3.4.0-alpha+master.ff048f5d27c4-windows.amd64-release.zip

**Comment by raphaelmatto** [comment]
Thanks, @odil24—I'll stick with the stable Blender release for now. Closing this issue.

**Comment by Sharlybg** [comment]
On Blender 3.5a you can't use or assign more than a single material
on a mesh even if the preview doesn't crash blender.
