### ISSUE TITLE
Installation error Blender 2.93.7: DLL load failed while importing pyluxcore: The specified module could not be found

### ISSUE THREAD

**Issue by TheAdeo** [LuxCoreRender/BlendLuxCore#800]
I could not install LuxCore in Blender 2.93.7, I checked and redownloaded the addon multiple times, but every time I got the same error.

Error message from Blender console:

Traceback (most recent call last):
  File "D:\Blender\Versions\Blender 2.93.7 zip\blender-2.93.7\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Adeo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.

OS: Windows 10
Blender version: 2.93.7
LuxCore version: 2.61

**Comment by odil24** [comment]
> I could not install LuxCore in Blender 2.93.7, I checked and redownloaded the addon multiple times, but every time I got the same error.
> 
> Error message from Blender console:
> 
> Traceback (most recent call last): File "D:\Blender\Versions\Blender 2.93.7 zip\blender-2.93.7\2.93\scripts\modules\addon_utils.py", line 351, in enable mod = **import**(module_name) File "C:\Users\Adeo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendLuxCore__init__.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Could not import pyluxcore. You probably forgot to install one of the redistributable packages. They are listed in the release announcement post.
> 
> ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.
> 
> OS: Windows 10 Blender version: 2.93.7 LuxCore version: 2.61

Hi. You must download the build for Blender 2.93.7:
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.6/BlendLuxCore-v2.6-win64.zip
