### ISSUE TITLE
How can I remove the add-on?

### ISSUE THREAD

**Issue by chuodi** [LuxCoreRender/BlendLuxCore#801]
I accidentally had the wrong version (for older version, Blender below 3.0) of BlendLuxCore and it cannot work so I decided to remove it and install the latest one. After I clicked on 'Remove' this error came out.

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 764, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\86158\\AppData\\Roaming\\Blender `Foundation\\Blender\\3.3\\scripts\\addons\\BlendLuxCore\\bin\\embree3.dll'`

Could someone help me out with it? Many thanks.

**Comment by odil24** [comment]
Hi. Just goto "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\BlendLuxCore" folder and delete "BlendLuxCore" folder. And unpack again latest version here again "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons". That's it.

**Comment by chuodi** [comment]
Hi, thank you @odil24 however when I downloaded the latest version from [https://github.com/LuxCoreRender/BlendLuxCore/releases](url) still the add-on cannot work.
<img width="743" alt="scs" src="https://user-images.githubusercontent.com/121859042/210470816-1adaff90-1251-4969-906c-bd40532c2dcd.png">

**Comment by odil24** [comment]
> Hi, thank you @odil24 however when I downloaded the latest version from [https://github.com/LuxCoreRender/BlendLuxCore/releases](url) still the add-on cannot work. <img alt="scs" width="743" src="https://user-images.githubusercontent.com/121859042/210470816-1adaff90-1251-4969-906c-bd40532c2dcd.png">

What exactly did not work? I see you have been enabled the addon.

**Comment by Loli-armpits** [comment]
disable the add-on, after restart blender and then try to remove it

**Comment by odil24** [comment]
I should close an issue. The reason: not responded!
