### ISSUE TITLE
Luxcore material nodes show up in difrend node editors

### ISSUE THREAD

**Issue by SlincHD** [LuxCoreRender/BlendLuxCore#803]
how to reproduce: search for nodes in an node editor of your choosing and the luxcore material will show up

![image](https://user-images.githubusercontent.com/85231739/211316671-f6218d2e-300b-4ae4-90a4-3235c64f3c4b.png)

**Comment by odil24** [comment]
> how to reproduce: search for nodes in an node editor of your choosing and the luxcore material will show up
> 
> ![image](https://user-images.githubusercontent.com/85231739/211316671-f6218d2e-300b-4ae4-90a4-3235c64f3c4b.png)

I have been already fixed this and pull requested from my fork. Soon it will be include in next release I hope.
