### ISSUE TITLE
Glitch while changing materials with image texture with new slots created in Cycles.

### ISSUE THREAD

**Issue by MigCurto** [LuxCoreRender/BlendLuxCore#808]
Could be its with transparent (PNGs) only, didn't test with more formats.

.blend file: 
https://drive.google.com/file/d/1KlAgVvi0GLRRGttg9fhixgZRGYZpjYNG/view?usp=sharing

Steps to reproduce:
(In video is more explicit)
(in Cycles) Duplicate the array -> Apply Array -> Separte result by Loose Parts -> Create new materials for top parts -> Change PNG (embedded in file) -> Go to Lux , turn viewport render on and replicate changed PNGs -> Turn off and on viewport.

Screenshots or rendered images:
https://youtu.be/dGJExhn8qqQ

Error message from Blender console:

OS: Mac OS 12.6.2
Blender version: 3.3
LuxCore version: Latest alpha (26 Jan)

**Comment by odil24** [comment]
I should close this issue. Solved a long time ago.
