### ISSUE TITLE
Point light IES option on = The scene doesn't include any light source

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/BlendLuxCore#81]
#### System Information
Win7 64bit
Quadro K5200

#### Software Version

Blender version: 2.79a RC
LuxCore version: 2.0 alpha5

#### Error message from Blender console

RuntimeError: The scene doesn't include any light source (note: volume emission
doesn't count for this check)

#### Exact steps for others to reproduce the error
Create a point Light. Active "use IES file". Choose a IES file.
Press F12 or make a rendered viewport  preview.
Render doesn't start and it give me the error message  "The scene doesn't include any light source (note: volume emission doesn't count for this check)"

**Comment by Theverat** [comment]
Thanks for the report. 
It was a regression due to refactoring - a unit test would have prevented it...
