### ISSUE TITLE
ImportError: DLL Load failed while importing pyluxcore: The specified module could not be found

### ISSUE THREAD

**Issue by arturlv** [LuxCoreRender/BlendLuxCore#817]
Traceback (most recent call last):
  File "D:\Blender\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlendLuxCore\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: DLL load failed while importing pyluxcore: The specified module could not be found.

**Comment by odil24** [comment]
Hi. Just redownload latest build and try to install on fresh Blender. I think you have tried install old version.

**Comment by arturlv** [comment]
Ah thanks. Didn't see the latest release on top.
