### ISSUE TITLE
Blender freeze after nvidia 530 update

### ISSUE THREAD

**Issue by aaronrancsik** [LuxCoreRender/BlendLuxCore#818]
Hi, 
Since NVIDIA 530 update It's freezing.
I was able to pin down the issue to NVIDIA update with some downgrades to 525 it's working fine.
Please help me to debug it. 

Error message from Blender console:
Unfortunately I don't see any logs `blender -d`
It's just hangs.

Not sure it's relevant but if I run `luxcoreui`
I've got this:
`luxcoreui: error while loading shared libraries: libImath-3_1.so.29: cannot open shared object file: No such file or directory
`

OS: Arch Linux
Blender version:  17:3.4.1-23
LuxCore version: 2.6.b3478-2
Nvidia: 530.41.03-1

**Comment by odil24** [comment]
Solved here:
https://github.com/LuxCoreRender/BlendLuxCore/issues/827
