### ISSUE TITLE
Crash when enabling BlendLuxCore Addon

### ISSUE THREAD

**Issue by HowardBlandy** [LuxCoreRender/BlendLuxCore#820]
Steps to reproduce:
1. Install addon
2. Enabling addon in perferences

Error message from Blender console:
No crash log file recorded

OS:  Windows 11 ProWorkstation 22H2
Blender version: 3.5
LuxCore version: LuxCore Latest Build
CPU: AMD Ryzen 7 5800H
GPU: AMD Radeon Graphics
RAM: 16GB

**Comment by Vidyut** [comment]
Same issue, but mine is an APU. Also Radeon.
