### ISSUE TITLE
Unknown geometry bug on viewport or in rendering

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/BlendLuxCore#821]
Steps to reproduce:
Just open my previous scene and gives me unknown glitched geometry inside viewport rendering

OS: Win10
Blender version: 3.5 (stable)
LuxCore version: v2.61a

**Comment by neo2068** [comment]
Can you describe the problem more in detail? Is it related to #809? Is the Bug still there with the latest version?

**Comment by odil24** [comment]
![985](https://user-images.githubusercontent.com/64298012/229353048-f3b15bf5-2bb3-446e-8cea-ad4b2114d9ba.jpg)
as you can see it does not fixed i guess

**Comment by odil24** [comment]
![issue](https://user-images.githubusercontent.com/64298012/229353212-8eccbcdd-898f-4e89-b2d7-3a81e3d94c69.gif)

**Comment by SlincHD** [comment]
![image](https://user-images.githubusercontent.com/85231739/229354361-6fca201c-1427-44bd-b9e7-ab18ad274d40.png)
![image](https://user-images.githubusercontent.com/85231739/229354367-82454141-8d65-4aa5-8b48-85aaf356c7e4.png)
i can not replicate that in gpu or cpu (windows 10, Nvidia RTX 3060, Amd 2700)

**Comment by neo2068** [comment]
Are you on the master branch or on your own?

**Comment by neo2068** [comment]
> ![985](https://user-images.githubusercontent.com/64298012/229353048-f3b15bf5-2bb3-446e-8cea-ad4b2114d9ba.jpg) as you can see it does not fixed i guess

The pipeline failed because of a shutdown server for some install packages. As you can see in the picture. The build of the last commit succeeded.

**Comment by neo2068** [comment]
@odil24 Can you retest? I cannot reproduce it on my side. HallBench scene renders fine here.

**Comment by odil24** [comment]
> @odil24 Can you retest? I cannot reproduce it on my side. HallBench scene renders fine here.

What test? There is still that issue. Maybe something need to check from PowerShell?

**Comment by neo2068** [comment]
@odil24 Are you sure that you use the latest BlendLuxCore version? I downloaded the latest version [link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip) and rendered the HallBench scene without any problems. 
![grafik](https://user-images.githubusercontent.com/17701407/229475591-1ccf69cf-a552-40c7-ae48-1958a2d5d6a9.png)

**Comment by odil24** [comment]
> @odil24 the latest version [link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip)
I re-downloaded again and it works fine now! Thanks.

**Comment by odil24** [comment]
I didn't changed any settings in the scene but this kind of issues on the floor:
![floor_issue](https://user-images.githubusercontent.com/64298012/229525337-d271b9f3-9789-4a08-8dfe-dd8ee7bbee68.gif)
