### ISSUE TITLE
Bevel modefier destroys material asignment

### ISSUE THREAD

**Issue by SlincHD** [LuxCoreRender/BlendLuxCore#822]
.blend file: 
[Bevel modefier broken.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/11132270/Bevel.modefier.broken.zip)

Steps to reproduce:
use the bevel modefier on any mesh

Screenshots or rendered images:
![image](https://user-images.githubusercontent.com/85231739/229354873-d737301c-f91c-4c95-b4a1-0fc73a775806.png)

Error message from Blender console:

OS: WIndows 10
Blender version: 3.5
LuxCore version: 2.61

**Comment by neo2068** [comment]
Hi! I can confirm this issue. It is not the material assignment but the geometry export. The whole process is still WIP. I will look into it.

**Comment by neo2068** [comment]
@SlincHD Can you test the latest version? I fixed an issue with missing material_index attribute in mesh export.

**Comment by SlincHD** [comment]
yes it has bean fixed! (sory i was on my holidays coudn't do it earlier)
