### ISSUE TITLE
Tasselation errors in the boolean objects

### ISSUE THREAD

**Issue by pafurijaz** [LuxCoreRender/BlendLuxCore#824]
Hi I tried this latest version released a few days ago with Blender V3.5, but with this file that uses booleans I have some problems that you can see in the attached video, the file is also attached. 
This is a problem that on a file I can't share is even more evident in the attached image.

Linux Ubuntu 22.04 LTS Operating System, Nvidia GTX 3070 Graphics Card for Lenovo Laptop PC.

With an other similar file
![image](https://user-images.githubusercontent.com/11751383/230889514-22b10006-80b5-4b43-816c-a05b84111457.png)
and that is the shaded viewport
![image](https://user-images.githubusercontent.com/11751383/230889640-30a27f74-9843-44b6-8995-d277fa358807.png)

Video of the problem that happen randomly.

https://user-images.githubusercontent.com/11751383/230889784-a15a8af9-1ad7-4701-8893-d39ccd33431c.mp4

file
[LuxBug.blend.tar.gz](https://github.com/LuxCoreRender/BlendLuxCore/files/11190064/LuxBug.blend.tar.gz)

Greetings!

**Comment by neo2068** [comment]
Hi @pafurijaz ! Please try the latest version. This bug is known and should have been fixed. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-linux64.zip)

**Comment by pafurijaz** [comment]
> ...This bug is known and should have been fixed...)
Very well, my concern was if it's was unknown bug.

**Comment by pafurijaz** [comment]
fixed. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-linux64.zip)
