### ISSUE TITLE
Blender 3.5.1 crashes when rendering is started.

### ISSUE THREAD

**Issue by zzador** [LuxCoreRender/BlendLuxCore#826]
Installed the last BlendLuxCore-Addon for Blender in version 3.5.1. "LuxCore" appeared in the "Renderers"-Dropdown box. I selected "Luxcore" and hit "Render Image" in the Menubar -> Instant crash without any message. After restart I tried to using LuxCore as the Viewport-Renderer....same effect: After choosing the "Full Render"-Icon in the viewport Blender crashes away.

**Comment by odil24** [comment]
Write this:
1. Luxcore version
2. System specs

P.s.: Works fine for me on 3.5.1 (Windows)

**Comment by zzador** [comment]
Sorry that I didn't provide that info in the first place.

1. The most current version of luxcore that is bundeled with the current blendluxcore-addon downloaded here: https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.6/BlendLuxCore-v2.6-win64.zip

2. My hardware is a Gigabyte G5 Gaming Notebook (Intel I5 12500H, 8GB RAM, Geforce RTX 3050, 4GB VRAM, Win10).

**Comment by zzador** [comment]
My bad. I should read. It clearly says "NOTE: This version is not compatible with Blender v3.0, it requires Blender 2.93LTS.". Sorry for bothering!

**Comment by odil24** [comment]
you must download this for 3.0+
https://github.com/LuxCoreRender/BlendLuxCore/releases/download/latest/BlendLuxCore-latest-win64.zip
