### ISSUE TITLE
After latest Windows 11 update (to build 22621.1848), OpenCL driver API error on BlendLuxCore whenever trying to render/view the viewport

### ISSUE THREAD

**Issue by Lunarien** [LuxCoreRender/BlendLuxCore#831]
.blend file: any, screenshot has the default cube scene which gets created upon opening blender.

Steps to reproduce:
(Parenthesized steps mean pre-steps, which are probably not necessary. Bold steps are the main steps.)

(-Have older Windows, older than the newest build as of writing this.)
(-Download+install BlendLuxCore normally, using the zipped version.)
**-Have Windows 11 (Home) on version 22H2, build 22621.1848
-Download+install BlendLuxCore normally, using the zipped version from https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest)
-Open blender
-Set the render engine to LuxCoreRender**

Screenshots or rendered images:
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/73956350/69ef564f-c7f6-4c8d-be36-df71eacaf557)
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/73956350/bc147805-5fff-4686-9aa9-29e550ca5487)

Error message from Blender console:
OpenCL driver API error (code: -1, file:D:\a\1\Luxcore\src\luxrays\devices\ocldevice.cpp, line: 89): CL_DEVICE_NOT_FOUND

Additional information:
It all worked fine before windows updated my machine. It stopped working after windows updated.
The viewport display this message, as well as the render window.
Cycles, Eevee & Workbench work just fine.
I don't have a D: drive and if I connect an external drive, it is D:, but there is no such folder as the one mentioned in the error message.
I have never (in the time of using LuxCore) used a different external drive than that one.
Kinda off topic, but Visual Studio Code Insiders also stopped working after the update, so it probably isn't just LuxCore related.

OS: Windows 11 Home, build 22621.1848
Blender version: 3.5
LuxCore version: 2.61

PC Specs:
GPU: GTX 1650 for laptops (4GB VRAM) (Selected to be rendered with)
CPU: AMD Ryzen 7 3750H for laptops
RAM: 16GB

**Comment by odil24** [comment]
Are you tried also update graphics driver to latest one?

**Comment by Lunarien** [comment]
> Are you tried also update graphics driver to latest one?

I just updated my graphics driver and restarted my pc. It still doesn't work and the error is the same.

**Comment by WACOMalt** [comment]
Same issue here on latest windows 11 update. Intel ARC drivers are up to date. Windows 11 build 22621.

**Comment by Lunarien** [comment]
I updated the first comment so that it has my PC's specifications at the end. I use the GPU for (attempting) rendering.
