### ISSUE TITLE
Lights not displaying at in scene at all no matter what I do

### ISSUE THREAD

**Issue by kingdopamine** [LuxCoreRender/BlendLuxCore#833]
I've gone through every single luxcore setting in blender. Even if I set the power of the light to 200MW, it has absolutely no affect on the scene... can't figure out what on earth is wrong.
I have checked in cycles and the light is definitely active

OS:  macOs 12.6.2
Blender version: 3.5
LuxCore version: 2.93.18

**Comment by MigCurto** [comment]
There's no BlendLuxCore 2.93, for Blender 3.5 you need to use the latest alpha build 2.6:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest

**Comment by neo2068** [comment]
Normally, in BlendLuxCore the camera has auto exposure enabled. If you only have one light, a change in brightness will not be visible. Please change the camera parameter to a manual exposure mode.
