### ISSUE TITLE
Render error with new 2.7beta in blender 3.6

### ISSUE THREAD

**Issue by sarmath123** [LuxCoreRender/BlendLuxCore#834]
File "C:\Users\sarma\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BlendLuxCore\export\mesh_converter.py", line 113, in convert
    mesh_definitions = luxcore_scene.DefineBlenderMesh(mesh_key, loopTriCount, loopTriPtr, loopTriPolyPtr, loopPtr,
Boost.Python.ArgumentError: Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, bool, list, list, int, int, NoneType, tuple, list, NoneType)
did not match C++ signature:
    DefineBlenderMesh(class luxcore::detail::SceneImpl * __ptr64, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, class boost::python::api::object, class boost::python::api::object, unsigned __int64, unsigned int, class boost::python::tuple, class boost::python::api::object, class boost::python::api::object)
    DefineBlenderMesh(class luxcore::detail::SceneImpl * __ptr64, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, class boost::python::api::object, class boost::python::api::object, unsigned __int64, unsigned int, class boost::python::api::object, class boost::python::tuple, class boost::python::api::object, class boost::python::api::object)

**Comment by neo2068** [comment]
There is a mismatch between the LuxCore library and BlendLuxCore. Please retest with the latest release. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1). Please retest again.

**Comment by sarmath123** [comment]
Thank you.  Its working Ok.

sob., 1 lip 2023 o 15:51 Michael Klemm ***@***.***>
napisał(a):
