### ISSUE TITLE
Error Version BlendLuxCore 2.7

### ISSUE THREAD

**Issue by maljos** [LuxCoreRender/BlendLuxCore#835]
.blend file: 

Steps to reproduce:
Only render o preview default scene (cube)

Error message from Blender console:

    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, bool, list, list, int, int, list, tuple, list, NoneType)
did not match C++ signature:

    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::tuple, boost::python::api::object, boost::python::api::object)

    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::api::object, boost::python::tuple, boost::python::api::object, boost::python::api::object)

OS: Linux Manjaro
Blender version: 3.6
LuxCore version: 3.7

![2023-07-01_10-11](https://github.com/LuxCoreRender/BlendLuxCore/assets/3738917/35a8a364-df22-4ec4-91db-7a04a7f40a72)

**Comment by neo2068** [comment]
There is a mismatch between the LuxCore library and BlendLuxCore. Please retest with the latest release. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1). Please retest again.

**Comment by maljos** [comment]
Ok thanks

**Comment by maljos** [comment]
Error en preview render

* -------------------------------------------------------------------------------------------------------------------------------------------
* Registered MESHmachine 0.13.0 with 2 plug libraries
 • plug library: Examples
 • plug library: MyPlugs
Registered MACHIN3tools 1.5.0 with 21 tools, 1 pie menu
BlendLuxCore 2.7beta registered (with pyluxcore 2.6)
Updating device list
==================================================
[Engine/Viewport] New session
[Exporter] Creating session
[SDL][27.531] Define ImageMap: NamedObject
[SDL][27.531] Camera type: perspective
[SDL][27.531] Camera position: Point[4.93234, -2.17855, 2.68522]
[SDL][27.531] Camera target: Point[4.11352, -1.81688, 2.23944]
[SDL][27.531] Camera clipping plane disabled
WARNING: Material "Material": Missing node tree
139938094581512
[SDL][27.533] Material definition: 139938094581512
[SDL][27.533] Scene objects count: 1
[SDL][27.533] Light definition: 139938094915592
[SDL][27.533] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][27.561] Configuration: 
[LuxCore][27.561]   path.pathdepth.total = 7
[LuxCore][27.561]   path.pathdepth.diffuse = 5
[LuxCore][27.561]   path.pathdepth.glossy = 5
[LuxCore][27.561]   path.pathdepth.specular = 6
[LuxCore][27.561]   path.hybridbackforward.enable = 0
[LuxCore][27.561]   path.hybridbackforward.partition = 0.8
[LuxCore][27.561]   path.hybridbackforward.glossinessthreshold = 0.049
[LuxCore][27.561]   rtpathcpu.zoomphase.size = 4
[LuxCore][27.561]   rtpathcpu.zoomphase.weight = 0
[LuxCore][27.561]   renderengine.type = "RTPATHCPU"
[LuxCore][27.561]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][27.561]   film.width = 785
[LuxCore][27.561]   film.height = 874
[LuxCore][27.561]   film.filter.type = "NONE"
[LuxCore][27.561]   film.filter.width = 1.5
[LuxCore][27.561]   lightstrategy.type = "LOG_POWER"
[LuxCore][27.561]   scene.epsilon.min = 1e-05
[LuxCore][27.561]   scene.epsilon.max = 0.1
[LuxCore][27.561]   path.albedospecular.type = "REFLECT_TRANSMIT"
[LuxCore][27.561]   path.albedospecular.glossinessthreshold = 0.05
[LuxCore][27.561]   film.opencl.enable = 1
[LuxCore][27.561]   film.opencl.device = 1
[LuxCore][27.561]   path.forceblackbackground.enable = 0
[LuxCore][27.561]   renderengine.seed = 1
[LuxCore][27.561]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][27.561]   film.outputs.0.index = 0
[LuxCore][27.561]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][27.561]   film.outputs.1.type = "ALBEDO"
[LuxCore][27.561]   film.outputs.1.filename = "ALBEDO.exr"
[LuxCore][27.561]   film.imagepipelines.000.0.type = "NOP"
[LuxCore][27.561]   film.imagepipelines.000.1.type = "TONEMAP_LINEAR"
[LuxCore][27.561]   film.imagepipelines.000.1.scale = 1
[LuxCore][27.561]   film.imagepipelines.000.2.type = "OPTIX_DENOISER"
[LuxCore][27.561]   film.imagepipelines.000.2.sharpness = 0
[LuxCore][27.561]   film.imagepipelines.000.2.minspp = 1
[LuxCore][27.561]   film.imagepipelines.000.radiancescales.0.enabled = 1
[LuxCore][27.561]   film.imagepipelines.000.radiancescales.0.globalscale = 1
[LuxCore][27.561]   film.imagepipelines.000.radiancescales.0.rgbscale = 1 1 1
[LuxCore][27.561]   batch.haltspp = 0 0
[LuxCore][27.561]   batch.halttime = 0
[LuxCore][27.561] File Name Resolver Configuration: 
Export took 0.0 s
[LuxCore][27.562] Film resolution: 785x874
[SDL][27.562] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][27.562] Image pipeline: film.imagepipelines.000
[SDL][27.562] Image pipeline step 0: NOP
[SDL][27.562] Image pipeline step 1: TONEMAP_LINEAR
[SDL][27.562] Image pipeline step 2: OPTIX_DENOISER
[SDL][27.562] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png]
[SDL][27.562] Film output definition: ALBEDO [ALBEDO.exr]
[LuxRays][27.563] OpenCL support: enabled
[LuxRays][27.563] OpenCL Platform 0: NVIDIA CUDA
[LuxRays][27.563] CUDA support: enabled
[LuxRays][27.563] CUDA support: available
[LuxRays][27.563] CUDA driver version: 12.10
[LuxRays][27.563] CUDA device count: 1
[LuxRays][27.563] Optix support: available
[LuxRays][27.563] Device 0 name: Native
[LuxRays][27.563] Device 0 type: NATIVE_THREAD
[LuxRays][27.563] Device 0 compute units: 1
[LuxRays][27.563] Device 0 preferred float vector width: 4
[LuxRays][27.563] Device 0 max allocable memory: 17592186044415MBytes
[LuxRays][27.563] Device 0 max allocable memory block size: 17592186044415MBytes
[LuxRays][27.563] Device 0 has out of core memory support: 0
[LuxRays][27.563] Device 1 name: NVIDIA GeForce GTX 1660 SUPER
[LuxRays][27.563] Device 1 type: OPENCL_GPU
[LuxRays][27.563] Device 1 compute units: 22
[LuxRays][27.563] Device 1 preferred float vector width: 1
[LuxRays][27.563] Device 1 max allocable memory: 5935MBytes
[LuxRays][27.563] Device 1 max allocable memory block size: 1483MBytes
[LuxRays][27.563] Device 1 has out of core memory support: 0
[LuxRays][27.563] Device 2 name: NVIDIA GeForce GTX 1660 SUPER
[LuxRays][27.563] Device 2 type: CUDA_GPU
[LuxRays][27.563] Device 2 compute units: 64
[LuxRays][27.563] Device 2 preferred float vector width: 1
[LuxRays][27.563] Device 2 max allocable memory: 5935MBytes
[LuxRays][27.563] Device 2 max allocable memory block size: 17592186044415MBytes
[LuxRays][27.563] Device 2 has out of core memory support: 1
[LuxRays][27.563] Device 2 CUDA compute capability: 7.5
[LuxRays][27.563] Creating 4 intersection device(s)
[LuxRays][27.563] Allocating intersection device 0: Native (Type = NATIVE_THREAD)
[LuxRays][27.563] Allocating intersection device 1: Native (Type = NATIVE_THREAD)
[LuxRays][27.563] Allocating intersection device 2: Native (Type = NATIVE_THREAD)
[LuxRays][27.563] Allocating intersection device 3: Native (Type = NATIVE_THREAD)
[LuxCore][27.563] Configuring 4 CPU render threads
[LuxRays][27.564] Preprocessing DataSet
[LuxRays][27.564] Total vertex count: 24
[LuxRays][27.564] Total triangle count: 12
[LuxRays][27.564] Preprocessing DataSet done
[LuxRays][27.564] Adding DataSet accelerator: EMBREE
[LuxRays][27.564] Total vertex count: 24
[LuxRays][27.564] Total triangle count: 12
[LuxRays][27.565] EmbreeAccel build time: 0ms
Writing: /tmp/blender.crash.txt
[1]    606376 segmentation fault (core dumped)  /mnt/app3d/blender360/blender

**Comment by leonidaltman** [comment]
Same thing for me on MacOs Ventura. Tried latest build and 2.7 for all Blender versions starting from 3.3 to 3.6. Nothing.

**Comment by odil24** [comment]
It was resolved with installation of respective version 2.7beta1
