### ISSUE TITLE
Please keep both 2.61 alpha and 2.7beta downlods

### ISSUE THREAD

**Issue by MigCurto** [LuxCoreRender/BlendLuxCore#836]
Hi, since new release in only Blender 3.6 compatible, wouldn't it make sense to keep the older latest release as unchanged from 8th April as a separate download?
More so since there isn't Mac version yet and usually takes a bit longer.
ATM there isn't a working downloadable version for Mac

**Comment by odil24** [comment]
I should close as it is not responded!
