### ISSUE TITLE
Luxcorerender 2.7b error in Blender 3.6.0 (Ubuntu-Studio 22.04 LTS)

### ISSUE THREAD

**Issue by FMHR78** [LuxCoreRender/BlendLuxCore#837]
As soon as I click the rendered Display render preview button Blender crashes.

My system: 
Ubuntu-Studio 22.04
AMDGPU 15.18.13 drivers.
Blender 3.6.0
Luxcorerender 2.7 beta. 

[Luxcorerender error.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/11937925/Luxcorerender.error.txt)
or
[https://pastebin.com/LfLncupW](url)

**Comment by FMHR78** [comment]
Downloading and installing the latest build gave me this error, Blender will not crash though, it will just wont render anything.

[Luxcorerender error_.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/11938075/Luxcorerender.error_.txt)

**Comment by DionXein** [comment]
Got same error on Win 11. (Blender 3.6 LTS, Latest build BlendLuxCore 2.71)

**Comment by neo2068** [comment]
I can reproduce the error and have to check where the problem is.

**Comment by Dez1gner** [comment]
On Linux, rendering in the viewport does not start.
The console says: "Segmentation fault", see the report file.
This is what the report file shows: https://pastebin.com/MH86q8wP

**Comment by p-mic** [comment]
On Ubuntu 22.04.3 LTS (i7-7700K CPU, Mesa Intel® HD Graphics 630), Blender 3.6.4 with LuxCoreRender 2.7 beta2

Does not render - objects don't have colors - in both: display render preview and render output

I used the simplest scene (box, area light, luxcore material).
When changing light type, or area light has 'Laser' checkbox on (in display render preview), blender crashes.

Terminal message: "Memory protection violation (memory dump)"
File crash.txt example content:
-----------------------
# Blender 3.6.4, Commit date: 2023-09-25 13:24, Hash 21bfc5e7fe3f
bpy.context.object.data.type = 'SPOT'  # Property
bpy.context.object.data.type = 'SUN'  # Property
Saved "lux_simple.blend"  # Info
bpy.context.object.data.type = 'POINT'  # Property
Saved "lux_simple.blend"  # Info
bpy.context.space_data.shading.type = 'RENDERED'  # Property

# backtrace

# Python backtrace
  File "/home/mp/.config/blender/3.6/scripts/addons/BlendLuxCore/engine/viewport.py", line 13 in start_session
----------------
