### ISSUE TITLE
 Blender 3.6

### ISSUE THREAD

**Issue by paulocferreira3d** [LuxCoreRender/BlendLuxCore#839]
Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, bool, list, list, int, int, NoneType, tuple, list, NoneType)
did not match C++ signature:
    DefineBlenderMesh(class luxcore::detail::SceneImpl * __ptr64, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, class boost::python::api::object, class boost::python::api::object, unsigned __int64, unsigned int, class boost::python::tuple, class boost::python::api::object, class boost::python::api::object)
    DefineBlenderMesh(class luxcore::detail::SceneImpl * __ptr64, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, unsigned __int64, class boost::python::api::object, class boost::python::api::object, unsigned __int64, unsigned int, class boost::python::api::object, class boost::python::tuple, class boost::python::api::object, class boost::python::api::object)

Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz   3.50 GHz
16GB
Gforce 690GTX

Blender 3.6

has no preview and does not render

![Captura de Tela (33)](https://github.com/LuxCoreRender/BlendLuxCore/assets/99772524/a12ec0bc-bb1f-49a4-8fdf-259155dff6b8)

**Comment by MattRM2** [comment]
Hi,

Same issue in 3.6. Devs, could you make a fix or tell us which version to take that works ?

Thx

**Comment by odil24** [comment]
Download latest version from here for Blender 3.6 LTS:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1

**Comment by MattRM2** [comment]
Hi Odil24,

Thank you, work very well !!!

Matt

**Comment by galferter** [comment]
Hi, i have the same problem and i downloaded the files today.
NVIDIA GeForce RTX 3060
Blender version: 3.6.0, branch: blender-v3.6-release, commit date: 2023-06-27 08:08, hash: c7fc78b81ecb, type: release
build date: 2023-06-27, 08:27:30
platform: 'Windows-10-10.0.19045-SP0'

**Comment by neo2068** [comment]
@galferter #835 is a different problem. There Blender crashes due to a seg fault under Linux. Here there is a mismatch between the installed Luxcore library and Blendluxcore, i.e. an error message with wrong C++ signature. For windows 10 the latest version should work. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/download/blendluxcore_v2.7beta1/BlendLuxCore-v2.7beta1-win64.zip)

**Comment by galferter** [comment]
o.k. my mistake it really works. 
I took the "BlendLuxCore-latest-win64.zip" that has the same date and that is linked at https://luxcorerender.org/

**Comment by paulocferreira3d** [comment]
BlendLuxCore v2.7beta1 -> this version is working now ... tks

Em dom., 16 de jul. de 2023 às 14:34, Michael Klemm <
***@***.***> escreveu:
