### ISSUE TITLE
Latest Experimental

### ISSUE THREAD

**Issue by ebutts531** [LuxCoreRender/BlendLuxCore#840]
Running Linux. The addon  detects the wrong model of my GPU. I have a 3080 RTX, and the addon says I have a 2080 super. Blender itself under system in preference detects the right model of my GPU.

**Comment by neo2068** [comment]
The addon only shows the information which it gets from the openCL driver. What do you get when you execute clinfo in a console?

**Comment by odil24** [comment]
I should close as it is not responded!
