### ISSUE TITLE
Error: | 'Mesh' object has no attribute 'loop_triangle_polygons' ()

### ISSUE THREAD

**Issue by Fatifer** [LuxCoreRender/BlendLuxCore#841]
Cant render anything.
Default Cube Scene
Blender 3.5
Luxcore 2.7 Beta

![grafik](https://github.com/LuxCoreRender/BlendLuxCore/assets/22914711/4e1bd3cc-d424-4959-8636-704fb197e509)

**Comment by neo2068** [comment]
The latest BlendLuxCore version, i.e. LuxCore 2.7 Beta, is only compatible with Blender 3.6.
