### ISSUE TITLE
BlendLuxCore Latest: argument types of Scene.DefineBlenderMesh does not match C++ signature (blender3.6)

### ISSUE THREAD

**Issue by TobiasP92** [LuxCoreRender/BlendLuxCore#842]
I wanted to test BlendLuxCore with the latest version of blender and got the following Error:

ERROR: Python argument types in

Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, bool, list, list, int, int, NoneType, tuple, list, NoneType)

did not match C++ signature:

DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::tuple, boost::python::api::object, boost::python::api::object)

DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::api::object, boost::python::tuple, boost::python::api::object, boost::python::api::object)

Traceback (most recent call last):
  
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/engine/viewport.py", line 76, in view_update
    engine.session = engine.exporter.create_session(depsgraph, context, engine=engine)
    
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/export/__init__.py", line 110, in create_session
    instances = self.object_cache2.first_run(self, depsgraph, view_layer, engine, luxcore_scene,
  
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 295, in first_run
    self._convert_obj(exporter, dg_obj_instance, obj, depsgraph, luxcore_scene,
  
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 392, in _convert_obj
    exported_stuff = self._convert_mesh_obj(exporter, dg_obj_instance, obj, obj_key, depsgraph,
  
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 463, in _convert_mesh_obj
    exported_mesh = mesh_converter.convert(obj, mesh_key, depsgraph, luxcore_scene,
  
  File "~/.config/blender/3.6/scripts/addons/BlendLuxCore/export/mesh_converter.py", line 113, in convert
    mesh_definitions = luxcore_scene.DefineBlenderMesh(mesh_key, loopTriCount, loopTriPtr, loopTriPolyPtr, loopPtr,
Boost.Python.ArgumentError: Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, int, int, bool, list, list, int, int, NoneType, tuple, list, NoneType)
did not match C++ signature:
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::tuple, boost::python::api::object, boost::python::api::object)
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object, boost::python::api::object, unsigned long, unsigned int, boost::python::api::object, boost::python::tuple, boost::python::api::object, boost::python::api::object)

The error appears both on windows and linux with the latest blender version (3.6) and the latest BlendLuxCore build (2.7 beta).

**Comment by odil24** [comment]
Are you tested from this link?
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1
