### ISSUE TITLE
PathOCL kernel OpenCL program compilation error. Double type is not supported on this platform.

### ISSUE THREAD

**Issue by iwqqw** [LuxCoreRender/BlendLuxCore#844]
I'm tring to render something with LuxRender ,but when it compiled the OpenCL Program it occur an error.
terminal says error: Double type is not supported on this platform.

Can i compile it without the Double type that it says?

Blender console content:
[console_output.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/12182373/console_output.txt)

Hardware:
CPU:i7-11700F
GPU:Intel ARC A770 (16G)
RAM:32G

**Comment by odil24** [comment]
LuxCore Render does not supported Intel Arc GPUs as Cycles renderer.
