### ISSUE TITLE
Blender 3.6 cannot install BlendLuxCore2.7 plugin

### ISSUE THREAD

**Issue by ODD-D** [LuxCoreRender/BlendLuxCore#846]
Prompt for errors when installing plugins:
<img width="818" alt="image" src="https://github.com/LuxCoreRender/BlendLuxCore/assets/141797004/ec87e8df-1344-4869-bb58-74479f417822">

Attempted to download several versions, but they were unable to use them
<img width="309" alt="image" src="https://github.com/LuxCoreRender/BlendLuxCore/assets/141797004/9a6b1f85-bb92-4fe8-ae33-5a4e42fc6eef">

**Comment by Skytale23** [comment]
> Prompt for errors when installing plugins: <img alt="image" width="818" src="https://user-images.githubusercontent.com/141797004/259285584-ec87e8df-1344-4869-bb58-74479f417822.png">
> 
> Attempted to download several versions, but they were unable to use them <img alt="image" width="309" src="https://user-images.githubusercontent.com/141797004/259285723-9a6b1f85-bb92-4fe8-ae33-5a4e42fc6eef.png">

I'd like to report the same error message - using Blender 3.6.2 on a Mac M1 OS 14.1.1

**Comment by odil24** [comment]
@ODD-D @Skytale23 

Download respective version here:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1
