### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by eMenshawi** [LuxCoreRender/BlendLuxCore#848]
when i try to render nothing shows and it gives this error ( 'Mesh' object has no attribute 'loop_triangle_polygons' )

**Comment by odil24** [comment]
This has been posted already here:
https://github.com/LuxCoreRender/BlendLuxCore/issues/841

Please, don't post the same issues over again.

Fix to your issue is downloading latest version from here:
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.7beta1

**Comment by eMenshawi** [comment]
Did that and still gets the same error.

**Comment by eMenshawi** [comment]
And here's what happens when i try to enable it on the latest Blender version.
![Screenshot 2023-08-24 at 3 11 53 PM](https://github.com/LuxCoreRender/BlendLuxCore/assets/143083145/395316e0-7fb8-4bb6-93cb-abeab1d7e081)

**Comment by odil24** [comment]
> And here's what happens when i try to enable it on the latest Blender version. ![Screenshot 2023-08-24 at 3 11 53 PM](https://user-images.githubusercontent.com/143083145/262968562-395316e0-7fb8-4bb6-93cb-abeab1d7e081.png)

It is MacOS?

**Comment by eMenshawi** [comment]
Yes.

**Comment by odil24** [comment]
> Yes.
Check this out:
https://github.com/LuxCoreRender/BlendLuxCore/issues/845
