### ISSUE TITLE
I am not able to activate the luxcore plugin after installing it int he blender software

### ISSUE THREAD

**Issue by 1997Bhavesh** [LuxCoreRender/BlendLuxCore#853]
![Screenshot 2023-09-04 151649](https://github.com/LuxCoreRender/BlendLuxCore/assets/144011716/4c187d48-3293-4eac-9125-e18878486fff)
I have already downloaded the redistributable Packages still I am not able to activate the plugin

**Comment by 1997Bhavesh** [comment]
> Hi. Please, post your:
> 
> * OS
> * Blender version
> * Luxcore exact version

Hello,
My OS version is windows 11
blender version is 3.6.2
Luxcore version is BlendLuxCore v2.6

**Comment by MigCurto** [comment]
> > Hi. Please, post your:
> > 
> > * OS
> > * Blender version
> > * Luxcore exact version
> 
> Hello, My OS version is windows 11 blender version is 3.6.2 Luxcore version is BlendLuxCore v2.6

Please note:

Blender 3.6.x you'll need to use BlendLuxCore beta 2.7
For Blender 3.3.x to 3.5.x you'll need BlendLuxCore alpha 2.6 (unfortunately there's no working download link for that)

**Comment by odil24** [comment]
I should close as it is not responded!
