### ISSUE TITLE
The luxcoreRendder can not install on Blender 4.0

### ISSUE THREAD

**Issue by ump45a** [LuxCoreRender/BlendLuxCore#858]
.blend file: 

Steps to reproduce:
![1](https://github.com/LuxCoreRender/BlendLuxCore/assets/47036626/f25bc246-cc52-4fac-9865-153c6dcaf5bc)

Screenshots or rendered images

Error message from Blender console:

OS: 
Blender version:4.0beta
LuxCore version:2.7beta2
![1](https://github.com/LuxCoreRender/BlendLuxCore/assets/47036626/7cac459d-2632-4578-b885-839daa1f00ec)

**Comment by foreachthing** [comment]
4.0 is not supperted yet.
https://github.com/LuxCoreRender/BlendLuxCore#supported-blender-versions

**Comment by neo2068** [comment]
BlendLuxCore version 2.8 alpha is the WIP version for Blender 4.x. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1)
