### ISSUE TITLE
luxcore can not install on the blender4.0beta

### ISSUE THREAD

**Issue by ump45a** [LuxCoreRender/BlendLuxCore#859]
luxcore can not install on the blender4.0beta
![1](https://github.com/LuxCoreRender/BlendLuxCore/assets/47036626/fb301976-200a-4566-bad5-1500fb1787f1)

**Comment by neo2068** [comment]
BlendLuxCore version 2.8 alpha is the WIP version for Blender 4.x. [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1)
