### ISSUE TITLE
it doesn work

### ISSUE THREAD

**Issue by IanGadielP** [LuxCoreRender/BlendLuxCore#865]
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/154022495/910c9e52-632c-42bf-a5ca-d758c6290102)
![Screenshot 2023-12wgeqeg45-16 164113](https://github.com/LuxCoreRender/BlendLuxCore/assets/154022495/e80922a0-3473-49b3-874c-f893e6575c6b)

**Comment by odil24** [comment]
@neo2068 close issue
