### ISSUE TITLE
Some Issues in blender 4.0

### ISSUE THREAD

**Issue by vasilis2017** [LuxCoreRender/BlendLuxCore#869]
. black dots when i use in compositing filter->box sharpen
. black spots in normal , when the camera angle decreases
. crash LoL ,when i change  the ui regions (particularly, when in startup.blend I change the position of the outliner)
(and a plea,if it could be done ,something similar to vraydirt or in arnold Curvature).
It's not flattery, I've used many renderers, this, is the best rendering machine, not because it's free, simply because I don't use photoshop!

**Comment by odil24** [comment]
Hi. Post your OS, Blender version with hash sum and your PC specs.

**Comment by vasilis2017** [comment]
Windows 10,blender 4.02,amd 3900x, rtx 2080 super 8gb, 32gb ram.

**Comment by odil24** [comment]
Can you make step by step video from 0 to final about your issue?

**Comment by vasilis2017** [comment]
![1 1](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/8013ed36-b4dc-43f4-b211-ab3a48fc3468)
![1 2](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/379e389b-d6be-4d65-bb29-8f561df04652)
For the first (filter)
![2 1](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/c106f7b4-764e-476a-b326-bf6fa2cd6bff)
![2 2](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/7b82fb3d-0ac5-4e36-b1e6-3ecf25734634)
For the second (normal map)
As for the third one, now I can't use it at all - always crash

I hope this helps (I've never used a video recorder before)
thanks !

**Comment by vasilis2017** [comment]
Glossy Translucent Material **![Uploading 4.jpg…]()**

**Comment by vasilis2017** [comment]
in Glossy Translucent Material node missing **output**
![4](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/2cf2290c-a2f7-45c6-a650-4c15ee6e8645)

**Comment by odil24** [comment]
> in Glossy Translucent Material node missing **output** ![4](https://private-user-images.githubusercontent.com/150131684/292895512-2cf2290c-a2f7-45c6-a650-4c15ee6e8645.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTYyNTksIm5iZiI6MTcwMzYxNTk1OSwicGF0aCI6Ii8xNTAxMzE2ODQvMjkyODk1NTEyLTJjZjIyOTBjLWEyZjctNDVjNi1hNjUwLTRjMTVlZTZlODY0NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxODM5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQxYTY0M2NlZGY0MTJlZDdkMzYzODRkOWZmM2QwMjYyODU5OTI0OTRmNWE4ZGU2NWM1MWE3Yjc4NzNjY2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t4gl50x6M3GGc9XCCdjoL1diZvqJorjTGCrTYukmqIo)

Already fixed issue on my PR patch:
https://github.com/LuxCoreRender/BlendLuxCore/pull/873/commits/cc1b40b448f3bc29be7453d7006d898ef697c503

**Comment by vasilis2017** [comment]
With CTRL+N (new file -> General) crash.

**Comment by odil24** [comment]
It is not by LuxCore it also always happen with Blender 3.3 + also as always. Do not know what was happen always. BF devs are need to revisit

**Comment by vasilis2017** [comment]
CTRL+N (new file -> General)  with blender 4.1 work perfect !
