### ISSUE TITLE
All nodes stop working if you click on a check mark or button, HELP!!!!!!!

### ISSUE THREAD

**Issue by wizard3376** [LuxCoreRender/BlendLuxCore#875]
All nodes stop working if you click on a checkmark or button, for example, if a node has (Metal Material) Enabled (Anisotropic Roughness) Or (Fresnel Texture) then you cannot change the color or Roughness and Opacity, even rebooting does not help, this is the error you get

Material "Material.003": 'bpy_prop_collection[key]: key "V-Roughness" not found'

this is an error for everyone, almost similar, for example this is an error from a node (Disney Material)
Material "Material.003": 'bpy_prop_collection[key]: key "Film Amount" not found'

Checkmarks and buttons not only do not allow you to change the color, but they themselves do not work
![Снимок экрана (46)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/a99f671c-bb32-44ee-a055-ab5de0d3b69c)

OS: Windows 10
Blender version: 4.0.2
LuxCore version: 2.7

**Comment by neo2068** [comment]
This is a known problem caused by the changed python API in Blender 4.0 . Please test the latest addon in the for_blender_4 branch. It should resolve the issue.

**Comment by wizard3376** [comment]
I'm testing this version of LoxCore, but I'm having the same problems.
https://blenderartists.org/t/luxcorerender-2-7-beta2-for-blender-4-0-only-windows-for-now/1409371?u=odil24

**Comment by odil24** [comment]
@wizard3376 @neo2068 My latest PR patchs will fixes issues:
https://github.com/LuxCoreRender/BlendLuxCore/pull/876

**Comment by wizard3376** [comment]
I can't install LuxCore

I downloaded the file with the new version of LuxCore, @neo2068 gave the link, here it is

https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4

but there is an error

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
mod = importlib.import_module(module_name)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4_init.py", line 66, in
raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-for_blender_4.bin' (C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4\bin_init_.py)

the error indicates a problem importing the pyluxcore module into Blender. Error "Failed to import pyluxcore

What to do? 0__0

**Comment by odil24** [comment]
> I'm testing this version of LoxCore, but I'm having the same problems.
> https://blenderartists.org/t/luxcorerender-2-7-beta2-for-blender-4-0-only-windows-for-now/1409371?u=odil24
> 
> 
> 

Are you downloaded this build from link? If so and if you did not deleted yet that downloaded build it will works with overwriting my PR patch files on it (like merge my patch files with existing ones)

**Comment by wizard3376** [comment]
I tried to install the new LuxCore from the link

https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4

but got the same error.

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
mod = importlib.import_module(module_name)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4_init.py", line 66, in
raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Maybe I'm doing something wrong? 0<_0?

**Comment by odil24** [comment]
> I tried to install the new LuxCore from the link
> 
> https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4
> 
> but got the same error.
> 
> Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable mod = importlib.import_module(module_name) File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in call_with_frames_removed File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4_init.py", line 66, in raise Exception(msg + "\n\nImportError: %s" % error) from None Exception:
> 
> Maybe I'm doing something wrong? 0<_0?

Download latest release: https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1

**Comment by wizard3376** [comment]
WOW!!!
LuxCore WORKS!!! THANK YOU SO MUCH @odil24 and @neo2068 and @Sharlybg FOR YOUR HELP, HAPPY NEW YEAR !!!
