### ISSUE TITLE
Blender V4 Luxcorerender Online Library thumbnails bar Problem

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#877]
.blend file: 
Default cube blender startup

Steps to reproduce:
Luxcorerender Online Library thumbnails bar is no longer visible .Just enable LOL in the blender NPanel. The bar
on top shouldn't be visible unlike previous versions.

Screenshots or rendered images:
![image (7)](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/9e03fdb8-e4a0-4814-8534-633b927cf6df)

Error message from Blender console:

`Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\operators\lol\assetbar.py", line 59, in draw_callback_2d
    draw_callback_2d_search(self, context)
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\operators\lol\assetbar.py", line 143, in draw_callback_2d_search
    ui_bgl.draw_rect(assetbar_props.x, assetbar_props.y - assetbar_props.height, assetbar_props.width,
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\draw\lol\viewport.py", line 66, in draw_rect
    bgl.glEnable(bgl.GL_BLEND)
TypeError: 'NoneType' object is not callable`

OS: Windows 10 Pro
Blender version: Blender 4.0.2
LuxCore version: 2.7

**Comment by neo2068** [comment]
Did you test it with the for_blender_4 branch? The LuxCore Library has been fixed a few weeks ago.

**Comment by Sharlybg** [comment]
I have downloaded this and it doesn't seems to be a valide
build. Can I get a Link ?
![Blendv4](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/d0e25a89-aaf6-4381-9f59-cdc1ee69f2b3)

**Comment by Sharlybg** [comment]
Edit I have overwritted file in previous version and it is working !
