### ISSUE TITLE
Lightgroup Node mixer is empty 

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#879]
.blend file: 
[B44 bugs.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/13793252/B44.bugs.zip)

Steps to reproduce:
When the blend file is open click on create/Update Light Grup Nodes button in
the Npanel : 
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/0ad337db-46eb-4158-9901-d85d3efe9f7e)

Screenshots or rendered images:
Old version :
![LGroup](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/2a268b32-cc40-4c70-85a0-a58957a1a942)

New Version :
![LGroup_New](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/f0b402ac-8c72-4df8-8e68-74e11a38f827)

Error message from Blender console:
`Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\operators\lightgroups.py", line 281, in execute
    scene.node_tree.links.new(renderlayer_node.outputs["ALBEDO"], mixer_node.inputs["ALBEDO"])
KeyError: 'bpy_prop_collection[key]: key "ALBEDO" not found'
Error: Python: Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore\operators\lightgroups.py", line 281, in execute
    scene.node_tree.links.new(renderlayer_node.outputs["ALBEDO"], mixer_node.inputs["ALBEDO"])
KeyError: 'bpy_prop_collection[key]: key "ALBEDO" not found'`

OS: W10 pro
Blender version: Blender 4.0.2
LuxCore version: for Blender4 branch

**Comment by neo2068** [comment]
This issue is fixed with commit ebae228
