### ISSUE TITLE
Blender v4 branch Hair issue with children

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#880]
.blend file: 
[B44 hair_bugs.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/13793381/B44.hair_bugs.zip)

Steps to reproduce:
Open the Blend file and start viewport rendering or final F12 render.
while the children option is enable the hair will not be visible in render.

Screenshots or rendered images:
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/1c292111-22e3-41bd-84cd-9b7b54813c5f)

OS: W10 Pro
Blender version: Blender 4.0.2
LuxCore version: for blender4 branch

**Comment by neo2068** [comment]
Hair data structure got changed in Blender 3.6. I am working on a fix together with curve hair support.

**Comment by odil24** [comment]
Fixed: https://github.com/LuxCoreRender/BlendLuxCore/pull/881/commits/e558dcb13374c40fc97d1679e68939eb43b610c2

**Comment by Sharlybg** [comment]
I can Confirm it is fixed. 
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/7d991c90-5622-4704-8b86-9dd0a82999c3)
