### ISSUE TITLE
F12(render) crash BlendLuxCore v2.8alpha1

### ISSUE THREAD

**Issue by vasilis2017** [LuxCoreRender/BlendLuxCore#882]
Immediately crashes, even with the initial settings of blender without addons
also 
. ctrl+new file
. material preview

Blender version: 4.0.2
LuxCore version: v2.8alpha1

**Comment by neo2068** [comment]
The builds are not ready yet. I have to check which part of the pipeline has failed. Which os are you using? Is there an error message in the console?

**Comment by vasilis2017** [comment]
windows 10
(I am new to blender - so I apologize if I don't understand something)
![1](https://github.com/LuxCoreRender/BlendLuxCore/assets/150131684/5f247bde-4349-4f08-a67a-9d5a47256561)

**Comment by neo2068** [comment]
I cannot reproduce the crash. Can you recheck with the latest version? [Link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1)

**Comment by vasilis2017** [comment]
. F12 ->  OK
. ctrl+new file -> CRASH
. material preview ->OK

Many thanks for your efforts! best wishes!

**Comment by odil24** [comment]
> . F12 -> OK . ctrl+new file -> CRASH . material preview ->OK
> 
> Many thanks for your efforts! best wishes!

It is known problem by Blender itself not LCR
