### ISSUE TITLE
Lightgroup node generate unwnted layers

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#885]
.blend file: 
[b4_test.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/13903328/b4_test.zip)

Steps to reproduce:
create a new scene and create 2 new light group to be attached to some light source in your 
scene. After a quick render go in compositor and look at the lightgroup node mixer there should
be a lot of new light group layers you didn't created.

Screenshots or rendered images:
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/2e8b4b22-44df-43a5-bf99-a7c97337173f)

Error message from Blender console:
none

OS: w10
Blender version: 4.0.2
LuxCore version: blendluxcore 2.8 alpha 1

**Comment by neo2068** [comment]
There are always 8 light group layers in the compositor because that is the maximum for LuxCore.
