### ISSUE TITLE
Carpaint node preset bug

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/BlendLuxCore#886]
.blend file: 
[CRpaint.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/13903358/CRpaint.zip)

Steps to reproduce:
Load the blend file and turn on render preview while the carpaint node shader is on a preset .
Instead of the normal colored shiny shader carpaint preset you get a default matte shader appearence

Screenshots or rendered images:
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/35496087/101e55fa-90b2-4339-a216-88aa4b07a791)

Error message from Blender console:
None : 

OS: w10
Blender version: 4.0.2
LuxCore version: 2.8 alpha 1

**Comment by odil24** [comment]
@Sharlybg The issue has been fixed

@neo2068 close issue

**Comment by neo2068** [comment]
I fixed the issue in the latest version.
