### ISSUE TITLE
Problem with LuxCore normals, Mark Sharp doesn't work and everything related to normals doesn't work either, HELLP!!!!!!

### ISSUE THREAD

**Issue by wizard3376** [LuxCoreRender/BlendLuxCore#887]
There is a problem with normal, it cannot be fixed, everything will look the same as Shade Smooth,
normal, no way to fix it

Strange, the LuxCore error log shows no errors.

This is when
Shade Auto Smooth \/ \/
![Снимок экрана (175)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/2e818c79-fcd6-42a2-bc87-188f04534d8e)

This is when
Shade Flat \/ \/
![Снимок экрана (174)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/02864698-d3b3-43c1-94d2-e906cb2f5171)

OS:  Windows 10
Blender version: 4.0.2
LuxCore version: 2.8 alpha1

2.8 alpha1 works great but there is one problem namely with normal

**Comment by wizard3376** [comment]
Strange LuxCore error log does not show errors

**Comment by odil24** [comment]
Please, provide us your blend file and add more info. There are have not enough info except screenshots

**Comment by wizard3376** [comment]
Here is the Blend.file https://drive.google.com/file/d/1_Hrnzk4sdgCBM07QkbVBJ9qjfid1L1uc/view?usp=sharing 

Here's a good example, a metal cube, the first render is from Cycles and the second is a curved render from Luxcore, for both I used Shade Auto Smooth and the Weighted Normal modifier. But if you enable Luxcore, the Weighted Normal modifier will stop working and
"Shade Auto Smooth" also stops working.

Cycles V V
![Снимок экрана (178)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/54ffdfce-d6ed-48eb-b502-4327f1c465fa)

LuxCore V V
![Снимок экрана (179)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/250f2275-76c2-4f02-ab78-d675a075fea1)

**Comment by boxfrogman** [comment]
Hey dude, where did you get LuxCore version: 2.8 alpha1?

**Comment by wizard3376** [comment]
Hello, this version was given to me by @odil24

**Comment by wizard3376** [comment]
@boxfrogman There's a problem with "Normal"

**Comment by neo2068** [comment]
@wizard3376 I cannot reproduce the problem with the latest version from here [Download link](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.8alpha1)

This is the render of the example file in BlendLuxCore:
![grafik](https://github.com/LuxCoreRender/BlendLuxCore/assets/17701407/3eb141f1-e566-4692-a518-94974cb1d487)

**Comment by wizard3376** [comment]
@neo2068 THANK YOU!! I just installed 2.8alpha1 using your link and everything worked for me!!
