### ISSUE TITLE
Anisotropy in LuxCore does not work as it should, sharp edges appear, PLEASE HELP

### ISSUE THREAD

**Issue by wizard3376** [LuxCoreRender/BlendLuxCore#892]
LuxCore creates sharp edges where there aren't any.

![Problem with anisotropic surface](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/6decb38c-cbbd-4a38-b42a-c617d336e995)

Here is a render of Cycles.

![Problem with anisotropic surface2](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/82fb17c4-3661-4cbd-ba79-6ff226379c8a)

Cycles doesn't have any problems with anisotropy.

Here is the Blend.file https://drive.google.com/file/d/1KVWK0D5-Z0kuORnmVki-VifjO64lImqW/view?usp=sharing

OS: Windows 10
Blender version: 4.0.2
LuxCore version: 2.8 alpha1

**Comment by boxfrogman** [comment]
How do you generally adjust anisotropy?
![Kettle (192)](https://github.com/LuxCoreRender/BlendLuxCore/assets/156538857/1acce084-8fe1-49a2-a957-9bfce7403b01)

**Comment by wizard3376** [comment]
@boxfrogman With LuxCore you can only “probably” direct anisotropy using UV
https://www.youtube.com/watch?v=FGhPAP0oV9k&t=0s

**Comment by boxfrogman** [comment]
It only got worse
![Снимок экрана (193)](https://github.com/LuxCoreRender/BlendLuxCore/assets/156538857/6d5d85e8-9952-4b34-9d11-c4ffd88bde1d)

**Comment by wizard3376** [comment]
I have the same stripes, but I still don't understand what it is

**Comment by wizard3376** [comment]
I noticed that the "Metal" node does not indicate that there are no UVs on the object.
![UV (195)](https://github.com/LuxCoreRender/BlendLuxCore/assets/133279496/f1342966-8d43-4b8a-9d6b-15acde6454ad)
It seems to me that LuxCore does not see UV

**Comment by odil24** [comment]
Hi. I have tested your blend file also with previous versions of LCR and it has the same problems like in the latest version. So I don't find  any solution for this now.

**Comment by wizard3376** [comment]
@odil24 why DRAVIA. STUDIO managed to create anisotropy without sharp edges?
Could this be due to Subdivision? 
https://www.youtube.com/watch?v=FGhPAP0oV9k

**Comment by yan3dx** [comment]
> Hi @odil24 why DRAVIA. STUDIO managed to create anisotropy without sharp edges? Could this be due to Subdivision? https://www.youtube.com/watch?v=FGhPAP0oV9k

I know, was struggling with Anisotropy in LuxCore, had similar result as in your file. I want to share how I've achieved working anisotropy:
![Screenshot 2024-06-24 170840](https://github.com/LuxCoreRender/BlendLuxCore/assets/158004719/0f3fe075-b449-4a34-95eb-d93d07e613c7)
Nothing special in material, by the way both U-roughness and V-roughness have strange behavior when difference in values are more than x2. The more the spread between them, the sharper the edges.

The result after rendering is completed:
![Screenshot 2024-06-24 171917](https://github.com/LuxCoreRender/BlendLuxCore/assets/158004719/5527cff8-aed0-4f43-9a0e-c306b79cc53f)
Don't look at middle point, just wanted to make everything as fast as possible


I was comparing that video tutorial to what you have in a .blend, everything was similar. But then I compared UV and amount of geometry and for some reason UV just needs to be straightened and subdiv level reduces the sharpness.
I can't find any explanation why it works like that

**Comment by yan3dx** [comment]
> > Hi @odil24 why DRAVIA. STUDIO managed to create anisotropy without sharp edges? Could this be due to Subdivision? https://www.youtube.com/watch?v=FGhPAP0oV9k
> 
> I was struggling with Anisotropy in LuxCore, had similar result as in your file. I want to share how I've achieved working anisotropy: ![Screenshot 2024-06-24 170840](https://private-user-images.githubusercontent.com/158004719/342348714-0f3fe075-b449-4a34-95eb-d93d07e613c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzYyMTgsIm5iZiI6MTcxOTIzNTkxOCwicGF0aCI6Ii8xNTgwMDQ3MTkvMzQyMzQ4NzE0LTBmM2ZlMDc1LWI0NDktNGEzNC05NWViLWQ5M2QwN2U2MTNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGVkYjYxNDFhNzVlY2ZkNGEwYzA2MDY5YTkzYTc2MzY3MGFjYzM0ODlmODg5ZDY5OTc4ODRiNWEwNTY1NDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GR-RojeaaJTOwoK9m4KCJScjYytyIqLZ4dXJRBuXRu0) Nothing special in the material. By the way, both U-roughness and V-roughness have strange behavior when the difference in values is more than x2. The more the spread between them, the sharper the edges.
> 
> The result after rendering is completed: ![Screenshot 2024-06-24 171917](https://private-user-images.githubusercontent.com/158004719/342352124-5527cff8-aed0-4f43-9a0e-c306b79cc53f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzYyMTgsIm5iZiI6MTcxOTIzNTkxOCwicGF0aCI6Ii8xNTgwMDQ3MTkvMzQyMzUyMTI0LTU1MjdjZmY4LWFlZDAtNGY0My05YTBlLWMzMDZiNzljYzUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjAxNTI3ZmUzMzQ3ZDA5OGNmNzVhMTBiYTJlMGU1YWI1NDllNTc0ZjA1M2FiOGQzZjYzMTQwZTVlMzYxYWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cuZ-eLnCfoXxYGSs-afA-vHDoQ06aDP9LGZUxyjwX9g) Don't look at the middle point; I just wanted to make everything as fast as possible.
> 
> I compared that video tutorial to what you have in the .blend file, and everything was similar. But then I compared the UV and the amount of geometry. For some reason, the UV just needs to be straightened, and the subdivision level reduces the sharpness. I can't find any explanation why it works like that.

Attached file with working anisotropy: https://drive.google.com/file/d/1amiST0-eWb5Y0vz1dduC3l0KzoATqETK/view?usp=sharing
