### ISSUE TITLE
Failed to load on Blender 3.4.1

### ISSUE THREAD

**Issue by dozerman-ms** [LuxCoreRender/BlendLuxCore#893]
Finding the downloaded Blender zip file (for the Blender addon) and importing it in blender 3.4.1 results in the error code:

```
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/.config/blender/3.4/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: /home/andrew/.config/blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference



```

**Comment by wizard3376** [comment]
What version of LuxCore and what operating system?

**Comment by odil24** [comment]
> Finding the downloaded Blender zip file (for the Blender addon) and importing it in blender 3.4.1 results in the error code:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/blender/scripts/modules/addon_utils.py", line 333, in enable
>     mod = __import__(module_name)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/andrew/.config/blender/3.4/scripts/addons/BlendLuxCore/__init__.py", line 66, in <module>
>     raise Exception(msg + "\n\nImportError: %s" % error) from None
> Exception: 
> 
> Could not import pyluxcore.
> 
> ImportError: /home/andrew/.config/blender/3.4/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: _PyTraceMalloc_NewReference
> ```

There are hae not for Blender 3.4.1 due to every new release has been posted into "last" release version.

**Comment by odil24** [comment]
You need jump to Blender 3.6 LTS if you would like to use at least
