### ISSUE TITLE
World is rendering everything blue -- I'm Blue (Da Ba Dee)  Blender 3.6.5 - LuxCore Render 2.7 beta

### ISSUE THREAD

**Issue by whitequill** [LuxCoreRender/BlendLuxCore#894]
I have absolutely no clue what is going on.  When I move the view camera around sometimes I get the correct colors.
Though the texture is rendering material (Stone) is rendering as blue. -- Its the outlined steps the look black, they are a dark blue.
Example 1: correct colors
![blender correct](https://github.com/LuxCoreRender/BlendLuxCore/assets/5000697/e3d97a43-d0e0-4a73-be33-fda5aadbc2cd)

Example 2: Why is the world blue?  Nothing has been changed in my World settings.
![LuxCore-bug](https://github.com/LuxCoreRender/BlendLuxCore/assets/5000697/fd74b67e-50ce-4707-a376-2535da86657f)

I have tried disabling and re-enabling the Add-on. I have tried shutting Blender and re-opening Blender. I have also tried removing and re-adding LuxCore Render and it **still** makes everything **BLUE**!
Oh ya'! Its also throwing, "No material defined" warnings!  Which is absurd as you can **see** the material that is defined in the node editor.

**Comment by whitequill** [comment]
I am on Linux. Kernel version 6.1.67-gentoo

**Comment by odil24** [comment]
@whitequill can you provide the scene with textures?

**Comment by whitequill** [comment]
[BlendLuxCore-v2.7beta1-linux64.zip](https://drive.google.com/file/d/1C1xbl-5ZVlGuK-csizWR8FzyMn_sml2c/view?usp=drive_link)
[Fantacy Library.tar.xz](https://drive.google.com/file/d/1PMHmiZeB-r1SN2fwkPz5tK4pz50iG9Ka/view?usp=drive_link)
