### ISSUE TITLE
هذه الاضافه لا تثبت

### ISSUE THREAD

**Issue by Mohammedc77** [LuxCoreRender/BlendLuxCore#895]
<img width="643" alt="Screenshot 1445-07-12 at 11 02 58 AM" src="https://github.com/LuxCoreRender/BlendLuxCore/assets/147446177/7c296793-fafb-42be-83c0-99c97032ce76">

**Comment by odil24** [comment]
Hi. Explain everything in english, also write topic in english too

**Comment by Mohammedc77** [comment]
This addition is not confirmed I use a MacBook M2
