### ISSUE TITLE
No material preview and no caustics in Blender 3.x and 4.0 / GeForce GTX 770 on Tumbleweed

### ISSUE THREAD

**Issue by joc11** [LuxCoreRender/BlendLuxCore#898]
No problems in Blender 2.93, but BlendluxCore addon 2.6 in 3.x and 2.8 in 4.02 renders without errors, but also completely without caustics on my system.
All settings according to the render settings helper (Pathtracing/Sobol).
Material preview and viewport render remain black.
The files created with the LuxCore Filesaver render without any problems with the luxcoreui 2.8. So far OK.
Unfortunately I don't have the options for light group nodes etc. there. 
Edit: The Radiance Group Editor in luxcoreui apparently corresponds to the Light group nodes. I'm happy with that.

I know the graphics card is very old, but the fact that the luxcoreui renders perfectly gives me hope that the BlendLuxcore addon can also handle it...

Anyway, thank you very much for your wonderful work.

joc

openSUSE Tumbleweed 20240121
12 × AMD Ryzen 5 1600 six-core processor
NVIDIA GeForce GTX 770/PCIe/SSE2
proprietary driver 470.223

**Comment by wizard3376** [comment]
By the way, do you know how to use LuxCore Tools? I'm talking about server rendering, if so, can you tell me how this can be done?
