### ISSUE TITLE
Viewport border rendering in camera view is broken

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#9]
The offset and size of the border render is not correct when panning around (right after the start of the rendering the offset is correct, but I think the size is not).
After starting the render:

![scrn_2017-12-04_17-31-00](https://user-images.githubusercontent.com/1584761/33563758-0b96929a-d919-11e7-8436-0ae5442cbcb5.png)
After panning in the view to the side:

![scrn_2017-12-04_17-31-13](https://user-images.githubusercontent.com/1584761/33563786-18eed93e-d919-11e7-9935-77e9ed2e32b5.png)

**Comment by Theverat** [comment]
The code is mostly here:
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/draw/__init__.py#L44
and
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/utils/__init__.py#L91

**Comment by neo2068** [comment]
I have a quick workaround for border rendering but with that we render the whole region and the image is cropped by blender. As I understand the code that's the way how border rendering worked in the old exporter.  I push the workaround and implement a proper border rendering where only the area inside the border is rendered.

**Comment by Theverat** [comment]
Yes, that's how it was in the past.
It was really bad then because film updates were very slow.
Since Dade implemented support for Blender's bgl.Buffer in LuxCore film updates are not expensive anymore, so this solution is not so bad anymore.

By the way if you get a headache from Blender's border stuff like I did, there's also another solution:
LuxCore allows the definition of a "subregion" to render. 
I never used this in the past because the framebuffer stays the same size (the rest is black pixels), but now that we have fast film updates we could use this and just forget about Blender's weird border stuff.

**Comment by neo2068** [comment]
Border rendering with camera view and orthographic camera is still broken. Normal viewport and perspective camera should work.

**Comment by Theverat** [comment]
Wow, thanks!

In perspective camera viewport there's sometimes a ~1px offset on the top and right borders, see screenshot:

![scrn_2017-12-22_23-13-09](https://user-images.githubusercontent.com/1584761/34313780-ff14d3fc-e76d-11e7-8ec1-442e1bd98a7e.png)

**Comment by Theverat** [comment]
I should have fixed the 1px offset.

**Comment by Theverat** [comment]
Sorry, I forgot.

**Comment by Theverat** [comment]
I found another issue related to border rendering: When you zoom in so far that the border area is bigger than the viewport, the film is not clamped but gets larger and larger.
We have to compute the film size like this:
```
width = min(border_width, viewport_width)
height = min(border_height, viewport_height)
```

**Comment by Theverat** [comment]
By the way the relevant Cycles code is here: https://github.com/dfelinto/blender/blob/master/intern/cycles/blender/blender_camera.cpp#L841

**Comment by neo2068** [comment]
It should be fixed now. I will close the issue, if it is ok for you.

**Comment by Theverat** [comment]
Great! Yes, close it, we can always re-open.
