### ISSUE TITLE
No Viewport Or final Luxcore render capability

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [LuxCoreRender/BlendLuxCore#902]
I get this report:
<img width="924" alt="Screenshot 2024-02-01 at 10 00 01 AM" src="https://github.com/LuxCoreRender/BlendLuxCore/assets/107887495/ea77d94d-51a3-4bd7-bc0c-510e43e0aa50">
I don't know what this means, OpenGL is enabled not Metal.

**Comment by neo2068** [comment]
Please give more information regarding used hardware, OS, blender version, BlendLuxCore version.

**Comment by neo2068** [comment]
User didn't respond to support request to give detailled information.
