### ISSUE TITLE
NVIDIA cards are not used on systems with NVIDIA GPU and AMD iGPU

### ISSUE THREAD

**Issue by EntityinArray** [LuxCoreRender/BlendLuxCore#909]
.blend file: 
[blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/14546701/blend.zip)

Steps to reproduce:
1. Make sure that Compute Device is set to GPU
2. Disable CPU

Screenshots or rendered images:
![render](https://github.com/LuxCoreRender/BlendLuxCore/assets/18554021/001cfad9-0831-4bee-977f-dd4f4c4ce127)

Error message from Blender console:
[blender.log](https://github.com/LuxCoreRender/BlendLuxCore/files/14546706/blender.log)

OS: Windows 10 Pro 22H2 19045.4046
Blender version: 4.0
LuxCore version: BlendLuxCore-v2.8alpha1-win64
GPU: NVidia RTX 3060
CPU: AMD Ryzen 7 5600G

Thank you for your amazing renderer, I'm ready to provide any additional info

**Comment by odil24** [comment]
> .blend file: [blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/14546701/blend.zip)
> 
> Steps to reproduce:
> 
> 1. Make sure that Compute Device is set to GPU
> 2. Disable CPU
> 
> Screenshots or rendered images: ![render](https://private-user-images.githubusercontent.com/18554021/311445917-001cfad9-0831-4bee-977f-dd4f4c4ce127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTk1MjYsIm5iZiI6MTcwOTk5OTIyNiwicGF0aCI6Ii8xODU1NDAyMS8zMTE0NDU5MTctMDAxY2ZhZDktMDgzMS00YmVlLTk3N2YtZGQ0ZjRjNGNlMTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE1NDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTkwMDk1YWY2MDE0ZTVkZWE0MTQ0ZDM4NTczNDUyMDZlMDc5YWQwZmY1ZmJiMmQ1YmI1MTQ0ZjBhMGUxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XMsGE7wswBFAXjfrHKWzOy-6CLw-BsG49FYD4IwoPwM)
> 
> Error message from Blender console: [blender.log](https://github.com/LuxCoreRender/BlendLuxCore/files/14546706/blender.log)
> 
> OS: Windows 10 Pro 22H2 19045.4046 Blender version: 4.0 LuxCore version: BlendLuxCore-v2.8alpha1-win64 GPU: NVidia RTX 3060 CPU: AMD Ryzen 7 5600G
> 
> Thank you for your amazing renderer, I'm ready to provide any additional info

Works fine for me
![1142](https://github.com/LuxCoreRender/BlendLuxCore/assets/64298012/26882a25-691e-4d08-b40c-bb0e60cec6e0)

**Comment by EntityinArray** [comment]
I went to BIOS and disabled iGPU, now it uses my the nVidia GPU properly.
It feels like it displays Nvidia RTX 3060 in Devices list, but in reality uses the AMD iGPU instead.

While iGPU was enabled in BIOS, I tried disabling AMD Radeon Graphics in devmgmt.msc and it hit me with CL_NO_DEVICE_FOUND, which further proves that you are using AMD iGPU instead of nVidia GPU, despite displaying it in Devices list

**Comment by EntityinArray** [comment]
Issue still occurs on [BlendLuxCore v2.9beta1](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.9beta1) Blender 4.3.0

**Comment by EntityinArray** [comment]
sorry, i bumped this and then realized i had CPU in Viewport Render.
I set it to GPU and everything worked fine
Thanks!

we can keep this open if someone happens to have this issue

**Comment by odil24** [comment]
> sorry, i bumped this and then realized i had CPU in Viewport Render. I set it to GPU and everything worked fine Thanks!
> 
> we can keep this open if someone happens to have this issue

No, i think it will confusing users so i will re-close again
