### ISSUE TITLE
Blender 4.1

### ISSUE THREAD

**Issue by CodingIsFun789** [LuxCoreRender/BlendLuxCore#913]
I seem to get an error message when trying to install luxcore for 4.1 that seemed to work fine for 4.0, by the way this is with: BlendLuxCore-v2.8alpha1-win64, just thought I should let you know, don't know if i've done something wrong on my end but I think it may have something to do with the python version being updated

**Comment by TouseefX** [comment]
the error may come from python on my linux devive is python3.11 same as 4.0 but on windows they chnaged it i guess

**Comment by odil24** [comment]
> I seem to get an error message when trying to install luxcore for 4.1 that seemed to work fine for 4.0, by the way this is with: BlendLuxCore-v2.8alpha1-win64, just thought I should let you know, don't know if i've done something wrong on my end but I think it may have something to do with the python version being updated

You cannot install on Blender 4.1+. The reason is Blender 4.1 has been builded on top of Python 3.11+ and it is limitation for LuxCoreRender v2.8 a1 which is based on previous version of Python version. I have tried to build by myself with Python 3.11+ but withoutsucces. So for now LuxCoreRender has supported only 4.0-4.0.3 versions of Blender.

**Comment by CodingIsFun789** [comment]
Thanks for the verification

**Comment by zERO123331** [comment]
but why does it then say "for blender 4.x"?

**Comment by odil24** [comment]
> but why does it then say "for blender 4.x"?

It is for 4.0 - 4.0.3 and not for 4.1+

**Comment by neo2068** [comment]
For windows a first alpha version is available for Blender 4.1. Please try, if this version works. There is a very early adaption and not all features will work, e.g. auto smooth normals are not available.
