### ISSUE TITLE
no geometry on render. it renders only the hdri

### ISSUE THREAD

**Issue by nocivo72** [LuxCoreRender/BlendLuxCore#914]
.blend file: 
https://cloud.mciani.net/s/tEMM5XgYidkEgEo

Error message from Blender console:
no errors. the render start normally but it shows only the background hdri. I reinstall many time cuda. I tried also with different scenes from forum and sample and also with different  blender versions and blendluxcore version combination, but the same beahviors. 

OS:  Linux Fedora 39 and 40
Blender version: 4.0.2 and 3.6.10
LuxCore version: Blendluxcore 2.8 alpha1 and BlendLuxCore v2.7beta1
Graphic card: Nvidia GTX 1060 6GB using proprietary driver from rpmfusion

**Comment by odil24** [comment]
> .blend file: https://cloud.mciani.net/s/tEMM5XgYidkEgEo
> 
> Error message from Blender console: no errors. the render start normally but it shows only the background hdri. I reinstall many time cuda. I tried also with different scenes from forum and sample and also with different blender versions and blendluxcore version combination, but the same beahviors.
> 
> OS: Linux Fedora 39 Blender version: 4.0.2 LuxCore version: Blendluxcore 2.8 alpha1

It works fine as expected. You have something wrong, try to reinstall both Blender and LCR
![1163](https://github.com/LuxCoreRender/BlendLuxCore/assets/64298012/5f498be1-af81-47a8-a010-5d069e0db3d0)

**Comment by neo2068** [comment]
There seems to be a problem with geometry export on Linux.

**Comment by nocivo72** [comment]
I tried everything to fix it but nothing works. When using CPU computing, only the HDRI appears, while rendering with GPU computing displays the geometry, but with an opacity of approximately 50%. Please refer to the attached images for reference.

![Screenshot_20240429_151923](https://github.com/LuxCoreRender/BlendLuxCore/assets/56474439/960654f9-81f4-40ac-8994-87088b3becaa)
![Screenshot_20240429_152054](https://github.com/LuxCoreRender/BlendLuxCore/assets/56474439/6f1d7a22-cc05-4424-bec2-a1ad6faa9b5f)

Furthermore, I've exported the project to LuxCore standalone, and everything works perfectly—no opacity issues or missing geometry.

> There seems to be a problem with geometry export on Linux.

It doesn't seem to be a problem with geometry export, as the geometry is present when using GPU computing, but with reduced opacity.

Any Idea?
thanks

**Comment by nocivo72** [comment]
Hi,
I did more test using also old blender 2.93 with Blendluxore 2.6. With this combination all work well. no hide or dissolved geometry. It works very well with this combination. 
Just for clarify, for all test I used gnome with Xorg, not Wayland. 
I also modify the first post inserting all version of fedora, blender and blendluxcore used in the tests.

Any idea?

Thanks
