### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Sorro123** [LuxCoreRender/BlendLuxCore#918]
Cannot install blendluxcore 2.8 on  blender 4.1.1
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/89468301/b2c84f41-3d4c-4f52-8afc-493ec31b6c9a)

**Comment by odil24** [comment]
It is known issue:
[](https://github.com/LuxCoreRender/BlendLuxCore/issues/913)

**Comment by neo2068** [comment]
For windows a first alpha version is available for Blender 4.1. Please try, if this version works. There is a very early adaption and not all features will work, e.g. auto smooth normals are not available.
