### ISSUE TITLE
I can't activate LuxCore addons from Blender User Preferences on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by ozguraydin74** [LuxCoreRender/BlendLuxCore#92]
#### System Information

Operating system and graphics card

Operating System | Ubuntu 16.04.4 LTS
Date/Time | Paz 04 Mar 2018 13:47:21 +03
Version
Kernel | Linux 4.4.0-116-generic (x86_64)
Compiled | #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
C Library | Unknown
Default C Compiler | GNU C Compiler version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
Distribution | Ubuntu 16.04.4 LTS
Display
Resolution | 3840x2160 pixels
OpenGL Renderer | GeForce GTX 1080 Ti/PCIe/SSE2
X11 Vendor | The X.Org Foundation

#### Software Version

* Blender version: Blender 2.79 (sub 0) Build: 2018-02-21 12:29:12 Linux Release
* LuxCore version: 2.0, Alpha5

#### Error message from Blender console
```
ozgur@ozgur-2:~/Downloads/blender-2.79a-linux-glibc219-x86_64$ '/home/ozgur/Downloads/blender-2.79a-linux-glibc219-x86_64/blender' -d
Switching to fully guarded memory allocator.
Blender 2.79 (sub 0)
Build: 2018-02-21 12:29:12 Linux Release
Version 279 sub 0 date unknown hash unknown
[Lux 2018-Mar-04 13:54:09] Attempting to import pylux module from "/home/ozgur/Documents/Blender/lux-opencl_linux64_18-12-2017"
[Lux 2018-Mar-04 13:54:09] Pylux module imported successfully
[Lux 2018-Mar-04 13:54:09] Using pylux version 1.7.0 dev Build 0
[Lux 2018-Mar-04 13:54:09] Attempting to import pyluxcore module from "/home/ozgur/Documents/Blender/lux-opencl_linux64_18-12-2017"
[Lux 2018-Mar-04 13:54:09] Pyluxcore module imported successfully
[Lux 2018-Mar-04 13:54:09] Using pyluxcore version 1.7dev
[Lux 2018-Mar-04 13:54:09] Installed scene post-update handler
path not found 
search for unknown operator 'VIEW3D_OT_modal_pc_click_dof', 'VIEW3D_OT_modal_pc_click_dof'
search for unknown operator 'VIEW3D_OT_modal_pc_click_dof', 'VIEW3D_OT_modal_pc_click_dof'
search for unknown operator 'VIEW3D_OT_modal_pc_click_dof', 'VIEW3D_OT_modal_pc_click_dof'
Traceback (most recent call last):
  File "/home/ozgur/Downloads/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/ozgur/.config/blender/2.79/scripts/addons/BlendLuxCore/__init__.py", line 4, in <module>
    from .bin import pyluxcore
ImportError: /home/ozgur/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so: undefined symbol: rtcSetTransform2
```
#### Short description of error
I can't activate LuxCore addons from Blender User Preferences

**Comment by Theverat** [comment]
Try to disable LuxBlend before enabling the new BlendLuxCore.
I doubt it will fix the issue, but it's worth a try.

`undefined symbol: rtcSetTransform2` seems to point to some issues with the embree version. Do you have embree installed in your system (maybe a newer version than the one pyluxcore is using?).

**Comment by Dade916** [comment]
It is an older embree version installed somewhere and loaded instead of the one included in BlendLuxCore.

**Comment by Theverat** [comment]
Can we force it to load the embree in the bin/ folder in BlendLuxCore?

**Comment by Dade916** [comment]
I'm afraid it is controlled by the OS and not by python because it is a DLL required by another DLL.

**Comment by ozguraydin74** [comment]
I try to disable LuxBlend before enabling BlendLuxCore than two things happened, one of downloaded version of Blender and its BlendLuxCore is enabled and worked but System wide install Blender which is PPA from Thomas-Schiex and its BlendLuxCore not worked.System wide Blender terminal give that output: 

`Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/ozgur/.config/blender/2.79/scripts/addons/BlendLuxCore/__init__.py", line 4, in <module>
    from .bin import pyluxcore
ImportError: /home/ozgur/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/libembree.so.2: undefined symbol: _ZN3tbb10interface78internal15task_arena_base24internal_max_concurrencyEPKNS0_10task_arenaE
`

so, I use dowloaded version blender  with LuxCoreRender instead PPA version. Thanks a lot.

**Comment by Theverat** [comment]
By the way, official Blender 2.79a is out now, so you can use that.

**Comment by Dade916** [comment]
We can close this issue, it now works, right ?

**Comment by ozguraydin74** [comment]
Yes right,  it works. Thanks a lot.

**Comment by Elias79** [comment]
I had these same issue in Linux Mint 18.3 so either the PPA version is broken or luxrender only have support very a specific version 2.79b?

```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/elias/.config/blender/2.79/scripts/addons/BlendLuxCore/__init__.py", line 13, in <module>
    from .bin import pyluxcore
ImportError: /home/elias/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/libembree.so.2: undefined symbol: _ZN3tbb10interface78internal15task_arena_base24internal_max_concurrencyEPKNS0_10task_arenaE


```

**Comment by Theverat** [comment]
Custom Blender builds and buildbot builds are not supported.
It might work there, or it might not, but you are on your own when using anything but the official builds.

> or luxrender only have support for a specific version 2.79b?

Yes, only the official 2.79b from https://www.blender.org/
