### ISSUE TITLE
Old bug - Viewport GPU rendering crashes.

### ISSUE THREAD

**Issue by Sarah-C** [LuxCoreRender/BlendLuxCore#924]
.blend file:         
Any with more than a cube in it. Looks like it may need a few material nodes.

Steps to reproduce:              
1: Select Lux Core Rendering.           
2: Select GPU Viewport rendering.                             

Error message from Blender console:
  # Python backtrace
  File "C:\Users\sarah\AppData\Roaming\Blender 
  Foundation\Blender\4.1\scripts\addons\BlendLuxCore\engine\viewport.py", line 13 in start_session

OS: Windows 10
Blender version: 4.1
LuxCore version: BlendLuxCore v2.9 alpha 1

--------------------------------------------------------------------
Of note - a question?
Is this a "Won't fix" issue, due to the excessive physical delays in piping edited data back through to the GPU?
I've read a couple of posts where moving light meshes with GPU viewport rendering is very slow due to that overhead of recalculating lighting from the meshes and material changes and such?

(In other words - Is GPU viewport rendering a no-go because the render time saved by hardware acceleration is lost by the frequent scene changes when editing a scene?)

**Comment by neo2068** [comment]
Hi! I cannot reproduce the error. For me, GPU rendering works. Keep in mind, that for the first time, CUDA needs to comile the render kernel. This process needs several minutes to complete but this is a one time delay. Can you give more information on the used hardware and give a detailled error message?

**Comment by Sarah-C** [comment]
Thanks for having a look!

>Keep in mind, that for the first time, CUDA needs to compile the render kernel. 

I made sure to wait - it took a bit over 10 minutes. I made sure not to try clicking buttons or alt-tabbing out.

I've included the details for what I could find - but the error doesn't get very detailed from what I could see?
EXCEPTION_ACCESS_VIOLATION, pyluxcore.pyd line 13 in start_session. 
The stack trace didn't mean much to me.

The full details are below, and in the crash.txt I included.



Graphics card: RTX2060

OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	HELLRAISER-4
System Manufacturer	Dell Inc.
System Model	OptiPlex 790
System Type	x64-based PC
System SKU	
Processor	Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A18, 24/09/2013
SMBIOS Version	2.6
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0HY9JP
BaseBoard Version	A00
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.19041.488"
Username	HELLRAISER-4\sarah
Time Zone	GMT Summer Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	32.0 GB
Available Physical Memory	19.5 GB
Total Virtual Memory	96.0 GB
Available Virtual Memory	78.5 GB
Page File Space	64.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes


Blender: blender-4.1.1

Blender crash . txt:
[ProceduralLeaves.crash.txt](https://github.com/user-attachments/files/15747134/ProceduralLeaves.crash.txt)

**Comment by Sarah-C** [comment]
A bit more information:
Starting a scene from scratch - the GPU Viewport render is doing well. 
I've tried adding things, alpha transparency, volumetrics, sun, spot, area lights, and moulding the cube (heh, GPU doesn't work with sculpting (it doesn't update the mesh) but I can guess why!)

Anyway - If I get it to crash, I'll report back and mention what crashed it!

![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/1586332/04966f4e-efcd-4dff-969f-f2fce970e4a4)

**Comment by Sarah-C** [comment]
I've tried saving the Leaves example in 4.1.1, then reloading the scene.
GPU Viewport rendering still crashes.  Hmmm.

**Comment by Sarah-C** [comment]
Ok, so using the leaves scene, it only STOPS crashing when I delete 2 of the 3 leaves, all but the single material node of the texture and the Subsurf modifier, and all of the lights, background, and focus. It seems like there's multiple "issues" in the demo file that cause the GPU Viewport to bomb out.

I'm going to leave it here, because the demo scenes are only meant to be rendered and tinkered with, there's no big reason to use GPU rendering with them. =)

Close if you like!

**Comment by odil24** [comment]
> Ok, so using the leaves scene, it only STOPS crashing when I delete 2 of the 3 leaves, all but the single material node of the texture and the Subsurf modifier, and all of the lights, background, and focus. It seems like there's multiple "issues" in the demo file that cause the GPU Viewport to bomb out.
> 
> I'm going to leave it here, because the demo scenes are only meant to be rendered and tinkered with, there's no big reason to use GPU rendering with them. =)
> 
> Close if you like!
> 

Are you using this version?
https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.9alpha1

**Comment by Sarah-C** [comment]
I am!

Additionally, I'm trying to download various files from years ago - the example files are old aren't they?
So far I've got one - and it renders with GPU Viewport fine. 

https://github.com/LuxCoreRender/LuxCore/issues/403  the file [volCaustics.blend.gz](https://github.com/LuxCoreRender/LuxCore/files/4852269/volCaustics.blend.gz) from 2020 works fine in Path trace GPU mode too.

I wonder if it's all down to some issue with file format - moving from an old file save for the example files, straight to V2.9 Alpha 1?

**Comment by neo2068** [comment]
I tested the procedural leaves scene and it works with GPU rendering on my system. Is your scene the original one from the repository?

**Comment by Sarah-C** [comment]
> I tested the procedural leaves scene and it works with GPU rendering on my system. Is your scene the original one from the repository?

Yes it is, directly from the site.

If this is just an odd edge case with my PC, I'm happy if it's closed?  No point wasting time on an issue that's obscurely based on 1 hardware setup!
