### ISSUE TITLE
unable to activate luxcore plugin after installing it in blender

### ISSUE THREAD

**Issue by bastard-salad** [LuxCoreRender/BlendLuxCore#925]
![2024-06-12](https://github.com/LuxCoreRender/BlendLuxCore/assets/172496876/336b0d22-3b8a-4391-91ea-16bb075731e6)

ive already downloaded the redistributable package and im still unable to activate the package.

OS version Windows 10
Blender version 4.0
Luxcore version is BlendLuxCore v2.9alpha1

**Comment by foreachthing** [comment]
As far as I understand is 2.9a1 for Blender 4.1.
If you want to use Blender 4.0, you'll need 2.8a1 - see here: https://github.com/LuxCoreRender/BlendLuxCore/releases

**Comment by bastard-salad** [comment]
> As far as I understand is 2.9a1 is for Blender 4.1. If you want to use Blender 4.0, you'll need 2.8a1 - see here: https://github.com/LuxCoreRender/BlendLuxCore/releases

thank you! it works

**Comment by odil24** [comment]
@neo2068 Close an issue
