### ISSUE TITLE
2.9 Alpha keeps crashing on linux

### ISSUE THREAD

**Issue by ValorCat2015** [LuxCoreRender/BlendLuxCore#928]
Debian 12 - RTX 4090 - Blender 4.0.2:
CPU, GPU, OPEN-CL, CUDA - all crashing on render... Is the alpha of this open-sourced renderer primarily developed on windows?

**Comment by odil24** [comment]
> Debian 12 - RTX 4090 - Blender 4.0.2:
> CPU, GPU, OPEN-CL, CUDA - all crashing on render... Is the alpha of this open-sourced renderer primarily developed on windows?
> 

The topic says by itself:
https://blenderartists.org/t/luxcorerender-2-9-alpha1-is-out-for-blender-4-1-windows-only

**Comment by ValorCat2015** [comment]
Sorry, I genuinely meant 2.8 - I guess my main confusion is why a FOSS project would be more windows-forward...
