### ISSUE TITLE
UDIM Support

### ISSUE THREAD

**Issue by ValorCat2015** [LuxCoreRender/BlendLuxCore#929]
I will migrate my entire asset library over to Luxcore if someone figures out the UDIM support!
![image](https://github.com/LuxCoreRender/BlendLuxCore/assets/65992722/a1067c3b-245b-4f6e-b48d-db5be84d4f3d)

**Comment by odil24** [comment]
No, it does not supported and also not planned yet to implementation:
https://github.com/LuxCoreRender/LuxCore/issues/258

**Comment by odil24** [comment]
@neo2068 Please, Close up an issue
