### ISSUE TITLE
blender texture node can not work in opencl rendering

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/BlendLuxCore#93]
#### System Information

windows 10 ,gtx 1060
#### Software Version

* Blender version: 2.79a
* LuxCore version: 2.0 alpha5
#### Error message from Blender console
error log:
Unknown texture in CompiledScene::CompileTextures(): 27

**Comment by Theverat** [comment]
Which node exactly?

**Comment by frankyifei** [comment]
noise

**Comment by frankyifei** [comment]
It is working in cpu mode

**Comment by Dade916** [comment]
Uh, it is true, the support for BLENDER_NOISE procedural texture is missing in OpenCL code. I'm adding it.

**Comment by Dade916** [comment]
There was a reason why the texture wasn't supported: the blender code wasn't thread safe and it can not simply work with the huge amount of threads of a GPU.
I rewrite the code (for the CPU) in a thread safe way and added the support to OpenCL code too: https://github.com/LuxCoreRender/LuxCore/commit/052a967bd5ea3e758e9eb40b5058494145f07a54

**Comment by Theverat** [comment]
Fixed in alpha6.
