### ISSUE TITLE
luxcore don't instal proprely 

### ISSUE THREAD

**Issue by Tisseurdevie** [LuxCoreRender/BlendLuxCore#933]
Luxcore render don't instal proprely on windows and blender 4.2

**Comment by odil24** [comment]
> Luxcore render don't instal proprely on windows and blender 4.2

Which version of BlendLuxCore you have tried to install?

**Comment by odil24** [comment]
Blender 4.1-4.3 uses BlendLuxCore v2.9.1 alpha

**Comment by odil24** [comment]
@neo2068 Close up issue. It does not responsed
