### ISSUE TITLE
crash on blender classroom scene, during compiling opencl kernel

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/BlendLuxCore#94]
#### System Information

windows 10 , gtx 1060

#### Software Version

* Blender version: 2.79a
* LuxCore version: alphav6

#### Error message from Blender console
none
#### Short description of error
I tried to convert this scene to render using luxrender, It uses huge amount of ram (8gb) when compiling opencl kernel and after 10 or 20 minutes it just crash blender. not all materials are converted, just linked objects, like chairs and some small objects.

**Comment by Dade916** [comment]
The NVIDIA OpenCL compilation issues are usually related to complex materials/textures (mostly procedural one). I assume you are the same "Frank" following the discussion about this topic on the forums.
I may have finally understood how the NVIDIA compiler bug (doesn't) work and I may be able to write a work around.

Can you post somewhere the scene not working for you ?

**Comment by Dade916** [comment]
Can you try with the pyluxcore.pyd attached to this post (https://forums.luxcorerender.org/viewtopic.php?f=4&t=159&start=30#p2161) ?

**Comment by frankyifei** [comment]
this can be closed now. I tried your lastest build and it did work without crash. there maybe more work to do with the re-compiling issue, it is so time-consuming.
