### ISSUE TITLE
Samples per pixel 100%, rendering done. But it continues the rendering in viewport

### ISSUE THREAD

**Issue by alnjmalsaat3** [LuxCoreRender/BlendLuxCore#943]
.blend file: all blend

Steps to reproduce:
when i use GPU and enable Halt Conditions ,The render stops working after approximately the first 5 seconds, and the samples/sec keeps decreasing. The more it decreases, the slower it gets, until it stops completely.

Screenshots or rendered images:
![image](https://github.com/user-attachments/assets/cc2fa260-1225-4c99-9435-7a2867e7ac84)

Error message from Blender console:

[LuxRays][940.829] [Optix][4][DENOISER] layers created for resolution 2114 1166, input inference channels 6, output channels 3
[LuxRays][940.954] [Optix][4][DENOISER] layers created for resolution 2114 1166, input inference channels 3, output channels 3
[LuxCore][946.907] Samples per pixel 100%, rendering done.
Traceback (most recent call last):
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\engine\base.py", line 128, in view_draw
    viewport.view_draw(self, context, depsgraph)
  File "C:\Users\alnjm\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\BlendLuxCore\engine\viewport.py", line 275, in view_draw
    engine.session.UpdateStats()
KeyboardInterrupt
[SDL][983.844] Define ImageMap: NamedObject
[SDL][983.844] Camera type: perspective
[SDL][983.844] Camera position: Point[0, 0, 0]
[SDL][983.844] Camera target: Point[0, 0, 0]
[SDL][983.844] Camera clipping plane disabled
[LuxCore][983.844] Configuration:
[LuxCore][983.844]   renderengine.type = "RTPATHOCL"
[LuxCore][983.844]   sampler.type = "TILEPATHSAMPLER"
[LuxCore][983.844]   scene.epsilon.min = 1e-05
[LuxCore][983.844]   scene.epsilon.max = 0.1
[LuxCore][983.844]   opencl.devices.select = "01"
[LuxCore][983.844] File Name Resolver Configuration:
==================================================
[Engine/Viewport] New session
[Exporter] Creating session
Updated node "Glass Material" in tree Material.001 to new version
[SDL][983.860] Define ImageMap: NamedObject
[SDL][983.860] Camera type: perspective
[SDL][983.860] Camera position: Point[3.43525, -4.99905, 4.08564]
[SDL][983.860] Camera target: Point[2.91646, -4.27892, 3.62492]
[SDL][983.860] Camera clipping plane disabled
[SDL][983.860] Material definition: 1923194343176
[SDL][983.860] Material definition: 1923147582344
[SDL][983.860] Scene objects count: 2
[SDL][983.860] Light definition: 1922854338848
[SDL][983.860] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][983.875] Configuration:
[LuxCore][983.875]   path.pathdepth.total = 7
[LuxCore][983.875]   path.pathdepth.diffuse = 5
[LuxCore][983.875]   path.pathdepth.glossy = 5
[LuxCore][983.875]   path.pathdepth.specular = 6
[LuxCore][983.875]   path.hybridbackforward.enable = 1
[LuxCore][983.875]   path.hybridbackforward.partition = 0
[LuxCore][983.875]   path.hybridbackforward.glossinessthreshold = 0.049
[LuxCore][983.875]   sampler.sobol.adaptive.strength = 0
[LuxCore][983.875]   opencl.cpu.use = 0
[LuxCore][983.875]   opencl.gpu.use = 1
[LuxCore][983.875]   opencl.devices.select = "01"
[LuxCore][983.875]   opencl.native.threads.count = 8
[LuxCore][983.875]   renderengine.type = "PATHOCL"
[LuxCore][983.875]   sampler.type = "SOBOL"
[LuxCore][983.875]   film.width = 2114
[LuxCore][983.875]   film.height = 1166
[LuxCore][983.875]   film.filter.type = "NONE"
[LuxCore][983.875]   film.filter.width = 1.5
[LuxCore][983.875]   lightstrategy.type = "LOG_POWER"
[LuxCore][983.875]   scene.epsilon.min = 1e-05
[LuxCore][983.875]   scene.epsilon.max = 0.1
[LuxCore][983.875]   path.albedospecular.type = "REFLECT_TRANSMIT"
[LuxCore][983.875]   path.albedospecular.glossinessthreshold = 0.05
[LuxCore][983.875]   film.opencl.enable = 1
[LuxCore][983.875]   film.opencl.device = 1
[LuxCore][983.875]   path.forceblackbackground.enable = 0
[LuxCore][983.875]   native.threads.count = 8
[LuxCore][983.875]   renderengine.seed = 1
[LuxCore][983.875]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][983.875]   film.outputs.0.index = 0
[LuxCore][983.875]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][983.875]   film.outputs.1.type = "ALBEDO"
[LuxCore][983.875]   film.outputs.1.filename = "ALBEDO.exr"
[LuxCore][983.875]   film.imagepipelines.000.0.type = "NOP"
[LuxCore][983.875]   film.imagepipelines.000.1.type = "TONEMAP_LINEAR"
[LuxCore][983.875]   film.imagepipelines.000.1.scale = 1
[LuxCore][983.875]   film.imagepipelines.000.2.type = "OPTIX_DENOISER"
[LuxCore][983.875]   film.imagepipelines.000.2.sharpness = 0
[LuxCore][983.875]   film.imagepipelines.000.2.minspp = 1
[LuxCore][983.875]   film.imagepipelines.000.radiancescales.0.enabled = 1
[LuxCore][983.875]   film.imagepipelines.000.radiancescales.0.globalscale = 1
[LuxCore][983.875]   film.imagepipelines.000.radiancescales.0.rgbscale = 1 1 1
[LuxCore][983.875]   batch.haltspp = 32 0
[LuxCore][983.875]   batch.halttime = 0
[LuxCore][983.875] File Name Resolver Configuration:
Export took 0.0 s
[LuxCore][983.875] Film resolution: 2114x1166
[SDL][983.875] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][983.875] Image pipeline: film.imagepipelines.000
[SDL][983.875] Image pipeline step 0: NOP
[SDL][983.875] Image pipeline step 1: TONEMAP_LINEAR
[SDL][983.875] Image pipeline step 2: OPTIX_DENOISER
[SDL][983.875] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png]
[SDL][983.875] Film output definition: ALBEDO [ALBEDO.exr]
[LuxRays][983.875] OpenCL support: enabled
[LuxRays][983.875] OpenCL Platform 0: NVIDIA CUDA
[LuxRays][983.875] CUDA support: enabled
[LuxRays][983.875] CUDA support: available
[LuxRays][983.875] CUDA driver version: 12.70
[LuxRays][983.875] CUDA device count: 1
[LuxRays][983.875] Optix support: available
[LuxRays][983.875] Device 0 name: Native
[LuxRays][983.875] Device 0 type: NATIVE_THREAD
[LuxRays][983.875] Device 0 compute units: 1
[LuxRays][983.875] Device 0 preferred float vector width: 4
[LuxRays][983.875] Device 0 max allocable memory: 17592186044415MBytes
[LuxRays][983.875] Device 0 max allocable memory block size: 17592186044415MBytes
[LuxRays][983.875] Device 0 has out of core memory support: 0
[LuxRays][983.875] Device 1 name: NVIDIA GeForce RTX 4060 Ti
[LuxRays][983.875] Device 1 type: OPENCL_GPU
[LuxRays][983.875] Device 1 compute units: 34
[LuxRays][983.875] Device 1 preferred float vector width: 1
[LuxRays][983.875] Device 1 max allocable memory: 8187MBytes
[LuxRays][983.875] Device 1 max allocable memory block size: 2046MBytes
[LuxRays][983.875] Device 1 has out of core memory support: 0
[LuxRays][983.875] Device 2 name: NVIDIA GeForce RTX 4060 Ti
[LuxRays][983.875] Device 2 type: CUDA_GPU
[LuxRays][983.875] Device 2 compute units: 1
[LuxRays][983.875] Device 2 preferred float vector width: 1
[LuxRays][983.875] Device 2 max allocable memory: 8187MBytes
[LuxRays][983.875] Device 2 max allocable memory block size: 17592186044415MBytes
[LuxRays][983.875] Device 2 has out of core memory support: 1
[LuxRays][983.875] Device 2 CUDA compute capability: 8.9
[LuxRays][983.875] Creating 9 intersection device(s)
[LuxRays][983.875] Allocating intersection device 0: NVIDIA GeForce RTX 4060 Ti (Type = CUDA_GPU)
[LuxRays][983.922] [Optix][4][KNOBS] All knobs on default.

[LuxRays][983.969] [Optix][4][DISKCACHE] Opened database: "C:\Users\alnjm\AppData\Local\NVIDIA\OptixCache\optix7cache.db"
[LuxRays][983.969] [Optix][4][DISKCACHE]     Cache data size: "177.5 MiB"
[LuxRays][983.969] Allocating intersection device 1: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 2: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 3: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 4: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 5: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 6: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 7: Native (Type = NATIVE_THREAD)
[LuxRays][983.969] Allocating intersection device 8: Native (Type = NATIVE_THREAD)
[LuxCore][983.969] CUDA devices used:
[LuxCore][983.969] [NVIDIA GeForce RTX 4060 Ti CUDAIntersect (Optix enabled: 1)]
[LuxCore][983.969] OpenCL devices used:
[LuxCore][983.969] Native devices used: 8
[LuxCore][983.969] Configuring 1 OpenCL render threads
[LuxCore][983.969] Configuring 8 native render threads
[LuxRays][983.969] Preprocessing DataSet
[LuxRays][983.969] Total vertex count: 2886
[LuxRays][983.969] Total triangle count: 970
[LuxRays][983.969] Preprocessing DataSet done
[LuxRays][983.969] Adding DataSet accelerator: OPTIX
[LuxRays][983.969] Total vertex count: 2886
[LuxRays][983.969] Total triangle count: 970
[LuxRays][983.969] Adding DataSet accelerator: EMBREE
[LuxRays][983.969] Total vertex count: 2886
[LuxRays][983.969] Total triangle count: 970
[LuxRays][983.969] EmbreeAccel build time: 0ms
[LuxRays][983.969] Building Optix accelerator
[LuxRays][983.969] Optix accelerator leafs: 2
[LuxRays][983.985] OptixAccel total build time: 16ms
[LuxRays][983.985] [OptixAccel] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D PARAM_RAY_EPSILON_MIN=1e-05f -D PARAM_RAY_EPSILON_MAX=0.1f -D LUXRAYS_CUDA_DEVICE -D LUXRAYS_OS_WINDOWS --use_fast_math
[LuxRays][983.985] [OptixAccel] Program cached
[LuxRays][983.985] [Optix][4][DISKCACHE] Cache hit for key: ptx-2547-key5fa4755654528968a8b856b608cd3d18-sm_89-rtc1-drv565.90

[LuxRays][983.985] [Optix][4][COMPILER]
[LuxRays][983.985] [Optix][4][COMPILER] Info: Pipeline statistics
        module(s)                            :     1
        entry function(s)                    :     3
        trace call(s)                        :     1
        continuation callable call(s)        :     0
        direct callable call(s)              :     0
        basic block(s) in entry functions    :     7
        instruction(s) in entry functions    :    89
        non-entry function(s)                :     0
        basic block(s) in non-entry functions:     0
        instruction(s) in non-entry functions:     0
        debug information                    :    no

[LuxRays][983.985] Total Optix memory usage: 24Kbytes
[LuxCore][984.016] [PathOCLRenderEngine] OpenCL task count: 262144
[LuxCore][984.032] [PathOCLBaseRenderEngine] OpenCL max. page memory size: 18014398509481983Kbytes
[LuxCore][984.032] Compile Geometry
[LuxCore][984.032] Scene geometry compilation time: 0ms
[LuxCore][984.032] Compile 4 Textures
[LuxCore][984.032] Texture evaluation ops count: 12
[LuxCore][984.032] Texture evaluation max. stack size: 3
[LuxCore][984.032] Textures compilation time: 0ms
[LuxCore][984.032] Compile 2 Materials
[LuxCore][984.032] Material evaluation ops count: 14
[LuxCore][984.032] Material evaluation max. stack size: 8
[LuxCore][984.032] Material compilation time: 0ms
[LuxCore][984.032] Compile Lights
[LuxCore][984.032] Lights compilation time: 0ms
[LuxCore][984.032] Compile ImageMaps
[LuxCore][984.032] Image maps page(s) count: 1
[LuxCore][984.032]  RGB channel page 0 size: 3072Kbytes
[LuxCore][984.032] Image maps compilation time: 0ms
[LuxCore][984.032] Always enabled OpenCL code:
[LuxCore][984.032] Compile Geometry
[LuxCore][984.032] Scene geometry compilation time: 0ms
[LuxCore][984.032] Compile 4 Textures
[LuxCore][984.032] Texture evaluation ops count: 12
[LuxCore][984.032] Texture evaluation max. stack size: 3
[LuxCore][984.032] Textures compilation time: 0ms
[LuxCore][984.032] Compile 2 Materials
[LuxCore][984.032] Material evaluation ops count: 14
[LuxCore][984.032] Material evaluation max. stack size: 8
[LuxCore][984.032] Material compilation time: 0ms
[LuxCore][984.032] Compile Lights
[LuxCore][984.032] Lights compilation time: 0ms
[LuxCore][984.032] Compile ImageMaps
[LuxCore][984.032] Image maps page(s) count: 1
[LuxCore][984.032]  RGB channel page 0 size: 3072Kbytes
[LuxCore][984.032] Image maps compilation time: 0ms
[LuxCore][984.032] Starting 1 OpenCL render threads
[LuxRays][984.032] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 38,514Kbytes
[LuxRays][984.032] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] ALBEDO buffer size: 38,514Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 38,514Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Camera buffer size: 5,492bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Normals buffer size: 33Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] UVs buffer size: 22Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Triangle normals buffer size: 11Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Vertices buffer size: 33Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Triangles buffer size: 11Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Mesh description buffer size: 624bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] ImageMap descriptions buffer size: 40bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] ImageMaps buffer size: 3,072Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Textures buffer size: 1,312bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Texture evaluation ops buffer size: 96bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Texture evaluation stacks buffer size: 3,072Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Materials buffer size: 456bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Material evaluation ops buffer size: 168bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Material evaluation stacks buffer size: 8,192Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Scene objects buffer size: 48bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Lights buffer size: 688bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Env. light indices buffer size: 4bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Light offsets (Part I) buffer size: 8bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Env. light distributions buffer size: 1,028Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] LightsDistribution buffer size: 24bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] InfiniteLightSourcesDistribution buffer size: 24bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Ray buffer size: 12,288Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] RayHit buffer size: 5,120Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] GPUTaskConfiguration buffer size: 336bytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] GPUTask buffer size: 169,984Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] GPUTaskDirectLight buffer size: 15,360Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] GPUTaskState buffer size: 100,352Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] GPUTask Stats buffer size: 1,024Kbytes
[LuxRays][984.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] SamplerSharedData buffer size: 9,638Kbytes
[LuxCore][984.063] [PathOCLBaseRenderThread::0] Size of a Sample: 40bytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Sample buffer size: 10,240Kbytes
[LuxCore][984.063] [PathOCLBaseRenderThread::0] Size of a SampleData: 8bytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] SampleData buffer size: 2,048Kbytes
[LuxCore][984.063] [PathOCLBaseRenderThread::0] Size of a SampleResult: 428bytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] SampleResult buffer size: 109,568Kbytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] PathInfo buffer size: 27,648Kbytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] DirectLightVolumeInfo buffer size: 11,264Kbytes
[LuxRays][984.063] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Pixel Filter Distribution buffer size: 33Kbytes
[LuxCore][984.063] [PathOCLBaseRenderThread::0] Compiling kernels
[LuxRays][984.063] [PathOCL kernel] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D RENDER_ENGINE_PATHOCL -D PARAM_RAY_EPSILON_MIN=1e-05f -D PARAM_RAY_EPSILON_MAX=0.1f -D LUXRAYS_CUDA_DEVICE -D LUXRAYS_OS_WINDOWS --use_fast_math
[LuxRays][984.063] [PathOCL kernel] Compiling kernels
[LuxRays][984.094] [PathOCL kernel] Program cached
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling Film_Clear Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling InitSeed Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling Init Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_NEXT_VERTEX Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_NOTHING Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_OBJECT Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_DL Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_ILLUMINATE Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_SAMPLE_BSDF Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_NEXT_VERTEX_RAY Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_SPLAT_SAMPLE Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_NEXT_SAMPLE Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_CAMERA_RAY Kernel
[LuxCore][984.094] [PathOCLBaseRenderThread::0] AdvancePaths_MK_* workgroup size: 32
[LuxCore][984.094] [PathOCLBaseRenderThread::0] Kernels compilation time: 31ms
[LuxCore][984.110] Starting 8 native render threads
[LuxCore][984.172] Film hardware image pipeline
[LuxCore][984.938] Film hardware device used: NVIDIA GeForce RTX 4060 Ti CUDAIntersect (Type: CUDA_GPU)
[LuxRays][984.938] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] IMAGEPIPELINE buffer size: 28,885Kbytes
[LuxRays][985.047] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] ALBEDO buffer size: 38,514Kbytes
[LuxRays][985.172] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Merge buffer size: 38,514Kbytes
[LuxRays][985.172] [MergeSampleBuffersOCL] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D LUXRAYS_CUDA_DEVICE -D LUXRAYS_OS_WINDOWS --use_fast_math
[LuxRays][985.188] [MergeSampleBuffersOCL] Compiling kernels
[LuxRays][985.188] [MergeSampleBuffersOCL] Program cached
[LuxCore][985.188] [MergeSampleBuffersOCL] Compiling Film_MergeBufferInitialize Kernel
[LuxCore][985.188] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_PIXEL_NORMALIZED Kernel
[LuxCore][985.188] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_SCREEN_NORMALIZED Kernel
[LuxCore][985.188] [MergeSampleBuffersOCL] Compiling Film_MergeBufferFinalize Kernel
[LuxCore][985.188] [MergeSampleBuffersOCL] Kernels compilation time: 15ms
[LuxRays][985.782] [LinearToneMap] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D LUXRAYS_CUDA_DEVICE -D LUXRAYS_OS_WINDOWS --use_fast_math
[LuxRays][985.782] [LinearToneMap] Compiling kernels
[LuxRays][985.782] [LinearToneMap] Program cached
[LuxCore][985.782] [AutoLinearToneMap] Compiling LinearToneMap_Apply Kernel
[LuxCore][985.782] [LinearToneMap] Kernels compilation time: 0ms
[LuxRays][986.485] [Optix][4][DENOISER] using cuda device "NVIDIA GeForce RTX 4060 Ti" (8.9), buffers: fp16, xmma/xmma-jit convolution, rt v12070
[LuxRays][986.485] [Optix][4][DENOISER] using cuda device "NVIDIA GeForce RTX 4060 Ti" (8.9), buffers: fp16, xmma/xmma-jit convolution, rt v12070
[LuxRays][986.500] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Optix denoiser state and scratch buffer buffer size: 972,554Kbytes
[LuxRays][986.500] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Optix denoiser temporary buffer buffer size: 28,885Kbytes
[LuxRays][986.500] [Device NVIDIA GeForce RTX 4060 Ti CUDAIntersect] Optix denoiser albedo temporary buffer buffer size: 28,885Kbytes
[LuxRays][986.500] [OptixDenoiserPlugin] Compiler options: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D LUXRAYS_CUDA_DEVICE -D LUXRAYS_OS_WINDOWS --use_fast_math
[LuxRays][986.500] [OptixDenoiserPlugin] Compiling kernels
[LuxRays][986.532] [OptixDenoiserPlugin] Program cached
[LuxCore][986.532] [OptixDenoiserPlugin] Compiling OptixDenoiserPlugin_BufferSetUp Kernel
[LuxRays][986.532] [Optix][4][DENOISER] layers created for resolution 2114 1166, input inference channels 6, output channels 3
[LuxRays][986.672] [Optix][4][DENOISER] layers created for resolution 2114 1166, input inference channels 3, output channels 3
[LuxCore][990.860] Samples per pixel 100%, rendering done.

OS: win 11 rtx 4060 ti
Blender version: 4.3
LuxCore version: 2.9 beta 2

**Comment by odil24** [comment]
@alnjmalsaat3 Its normal behaviour. You just missed that Render properties > Viewport render > Halt time is not the same as Render properties > Halt conditions.

- Halt conditions for Final render;
- Viewport render > Halt time for Viewport rendering.
